/*
 * C code generated by Aldor from file "enum0.as".
 */

#include "foam_c.h"

typedef struct Fmt5  *PFmt5;
struct Fmt5 {
        FiWord X0_Boolean;
        FiWord X1_Character;
        FiWord X2_TextWriter;
        FiClos X3__LT__LT_;
        FiClos X4__LT__LT_;
        FiWord X5_newline;
        FiWord X6_print;
        FiWord X7_dom;
        FiWord X8_dom;
        FiWord X9_dom;
        FiBool X10;
        FiBool X11;
        FiBool X12;
};
static FiProg C0_enum0;
static void CF0_enum0(FiEnv e1);
static FiProg C1_char_MINUS_init;
static FiWord CF1_char_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C2_textwrit_MINUS_init;
static FiWord CF2_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C3_boolean_MINUS_init;
static FiWord CF3_boolean_MINUS_init(FiEnv e1, FiSInt P0_idx);
extern FiClos G_WTL3P_enum0;
static FiClos *pG_NQYQM_noOperation;
static FiClos *pG_XIPRL_runtime;
static FiWord *pG_NBIQ7_textwrit__TextWriter;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiWord *pG_M9OLC_boolean__Boolean__494;
static FiClos *pG_QRAZA_rtDelayedGetExport;
static FiClos *pG_DLXW8_stdGetWordWordRetWord;
static FiWord *pG_4KA9O_char__Character__1578;
static FiClos *pG_AKTR8_char;
static FiClos *pG_EC2QI_textwrit;
static FiClos *pG_P63GL_boolean;



static void
CF0_enum0(FiEnv e1)
{
        FiWord T3, T4;
        FiClos T0, T1, T2;
        PFmt5 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt5 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCCall0(void, (*pG_XIPRL_runtime));
        G_WTL3P_enum0 = (FiClos) (*pG_NQYQM_noOperation);
        T0 = fiClosMake(e0, C2_textwrit_MINUS_init);
        T1 = fiClosMake(e0, C3_boolean_MINUS_init);
        T2 = fiClosMake(e0, C1_char_MINUS_init);
        l0->X10 = 0L;
        l0->X11 = 0L;
        l0->X12 = 0L;
        l0->X2_TextWriter = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T0, 0L);
        l0->X7_dom = l0->X2_TextWriter;
        l0->X6_print = fiCCall3(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X7_dom, 828947258L, 182752316L);
        l0->X0_Boolean = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T1, 0L);
        l0->X8_dom = l0->X0_Boolean;
        T3 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X8_dom, 
        	51492426L, 212729660L);
        l0->X3__LT__LT_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T3);
        l0->X1_Character = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T2, 0L);
        l0->X9_dom = l0->X1_Character;
        l0->X5_newline = fiCCall3(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X9_dom, 493486801L, 803414590L);
        T3 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X9_dom, 
        	51492426L, 186261308L);
        l0->X4__LT__LT_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T3);
        T3 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l0->X6_print);
        T3 = fiCCall2(FiWord, l0->X3__LT__LT_, T3, 1L);
        T4 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l0->
        	X5_newline);
        fiCCall2(FiWord, l0->X4__LT__LT_, T3, T4);
        T3 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l0->X6_print);
        T3 = fiCCall2(FiWord, l0->X3__LT__LT_, T3, 0L);
        T4 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l0->
        	X5_newline);
        fiCCall2(FiWord, l0->X4__LT__LT_, T3, T4);
        T3 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l0->X6_print);
        T3 = fiCCall2(FiWord, l0->X3__LT__LT_, T3, 1L);
        T4 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l0->
        	X5_newline);
        fiCCall2(FiWord, l0->X4__LT__LT_, T3, T4);
        return ;
}

static struct _FiProg  tmp0_enum0 = {
        (FiFun) CF0_enum0,
        0L,
        0L,
        0L
};


static FiWord
CF1_char_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X10) goto L0;
        l1->X10 = 1L;
        fiCCall0(void, (*pG_AKTR8_char));
L0:	return (FiWord) (*pG_4KA9O_char__Character__1578);
}

static struct _FiProg  tmp1_char_MINUS_init = {
        (FiFun) CF1_char_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF2_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X11) goto L0;
        l1->X11 = 1L;
        fiCCall0(void, (*pG_EC2QI_textwrit));
L0:	return (FiWord) (*pG_NBIQ7_textwrit__TextWriter);
}

static struct _FiProg  tmp2_textwrit_MINUS_init = {
        (FiFun) CF2_textwrit_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF3_boolean_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X12) goto L0;
        l1->X12 = 1L;
        fiCCall0(void, (*pG_P63GL_boolean));
L0:	return (FiWord) (*pG_M9OLC_boolean__Boolean__494);
}

static struct _FiProg  tmp3_boolean_MINUS_init = {
        (FiFun) CF3_boolean_MINUS_init,
        0L,
        0L,
        0L
};

extern int
INIT__0_enum0(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_boolean(void);
        extern int INIT__0_textwrit(void);
        extern int INIT__0_char(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_char_MINUS_init = &tmp1_char_MINUS_init;
        C2_textwrit_MINUS_init = &tmp2_textwrit_MINUS_init;
        C3_boolean_MINUS_init = &tmp3_boolean_MINUS_init;
        C0_enum0 = &tmp0_enum0;
        fiExportGlobal("G_WTL3P_enum0", G_WTL3P_enum0);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_NBIQ7_textwrit__TextWriter__", 
        	pG_NBIQ7_textwrit__TextWriter);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_M9OLC_boolean__Boolean__4942", 
        	pG_M9OLC_boolean__Boolean__494);
        fiImportGlobal("G_QRAZA_rtDelayedGetExport", 
        	pG_QRAZA_rtDelayedGetExport);
        fiImportGlobal("G_DLXW8_stdGetWordWordRetWord0", 
        	pG_DLXW8_stdGetWordWordRetWord);
        fiImportGlobal("G_4KA9O_char__Character__15781", 
        	pG_4KA9O_char__Character__1578);
        fiImportGlobal("G_AKTR8_char", pG_AKTR8_char);
        fiImportGlobal("G_EC2QI_textwrit", pG_EC2QI_textwrit);
        fiImportGlobal("G_P63GL_boolean", pG_P63GL_boolean);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("boolean");
                fiFileInitializer("textwrit");
                fiFileInitializer("char");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_boolean();
                INIT__0_textwrit();
                INIT__0_char();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}


static struct _FiClos  tmpClos0_enum0 = {
        0L,
        (FiProg) &tmp0_enum0
};
FiClos G_WTL3P_enum0 = &tmpClos0_enum0;
