/*
 * C code generated by Aldor from file "fact.as".
 */

#include "foam_c.h"

typedef struct Fmt5  *PFmt5;
struct Fmt5 {
        FiWord X0_Integer;
        FiClos X1__LT_;
        FiClos X2__MINUS_;
        FiWord X3_1;
        FiClos X4__STAR_;
        FiWord X5_dom;
        FiBool X6;
};
static FiProg C0_fact;
static void CF0_fact(FiEnv e1);
static FiProg C1_factorial;
static FiWord CF1_factorial(FiEnv e1, FiWord P0_n);
static FiProg C2_integer_MINUS_init;
static FiWord CF2_integer_MINUS_init(FiEnv e1, FiSInt P0_idx);
extern FiClos G_9M4BW_fact;
static FiClos *pG_NQYQM_noOperation;
extern FiClos G_GULGK_fact__factorial__84784;
static FiClos *pG_XIPRL_runtime;
static FiWord *pG_MGD01_integer__Integer__856;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiClos *pG_QRAZA_rtDelayedGetExport;
static FiClos *pG_DLXW8_stdGetWordWordRetWord;
static FiClos *pG_WJ27Y_integer;



static void
CF0_fact(FiEnv e1)
{
        FiWord T1;
        FiClos T0;
        PFmt5 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt5 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCCall0(void, (*pG_XIPRL_runtime));
        G_9M4BW_fact = (FiClos) (*pG_NQYQM_noOperation);
        T0 = fiClosMake(e0, C2_integer_MINUS_init);
        G_GULGK_fact__factorial__84784 = fiClosMake(e0, C1_factorial);
        l0->X6 = 0L;
        l0->X0_Integer = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T0, 0L);
        l0->X5_dom = l0->X0_Integer;
        l0->X3_1 = fiCCall3(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X5_dom, 200090L, 484208045L);
        T1 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X5_dom, 
        	200101L, 651003586L);
        l0->X1__LT_ = fiCCall1(FiClos, (*pG_DLXW8_stdGetWordWordRetWord), 
        	T1);
        T1 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X5_dom, 
        	200086L, 394967248L);
        l0->X2__MINUS_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T1);
        T1 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X5_dom, 
        	200083L, 394967248L);
        l0->X4__STAR_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T1);
        return ;
}

static struct _FiProg  tmp0_fact = {
        (FiFun) CF0_fact,
        0L,
        0L,
        0L
};


static FiWord
CF1_factorial(FiEnv e1, FiWord P0_n)
{
        FiWord T0, T1;
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        T1 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l1->X3_1);
        if ((FiBool) fiCCall2(FiWord, l1->X1__LT_, P0_n, T1)) goto L0;
        T1 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l1->X3_1);
        T1 = fiCCall2(FiWord, l1->X2__MINUS_, P0_n, T1);
        T1 = CF1_factorial(e1, (FiWord) T1);
        T0 = fiCCall2(FiWord, l1->X4__STAR_, P0_n, T1);
        goto L1;
L0:	T0 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l1->X3_1);
L1:	return T0;
}

static struct _FiProg  tmp1_factorial = {
        (FiFun) CF1_factorial,
        0L,
        0L,
        0L
};


static FiWord
CF2_integer_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X6) goto L0;
        l1->X6 = 1L;
        fiCCall0(void, (*pG_WJ27Y_integer));
L0:	return (FiWord) (*pG_MGD01_integer__Integer__856);
}

static struct _FiProg  tmp2_integer_MINUS_init = {
        (FiFun) CF2_integer_MINUS_init,
        0L,
        0L,
        0L
};

extern int
INIT__0_fact(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_integer(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_factorial = &tmp1_factorial;
        C2_integer_MINUS_init = &tmp2_integer_MINUS_init;
        C0_fact = &tmp0_fact;
        fiExportGlobal("G_9M4BW_fact", G_9M4BW_fact);
        fiExportGlobal("G_GULGK_fact__factorial__84784", 
        	G_GULGK_fact__factorial__84784);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_MGD01_integer__Integer__8561", 
        	pG_MGD01_integer__Integer__856);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_QRAZA_rtDelayedGetExport", 
        	pG_QRAZA_rtDelayedGetExport);
        fiImportGlobal("G_DLXW8_stdGetWordWordRetWord0", 
        	pG_DLXW8_stdGetWordWordRetWord);
        fiImportGlobal("G_WJ27Y_integer", pG_WJ27Y_integer);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("integer");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_integer();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}

FiClos G_GULGK_fact__factorial__84784;

static struct _FiClos  tmpClos0_fact = {
        0L,
        (FiProg) &tmp0_fact
};
FiClos G_9M4BW_fact = &tmpClos0_fact;
