/*
 * C code generated by Aldor from file "forn3.as".
 */

#include "foam_c.h"

typedef struct Fmt7  *PFmt7;
typedef struct Fmt8  *PFmt8;
typedef struct Fmt9  *PFmt9;
typedef struct Fmt10  *PFmt10;
typedef struct Fmt11  *PFmt11;
typedef struct Fmt12  *PFmt12;
typedef struct Fmt13  *PFmt13;
typedef struct Fmt14  *PFmt14;
typedef struct Fmt15  *PFmt15;
typedef struct Fmt16  *PFmt16;
typedef struct Fmt17  *PFmt17;
typedef struct Fmt18  *PFmt18;
typedef struct Fmt19  *PFmt19;
typedef struct Fmt20  *PFmt20;
struct Fmt7 {
        FiPtr X0_empty;
};
struct Fmt8 {
        FiPtr X0_empty;
};
struct Fmt9 {
        FiWord X0;
        FiWord X1;
};
struct Fmt10 {
        FiPtr X0_empty;
};
struct Fmt11 {
        FiWord X0_TextWriter;
        FiWord X1_print;
        FiWord X2_dom;
        FiBool X3;
};
struct Fmt12 {
        FiPtr X0_empty;
};
struct Fmt13 {
        FiClos X0;
        FiClos X1;
        FiClos X2;
};
struct Fmt14 {
        FiPtr X0_empty;
};
struct Fmt15 {
        FiPtr X0_empty;
};
struct Fmt16 {
        FiPtr X0_empty;
};
struct Fmt17 {
        FiPtr X0_empty;
};
struct Fmt18 {
        FiPtr X0_empty;
};
struct Fmt19 {
        FiPtr X0_empty;
};
struct Fmt20 {
        FiPtr X0_empty;
};
static FiProg C0_forn3;
static void CF0_forn3(FiEnv e1);
static FiProg C1_T1;
static void CF1_T1(FiEnv e1);
static FiProg C2_t1;
static void CF2_t1(FiEnv e1, FiClos P0_f);
static FiProg C3_foreignWrapper;
static FiDFlo CF3_foreignWrapper(FiEnv e1, FiDFlo P0);
static FiProg C4_foreignWrapper;
static FiDFlo CF4_foreignWrapper(FiEnv e1, FiDFlo P0);
static FiProg C5_foreignWrapper;
static FiDFlo CF5_foreignWrapper(FiEnv e1, FiDFlo P0);
static FiProg C6_T2;
static void CF6_T2(FiEnv e1);
static FiProg C7_foreignWrapper;
static void CF7_foreignWrapper(FiEnv e1, FiWord P0, FiWord* R0, FiWord* R1);
static FiProg C8_textwrit_MINUS_init;
static FiWord CF8_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx);
extern FiClos G_336E0_forn3;
static FiClos *pG_NQYQM_noOperation;
extern FiDFlo sin(FiDFlo P0);
extern FiDFlo cos(FiDFlo P0);
extern FiDFlo tan(FiDFlo P0);
extern void zzz(FiWord P0, FiPtr R0, FiPtr R1);
extern FiClos G_3UUT1_forn3__T2__778822608;
extern FiClos G_Q798B_forn3__T1__778822608;
static FiClos *pG_XIPRL_runtime;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiWord *pG_NBIQ7_textwrit__TextWriter;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiClos *pG_EC2QI_textwrit;
extern FiWord formatSInt();



static void
CF0_forn3(FiEnv e1)
{
        FiClos T0;
        PFmt11 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt11 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCCall0(void, (*pG_XIPRL_runtime));
        G_336E0_forn3 = (FiClos) (*pG_NQYQM_noOperation);
        T0 = fiClosMake(e0, C8_textwrit_MINUS_init);
        G_Q798B_forn3__T1__778822608 = fiClosMake(e0, C1_T1);
        G_3UUT1_forn3__T2__778822608 = fiClosMake(e0, C6_T2);
        l0->X3 = 0L;
        l0->X0_TextWriter = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T0, 0L);
        l0->X2_dom = l0->X0_TextWriter;
        l0->X1_print = fiCCall3(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X2_dom, 828947258L, 182752316L);
        CF1_T1(e0);
        return ;
}

static struct _FiProg  tmp0_forn3 = {
        (FiFun) CF0_forn3,
        0L,
        0L,
        0L
};


static void
CF1_T1(FiEnv e1)
{
        FiEnv e0;
        PFmt11 l1;
        e0 = fiEnvPush(fiNil, e1);
        l1 = (PFmt11) fiEnvLevel(e1);
        CF2_t1(e0, (FiClos) fiClosMake(e0, C3_foreignWrapper));
        CF2_t1(e0, (FiClos) fiClosMake(e0, C4_foreignWrapper));
        CF2_t1(e0, (FiClos) fiClosMake(e0, C5_foreignWrapper));
        return ;
}

static struct _FiProg  tmp1_T1 = {
        (FiFun) CF1_T1,
        0L,
        0L,
        0L
};


static void
CF2_t1(FiEnv e1, FiClos P0_f)
{
        FiSInt T11, T13, T18, T20, T29_a, T30, T31;
        FiDFlo T4, T22, T23, T24_double, T25_double, T26_double, T27_double, T28_double;
        FiWord T3, T14, T21;
        FiChar *T12, *T19;
        FiClos T0, T1, T2, T5, T6, T7, T8, T9, T10, T15, T16, T17;
        PFmt11 l2;
        FiEnv e2;
        e2 = fiEnvNext(e1);
        l2 = (PFmt11) fiEnvLevel(e2);
        T24_double = 0.0000000000000000;
        T25_double = 1.0000000000000000;
        T22 = T25_double - T24_double;
        fiSINT_TO_DFLO(T23, FiDFlo, 10L);
        T27_double = T22 / T23;
        T28_double = T24_double;
        T29_a = 1L;
L4:	if (T29_a <= 11L) goto L5;
        return ;
L5:	T14 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l2->X1_print);
        fiARRNEW_Char(T12, FiChar*, 51L);
        T12[0L] = 0L;
        T12[50L] = 0L;
        T13 = 1L;
L0:	if (T13 <= 50L) goto L1;
        fiFORMAT_DFLO(T30, FiSInt, T28_double, T12, 0L);
        ((void(*)(FiEnv , FiClos* , FiClos* , FiClos* )) fiRawCProg((
        	FiClos) T14))(((FiClos) T14)->env, &T8, &T9, &T10);
        fiCCall3(FiWord, T9, (FiWord) T12, (FiWord) 1L, (FiWord) 0L);
        fiFree((FiPtr) T12);
        ((void(*)(FiEnv , FiClos* , FiClos* , FiClos* )) fiRawCProg((
        	FiClos) T14))(((FiClos) T14)->env, &T5, &T6, &T7);
        fiCCall3(FiWord, T6, (FiWord) "->", (FiWord) 1L, (FiWord) 0L);
        T4 = ((FiDFlo(*)(FiEnv , FiDFlo )) fiRawCProg(P0_f))((P0_f)->
        	env, T28_double);
        T21 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l2->X1_print);
        fiARRNEW_Char(T19, FiChar*, 51L);
        T19[0L] = 0L;
        T19[50L] = 0L;
        T20 = 1L;
L2:	if (T20 <= 50L) goto L3;
        fiFORMAT_DFLO(T31, FiSInt, T4, T19, 0L);
        ((void(*)(FiEnv , FiClos* , FiClos* , FiClos* )) fiRawCProg((
        	FiClos) T21))(((FiClos) T21)->env, &T15, &T16, &T17);
        fiCCall3(FiWord, T16, (FiWord) T19, (FiWord) 1L, (FiWord) 0L);
        fiFree((FiPtr) T19);
        T3 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l2->X1_print);
        ((void(*)(FiEnv , FiClos* , FiClos* , FiClos* )) fiRawCProg((
        	FiClos) T3))(((FiClos) T3)->env, &T0, &T1, &T2);
        fiCCall1(void, T0, (FiWord) 10L);
        T26_double = T28_double + T27_double;
        T28_double = T26_double;
        T29_a = T29_a + 1L;
        goto L4;
L3:	T18 = T20 - 1L;
        T19[T18] = 32L;
        T20 = T20 + 1L;
        goto L2;
L1:	T11 = T13 - 1L;
        T12[T11] = 32L;
        T13 = T13 + 1L;
        goto L0;
}

static struct _FiProg  tmp2_t1 = {
        (FiFun) CF2_t1,
        0L,
        0L,
        0L
};


static FiDFlo
CF3_foreignWrapper(FiEnv e1, FiDFlo P0)
{
        return sin(P0);
}

static struct _FiProg  tmp3_foreignWrapper = {
        (FiFun) CF3_foreignWrapper,
        0L,
        0L,
        0L
};


static FiDFlo
CF4_foreignWrapper(FiEnv e1, FiDFlo P0)
{
        return cos(P0);
}

static struct _FiProg  tmp4_foreignWrapper = {
        (FiFun) CF4_foreignWrapper,
        0L,
        0L,
        0L
};


static FiDFlo
CF5_foreignWrapper(FiEnv e1, FiDFlo P0)
{
        return tan(P0);
}

static struct _FiProg  tmp5_foreignWrapper = {
        (FiFun) CF5_foreignWrapper,
        0L,
        0L,
        0L
};


static void
CF6_T2(FiEnv e1)
{
        FiWord T6, T7;
        FiClos T0, T1, T2, T3, T4, T5;
        FiEnv e0;
        PFmt11 l1;
        e0 = fiEnvPush(fiNil, e1);
        l1 = (PFmt11) fiEnvLevel(e1);
        T7 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l1->X1_print);
        T6 = formatSInt((FiSInt) fiClosMake(e0, C7_foreignWrapper));
        ((void(*)(FiEnv , FiClos* , FiClos* , FiClos* )) fiRawCProg((
        	FiClos) T7))(((FiClos) T7)->env, &T3, &T4, &T5);
        fiCCall3(FiWord, T4, T6, (FiWord) 1L, (FiWord) 0L);
        ((void(*)(FiEnv , FiClos* , FiClos* , FiClos* )) fiRawCProg((
        	FiClos) T7))(((FiClos) T7)->env, &T0, &T1, &T2);
        fiCCall1(void, T0, (FiWord) 10L);
        return ;
}

static struct _FiProg  tmp6_T2 = {
        (FiFun) CF6_T2,
        0L,
        0L,
        0L
};


static void
CF7_foreignWrapper(FiEnv e1, FiWord P0, FiWord* R0, FiWord* R1)
{
        FiWord T0, T1;
        zzz(P0, &T0, &T1);
        *R0 = T0;
        *R1 = T1;
        return ;
}

static struct _FiProg  tmp7_foreignWrapper = {
        (FiFun) CF7_foreignWrapper,
        0L,
        0L,
        0L
};


static FiWord
CF8_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt11 l1;
        l1 = (PFmt11) fiEnvLevel(e1);
        if (l1->X3) goto L0;
        l1->X3 = 1L;
        fiCCall0(void, (*pG_EC2QI_textwrit));
L0:	return (FiWord) (*pG_NBIQ7_textwrit__TextWriter);
}

static struct _FiProg  tmp8_textwrit_MINUS_init = {
        (FiFun) CF8_textwrit_MINUS_init,
        0L,
        0L,
        0L
};

extern int
INIT__0_forn3(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_textwrit(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_T1 = &tmp1_T1;
        C2_t1 = &tmp2_t1;
        C3_foreignWrapper = &tmp3_foreignWrapper;
        C4_foreignWrapper = &tmp4_foreignWrapper;
        C5_foreignWrapper = &tmp5_foreignWrapper;
        C6_T2 = &tmp6_T2;
        C7_foreignWrapper = &tmp7_foreignWrapper;
        C8_textwrit_MINUS_init = &tmp8_textwrit_MINUS_init;
        C0_forn3 = &tmp0_forn3;
        fiExportGlobal("G_336E0_forn3", G_336E0_forn3);
        fiExportGlobal("G_3UUT1_forn3__T2__778822608", 
        	G_3UUT1_forn3__T2__778822608);
        fiExportGlobal("G_Q798B_forn3__T1__778822608", 
        	G_Q798B_forn3__T1__778822608);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_NBIQ7_textwrit__TextWriter__", 
        	pG_NBIQ7_textwrit__TextWriter);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_EC2QI_textwrit", pG_EC2QI_textwrit);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("textwrit");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_textwrit();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}

FiClos G_Q798B_forn3__T1__778822608;
FiClos G_3UUT1_forn3__T2__778822608;

static struct _FiClos  tmpClos0_forn3 = {
        0L,
        (FiProg) &tmp0_forn3
};
FiClos G_336E0_forn3 = &tmpClos0_forn3;
