/*
 * C code generated by Aldor from file "forn2.as".
 */

#include "foam_c.h"

typedef struct Fmt5  *PFmt5;
struct Fmt5 {
        FiWord X0_SingleInteger;
        FiWord X1_Character;
        FiWord X2_String;
        FiWord X3_TextWriter;
        FiClos X4_string;
        FiClos X5__LT__LT_;
        FiClos X6__LT__LT_;
        FiWord X7_newline;
        FiWord X8_print;
        FiClos X9__LT__LT_;
        FiWord X10_dom;
        FiWord X11_dom;
        FiWord X12_dom;
        FiWord X13_dom;
        FiBool X14;
        FiBool X15;
        FiBool X16;
        FiBool X17;
};
static FiProg C0_forn2;
static void CF0_forn2(FiEnv e1);
static FiProg C1_string_MINUS_init;
static FiWord CF1_string_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C2_char_MINUS_init;
static FiWord CF2_char_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C3_textwrit_MINUS_init;
static FiWord CF3_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C4_sinteger_MINUS_init;
static FiWord CF4_sinteger_MINUS_init(FiEnv e1, FiSInt P0_idx);
extern FiClos G_336DZ_forn2;
static FiClos *pG_NQYQM_noOperation;
extern FiWord errno;
static FiClos *pG_XIPRL_runtime;
static FiWord *pG_NBIQ7_textwrit__TextWriter;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiWord *pG_FXGEB_string__String__51771;
static FiClos *pG_QRAZA_rtDelayedGetExport;
static FiClos *pG_ZZZKG_stdGetWordRetWord0;
static FiClos *pG_DLXW8_stdGetWordWordRetWord;
static FiWord *pG_JWPLO_sinteger__SingleInteg;
static FiWord *pG_4KA9O_char__Character__1578;
static FiClos *pG_OGNYK_string;
static FiClos *pG_AKTR8_char;
static FiClos *pG_EC2QI_textwrit;
static FiClos *pG_HAQ5R_sinteger;



static void
CF0_forn2(FiEnv e1)
{
        FiWord T4, T5;
        FiClos T0, T1, T2, T3;
        PFmt5 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt5 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCCall0(void, (*pG_XIPRL_runtime));
        G_336DZ_forn2 = (FiClos) (*pG_NQYQM_noOperation);
        T0 = fiClosMake(e0, C3_textwrit_MINUS_init);
        T1 = fiClosMake(e0, C1_string_MINUS_init);
        T2 = fiClosMake(e0, C4_sinteger_MINUS_init);
        T3 = fiClosMake(e0, C2_char_MINUS_init);
        l0->X14 = 0L;
        l0->X15 = 0L;
        l0->X16 = 0L;
        l0->X17 = 0L;
        l0->X3_TextWriter = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T0, 0L);
        l0->X10_dom = l0->X3_TextWriter;
        l0->X8_print = fiCCall3(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X10_dom, 828947258L, 182752316L);
        l0->X2_String = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), T1, 
        	0L);
        l0->X11_dom = l0->X2_String;
        T4 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X11_dom, 585283853L, 406869008L);
        l0->X4_string = fiCCall1(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T4);
        T4 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X11_dom, 51492426L, 981655356L);
        l0->X5__LT__LT_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T4);
        l0->X0_SingleInteger = fiCCall2(FiWord, (*
        	pG_KK8CX_rtLazyDomFrInit), T2, 0L);
        l0->X12_dom = l0->X0_SingleInteger;
        T4 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X12_dom, 51492426L, 941383484L);
        l0->X9__LT__LT_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T4);
        l0->X1_Character = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T3, 0L);
        l0->X13_dom = l0->X1_Character;
        l0->X7_newline = fiCCall3(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X13_dom, 493486801L, 803414590L);
        T4 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X13_dom, 51492426L, 186261308L);
        l0->X6__LT__LT_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T4);
        T4 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l0->X8_print);
        T5 = fiCCall1(FiWord, l0->X4_string, (FiWord) "Errno is");
        T4 = fiCCall2(FiWord, l0->X5__LT__LT_, T4, T5);
        T4 = fiCCall2(FiWord, l0->X9__LT__LT_, T4, errno);
        T5 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l0->
        	X7_newline);
        fiCCall2(FiWord, l0->X6__LT__LT_, T4, T5);
        return ;
}

static struct _FiProg  tmp0_forn2 = {
        (FiFun) CF0_forn2,
        0L,
        0L,
        0L
};


static FiWord
CF1_string_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X14) goto L0;
        l1->X14 = 1L;
        fiCCall0(void, (*pG_OGNYK_string));
L0:	return (FiWord) (*pG_FXGEB_string__String__51771);
}

static struct _FiProg  tmp1_string_MINUS_init = {
        (FiFun) CF1_string_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF2_char_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X15) goto L0;
        l1->X15 = 1L;
        fiCCall0(void, (*pG_AKTR8_char));
L0:	return (FiWord) (*pG_4KA9O_char__Character__1578);
}

static struct _FiProg  tmp2_char_MINUS_init = {
        (FiFun) CF2_char_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF3_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X16) goto L0;
        l1->X16 = 1L;
        fiCCall0(void, (*pG_EC2QI_textwrit));
L0:	return (FiWord) (*pG_NBIQ7_textwrit__TextWriter);
}

static struct _FiProg  tmp3_textwrit_MINUS_init = {
        (FiFun) CF3_textwrit_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF4_sinteger_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X17) goto L0;
        l1->X17 = 1L;
        fiCCall0(void, (*pG_HAQ5R_sinteger));
L0:	return (FiWord) (*pG_JWPLO_sinteger__SingleInteg);
}

static struct _FiProg  tmp4_sinteger_MINUS_init = {
        (FiFun) CF4_sinteger_MINUS_init,
        0L,
        0L,
        0L
};

extern int
INIT__0_forn2(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_sinteger(void);
        extern int INIT__0_textwrit(void);
        extern int INIT__0_char(void);
        extern int INIT__0_string(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_string_MINUS_init = &tmp1_string_MINUS_init;
        C2_char_MINUS_init = &tmp2_char_MINUS_init;
        C3_textwrit_MINUS_init = &tmp3_textwrit_MINUS_init;
        C4_sinteger_MINUS_init = &tmp4_sinteger_MINUS_init;
        C0_forn2 = &tmp0_forn2;
        fiExportGlobal("G_336DZ_forn2", G_336DZ_forn2);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_NBIQ7_textwrit__TextWriter__", 
        	pG_NBIQ7_textwrit__TextWriter);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_FXGEB_string__String__517719", 
        	pG_FXGEB_string__String__51771);
        fiImportGlobal("G_QRAZA_rtDelayedGetExport", 
        	pG_QRAZA_rtDelayedGetExport);
        fiImportGlobal("G_ZZZKG_stdGetWordRetWord0", 
        	pG_ZZZKG_stdGetWordRetWord0);
        fiImportGlobal("G_DLXW8_stdGetWordWordRetWord0", 
        	pG_DLXW8_stdGetWordWordRetWord);
        fiImportGlobal("G_JWPLO_sinteger__SingleIntege", 
        	pG_JWPLO_sinteger__SingleInteg);
        fiImportGlobal("G_4KA9O_char__Character__15781", 
        	pG_4KA9O_char__Character__1578);
        fiImportGlobal("G_OGNYK_string", pG_OGNYK_string);
        fiImportGlobal("G_AKTR8_char", pG_AKTR8_char);
        fiImportGlobal("G_EC2QI_textwrit", pG_EC2QI_textwrit);
        fiImportGlobal("G_HAQ5R_sinteger", pG_HAQ5R_sinteger);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("sinteger");
                fiFileInitializer("textwrit");
                fiFileInitializer("char");
                fiFileInitializer("string");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_sinteger();
                INIT__0_textwrit();
                INIT__0_char();
                INIT__0_string();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}


static struct _FiClos  tmpClos0_forn2 = {
        0L,
        (FiProg) &tmp0_forn2
};
FiClos G_336DZ_forn2 = &tmpClos0_forn2;
