/*
 * C code generated by Aldor from file "forn6.as".
 */

#include "foam_c.h"

#include <string.h>

typedef struct Fmt9  *PFmt9;
typedef struct Fmt10  *PFmt10;
typedef struct Fmt11  *PFmt11;
typedef struct Fmt12  *PFmt12;
typedef struct Fmt13  *PFmt13;
typedef struct Fmt14  *PFmt14;
typedef struct Fmt15  *PFmt15;
struct Fmt9 {
        FiPtr X0_empty;
};
struct Fmt10 {
        FiSInt X0_int;
};
struct Fmt11 {
        FiSFlo X0_real;
        FiSFlo X1_imag;
};
struct Fmt12 {
        FiWord X0_real;
        FiWord X1_imag;
};
struct Fmt13 {
        FiDFlo X0_double;
};
struct Fmt14 {
        FiSFlo X0_float;
};
struct Fmt15 {
        FiWord X0_SingleInteger;
        FiWord X1_Character;
        FiWord X2_String;
        FiWord X3_SingleFloat;
        FiWord X4_DoubleFloat;
        FiClos X5_Complex;
        FiWord X6_TextWriter;
        FiClos X7__LT__LT_;
        FiClos X8__LT__LT_;
        FiWord X9_newline;
        FiWord X10_print;
        FiClos X11__LT__LT_;
        FiWord X12_1;
        FiClos X13__LT__LT_;
        FiClos X14_float;
        FiClos X15_real;
        FiWord X16_dom;
        FiWord X17_dom;
        FiWord X18_dom;
        FiWord X19_dom;
        FiWord X20_dom;
        FiWord X21_dom;
        FiWord X22_dom;
        FiBool X23;
        FiBool X24;
        FiBool X25;
        FiBool X26;
        FiBool X27;
        FiBool X28;
        FiBool X29;
};
static FiProg C0_forn6;
static void CF0_forn6(FiEnv e1);
static FiProg C1_xl1;
static FiWord CF1_xl1(FiEnv e1, FiWord P0_a, FiWord P1_b);
static FiProg C2_xl2;
static void CF2_xl2(FiEnv e1, FiWord P0_a, FiWord P1_b);
static FiProg C3_x;
static FiDFlo CF3_x(FiEnv e1, FiWord P0_x0, FiWord P1_x1);
static FiProg C4_x;
static void CF4_x(FiEnv e1, FiWord P0_x0, FiWord P1_x1);
static FiProg C5_x;
static FiDFlo CF5_x(FiEnv e1, FiWord P0_x0, FiWord P1_x1);
static FiProg C6_x;
static void CF6_x(FiEnv e1, FiWord P0_x0, FiWord P1_x1);
static FiProg C7_x;
static FiDFlo CF7_x(FiEnv e1, FiWord P0_x0, FiWord P1_x1);
static FiProg C8_x;
static void CF8_x(FiEnv e1, FiWord P0_x0, FiWord P1_x1);
static FiProg C9_foreignWrapper;
static FiWord CF9_foreignWrapper(FiEnv e1, FiWord P0, FiWord P1);
static FiProg C10_x;
static FiDFlo CF10_x(FiEnv e1, FiWord P0_x0, FiWord P1_x1);
static FiProg C11_x;
static void CF11_x(FiEnv e1, FiWord P0_x0, FiWord P1_x1);
static FiProg C12_string_MINUS_init;
static FiWord CF12_string_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C13_dfloat_MINUS_init;
static FiWord CF13_dfloat_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C14_char_MINUS_init;
static FiWord CF14_char_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C15_textwrit_MINUS_init;
static FiWord CF15_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C16_sinteger_MINUS_init;
static FiWord CF16_sinteger_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C17_complex_MINUS_init;
static FiWord CF17_complex_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C18_sfloat_MINUS_init;
static FiWord CF18_sfloat_MINUS_init(FiEnv e1, FiSInt P0_idx);
extern FiClos G_336E3_forn6;
static FiClos *pG_NQYQM_noOperation;
extern FiSInt x_();
static FiClos GFtnClo__x0;
static FiDFlo GFtnPar__x0();
static FiClos GFtnClo__x1;
static void GFtnPar__x1();
extern FiDFlo y_();
extern FiClos G_4WKMJ_forn6__xl2__953380000;
extern FiClos G_A7UEE_forn6__xl1__201174703;
static FiClos *pG_XIPRL_runtime;
static FiWord *pG_NBIQ7_textwrit__TextWriter;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_LD0B5_domainHash_BANG_;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiWord *pG_JWPLO_sinteger__SingleInteg;
static FiClos *pG_QRAZA_rtDelayedGetExport;
static FiClos *pG_DLXW8_stdGetWordWordRetWord;
static FiWord *pG_7Q898_sfloat__SingleFloat__;
static FiClos *pG_LM9I3_complex__Complex__500;
static FiClos *pG_RSHLY_rtDelayedInit_BANG_;
static FiClos *pG_ZZZKG_stdGetWordRetWord0;
static FiWord *pG_4KA9O_char__Character__1578;
static FiWord *pG_KJ3UJ_dfloat__DoubleFloat__;
static FiWord *pG_FXGEB_string__String__51771;
static FiClos *pG_OGNYK_string;
static FiClos *pG_DEGQL_dfloat;
static FiClos *pG_AKTR8_char;
static FiClos *pG_EC2QI_textwrit;
static FiClos *pG_HAQ5R_sinteger;
static FiClos *pG_I0RMM_complex;
static FiClos *pG_T13QO_sfloat;


static FiDFlo
GFtnPar__x0(FiWord P0, FiWord P1)
{
        FiDFlo T0;
        T0 = (FiDFlo) ((FiDFlo(*)(FiEnv , FiWord , FiWord )) 
        	fiRawCProg(GFtnClo__x0))((GFtnClo__x0)->env, (FiWord) P0, (
        	FiWord) P1);
        return T0;
}

static void
GFtnPar__x1(FiWord P0, FiWord P1, int CHRLEN0)
{
        FiWord T1;
        fiARRNEW_Char(T1, FiWord, CHRLEN0 + 1);
        strncpy((char *) T1, (char *) P1, CHRLEN0);
        ((char *) T1)[CHRLEN0] = (char ) 0;
        fiCCall2(void, GFtnClo__x1, P0, T1);
}


static void
CF0_forn6(FiEnv e1)
{
        FiWord T14, T18, T22, T23;
        FiClos T0, T1, T2, T3, T5, T6, T7, T8, T10, T11, T13, T15, T17, T19, T21;
        PFmt10 T9, T12, T16, T20;
        FiSInt T4;
        PFmt15 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt15 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCCall0(void, (*pG_XIPRL_runtime));
        G_336E3_forn6 = (FiClos) (*pG_NQYQM_noOperation);
        T0 = fiClosMake(e0, C15_textwrit_MINUS_init);
        T1 = fiClosMake(e0, C16_sinteger_MINUS_init);
        T2 = fiClosMake(e0, C18_sfloat_MINUS_init);
        T3 = fiClosMake(e0, C17_complex_MINUS_init);
        T5 = fiClosMake(e0, C14_char_MINUS_init);
        T6 = fiClosMake(e0, C13_dfloat_MINUS_init);
        G_A7UEE_forn6__xl1__201174703 = fiClosMake(e0, C1_xl1);
        T7 = fiClosMake(e0, C12_string_MINUS_init);
        G_4WKMJ_forn6__xl2__953380000 = fiClosMake(e0, C2_xl2);
        l0->X23 = 0L;
        l0->X24 = 0L;
        l0->X25 = 0L;
        l0->X26 = 0L;
        l0->X27 = 0L;
        l0->X28 = 0L;
        l0->X29 = 0L;
        l0->X6_TextWriter = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T0, 0L);
        l0->X16_dom = l0->X6_TextWriter;
        l0->X10_print = fiCCall3(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X16_dom, 828947258L, 182752316L);
        l0->X0_SingleInteger = fiCCall2(FiWord, (*
        	pG_KK8CX_rtLazyDomFrInit), T1, 0L);
        l0->X17_dom = l0->X0_SingleInteger;
        T22 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X17_dom, 51492426L, 941383484L);
        l0->X11__LT__LT_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T22);
        l0->X3_SingleFloat = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T2, 0L);
        T22 = fiCCall2(FiWord, (*pG_RSHLY_rtDelayedInit_BANG_), T3, 0L);
        l0->X5_Complex = fiCCall1(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T22);
        l0->X18_dom = fiCCall1(FiWord, l0->X5_Complex, l0->
        	X3_SingleFloat);
        fiEnvEnsure(l0->X5_Complex->env);
        T4 = 763117211L;
L1:	T22 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X18_dom, 
        	715535944L, (189518043L + (((32236L + (((
        	T4 + 74075968L) % 1073741789L & 16777215L) << 6L)) % 
        	1073741789L & 16777215L) << 6L)) % 1073741789L);
        l0->X15_real = fiCCall1(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T22);
        l0->X19_dom = l0->X3_SingleFloat;
        T22 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X19_dom, 51492426L, 369213244L);
        l0->X13__LT__LT_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T22);
        l0->X1_Character = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T5, 0L);
        l0->X20_dom = l0->X1_Character;
        l0->X9_newline = fiCCall3(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X20_dom, 493486801L, 803414590L);
        T22 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X20_dom, 51492426L, 186261308L);
        l0->X8__LT__LT_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T22);
        l0->X4_DoubleFloat = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T6, 0L);
        l0->X21_dom = l0->X4_DoubleFloat;
        T22 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X21_dom, 474568739L, 634651895L);
        l0->X14_float = fiCCall1(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T22);
        l0->X2_String = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), T7, 
        	0L);
        l0->X22_dom = l0->X2_String;
        T22 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X22_dom, 51492426L, 981655356L);
        l0->X7__LT__LT_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T22);
        l0->X12_1 = fiCCall3(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X17_dom, 200090L, 142471813L);
        T8 = fiClosMake(e0, C3_x);
        T9 = fi0RecNew(struct Fmt10 , CENSUS_Rec);
        T9->X0_int = (FiSInt) fiCCall1(FiWord, (*
        	pG_R3D1K_lazyForceImport), l0->X12_1);
        T10 = fiClosMake(e0, C4_x);
        if (GFtnClo__x0) fiHalt((FiSInt) 105);
        GFtnClo__x0 = T8;
        if (GFtnClo__x1) fiHalt((FiSInt) 105);
        GFtnClo__x1 = T10;
        x_(GFtnPar__x0, (FiWord) T9, GFtnPar__x1);
        GFtnClo__x0 = NULL;
        GFtnClo__x1 = NULL;
        T11 = fiClosMake(e0, C5_x);
        T12 = fi0RecNew(struct Fmt10 , CENSUS_Rec);
        T12->X0_int = (FiSInt) fiCCall1(FiWord, (*
        	pG_R3D1K_lazyForceImport), l0->X12_1);
        T13 = fiClosMake(e0, C6_x);
        if (GFtnClo__x0) fiHalt((FiSInt) 105);
        GFtnClo__x0 = T11;
        if (GFtnClo__x1) fiHalt((FiSInt) 105);
        GFtnClo__x1 = T13;
        T14 = x_(GFtnPar__x0, (FiWord) T12, GFtnPar__x1);
        GFtnClo__x0 = NULL;
        GFtnClo__x1 = NULL;
        T15 = fiClosMake(e0, C7_x);
        T16 = fi0RecNew(struct Fmt10 , CENSUS_Rec);
        T16->X0_int = (FiSInt) fiCCall1(FiWord, (*
        	pG_R3D1K_lazyForceImport), l0->X12_1);
        T17 = fiClosMake(e0, C8_x);
        if (GFtnClo__x0) fiHalt((FiSInt) 105);
        GFtnClo__x0 = T15;
        if (GFtnClo__x1) fiHalt((FiSInt) 105);
        GFtnClo__x1 = T17;
        T18 = x_(GFtnPar__x0, (FiWord) T16, GFtnPar__x1);
        GFtnClo__x0 = NULL;
        GFtnClo__x1 = NULL;
        T22 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l0->
        	X10_print);
        T22 = fiCCall2(FiWord, l0->X11__LT__LT_, T22, T14);
        T22 = fiCCall2(FiWord, l0->X11__LT__LT_, T22, T18);
        T23 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l0->
        	X9_newline);
        fiCCall2(FiWord, l0->X8__LT__LT_, T22, T23);
        T19 = fiClosMake(e0, C10_x);
        T20 = fi0RecNew(struct Fmt10 , CENSUS_Rec);
        T20->X0_int = (FiSInt) fiCCall1(FiWord, (*
        	pG_R3D1K_lazyForceImport), l0->X12_1);
        T21 = fiClosMake(e0, C11_x);
        if (GFtnClo__x0) fiHalt((FiSInt) 105);
        GFtnClo__x0 = T19;
        if (GFtnClo__x1) fiHalt((FiSInt) 105);
        GFtnClo__x1 = T21;
        x_(GFtnPar__x0, (FiWord) T20, GFtnPar__x1);
        GFtnClo__x0 = NULL;
        GFtnClo__x1 = NULL;
        return ;
L0:	T22 = fiCCall1(FiWord, l0->X5_Complex, l0->X3_SingleFloat);
        T4 = fiCCall1(FiSInt, (*pG_LD0B5_domainHash_BANG_), T22);
        goto L1;
}

static struct _FiProg  tmp0_forn6 = {
        (FiFun) CF0_forn6,
        0L,
        0L,
        0L
};


static FiWord
CF1_xl1(FiEnv e1, FiWord P0_a, FiWord P1_b)
{
        FiWord T0, T1;
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        T0 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l1->X10_print);
        T0 = fiCCall2(FiWord, l1->X11__LT__LT_, T0, P0_a);
        T1 = fiCCall1(FiWord, l1->X15_real, P1_b);
        T0 = fiCCall2(FiWord, l1->X13__LT__LT_, T0, T1);
        T1 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l1->
        	X9_newline);
        fiCCall2(FiWord, l1->X8__LT__LT_, T0, T1);
        return fiCCall1(FiWord, l1->X14_float, (FiWord) "99.9");
}

static struct _FiProg  tmp1_xl1 = {
        (FiFun) CF1_xl1,
        0L,
        0L,
        0L
};


static void
CF2_xl2(FiEnv e1, FiWord P0_a, FiWord P1_b)
{
        FiWord T0, T1;
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        T0 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l1->X10_print);
        T0 = fiCCall2(FiWord, l1->X13__LT__LT_, T0, P0_a);
        T0 = fiCCall2(FiWord, l1->X7__LT__LT_, T0, P1_b);
        T1 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l1->
        	X9_newline);
        fiCCall2(FiWord, l1->X8__LT__LT_, T0, T1);
        return ;
}

static struct _FiProg  tmp2_xl2 = {
        (FiFun) CF2_xl2,
        0L,
        0L,
        0L
};


static FiDFlo
CF3_x(FiEnv e1, FiWord P0_x0, FiWord P1_x1)
{
        FiWord T0, T2;
        PFmt12 T1;
        FiEnv e0;
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        T0 = (FiWord) ((PFmt10) P0_x0)->X0_int;
        T1 = fi0RecNew(struct Fmt12 , CENSUS_Rec);
        fiWORD_FR_SFLO(T1->X0_real, ((PFmt11) P1_x1)->X0_real);
        fiWORD_FR_SFLO(T1->X1_imag, ((PFmt11) P1_x1)->X1_imag);
        T2 = fiCCall2(FiWord, G_A7UEE_forn6__xl1__201174703, T0, T1);
        return ((PFmt13) T2)->X0_double;
}

static struct _FiProg  tmp3_x = {
        (FiFun) CF3_x,
        0L,
        0L,
        0L
};


static void
CF4_x(FiEnv e1, FiWord P0_x0, FiWord P1_x1)
{
        FiWord T0;
        FiEnv e0;
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        fiWORD_FR_SFLO(T0, ((PFmt14) P0_x0)->X0_float);
        fiCCall2(void, G_4WKMJ_forn6__xl2__953380000, T0, P1_x1);
        return ;
}

static struct _FiProg  tmp4_x = {
        (FiFun) CF4_x,
        0L,
        0L,
        0L
};


static FiDFlo
CF5_x(FiEnv e1, FiWord P0_x0, FiWord P1_x1)
{
        FiWord T0, T2;
        PFmt12 T1;
        FiEnv e0;
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        T0 = (FiWord) ((PFmt10) P0_x0)->X0_int;
        T1 = fi0RecNew(struct Fmt12 , CENSUS_Rec);
        fiWORD_FR_SFLO(T1->X0_real, ((PFmt11) P1_x1)->X0_real);
        fiWORD_FR_SFLO(T1->X1_imag, ((PFmt11) P1_x1)->X1_imag);
        T2 = fiCCall2(FiWord, G_A7UEE_forn6__xl1__201174703, T0, T1);
        return ((PFmt13) T2)->X0_double;
}

static struct _FiProg  tmp5_x = {
        (FiFun) CF5_x,
        0L,
        0L,
        0L
};


static void
CF6_x(FiEnv e1, FiWord P0_x0, FiWord P1_x1)
{
        FiWord T0;
        FiEnv e0;
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        fiWORD_FR_SFLO(T0, ((PFmt14) P0_x0)->X0_float);
        fiCCall2(void, G_4WKMJ_forn6__xl2__953380000, T0, P1_x1);
        return ;
}

static struct _FiProg  tmp6_x = {
        (FiFun) CF6_x,
        0L,
        0L,
        0L
};


static FiDFlo
CF7_x(FiEnv e1, FiWord P0_x0, FiWord P1_x1)
{
        FiWord T0, T2;
        PFmt12 T1;
        FiEnv e0;
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        T0 = (FiWord) ((PFmt10) P0_x0)->X0_int;
        T1 = fi0RecNew(struct Fmt12 , CENSUS_Rec);
        fiWORD_FR_SFLO(T1->X0_real, ((PFmt11) P1_x1)->X0_real);
        fiWORD_FR_SFLO(T1->X1_imag, ((PFmt11) P1_x1)->X1_imag);
        T2 = fiCCall2(FiWord, G_A7UEE_forn6__xl1__201174703, T0, T1);
        return ((PFmt13) T2)->X0_double;
}

static struct _FiProg  tmp7_x = {
        (FiFun) CF7_x,
        0L,
        0L,
        0L
};


static void
CF8_x(FiEnv e1, FiWord P0_x0, FiWord P1_x1)
{
        FiWord T0;
        FiEnv e0;
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        fiWORD_FR_SFLO(T0, ((PFmt14) P0_x0)->X0_float);
        fiCCall2(void, G_4WKMJ_forn6__xl2__953380000, T0, P1_x1);
        return ;
}

static struct _FiProg  tmp8_x = {
        (FiFun) CF8_x,
        0L,
        0L,
        0L
};


static FiWord
CF9_foreignWrapper(FiEnv e1, FiWord P0, FiWord P1)
{
        PFmt13 T2;
        PFmt11 T1;
        PFmt10 T0;
        PFmt15 l0;
        FiEnv e0;
        T0 = fi0RecNew(struct Fmt10 , CENSUS_Rec);
        T0->X0_int = (FiSInt) P0;
        T1 = fi0RecNew(struct Fmt11 , CENSUS_Rec);
        fiSFLO_FR_WORD(T1->X0_real, ((PFmt12) P1)->X0_real);
        fiSFLO_FR_WORD(T1->X1_imag, ((PFmt12) P1)->X1_imag);
        T2 = fi0RecNew(struct Fmt13 , CENSUS_Rec);
        T2->X0_double = y_((FiWord) T0, T1);
        return (FiWord) T2;
}

static struct _FiProg  tmp9_foreignWrapper = {
        (FiFun) CF9_foreignWrapper,
        0L,
        0L,
        0L
};


static FiDFlo
CF10_x(FiEnv e1, FiWord P0_x0, FiWord P1_x1)
{
        FiWord T0, T2;
        PFmt12 T1;
        FiEnv e0;
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        T0 = (FiWord) ((PFmt10) P0_x0)->X0_int;
        T1 = fi0RecNew(struct Fmt12 , CENSUS_Rec);
        fiWORD_FR_SFLO(T1->X0_real, ((PFmt11) P1_x1)->X0_real);
        fiWORD_FR_SFLO(T1->X1_imag, ((PFmt11) P1_x1)->X1_imag);
        T2 = fiCCall2(FiWord, fiClosMake(e1, C9_foreignWrapper), T0, T1);
        return ((PFmt13) T2)->X0_double;
}

static struct _FiProg  tmp10_x = {
        (FiFun) CF10_x,
        0L,
        0L,
        0L
};


static void
CF11_x(FiEnv e1, FiWord P0_x0, FiWord P1_x1)
{
        FiWord T0;
        FiEnv e0;
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        fiWORD_FR_SFLO(T0, ((PFmt14) P0_x0)->X0_float);
        fiCCall2(void, G_4WKMJ_forn6__xl2__953380000, T0, P1_x1);
        return ;
}

static struct _FiProg  tmp11_x = {
        (FiFun) CF11_x,
        0L,
        0L,
        0L
};


static FiWord
CF12_string_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        if (l1->X23) goto L0;
        l1->X23 = 1L;
        fiCCall0(void, (*pG_OGNYK_string));
L0:	return (FiWord) (*pG_FXGEB_string__String__51771);
}

static struct _FiProg  tmp12_string_MINUS_init = {
        (FiFun) CF12_string_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF13_dfloat_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        if (l1->X24) goto L0;
        l1->X24 = 1L;
        fiCCall0(void, (*pG_DEGQL_dfloat));
L0:	return (FiWord) (*pG_KJ3UJ_dfloat__DoubleFloat__);
}

static struct _FiProg  tmp13_dfloat_MINUS_init = {
        (FiFun) CF13_dfloat_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF14_char_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        if (l1->X25) goto L0;
        l1->X25 = 1L;
        fiCCall0(void, (*pG_AKTR8_char));
L0:	return (FiWord) (*pG_4KA9O_char__Character__1578);
}

static struct _FiProg  tmp14_char_MINUS_init = {
        (FiFun) CF14_char_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF15_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        if (l1->X26) goto L0;
        l1->X26 = 1L;
        fiCCall0(void, (*pG_EC2QI_textwrit));
L0:	return (FiWord) (*pG_NBIQ7_textwrit__TextWriter);
}

static struct _FiProg  tmp15_textwrit_MINUS_init = {
        (FiFun) CF15_textwrit_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF16_sinteger_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        if (l1->X27) goto L0;
        l1->X27 = 1L;
        fiCCall0(void, (*pG_HAQ5R_sinteger));
L0:	return (FiWord) (*pG_JWPLO_sinteger__SingleInteg);
}

static struct _FiProg  tmp16_sinteger_MINUS_init = {
        (FiFun) CF16_sinteger_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF17_complex_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        if (l1->X28) goto L0;
        l1->X28 = 1L;
        fiCCall0(void, (*pG_I0RMM_complex));
L0:	return (FiWord) (*pG_LM9I3_complex__Complex__500);
}

static struct _FiProg  tmp17_complex_MINUS_init = {
        (FiFun) CF17_complex_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF18_sfloat_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        if (l1->X29) goto L0;
        l1->X29 = 1L;
        fiCCall0(void, (*pG_T13QO_sfloat));
L0:	return (FiWord) (*pG_7Q898_sfloat__SingleFloat__);
}

static struct _FiProg  tmp18_sfloat_MINUS_init = {
        (FiFun) CF18_sfloat_MINUS_init,
        0L,
        0L,
        0L
};

extern int
INIT__0_forn6(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_sfloat(void);
        extern int INIT__0_complex(void);
        extern int INIT__0_sinteger(void);
        extern int INIT__0_textwrit(void);
        extern int INIT__0_char(void);
        extern int INIT__0_dfloat(void);
        extern int INIT__0_string(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_xl1 = &tmp1_xl1;
        C2_xl2 = &tmp2_xl2;
        C3_x = &tmp3_x;
        C4_x = &tmp4_x;
        C5_x = &tmp5_x;
        C6_x = &tmp6_x;
        C7_x = &tmp7_x;
        C8_x = &tmp8_x;
        C9_foreignWrapper = &tmp9_foreignWrapper;
        C10_x = &tmp10_x;
        C11_x = &tmp11_x;
        C12_string_MINUS_init = &tmp12_string_MINUS_init;
        C13_dfloat_MINUS_init = &tmp13_dfloat_MINUS_init;
        C14_char_MINUS_init = &tmp14_char_MINUS_init;
        C15_textwrit_MINUS_init = &tmp15_textwrit_MINUS_init;
        C16_sinteger_MINUS_init = &tmp16_sinteger_MINUS_init;
        C17_complex_MINUS_init = &tmp17_complex_MINUS_init;
        C18_sfloat_MINUS_init = &tmp18_sfloat_MINUS_init;
        C0_forn6 = &tmp0_forn6;
        fiExportGlobal("G_336E3_forn6", G_336E3_forn6);
        fiExportGlobal("G_4WKMJ_forn6__xl2__953380000", 
        	G_4WKMJ_forn6__xl2__953380000);
        fiExportGlobal("G_A7UEE_forn6__xl1__201174703", 
        	G_A7UEE_forn6__xl1__201174703);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_NBIQ7_textwrit__TextWriter__", 
        	pG_NBIQ7_textwrit__TextWriter);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_LD0B5_domainHash_BANG_", pG_LD0B5_domainHash_BANG_);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_JWPLO_sinteger__SingleIntege", 
        	pG_JWPLO_sinteger__SingleInteg);
        fiImportGlobal("G_QRAZA_rtDelayedGetExport", 
        	pG_QRAZA_rtDelayedGetExport);
        fiImportGlobal("G_DLXW8_stdGetWordWordRetWord0", 
        	pG_DLXW8_stdGetWordWordRetWord);
        fiImportGlobal("G_7Q898_sfloat__SingleFloat__5", 
        	pG_7Q898_sfloat__SingleFloat__);
        fiImportGlobal("G_LM9I3_complex__Complex__5006", 
        	pG_LM9I3_complex__Complex__500);
        fiImportGlobal("G_RSHLY_rtDelayedInit_BANG_", 
        	pG_RSHLY_rtDelayedInit_BANG_);
        fiImportGlobal("G_ZZZKG_stdGetWordRetWord0", 
        	pG_ZZZKG_stdGetWordRetWord0);
        fiImportGlobal("G_4KA9O_char__Character__15781", 
        	pG_4KA9O_char__Character__1578);
        fiImportGlobal("G_KJ3UJ_dfloat__DoubleFloat__9", 
        	pG_KJ3UJ_dfloat__DoubleFloat__);
        fiImportGlobal("G_FXGEB_string__String__517719", 
        	pG_FXGEB_string__String__51771);
        fiImportGlobal("G_OGNYK_string", pG_OGNYK_string);
        fiImportGlobal("G_DEGQL_dfloat", pG_DEGQL_dfloat);
        fiImportGlobal("G_AKTR8_char", pG_AKTR8_char);
        fiImportGlobal("G_EC2QI_textwrit", pG_EC2QI_textwrit);
        fiImportGlobal("G_HAQ5R_sinteger", pG_HAQ5R_sinteger);
        fiImportGlobal("G_I0RMM_complex", pG_I0RMM_complex);
        fiImportGlobal("G_T13QO_sfloat", pG_T13QO_sfloat);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("sfloat");
                fiFileInitializer("complex");
                fiFileInitializer("sinteger");
                fiFileInitializer("textwrit");
                fiFileInitializer("char");
                fiFileInitializer("dfloat");
                fiFileInitializer("string");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_sfloat();
                INIT__0_complex();
                INIT__0_sinteger();
                INIT__0_textwrit();
                INIT__0_char();
                INIT__0_dfloat();
                INIT__0_string();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}

FiClos G_A7UEE_forn6__xl1__201174703;
FiClos G_4WKMJ_forn6__xl2__953380000;

static struct _FiClos  tmpClos0_forn6 = {
        0L,
        (FiProg) &tmp0_forn6
};
FiClos G_336E3_forn6 = &tmpClos0_forn6;
