"funct6.as", line 47: a: Integer == mantissa( 1.3 )
                      ........................^
[L47 C25] #1 (Error) Argument 1 of `mantissa' did not match any possible parameter type.
    The rejected type is Float.
    Expected type SingleInteger.
The following could be suitable if imported:
  mantissa: Float -> Integer from Float

"funct6.as", line 49: b: Integer == exponent( 1.2 )
                      ..............^
[L49 C15] #2 (Error) There are no suitable meanings for the operator `exponent'.
The following could be suitable if imported:
  exponent: Float -> Integer from Float

