"funct8.as", line 20: 
f1 () : Integer == left(b, false, y, false) -- 0 poss. types
...................^
[L20 C20] #1 (Error) No one possible return type satisfies the context type.
  These possible return types were rejected:
          -- String
  The context requires an expression of type Integer.

"funct8.as", line 21: y(b)
                      ^
[L21 C1] #2 (Error) There are no suitable meanings for the operator `y'.

