/*
 * C code generated by Aldor from file "genc2.as".
 */

#include "foam_c.h"

typedef struct Fmt5  *PFmt5;
struct Fmt5 {
        FiWord X0_Integer;
        FiWord X1_Character;
        FiWord X2_TextWriter;
        FiClos X3__LT__LT_;
        FiWord X4_newline;
        FiWord X5_print;
        FiClos X6_integer;
        FiClos X7__LT__LT_;
        FiWord X8_0;
        FiClos X9__PLUS_;
        FiClos X10__MINUS_;
        FiWord X11_dom;
        FiWord X12_dom;
        FiWord X13_dom;
        FiBool X14;
        FiBool X15;
        FiBool X16;
};
static FiProg C0_genc2;
static void CF0_genc2(FiEnv e1);
static FiProg C1_char_MINUS_init;
static FiWord CF1_char_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C2_textwrit_MINUS_init;
static FiWord CF2_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C3_integer_MINUS_init;
static FiWord CF3_integer_MINUS_init(FiEnv e1, FiSInt P0_idx);
extern FiClos G_MUMGG_genc2;
static FiClos *pG_NQYQM_noOperation;
static FiClos *pG_XIPRL_runtime;
static FiWord *pG_MGD01_integer__Integer__856;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_QRAZA_rtDelayedGetExport;
static FiClos *pG_ZZZKG_stdGetWordRetWord0;
static FiWord *pG_NBIQ7_textwrit__TextWriter;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiClos *pG_DLXW8_stdGetWordWordRetWord;
static FiWord *pG_4KA9O_char__Character__1578;
static FiClos *pG_AKTR8_char;
static FiClos *pG_EC2QI_textwrit;
static FiClos *pG_WJ27Y_integer;



static void
CF0_genc2(FiEnv e1)
{
        FiWord T0_j, T4, T5;
        FiClos T1, T2, T3;
        PFmt5 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt5 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCCall0(void, (*pG_XIPRL_runtime));
        G_MUMGG_genc2 = (FiClos) (*pG_NQYQM_noOperation);
        T1 = fiClosMake(e0, C3_integer_MINUS_init);
        T2 = fiClosMake(e0, C2_textwrit_MINUS_init);
        T3 = fiClosMake(e0, C1_char_MINUS_init);
        l0->X14 = 0L;
        l0->X15 = 0L;
        l0->X16 = 0L;
        l0->X0_Integer = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T1, 0L);
        l0->X11_dom = l0->X0_Integer;
        T4 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X11_dom, 477900237L, 305834192L);
        l0->X6_integer = fiCCall1(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T4);
        T0_j = fiCCall1(FiWord, l0->X6_integer, (FiWord) "2");
        l0->X2_TextWriter = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T2, 0L);
        l0->X12_dom = l0->X2_TextWriter;
        l0->X5_print = fiCCall3(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X12_dom, 828947258L, 182752316L);
        l0->X8_0 = fiCCall3(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X11_dom, 200089L, 484208045L);
        T4 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X11_dom, 200084L, 394967248L);
        l0->X9__PLUS_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T4);
        T4 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X11_dom, 51492426L, 533651260L);
        l0->X7__LT__LT_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T4);
        T4 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X11_dom, 200086L, 394967248L);
        l0->X10__MINUS_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T4);
        l0->X1_Character = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T3, 0L);
        l0->X13_dom = l0->X1_Character;
        l0->X4_newline = fiCCall3(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X13_dom, 493486801L, 803414590L);
        T4 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X13_dom, 51492426L, 186261308L);
        l0->X3__LT__LT_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T4);
        T4 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l0->X5_print);
        T5 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l0->X8_0);
        T5 = fiCCall2(FiWord, l0->X9__PLUS_, T0_j, T5);
        T4 = fiCCall2(FiWord, l0->X7__LT__LT_, T4, T5);
        T5 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l0->X8_0);
        T5 = fiCCall2(FiWord, l0->X10__MINUS_, T0_j, T5);
        T4 = fiCCall2(FiWord, l0->X7__LT__LT_, T4, T5);
        T5 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l0->
        	X4_newline);
        fiCCall2(FiWord, l0->X3__LT__LT_, T4, T5);
        return ;
}

static struct _FiProg  tmp0_genc2 = {
        (FiFun) CF0_genc2,
        0L,
        0L,
        0L
};


static FiWord
CF1_char_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X14) goto L0;
        l1->X14 = 1L;
        fiCCall0(void, (*pG_AKTR8_char));
L0:	return (FiWord) (*pG_4KA9O_char__Character__1578);
}

static struct _FiProg  tmp1_char_MINUS_init = {
        (FiFun) CF1_char_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF2_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X15) goto L0;
        l1->X15 = 1L;
        fiCCall0(void, (*pG_EC2QI_textwrit));
L0:	return (FiWord) (*pG_NBIQ7_textwrit__TextWriter);
}

static struct _FiProg  tmp2_textwrit_MINUS_init = {
        (FiFun) CF2_textwrit_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF3_integer_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X16) goto L0;
        l1->X16 = 1L;
        fiCCall0(void, (*pG_WJ27Y_integer));
L0:	return (FiWord) (*pG_MGD01_integer__Integer__856);
}

static struct _FiProg  tmp3_integer_MINUS_init = {
        (FiFun) CF3_integer_MINUS_init,
        0L,
        0L,
        0L
};

extern int
INIT__0_genc2(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_integer(void);
        extern int INIT__0_textwrit(void);
        extern int INIT__0_char(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_char_MINUS_init = &tmp1_char_MINUS_init;
        C2_textwrit_MINUS_init = &tmp2_textwrit_MINUS_init;
        C3_integer_MINUS_init = &tmp3_integer_MINUS_init;
        C0_genc2 = &tmp0_genc2;
        fiExportGlobal("G_MUMGG_genc2", G_MUMGG_genc2);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_MGD01_integer__Integer__8561", 
        	pG_MGD01_integer__Integer__856);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_QRAZA_rtDelayedGetExport", 
        	pG_QRAZA_rtDelayedGetExport);
        fiImportGlobal("G_ZZZKG_stdGetWordRetWord0", 
        	pG_ZZZKG_stdGetWordRetWord0);
        fiImportGlobal("G_NBIQ7_textwrit__TextWriter__", 
        	pG_NBIQ7_textwrit__TextWriter);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_DLXW8_stdGetWordWordRetWord0", 
        	pG_DLXW8_stdGetWordWordRetWord);
        fiImportGlobal("G_4KA9O_char__Character__15781", 
        	pG_4KA9O_char__Character__1578);
        fiImportGlobal("G_AKTR8_char", pG_AKTR8_char);
        fiImportGlobal("G_EC2QI_textwrit", pG_EC2QI_textwrit);
        fiImportGlobal("G_WJ27Y_integer", pG_WJ27Y_integer);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("integer");
                fiFileInitializer("textwrit");
                fiFileInitializer("char");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_integer();
                INIT__0_textwrit();
                INIT__0_char();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}


static struct _FiClos  tmpClos0_genc2 = {
        0L,
        (FiProg) &tmp0_genc2
};
FiClos G_MUMGG_genc2 = &tmpClos0_genc2;
