/*
 * C code generated by Aldor from file "hilbert.as".
 */

#include "foam_c.h"

typedef struct Fmt5  *PFmt5;
typedef struct Fmt6  *PFmt6;
typedef struct Fmt7  *PFmt7;
typedef struct Fmt8  *PFmt8;
struct Fmt5 {
        FiClos X0_done_QMARK_;
        FiClos X1_step_BANG_;
        FiClos X2_value;
        FiClos X3_bound;
};
struct Fmt6 {
        FiWord X0_n;
        FiBool X1;
        FiClos X2;
        FiClos X3;
        FiClos X4;
        FiClos X5;
        FiBool X6;
        FiSInt X7;
        FiWord X8;
        FiWord X9_j;
        FiBool X10;
        FiClos X11;
        FiClos X12;
        FiClos X13;
        FiClos X14;
        FiBool X15;
        FiSInt X16;
        FiWord X17;
        FiWord X18_i;
};
struct Fmt7 {
        FiClos X0_getter;
        FiBool X1_flag;
        FiClos X2_self;
};
struct Fmt8 {
        FiClos X0_Segment;
        FiWord X1_Integer;
        FiWord X2_Character;
        FiClos X3_List;
        FiClos X4_Array;
        FiClos X5_Ratio;
        FiWord X6_TextWriter;
        FiClos X7__LT__LT_;
        FiWord X8_newline;
        FiWord X9_print;
        FiClos X10_integer;
        FiClos X11__PLUS_;
        FiClos X12__MINUS_;
        FiWord X13_1;
        FiClos X14__DOT__DOT_;
        FiClos X15_generator;
        FiClos X16__SLASH_;
        FiClos X17_list;
        FiClos X18__LT__LT_;
        FiClos X19_array;
        FiWord X20_dom;
        FiClos X21_ClosedSegment;
        FiWord X22_dom;
        FiWord X23_dom;
        FiWord X24_dom;
        FiWord X25_dom;
        FiWord X26_dom;
        FiWord X27_dom;
        FiBool X28;
        FiBool X29;
        FiBool X30;
        FiBool X31;
        FiBool X32;
        FiBool X33;
        FiBool X34;
};
static FiProg C0_hilbert;
static void CF0_hilbert(FiEnv e1);
static FiProg C1_Hilbert;
static FiWord CF1_Hilbert(FiEnv e1, FiWord P0_n);
static FiProg C2_generBaseFn;
static void CF2_generBaseFn(FiEnv e1, FiClos* R0, FiClos* R1, FiClos* R2, FiClos* R3);
static FiProg C3_generStepper;
static void CF3_generStepper(FiEnv e1);
static FiProg C4_generBaseFn;
static void CF4_generBaseFn(FiEnv e1, FiClos* R0, FiClos* R1, FiClos* R2, FiClos* R3);
static FiProg C5_generStepper;
static void CF5_generStepper(FiEnv e1);
static FiProg C6_generDone_QMARK_;
static FiBool CF6_generDone_QMARK_(FiEnv e1);
static FiProg C7_generValue;
static FiWord CF7_generValue(FiEnv e1);
static FiProg C8_generBound;
static FiSInt CF8_generBound(FiEnv e1);
static FiProg C9_generDone_QMARK_;
static FiBool CF9_generDone_QMARK_(FiEnv e1);
static FiProg C10_generValue;
static FiWord CF10_generValue(FiEnv e1);
static FiProg C11_generBound;
static FiSInt CF11_generBound(FiEnv e1);
static FiProg C12_lazyFnGetter;
static FiClos CF12_lazyFnGetter(FiEnv e1, FiWord P0_init);
static FiProg C13_lazyGetter;
static FiClos CF13_lazyGetter(FiEnv e1, FiWord P0_a);
static FiProg C14_lazyGetter2;
static void CF14_lazyGetter2(FiEnv e1);
static FiProg C15_char_MINUS_init;
static FiWord CF15_char_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C16_textwrit_MINUS_init;
static FiWord CF16_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C17_array_MINUS_init;
static FiWord CF17_array_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C18_integer_MINUS_init;
static FiWord CF18_integer_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C19_list_MINUS_init;
static FiWord CF19_list_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C20_segment_MINUS_init;
static FiWord CF20_segment_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C21_ratio_MINUS_init;
static FiWord CF21_ratio_MINUS_init(FiEnv e1, FiSInt P0_idx);
extern FiClos G_CV7QD_hilbert;
static FiClos *pG_NQYQM_noOperation;
extern FiClos G_NAKLZ_hilbert__Hilbert__6214;
static FiClos *pG_XIPRL_runtime;
static FiWord *pG_MGD01_integer__Integer__856;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_NYJZQ_segment__Segment__234;
static FiClos *pG_RSHLY_rtDelayedInit_BANG_;
static FiClos *pG_ZZZKG_stdGetWordRetWord0;
static FiClos *pG_MN6X6_segment__ClosedSegmen;
static FiClos *pG_LD0B5_domainHash_BANG_;
static FiClos *pG_QRAZA_rtDelayedGetExport;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiClos *pG_DLXW8_stdGetWordWordRetWord;
static FiClos *pG_VOMTT_ratio__Ratio__9872531;
static FiClos *pG_SSBVZ_list__List__638686394;
static FiClos *pG_YCI2U_stdGetClosRetWord0;
static FiClos *pG_H33WF_array__Array__0679756;
static FiWord *pG_NBIQ7_textwrit__TextWriter;
static FiWord *pG_4KA9O_char__Character__1578;
static FiClos *pG_AKTR8_char;
static FiClos *pG_EC2QI_textwrit;
static FiClos *pG_AL27T_array;
static FiClos *pG_WJ27Y_integer;
static FiClos *pG_AREZX_list;
static FiClos *pG_WVJG4_segment;
static FiClos *pG_JQTZC_ratio;



static void
CF0_hilbert(FiEnv e1)
{
        FiWord T0_p, T22, T23;
        FiClos T1, T2, T5, T7, T11, T17, T21;
        FiSInt T3, T4, T6, T8, T9, T10, T12, T13, T14, T15, T16, T18, T19, T20;
        PFmt8 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt8 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCCall0(void, (*pG_XIPRL_runtime));
        G_CV7QD_hilbert = (FiClos) (*pG_NQYQM_noOperation);
        T1 = fiClosMake(e0, C18_integer_MINUS_init);
        T2 = fiClosMake(e0, C20_segment_MINUS_init);
        T5 = fiClosMake(e0, C21_ratio_MINUS_init);
        T7 = fiClosMake(e0, C19_list_MINUS_init);
        T11 = fiClosMake(e0, C17_array_MINUS_init);
        G_NAKLZ_hilbert__Hilbert__6214 = fiClosMake(e0, C1_Hilbert);
        T17 = fiClosMake(e0, C16_textwrit_MINUS_init);
        T21 = fiClosMake(e0, C15_char_MINUS_init);
        l0->X28 = 0L;
        l0->X29 = 0L;
        l0->X30 = 0L;
        l0->X31 = 0L;
        l0->X32 = 0L;
        l0->X33 = 0L;
        l0->X34 = 0L;
        l0->X1_Integer = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T1, 0L);
        T22 = fiCCall2(FiWord, (*pG_RSHLY_rtDelayedInit_BANG_), T2, 0L);
        l0->X0_Segment = fiCCall1(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T22);
        l0->X20_dom = fiCCall1(FiWord, l0->X0_Segment, l0->
        	X1_Integer);
        T22 = fiCCall2(FiWord, (*pG_RSHLY_rtDelayedInit_BANG_), T2, 1L);
        l0->X21_ClosedSegment = fiCCall1(FiClos, (*
        	pG_ZZZKG_stdGetWordRetWord0), T22);
        fiEnvEnsure(l0->X21_ClosedSegment->env);
        T3 = 794824237L;
L1:	l0->X15_generator = CF12_lazyFnGetter(e0, (FiWord) fiCCall3(FiWord, (*
        	pG_QRAZA_rtDelayedGetExport), l0->X20_dom, 113320568L, (
        	490013613L + (((32236L + (((T3 + 
        	74075968L) % 1073741789L & 16777215L) << 6L)) % 1073741789L & 
        	16777215L) << 6L)) % 1073741789L));
        l0->X22_dom = l0->X1_Integer;
        l0->X13_1 = fiCCall3(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X22_dom, 200090L, 484208045L);
        fiEnvEnsure(l0->X21_ClosedSegment->env);
        T4 = 794824237L;
L3:	T22 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X20_dom, 
        	51488814L, (T4 + 984500992L) % 1073741789L);
        l0->X14__DOT__DOT_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T22);
        T22 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X22_dom, 200084L, 394967248L);
        l0->X11__PLUS_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T22);
        T22 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X22_dom, 200086L, 394967248L);
        l0->X12__MINUS_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T22);
        T22 = fiCCall2(FiWord, (*pG_RSHLY_rtDelayedInit_BANG_), T5, 0L);
        l0->X5_Ratio = fiCCall1(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T22);
        l0->X23_dom = fiCCall1(FiWord, l0->X5_Ratio, l0->X1_Integer);
        fiEnvEnsure(l0->X5_Ratio->env);
        T6 = 98808016L;
L5:	T22 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X23_dom, 
        	200088L, (T6 + 984500992L) % 1073741789L);
        l0->X16__SLASH_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T22);
        T22 = fiCCall2(FiWord, (*pG_RSHLY_rtDelayedInit_BANG_), T7, 0L);
        l0->X3_List = fiCCall1(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T22);
        T22 = fiCCall1(FiWord, l0->X5_Ratio, l0->X1_Integer);
        l0->X24_dom = fiCCall1(FiWord, l0->X3_List, T22);
        fiEnvEnsure(l0->X5_Ratio->env);
        T8 = 98808016L;
L7:	fiEnvEnsure(l0->X3_List->env);
        fiEnvEnsure(l0->X5_Ratio->env);
        T10 = 98808016L;
L11:	T9 = (T10 + 638488576L) % 1073741789L;
L9:	T22 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X24_dom, 
        	683203168L, (T9 + (((32236L + ((((
        	T8 + 5805568L) % 1073741789L + 74075968L) % 1073741789L & 
        	16777215L) << 6L)) % 1073741789L & 16777215L) << 6L)) % 
        	1073741789L);
        l0->X17_list = fiCCall1(FiClos, (*pG_YCI2U_stdGetClosRetWord0), 
        	T22);
        T22 = fiCCall2(FiWord, (*pG_RSHLY_rtDelayedInit_BANG_), T11, 0L);
        l0->X4_Array = fiCCall1(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T22);
        T22 = fiCCall1(FiWord, l0->X5_Ratio, l0->X1_Integer);
        T22 = fiCCall1(FiWord, l0->X3_List, T22);
        l0->X25_dom = fiCCall1(FiWord, l0->X4_Array, T22);
        fiEnvEnsure(l0->X3_List->env);
        fiEnvEnsure(l0->X5_Ratio->env);
        T13 = 98808016L;
L15:	T12 = (T13 + 638488576L) % 1073741789L;
L13:	fiEnvEnsure(l0->X4_Array->env);
        fiEnvEnsure(l0->X3_List->env);
        fiEnvEnsure(l0->X5_Ratio->env);
        T16 = 98808016L;
L21:	T15 = (T16 + 638488576L) % 1073741789L;
L19:	T14 = (T15 + 1020592896L) % 1073741789L;
L17:	T22 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X25_dom, 
        	682906668L, (T14 + (((32236L + ((((
        	T12 + 5805568L) % 1073741789L + 74075968L) % 1073741789L & 
        	16777215L) << 6L)) % 1073741789L & 16777215L) << 6L)) % 
        	1073741789L);
        l0->X19_array = fiCCall1(FiClos, (*pG_YCI2U_stdGetClosRetWord0), 
        	T22);
        T22 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X22_dom, 477900237L, 305834192L);
        l0->X10_integer = fiCCall1(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T22);
        l0->X6_TextWriter = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T17, 0L);
        l0->X26_dom = l0->X6_TextWriter;
        l0->X9_print = fiCCall3(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X26_dom, 828947258L, 182752316L);
        fiEnvEnsure(l0->X4_Array->env);
        fiEnvEnsure(l0->X3_List->env);
        fiEnvEnsure(l0->X5_Ratio->env);
        T20 = 98808016L;
L27:	T19 = (T20 + 638488576L) % 1073741789L;
L25:	T18 = (T19 + 1020592896L) % 1073741789L;
L23:	T22 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X25_dom, 
        	51492426L, (182752316L + (((32236L + (((
        	T18 + 330882816L) % 1073741789L & 16777215L) << 6L)) % 
        	1073741789L & 16777215L) << 6L)) % 1073741789L);
        l0->X18__LT__LT_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T22);
        l0->X2_Character = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T21, 0L);
        l0->X27_dom = l0->X2_Character;
        l0->X8_newline = fiCCall3(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X27_dom, 493486801L, 803414590L);
        T22 = fiCCall3(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->
        	X27_dom, 51492426L, 186261308L);
        l0->X7__LT__LT_ = fiCCall1(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T22);
        T0_p = CF1_Hilbert(e0, (FiWord) fiCCall1(FiWord, l0->X10_integer, (
        	FiWord) "3"));
        T22 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l0->X9_print);
        T22 = fiCCall2(FiWord, l0->X18__LT__LT_, T22, T0_p);
        T23 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l0->
        	X8_newline);
        fiCCall2(FiWord, l0->X7__LT__LT_, T22, T23);
        return ;
L26:	T22 = fiCCall1(FiWord, l0->X5_Ratio, l0->X1_Integer);
        T20 = fiCCall1(FiSInt, (*pG_LD0B5_domainHash_BANG_), T22);
        goto L27;
L24:	T22 = fiCCall1(FiWord, l0->X5_Ratio, l0->X1_Integer);
        T22 = fiCCall1(FiWord, l0->X3_List, T22);
        T19 = fiCCall1(FiSInt, (*pG_LD0B5_domainHash_BANG_), T22);
        goto L25;
L22:	T22 = fiCCall1(FiWord, l0->X5_Ratio, l0->X1_Integer);
        T22 = fiCCall1(FiWord, l0->X3_List, T22);
        T22 = fiCCall1(FiWord, l0->X4_Array, T22);
        T18 = fiCCall1(FiSInt, (*pG_LD0B5_domainHash_BANG_), T22);
        goto L23;
L20:	T22 = fiCCall1(FiWord, l0->X5_Ratio, l0->X1_Integer);
        T16 = fiCCall1(FiSInt, (*pG_LD0B5_domainHash_BANG_), T22);
        goto L21;
L18:	T22 = fiCCall1(FiWord, l0->X5_Ratio, l0->X1_Integer);
        T22 = fiCCall1(FiWord, l0->X3_List, T22);
        T15 = fiCCall1(FiSInt, (*pG_LD0B5_domainHash_BANG_), T22);
        goto L19;
L16:	T22 = fiCCall1(FiWord, l0->X5_Ratio, l0->X1_Integer);
        T22 = fiCCall1(FiWord, l0->X3_List, T22);
        T22 = fiCCall1(FiWord, l0->X4_Array, T22);
        T14 = fiCCall1(FiSInt, (*pG_LD0B5_domainHash_BANG_), T22);
        goto L17;
L14:	T22 = fiCCall1(FiWord, l0->X5_Ratio, l0->X1_Integer);
        T13 = fiCCall1(FiSInt, (*pG_LD0B5_domainHash_BANG_), T22);
        goto L15;
L12:	T22 = fiCCall1(FiWord, l0->X5_Ratio, l0->X1_Integer);
        T22 = fiCCall1(FiWord, l0->X3_List, T22);
        T12 = fiCCall1(FiSInt, (*pG_LD0B5_domainHash_BANG_), T22);
        goto L13;
L10:	T22 = fiCCall1(FiWord, l0->X5_Ratio, l0->X1_Integer);
        T10 = fiCCall1(FiSInt, (*pG_LD0B5_domainHash_BANG_), T22);
        goto L11;
L8:	T22 = fiCCall1(FiWord, l0->X5_Ratio, l0->X1_Integer);
        T22 = fiCCall1(FiWord, l0->X3_List, T22);
        T9 = fiCCall1(FiSInt, (*pG_LD0B5_domainHash_BANG_), T22);
        goto L9;
L6:	T22 = fiCCall1(FiWord, l0->X5_Ratio, l0->X1_Integer);
        T8 = fiCCall1(FiSInt, (*pG_LD0B5_domainHash_BANG_), T22);
        goto L7;
L4:	T22 = fiCCall1(FiWord, l0->X5_Ratio, l0->X1_Integer);
        T6 = fiCCall1(FiSInt, (*pG_LD0B5_domainHash_BANG_), T22);
        goto L5;
L2:	T22 = fiCCall1(FiWord, l0->X21_ClosedSegment, l0->X1_Integer);
        T4 = fiCCall1(FiSInt, (*pG_LD0B5_domainHash_BANG_), T22);
        goto L3;
L0:	T22 = fiCCall1(FiWord, l0->X21_ClosedSegment, l0->X1_Integer);
        T3 = fiCCall1(FiSInt, (*pG_LD0B5_domainHash_BANG_), T22);
        goto L1;
}

static struct _FiProg  tmp0_hilbert = {
        (FiFun) CF0_hilbert,
        0L,
        0L,
        0L
};


static FiWord
CF1_Hilbert(FiEnv e1, FiWord P0_n)
{
        PFmt6 l0;
        FiEnv e0;
        PFmt8 l1;
        l0 = fi0New(struct Fmt6 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        l1 = (PFmt8) fiEnvLevel(e1);
        l0->X0_n = P0_n;
        l0->X1 = 0L;
        l0->X7 = 0L;
        return fiCCall1(FiWord, l1->X19_array, fiClosMake(e0, C2_generBaseFn));
}

static struct _FiProg  tmp1_Hilbert = {
        (FiFun) CF1_Hilbert,
        0L,
        0L,
        0L
};


static void
CF2_generBaseFn(FiEnv e1, FiClos* R0, FiClos* R1, FiClos* R2, FiClos* 
        	R3)
{
        FiEnv e2, e0;
        PFmt6 l1;
        PFmt8 l2;
        e0 = fiEnvPush(fiNil, e1);
        l1 = (PFmt6) fiEnvLevel(e1);
        e2 = fiEnvNext(e1);
        l2 = (PFmt8) fiEnvLevel(e2);
        *R0 = fiClosMake(e0, C9_generDone_QMARK_);
        *R1 = fiClosMake(e0, C3_generStepper);
        *R2 = fiClosMake(e0, C10_generValue);
        *R3 = fiClosMake(e0, C11_generBound);
        return ;
}

static struct _FiProg  tmp2_generBaseFn = {
        (FiFun) CF2_generBaseFn,
        0L,
        0L,
        0L
};


static void
CF3_generStepper(FiEnv e1)
{
        FiClos T1, T2, T3, T4, T6;
        FiWord T0, T5;
        PFmt6 l2;
        FiEnv e3, e2;
        PFmt8 l3;
        e2 = fiEnvNext(e1);
        l2 = (PFmt6) fiEnvLevel(e2);
        e3 = fiEnvNext(e2);
        l3 = (PFmt8) fiEnvLevel(e3);
        switch (l2->X7) {
        case 0L: goto L0;
        case 1L: goto L5;
        }
L0:	l2->X6 = 0L;
        T5 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l3->X13_1);
        T5 = fiCCall2(FiWord, l3->X14__DOT__DOT_, T5, l2->X0_n);
        T6 = fiCCall1(FiClos, l3->X15_generator, T5);
        ((void(*)(FiEnv , FiClos* , FiClos* , FiClos* , FiClos* )) 
        	fiRawCProg(T6))((T6)->env, &T1, &T2, &T3, &T4);
        l2->X1 = 1L;
        l2->X2 = T1;
        l2->X3 = T2;
        l2->X4 = T3;
        l2->X5 = T4;
        goto L3;
L2:	l2->X7 = 1L;
        l2->X10 = 0L;
        l2->X16 = 0L;
        T0 = fiCCall1(FiWord, l3->X17_list, fiClosMake(e2, 
        	C4_generBaseFn));
        goto L1;
L5:	
L3:	fiCCall0(void, l2->X3);
        if ((FiBool) fiCCall0(FiWord, l2->X2)) goto L4;
        l2->X9_j = fiCCall0(FiWord, l2->X4);
        goto L2;
L4:	l2->X6 = 1L;
        return ;
L1:	l2->X8 = T0;
        return ;
}

static struct _FiProg  tmp3_generStepper = {
        (FiFun) CF3_generStepper,
        0L,
        0L,
        0L
};


static void
CF4_generBaseFn(FiEnv e1, FiClos* R0, FiClos* R1, FiClos* R2, FiClos* 
        	R3)
{
        FiEnv e2, e0;
        PFmt6 l1;
        PFmt8 l2;
        e0 = fiEnvPush(fiNil, e1);
        l1 = (PFmt6) fiEnvLevel(e1);
        e2 = fiEnvNext(e1);
        l2 = (PFmt8) fiEnvLevel(e2);
        *R0 = fiClosMake(e0, C6_generDone_QMARK_);
        *R1 = fiClosMake(e0, C5_generStepper);
        *R2 = fiClosMake(e0, C7_generValue);
        *R3 = fiClosMake(e0, C8_generBound);
        return ;
}

static struct _FiProg  tmp4_generBaseFn = {
        (FiFun) CF4_generBaseFn,
        0L,
        0L,
        0L
};


static void
CF5_generStepper(FiEnv e1)
{
        FiWord T0, T5, T7, T8;
        FiClos T1, T2, T3, T4, T6;
        PFmt6 l2;
        FiEnv e3, e2;
        PFmt8 l3;
        e2 = fiEnvNext(e1);
        l2 = (PFmt6) fiEnvLevel(e2);
        e3 = fiEnvNext(e2);
        l3 = (PFmt8) fiEnvLevel(e3);
        switch (l2->X16) {
        case 0L: goto L0;
        case 1L: goto L5;
        }
L0:	l2->X15 = 0L;
        T5 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l3->X13_1);
        T5 = fiCCall2(FiWord, l3->X14__DOT__DOT_, T5, l2->X0_n);
        T6 = fiCCall1(FiClos, l3->X15_generator, T5);
        ((void(*)(FiEnv , FiClos* , FiClos* , FiClos* , FiClos* )) 
        	fiRawCProg(T6))((T6)->env, &T1, &T2, &T3, &T4);
        l2->X10 = 1L;
        l2->X11 = T1;
        l2->X12 = T2;
        l2->X13 = T3;
        l2->X14 = T4;
        goto L3;
L2:	l2->X16 = 1L;
        T5 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l3->X13_1);
        T7 = fiCCall2(FiWord, l3->X11__PLUS_, l2->X18_i, l2->X9_j);
        T8 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l3->X13_1);
        T7 = fiCCall2(FiWord, l3->X12__MINUS_, T7, T8);
        T0 = fiCCall2(FiWord, l3->X16__SLASH_, T5, T7);
        goto L1;
L5:	
L3:	fiCCall0(void, l2->X12);
        if ((FiBool) fiCCall0(FiWord, l2->X11)) goto L4;
        l2->X18_i = fiCCall0(FiWord, l2->X13);
        goto L2;
L4:	l2->X15 = 1L;
        return ;
L1:	l2->X17 = T0;
        return ;
}

static struct _FiProg  tmp5_generStepper = {
        (FiFun) CF5_generStepper,
        0L,
        0L,
        0L
};


static FiBool
CF6_generDone_QMARK_(FiEnv e1)
{
        PFmt6 l2;
        FiEnv e3, e2;
        PFmt8 l3;
        e2 = fiEnvNext(e1);
        l2 = (PFmt6) fiEnvLevel(e2);
        e3 = fiEnvNext(e2);
        l3 = (PFmt8) fiEnvLevel(e3);
        return l2->X15;
}

static struct _FiProg  tmp6_generDone_QMARK_ = {
        (FiFun) CF6_generDone_QMARK_,
        0L,
        0L,
        0L
};


static FiWord
CF7_generValue(FiEnv e1)
{
        PFmt6 l2;
        FiEnv e3, e2;
        PFmt8 l3;
        e2 = fiEnvNext(e1);
        l2 = (PFmt6) fiEnvLevel(e2);
        e3 = fiEnvNext(e2);
        l3 = (PFmt8) fiEnvLevel(e3);
        return l2->X17;
}

static struct _FiProg  tmp7_generValue = {
        (FiFun) CF7_generValue,
        0L,
        0L,
        0L
};


static FiSInt
CF8_generBound(FiEnv e1)
{
        FiSInt T0, T1;
        PFmt6 l2;
        FiEnv e3, e2;
        PFmt8 l3;
        e2 = fiEnvNext(e1);
        l2 = (PFmt6) fiEnvLevel(e2);
        e3 = fiEnvNext(e2);
        l3 = (PFmt8) fiEnvLevel(e3);
        if (!l2->X10) goto L0;
        T1 = fiCCall0(FiSInt, l2->X14);
        if (T1 < 0) goto L0;
        T0 = T1;
L1:	return T0;
L0:	T0 = -1L;
        goto L1;
}

static struct _FiProg  tmp8_generBound = {
        (FiFun) CF8_generBound,
        0L,
        0L,
        0L
};


static FiBool
CF9_generDone_QMARK_(FiEnv e1)
{
        PFmt6 l2;
        FiEnv e3, e2;
        PFmt8 l3;
        e2 = fiEnvNext(e1);
        l2 = (PFmt6) fiEnvLevel(e2);
        e3 = fiEnvNext(e2);
        l3 = (PFmt8) fiEnvLevel(e3);
        return l2->X6;
}

static struct _FiProg  tmp9_generDone_QMARK_ = {
        (FiFun) CF9_generDone_QMARK_,
        0L,
        0L,
        0L
};


static FiWord
CF10_generValue(FiEnv e1)
{
        PFmt6 l2;
        FiEnv e3, e2;
        PFmt8 l3;
        e2 = fiEnvNext(e1);
        l2 = (PFmt6) fiEnvLevel(e2);
        e3 = fiEnvNext(e2);
        l3 = (PFmt8) fiEnvLevel(e3);
        return l2->X8;
}

static struct _FiProg  tmp10_generValue = {
        (FiFun) CF10_generValue,
        0L,
        0L,
        0L
};


static FiSInt
CF11_generBound(FiEnv e1)
{
        FiSInt T0, T1;
        PFmt6 l2;
        FiEnv e3, e2;
        PFmt8 l3;
        e2 = fiEnvNext(e1);
        l2 = (PFmt6) fiEnvLevel(e2);
        e3 = fiEnvNext(e2);
        l3 = (PFmt8) fiEnvLevel(e3);
        if (!l2->X1) goto L0;
        T1 = fiCCall0(FiSInt, l2->X5);
        if (T1 < 0) goto L0;
        T0 = T1;
L1:	return T0;
L0:	T0 = -1L;
        goto L1;
}

static struct _FiProg  tmp11_generBound = {
        (FiFun) CF11_generBound,
        0L,
        0L,
        0L
};


static FiClos
CF12_lazyFnGetter(FiEnv e1, FiWord P0_init)
{
        PFmt7 l0;
        FiEnv e0;
        PFmt8 l1;
        l0 = fi0New(struct Fmt7 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        l1 = (PFmt8) fiEnvLevel(e1);
        l0->X0_getter = (FiClos) P0_init;
        l0->X1_flag = 0L;
        l0->X2_self = fiClosMake(e0, C13_lazyGetter);
        fiEnvInfo(e0) = (FiWord) fiClosMake(e0, C14_lazyGetter2);
        return l0->X2_self;
}

static struct _FiProg  tmp12_lazyFnGetter = {
        (FiFun) CF12_lazyFnGetter,
        0L,
        0L,
        0L
};


static FiClos
CF13_lazyGetter(FiEnv e1, FiWord P0_a)
{
        FiClos T0;
        PFmt7 l1;
        PFmt8 l2;
        FiEnv e2;
        l1 = (PFmt7) fiEnvLevel(e1);
        e2 = fiEnvNext(e1);
        l2 = (PFmt8) fiEnvLevel(e2);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCCall0(FiWord, l1->X0_getter);
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        l1->X1_flag = 1L;
L0:	return fiCCall1(FiClos, l1->X2_self, P0_a);
}

static struct _FiProg  tmp13_lazyGetter = {
        (FiFun) CF13_lazyGetter,
        0L,
        0L,
        0L
};


static void
CF14_lazyGetter2(FiEnv e1)
{
        FiClos T0;
        PFmt7 l1;
        PFmt8 l2;
        FiEnv e2;
        l1 = (PFmt7) fiEnvLevel(e1);
        e2 = fiEnvNext(e1);
        l2 = (PFmt8) fiEnvLevel(e2);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCCall0(FiWord, l1->X0_getter);
        l1->X1_flag = 1L;
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        fiEnvInfo(e1) = (FiWord) fiNil;
L0:	return ;
}

static struct _FiProg  tmp14_lazyGetter2 = {
        (FiFun) CF14_lazyGetter2,
        0L,
        0L,
        0L
};


static FiWord
CF15_char_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt8 l1;
        l1 = (PFmt8) fiEnvLevel(e1);
        if (l1->X28) goto L0;
        l1->X28 = 1L;
        fiCCall0(void, (*pG_AKTR8_char));
L0:	return (FiWord) (*pG_4KA9O_char__Character__1578);
}

static struct _FiProg  tmp15_char_MINUS_init = {
        (FiFun) CF15_char_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF16_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt8 l1;
        l1 = (PFmt8) fiEnvLevel(e1);
        if (l1->X29) goto L0;
        l1->X29 = 1L;
        fiCCall0(void, (*pG_EC2QI_textwrit));
L0:	return (FiWord) (*pG_NBIQ7_textwrit__TextWriter);
}

static struct _FiProg  tmp16_textwrit_MINUS_init = {
        (FiFun) CF16_textwrit_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF17_array_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt8 l1;
        l1 = (PFmt8) fiEnvLevel(e1);
        if (l1->X30) goto L0;
        l1->X30 = 1L;
        fiCCall0(void, (*pG_AL27T_array));
L0:	return (FiWord) (*pG_H33WF_array__Array__0679756);
}

static struct _FiProg  tmp17_array_MINUS_init = {
        (FiFun) CF17_array_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF18_integer_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt8 l1;
        l1 = (PFmt8) fiEnvLevel(e1);
        if (l1->X31) goto L0;
        l1->X31 = 1L;
        fiCCall0(void, (*pG_WJ27Y_integer));
L0:	return (FiWord) (*pG_MGD01_integer__Integer__856);
}

static struct _FiProg  tmp18_integer_MINUS_init = {
        (FiFun) CF18_integer_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF19_list_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt8 l1;
        l1 = (PFmt8) fiEnvLevel(e1);
        if (l1->X32) goto L0;
        l1->X32 = 1L;
        fiCCall0(void, (*pG_AREZX_list));
L0:	return (FiWord) (*pG_SSBVZ_list__List__638686394);
}

static struct _FiProg  tmp19_list_MINUS_init = {
        (FiFun) CF19_list_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF20_segment_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt8 l1;
        l1 = (PFmt8) fiEnvLevel(e1);
        if (l1->X33) goto L0;
        l1->X33 = 1L;
        fiCCall0(void, (*pG_WVJG4_segment));
L0:	if (P0_idx != 1L) goto L1;
        return (FiWord) (*pG_MN6X6_segment__ClosedSegmen);
L1:	return (FiWord) (*pG_NYJZQ_segment__Segment__234);
}

static struct _FiProg  tmp20_segment_MINUS_init = {
        (FiFun) CF20_segment_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF21_ratio_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt8 l1;
        l1 = (PFmt8) fiEnvLevel(e1);
        if (l1->X34) goto L0;
        l1->X34 = 1L;
        fiCCall0(void, (*pG_JQTZC_ratio));
L0:	return (FiWord) (*pG_VOMTT_ratio__Ratio__9872531);
}

static struct _FiProg  tmp21_ratio_MINUS_init = {
        (FiFun) CF21_ratio_MINUS_init,
        0L,
        0L,
        0L
};

extern int
INIT__0_hilbert(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_ratio(void);
        extern int INIT__0_segment(void);
        extern int INIT__0_list(void);
        extern int INIT__0_integer(void);
        extern int INIT__0_array(void);
        extern int INIT__0_textwrit(void);
        extern int INIT__0_char(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_Hilbert = &tmp1_Hilbert;
        C2_generBaseFn = &tmp2_generBaseFn;
        C3_generStepper = &tmp3_generStepper;
        C4_generBaseFn = &tmp4_generBaseFn;
        C5_generStepper = &tmp5_generStepper;
        C6_generDone_QMARK_ = &tmp6_generDone_QMARK_;
        C7_generValue = &tmp7_generValue;
        C8_generBound = &tmp8_generBound;
        C9_generDone_QMARK_ = &tmp9_generDone_QMARK_;
        C10_generValue = &tmp10_generValue;
        C11_generBound = &tmp11_generBound;
        C12_lazyFnGetter = &tmp12_lazyFnGetter;
        C13_lazyGetter = &tmp13_lazyGetter;
        C14_lazyGetter2 = &tmp14_lazyGetter2;
        C15_char_MINUS_init = &tmp15_char_MINUS_init;
        C16_textwrit_MINUS_init = &tmp16_textwrit_MINUS_init;
        C17_array_MINUS_init = &tmp17_array_MINUS_init;
        C18_integer_MINUS_init = &tmp18_integer_MINUS_init;
        C19_list_MINUS_init = &tmp19_list_MINUS_init;
        C20_segment_MINUS_init = &tmp20_segment_MINUS_init;
        C21_ratio_MINUS_init = &tmp21_ratio_MINUS_init;
        C0_hilbert = &tmp0_hilbert;
        fiExportGlobal("G_CV7QD_hilbert", G_CV7QD_hilbert);
        fiExportGlobal("G_NAKLZ_hilbert__Hilbert__6214", 
        	G_NAKLZ_hilbert__Hilbert__6214);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_MGD01_integer__Integer__8561", 
        	pG_MGD01_integer__Integer__856);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_NYJZQ_segment__Segment__2349", 
        	pG_NYJZQ_segment__Segment__234);
        fiImportGlobal("G_RSHLY_rtDelayedInit_BANG_", 
        	pG_RSHLY_rtDelayedInit_BANG_);
        fiImportGlobal("G_ZZZKG_stdGetWordRetWord0", 
        	pG_ZZZKG_stdGetWordRetWord0);
        fiImportGlobal("G_MN6X6_segment__ClosedSegment", 
        	pG_MN6X6_segment__ClosedSegmen);
        fiImportGlobal("G_LD0B5_domainHash_BANG_", pG_LD0B5_domainHash_BANG_);
        fiImportGlobal("G_QRAZA_rtDelayedGetExport", 
        	pG_QRAZA_rtDelayedGetExport);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_DLXW8_stdGetWordWordRetWord0", 
        	pG_DLXW8_stdGetWordWordRetWord);
        fiImportGlobal("G_VOMTT_ratio__Ratio__98725315", 
        	pG_VOMTT_ratio__Ratio__9872531);
        fiImportGlobal("G_SSBVZ_list__List__638686394", 
        	pG_SSBVZ_list__List__638686394);
        fiImportGlobal("G_YCI2U_stdGetClosRetWord0", 
        	pG_YCI2U_stdGetClosRetWord0);
        fiImportGlobal("G_H33WF_array__Array__06797563", 
        	pG_H33WF_array__Array__0679756);
        fiImportGlobal("G_NBIQ7_textwrit__TextWriter__", 
        	pG_NBIQ7_textwrit__TextWriter);
        fiImportGlobal("G_4KA9O_char__Character__15781", 
        	pG_4KA9O_char__Character__1578);
        fiImportGlobal("G_AKTR8_char", pG_AKTR8_char);
        fiImportGlobal("G_EC2QI_textwrit", pG_EC2QI_textwrit);
        fiImportGlobal("G_AL27T_array", pG_AL27T_array);
        fiImportGlobal("G_WJ27Y_integer", pG_WJ27Y_integer);
        fiImportGlobal("G_AREZX_list", pG_AREZX_list);
        fiImportGlobal("G_WVJG4_segment", pG_WVJG4_segment);
        fiImportGlobal("G_JQTZC_ratio", pG_JQTZC_ratio);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("ratio");
                fiFileInitializer("segment");
                fiFileInitializer("list");
                fiFileInitializer("integer");
                fiFileInitializer("array");
                fiFileInitializer("textwrit");
                fiFileInitializer("char");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_ratio();
                INIT__0_segment();
                INIT__0_list();
                INIT__0_integer();
                INIT__0_array();
                INIT__0_textwrit();
                INIT__0_char();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}

FiClos G_NAKLZ_hilbert__Hilbert__6214;

static struct _FiClos  tmpClos0_hilbert = {
        0L,
        (FiProg) &tmp0_hilbert
};
FiClos G_CV7QD_hilbert = &tmpClos0_hilbert;
