"if1.as", line 16:         g(): () == y: P Integer := (1 + 1) / 0;
                   ....................................^.^....^.^
[L16 C37] #3 (Error) No meaning for identifier `1'.
[L16 C39] #2 (Error) There are no suitable meanings for the operator `+'.
[L16 C44] #1 (Error) There are no suitable meanings for the operator `/'.
[L16 C46] #4 (Error) No meaning for identifier `0'.

"if1.as", line 28:         g(): () == y: P Integer := (1 + 1) / 0;
                   ....................................^.^....^.^
[L28 C37] #7 (Error) No meaning for identifier `1'.
[L28 C39] #6 (Error) There are no suitable meanings for the operator `+'.
[L28 C44] #5 (Error) There are no suitable meanings for the operator `/'.
[L28 C46] #8 (Error) No meaning for identifier `0'.

"if1.as", line 40:         g(): () == y: P Integer := (1 + 1) / 0;
                   ...........................................^
[L40 C44] #9 (Error) There are no suitable meanings for the operator `/'.

"if1.as", line 52:         g(): () == y: P Integer := (1 + 1) / 0;
                   ...........................................^
[L52 C44] #10 (Error) There are no suitable meanings for the operator `/'.

