;;;
;;; Lisp code generated by Aldor from file "loop1.as".
;;;

(in-package "FOAM-USER" :use '("FOAM" "LISP"))

(declare-prog (|C0-loop1-loop1|) ((|e1| |Env|)))

(declare-prog
  (|C1-loop1-treeIter| |Clos|)
  ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C2-loop1-generBaseFn| |Clos| |Clos| |Clos| |Clos|)
  ((|e1| |Env|)))

(declare-prog (|C3-loop1-generStepper|) ((|e1| |Env|)))

(declare-prog (|C4-loop1-generDone?| |Bool|) ((|e1| |Env|)))

(declare-prog (|C5-loop1-generValue| |Word|) ((|e1| |Env|)))

(declare-prog (|C6-loop1-generBound| |SInt|) ((|e1| |Env|)))

(declare-prog (|C7-loop1-treePrint|) ((|P0-i| |Word|) (|e1| |Env|)))

(declare-prog
  (|C8-loop1-string-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C9-loop1-char-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C10-loop1-textwrit-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C11-loop1-sinteger-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-type |G-loop1| |Clos|)

(declare-type |G-loop1_treeIter_578784298| |Clos|)

(declare-type |G-loop1_treePrint_793370333| |Clos|)

(defspecials
  |G-loop1_treePrint_793370333|
  |G-loop1_treeIter_578784298|)

(|DDecl|
  |Struct-loop1-5|
  (|done?-0| |Clos|)
  (|step!-1| |Clos|)
  (|value-2| |Clos|)
  (|bound-3| |Clos|))

(|DDecl|
  |Struct-loop1-6|
  (|i-0| |Word|)
  (\-1 |Bool|)
  (\-2 |SInt|)
  (\-3 |Word|)
  (|k-4| |Word|)
  (\-5 |Clos|)
  (\-6 |Clos|)
  (\-7 |Clos|)
  (|k-8| |Word|)
  (\-9 |Clos|)
  (\-10 |Clos|)
  (\-11 |Clos|))

(|DDecl|
  |Struct-loop1-8|
  (|SingleInteger-0| |Word|)
  (|Character-1| |Word|)
  (|String-2| |Word|)
  (|TextWriter-3| |Word|)
  (|string-4| |Clos|)
  (<<-5 |Clos|)
  (<<-6 |Clos|)
  (|newline-7| |Word|)
  (|print-8| |Word|)
  (<<-9 |Clos|)
  (<-10 |Clos|)
  (\1-11 |Word|)
  (|quo-12| |Clos|)
  (|integer-13| |Clos|)
  (|dom-14| |Word|)
  (|dom-15| |Word|)
  (|dom-16| |Word|)
  (|dom-17| |Word|)
  (\-18 |Bool|)
  (\-19 |Bool|)
  (\-20 |Bool|)
  (\-21 |Bool|))

(defprog
  ((|C0-loop1-loop1|) ((|e1| |Env|)))
  ((t0 |Clos|)
    (t1 |Clos|)
    (t2 |Clos|)
    (t3 |Clos|)
    (|l0| |Level|)
    (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-loop1-8| |Struct-loop1-8|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall| |G-runtime|)
  (setq |G-loop1| |G-noOperation|)
  (setq t0 (|Clos| |e0| |C11-loop1-sinteger-init|))
  (setq |G-loop1_treeIter_578784298| (|Clos| |e0| |C1-loop1-treeIter|))
  (setq t1 (|Clos| |e0| |C10-loop1-textwrit-init|))
  (setq t2 (|Clos| |e0| |C8-loop1-string-init|))
  (setq t3 (|Clos| |e0| |C9-loop1-char-init|))
  (setq
    |G-loop1_treePrint_793370333|
    (|Clos| |e0| |C7-loop1-treePrint|))
  (|SetLex| |Struct-loop1-8--18| 18 |l0| (the |Bool| nil))
  (|SetLex| |Struct-loop1-8--19| 19 |l0| (the |Bool| nil))
  (|SetLex| |Struct-loop1-8--20| 20 |l0| (the |Bool| nil))
  (|SetLex| |Struct-loop1-8--21| 21 |l0| (the |Bool| nil))
  (|SetLex|
    |Struct-loop1-8-SingleInteger-0|
    0
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t0 (the |SInt| 0)))
  (|SetLex|
    |Struct-loop1-8-dom-14|
    14
    |l0|
    (|Lex| |Struct-loop1-8-SingleInteger-0| 0 |l0|))
  (|SetLex|
    |Struct-loop1-8-1-11|
    11
    |l0|
    (|CCall|
      |G-lazyGetExport!|
      (|Lex| |Struct-loop1-8-dom-14| 14 |l0|)
      (the |SInt| 200090)
      (the |SInt| 142471813)))
  (|SetLex|
    |Struct-loop1-8-<-10|
    10
    |l0|
    (|CCall|
      |G-stdGetWordWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-loop1-8-dom-14| 14 |l0|)
        (the |SInt| 200101)
        (the |SInt| 310195906))))
  (|SetLex|
    |Struct-loop1-8-integer-13|
    13
    |l0|
    (|CCall|
      |G-stdGetWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-loop1-8-dom-14| 14 |l0|)
        (the |SInt| 477900237)
        (the |SInt| 1037839749))))
  (|SetLex|
    |Struct-loop1-8-quo-12|
    12
    |l0|
    (|CCall|
      |G-stdGetWordWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-loop1-8-dom-14| 14 |l0|)
        (the |SInt| 318204816)
        (the |SInt| 786165125))))
  (|SetLex|
    |Struct-loop1-8-TextWriter-3|
    3
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t1 (the |SInt| 0)))
  (|SetLex|
    |Struct-loop1-8-dom-15|
    15
    |l0|
    (|Lex| |Struct-loop1-8-TextWriter-3| 3 |l0|))
  (|SetLex|
    |Struct-loop1-8-print-8|
    8
    |l0|
    (|CCall|
      |G-lazyGetExport!|
      (|Lex| |Struct-loop1-8-dom-15| 15 |l0|)
      (the |SInt| 828947258)
      (the |SInt| 182752316)))
  (|SetLex|
    |Struct-loop1-8-<<-9|
    9
    |l0|
    (|CCall|
      |G-stdGetWordWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-loop1-8-dom-14| 14 |l0|)
        (the |SInt| 51492426)
        (the |SInt| 941383484))))
  (|SetLex|
    |Struct-loop1-8-String-2|
    2
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t2 (the |SInt| 0)))
  (|SetLex|
    |Struct-loop1-8-dom-16|
    16
    |l0|
    (|Lex| |Struct-loop1-8-String-2| 2 |l0|))
  (|SetLex|
    |Struct-loop1-8-string-4|
    4
    |l0|
    (|CCall|
      |G-stdGetWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-loop1-8-dom-16| 16 |l0|)
        (the |SInt| 585283853)
        (the |SInt| 406869008))))
  (|SetLex|
    |Struct-loop1-8-<<-5|
    5
    |l0|
    (|CCall|
      |G-stdGetWordWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-loop1-8-dom-16| 16 |l0|)
        (the |SInt| 51492426)
        (the |SInt| 981655356))))
  (|SetLex|
    |Struct-loop1-8-Character-1|
    1
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t3 (the |SInt| 0)))
  (|SetLex|
    |Struct-loop1-8-dom-17|
    17
    |l0|
    (|Lex| |Struct-loop1-8-Character-1| 1 |l0|))
  (|SetLex|
    |Struct-loop1-8-newline-7|
    7
    |l0|
    (|CCall|
      |G-lazyGetExport!|
      (|Lex| |Struct-loop1-8-dom-17| 17 |l0|)
      (the |SInt| 493486801)
      (the |SInt| 803414590)))
  (|SetLex|
    |Struct-loop1-8-<<-6|
    6
    |l0|
    (|CCall|
      |G-stdGetWordWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-loop1-8-dom-17| 17 |l0|)
        (the |SInt| 51492426)
        (the |SInt| 186261308))))
  (|C7-loop1-treePrint|
    (|CCall|
      (|Lex| |Struct-loop1-8-integer-13| 13 |l0|)
      (|MakeLit| "10"))
    |e0|)
  (block-return |C0-loop1-loop1| ()))

(defprog
  ((|C1-loop1-treeIter| |Clos|) ((|P0-i| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-loop1-6| |Struct-loop1-6|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|SetLex| |Struct-loop1-6-i-0| 0 |l0| |P0-i|)
  (|SetLex| |Struct-loop1-6--2| 2 |l0| (the |SInt| 0))
  (block-return
    |C1-loop1-treeIter|
    (|Clos| |e0| |C2-loop1-generBaseFn|)))

(defprog
  ((|C2-loop1-generBaseFn| |Clos| |Clos| |Clos| |Clos|) ((|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (block-return
    |C2-loop1-generBaseFn|
    (values
      (|Clos| |e0| |C4-loop1-generDone?|)
      (|Clos| |e0| |C3-loop1-generStepper|)
      (|Clos| |e0| |C5-loop1-generValue|)
      (|Clos| |e0| |C6-loop1-generBound|))))

(defprog
  ((|C3-loop1-generStepper|) ((|e1| |Env|)))
  ((t0 |Word|)
    (t1 |Clos|)
    (t2 |Clos|)
    (t3 |Clos|)
    (t4 |Clos|)
    (t5 |Clos|)
    (t6 |Clos|)
    (t7 |Clos|)
    (t8 |Clos|)
    (|e2| |Env|)
    (|l2| |Level|)
    (|e3| |Env|)
    (|l3| |Level|))
  (setq |e2| (|EnvNext| |e1|))
  (setq |l2| (|EnvLevel| |e2|))
  (setq |e3| (|EnvNext| |e2|))
  (setq |l3| (|EnvLevel| |e3|))
  (tagbody
    (cases
      (|Lex| |Struct-loop1-6--2| 2 |l2|)
      (4 (go |Lab13|))
      (3 (go |Lab12|))
      (2 (go |Lab8|))
      (1 (go |Lab7|))
      (0 (go |Lab0|)))
    |Lab0|
    (|SetLex| |Struct-loop1-6--1| 1 |l2| (the |Bool| nil))
    (when
      (|CCall|
        (|Lex| |Struct-loop1-8-<-10| 10 |l3|)
        (|Lex| |Struct-loop1-6-i-0| 0 |l2|)
        (|CCall| |G-lazyForceImport| (|Lex| |Struct-loop1-8-1-11| 11 |l3|)))
      (go |Lab2|))
    (multiple-value-setq
      (t1 t2 t3 t4)
      (|CCall|
        (|C1-loop1-treeIter|
          (|CCall|
            (|Lex| |Struct-loop1-8-quo-12| 12 |l3|)
            (|Lex| |Struct-loop1-6-i-0| 0 |l2|)
            (|CCall| (|Lex| |Struct-loop1-8-integer-13| 13 |l3|) (|MakeLit| "2")))
          |e3|)))
    (|SetLex| |Struct-loop1-6--5| 5 |l2| t1)
    (|SetLex| |Struct-loop1-6--6| 6 |l2| t2)
    (|SetLex| |Struct-loop1-6--7| 7 |l2| t3)
    (go |Lab5|)
    |Lab4|
    (|SetLex| |Struct-loop1-6--2| 2 |l2| (the |SInt| 1))
    (setq t0 (|Lex| |Struct-loop1-6-k-4| 4 |l2|))
    (go |Lab1|)
    |Lab7|
    |Lab5|
    (|CCall| (|Lex| |Struct-loop1-6--6| 6 |l2|))
    (when (|CCall| (|Lex| |Struct-loop1-6--5| 5 |l2|)) (go |Lab6|))
    (|SetLex|
      |Struct-loop1-6-k-4|
      4
      |l2|
      (|CCall| (|Lex| |Struct-loop1-6--7| 7 |l2|)))
    (go |Lab4|)
    |Lab6|
    (|SetLex| |Struct-loop1-6--2| 2 |l2| (the |SInt| 2))
    (setq t0 (|Lex| |Struct-loop1-6-i-0| 0 |l2|))
    (go |Lab1|)
    |Lab8|
    (multiple-value-setq
      (t5 t6 t7 t8)
      (|CCall|
        (|C1-loop1-treeIter|
          (|CCall|
            (|Lex| |Struct-loop1-8-quo-12| 12 |l3|)
            (|Lex| |Struct-loop1-6-i-0| 0 |l2|)
            (|CCall| (|Lex| |Struct-loop1-8-integer-13| 13 |l3|) (|MakeLit| "3")))
          |e3|)))
    (|SetLex| |Struct-loop1-6--9| 9 |l2| t5)
    (|SetLex| |Struct-loop1-6--10| 10 |l2| t6)
    (|SetLex| |Struct-loop1-6--11| 11 |l2| t7)
    (go |Lab10|)
    |Lab9|
    (|SetLex| |Struct-loop1-6--2| 2 |l2| (the |SInt| 3))
    (setq t0 (|Lex| |Struct-loop1-6-k-8| 8 |l2|))
    (go |Lab1|)
    |Lab12|
    |Lab10|
    (|CCall| (|Lex| |Struct-loop1-6--10| 10 |l2|))
    (when (|CCall| (|Lex| |Struct-loop1-6--9| 9 |l2|)) (go |Lab11|))
    (|SetLex|
      |Struct-loop1-6-k-8|
      8
      |l2|
      (|CCall| (|Lex| |Struct-loop1-6--11| 11 |l2|)))
    (go |Lab9|)
    |Lab11|
    (go |Lab3|)
    |Lab2|
    (|SetLex| |Struct-loop1-6--2| 2 |l2| (the |SInt| 4))
    (setq t0 (|Lex| |Struct-loop1-6-i-0| 0 |l2|))
    (go |Lab1|)
    |Lab13|
    |Lab3|
    (|SetLex| |Struct-loop1-6--1| 1 |l2| (the |Bool| t))
    (block-return |C3-loop1-generStepper| ())
    |Lab1|
    (|SetLex| |Struct-loop1-6--3| 3 |l2| t0)
    (block-return |C3-loop1-generStepper| ())))

(defprog
  ((|C4-loop1-generDone?| |Bool|) ((|e1| |Env|)))
  ((|e2| |Env|) (|l2| |Level|))
  (setq |e2| (|EnvNext| |e1|))
  (setq |l2| (|EnvLevel| |e2|))
  (block-return
    |C4-loop1-generDone?|
    (|Lex| |Struct-loop1-6--1| 1 |l2|)))

(defprog
  ((|C5-loop1-generValue| |Word|) ((|e1| |Env|)))
  ((|e2| |Env|) (|l2| |Level|))
  (setq |e2| (|EnvNext| |e1|))
  (setq |l2| (|EnvLevel| |e2|))
  (block-return
    |C5-loop1-generValue|
    (|Lex| |Struct-loop1-6--3| 3 |l2|)))

(defprog
  ((|C6-loop1-generBound| |SInt|) ((|e1| |Env|)))
  ()
  (block-return |C6-loop1-generBound| (the |SInt| -1)))

(defprog
  ((|C7-loop1-treePrint|) ((|P0-i| |Word|) (|e1| |Env|)))
  ((|T0-k| |Word|)
    (t1 |Clos|)
    (t2 |Clos|)
    (t3 |Clos|)
    (t4 |Clos|)
    (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (multiple-value-setq
      (t1 t2 t3 t4)
      (|CCall| (|C1-loop1-treeIter| |P0-i| |e1|)))
    |Lab1|
    (|CCall| t2)
    (when (|CCall| t1) (go |Lab2|))
    (setq |T0-k| (|CCall| t3))
    (|CCall|
      (|Lex| |Struct-loop1-8-<<-9| 9 |l1|)
      (|CCall|
        |G-lazyForceImport|
        (|Lex| |Struct-loop1-8-print-8| 8 |l1|))
      |T0-k|)
    (|CCall|
      (|Lex| |Struct-loop1-8-<<-5| 5 |l1|)
      (|CCall|
        |G-lazyForceImport|
        (|Lex| |Struct-loop1-8-print-8| 8 |l1|))
      (|CCall| (|Lex| |Struct-loop1-8-string-4| 4 |l1|) (|MakeLit| " ")))
    (go |Lab1|)
    |Lab2|
    (|CCall|
      (|Lex| |Struct-loop1-8-<<-6| 6 |l1|)
      (|CCall|
        |G-lazyForceImport|
        (|Lex| |Struct-loop1-8-print-8| 8 |l1|))
      (|CCall|
        |G-lazyForceImport|
        (|Lex| |Struct-loop1-8-newline-7| 7 |l1|)))
    (block-return |C7-loop1-treePrint| ())))

(defprog
  ((|C8-loop1-string-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-loop1-8--18| 18 |l1|) (go |Lab0|))
    (|SetLex| |Struct-loop1-8--18| 18 |l1| (the |Bool| t))
    (|CCall| |G-string|)
    |Lab0|
    (block-return |C8-loop1-string-init| |G-string_String_517719887|)))

(defprog
  ((|C9-loop1-char-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-loop1-8--19| 19 |l1|) (go |Lab0|))
    (|SetLex| |Struct-loop1-8--19| 19 |l1| (the |Bool| t))
    (|CCall| |G-char|)
    |Lab0|
    (block-return |C9-loop1-char-init| |G-char_Character_157812325|)))

(defprog
  ((|C10-loop1-textwrit-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-loop1-8--20| 20 |l1|) (go |Lab0|))
    (|SetLex| |Struct-loop1-8--20| 20 |l1| (the |Bool| t))
    (|CCall| |G-textwrit|)
    |Lab0|
    (block-return
      |C10-loop1-textwrit-init|
      |G-textwrit_TextWriter_981343789|)))

(defprog
  ((|C11-loop1-sinteger-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-loop1-8--21| 21 |l1|) (go |Lab0|))
    (|SetLex| |Struct-loop1-8--21| 21 |l1| (the |Bool| t))
    (|CCall| |G-sinteger|)
    |Lab0|
    (block-return
      |C11-loop1-sinteger-init|
      |G-sinteger_SingleInteger_956566065|)))

(setq |G-loop1| (|Clos| nil |C0-loop1-loop1|))

(setq |G-loop1_treePrint_793370333| nil)

(setq |G-loop1_treeIter_578784298| nil)

(file-imports
  '((|G-sinteger| "sinteger" |initializer| "")
      (|G-textwrit| "textwrit" |initializer| "")
      (|G-char| "char" |initializer| "")
      (|G-string| "string" |initializer| "")
      (|G-char_Character_157812325| "Character" 157812325 "char")
      (|G-string_String_517719887| "String" 517719887 "string")
      (|G-textwrit_TextWriter_981343789| "TextWriter" 981343789 "textwrit")
      (|G-stdGetWordRetWord0| "stdGetWordRetWord0" 0 "")
      (|G-stdGetWordWordRetWord0| "stdGetWordWordRetWord0" 0 "")
      (|G-rtDelayedGetExport!| "rtDelayedGetExport!" 0 "")
      (|G-lazyForceImport| "lazyForceImport" 0 "")
      (|G-lazyGetExport!| "lazyGetExport!" 0 "")
      (|G-rtLazyDomFrInit| "rtLazyDomFrInit" 0 "")
      (|G-sinteger_SingleInteger_956566065|
        "SingleInteger"
        956566065
        "sinteger")
      (|G-runtime| "runtime" |initializer| "")
      (|G-noOperation| "noOperation" 0 "")))

(file-exports
  '((|G-loop1_treeIter_578784298| "treeIter" 578784298 "loop1")
      (|G-loop1_treePrint_793370333| "treePrint" 793370333 "loop1")
      (|G-loop1| "loop1" |initializer| "")))
