;;;
;;; Lisp code generated by Aldor from file "loop0.as".
;;;

(in-package "FOAM-USER" :use '("FOAM" "LISP"))

(declare-prog (|C0-loop0-loop0|) ((|e1| |Env|)))

(declare-prog
  (|C1-loop0-pow1| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C2-loop0-pow2| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C3-loop0-pow3| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C4-loop0-pow4| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))

(declare-prog
  (|C5-loop0-lazyFnGetter| |Clos|)
  ((|P0-init| |Word|) (|e1| |Env|)))

(declare-prog
  (|C6-loop0-lazyGetter| |Clos|)
  ((|P0-a| |Word|) (|e1| |Env|)))

(declare-prog (|C7-loop0-lazyGetter2|) ((|e1| |Env|)))

(declare-prog
  (|C8-loop0-char-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C9-loop0-textwrit-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C10-loop0-integer-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C11-loop0-segment-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C12-loop0-boolean-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-type |G-loop0| |Clos|)

(declare-type |G-loop0_pow1_933001063| |Clos|)

(declare-type |G-loop0_pow2_933001063| |Clos|)

(declare-type |G-loop0_pow3_933001063| |Clos|)

(declare-type |G-loop0_pow4_933001063| |Clos|)

(defspecials
  |G-loop0_pow4_933001063|
  |G-loop0_pow3_933001063|
  |G-loop0_pow2_933001063|
  |G-loop0_pow1_933001063|)

(|DDecl|
  |Struct-loop0-5|
  (|done?-0| |Clos|)
  (|step!-1| |Clos|)
  (|value-2| |Clos|)
  (|bound-3| |Clos|))

(|DDecl|
  |Struct-loop0-6|
  (|getter-0| |Clos|)
  (|flag-1| |Bool|)
  (|self-2| |Clos|))

(|DDecl|
  |Struct-loop0-7|
  (|Boolean-0| |Word|)
  (|Segment-1| |Clos|)
  (|Integer-2| |Word|)
  (|Character-3| |Word|)
  (|TextWriter-4| |Word|)
  (|true-5| |Word|)
  (<<-6 |Clos|)
  (|newline-7| |Word|)
  (|print-8| |Word|)
  (\..-9 |Clos|)
  (|generator-10| |Clos|)
  (|integer-11| |Clos|)
  (<<-12 |Clos|)
  (>-13 |Clos|)
  (<=-14 |Clos|)
  (\0-15 |Word|)
  (\+-16 |Clos|)
  (\--17 |Clos|)
  (\1-18 |Word|)
  (*-19 |Clos|)
  (|dom-20| |Word|)
  (|dom-21| |Word|)
  (|dom-22| |Word|)
  (|ClosedSegment-23| |Clos|)
  (|dom-24| |Word|)
  (|dom-25| |Word|)
  (\-26 |Bool|)
  (\-27 |Bool|)
  (\-28 |Bool|)
  (\-29 |Bool|)
  (\-30 |Bool|))

(defprog
  ((|C0-loop0-loop0|) ((|e1| |Env|)))
  ((t0 |Clos|)
    (t1 |Clos|)
    (t2 |Clos|)
    (t3 |SInt|)
    (t4 |SInt|)
    (t5 |Clos|)
    (t6 |Clos|)
    (|l0| |Level|)
    (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-loop0-7| |Struct-loop0-7|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (tagbody
    (|CCall| |G-runtime|)
    (setq |G-loop0| |G-noOperation|)
    (setq t0 (|Clos| |e0| |C10-loop0-integer-init|))
    (setq t1 (|Clos| |e0| |C12-loop0-boolean-init|))
    (setq |G-loop0_pow1_933001063| (|Clos| |e0| |C1-loop0-pow1|))
    (setq |G-loop0_pow2_933001063| (|Clos| |e0| |C2-loop0-pow2|))
    (setq t2 (|Clos| |e0| |C11-loop0-segment-init|))
    (setq |G-loop0_pow3_933001063| (|Clos| |e0| |C3-loop0-pow3|))
    (setq |G-loop0_pow4_933001063| (|Clos| |e0| |C4-loop0-pow4|))
    (setq t5 (|Clos| |e0| |C9-loop0-textwrit-init|))
    (setq t6 (|Clos| |e0| |C8-loop0-char-init|))
    (|SetLex| |Struct-loop0-7--26| 26 |l0| (the |Bool| nil))
    (|SetLex| |Struct-loop0-7--27| 27 |l0| (the |Bool| nil))
    (|SetLex| |Struct-loop0-7--28| 28 |l0| (the |Bool| nil))
    (|SetLex| |Struct-loop0-7--29| 29 |l0| (the |Bool| nil))
    (|SetLex| |Struct-loop0-7--30| 30 |l0| (the |Bool| nil))
    (|SetLex|
      |Struct-loop0-7-Integer-2|
      2
      |l0|
      (|CCall| |G-rtLazyDomFrInit| t0 (the |SInt| 0)))
    (|SetLex|
      |Struct-loop0-7-dom-20|
      20
      |l0|
      (|Lex| |Struct-loop0-7-Integer-2| 2 |l0|))
    (|SetLex|
      |Struct-loop0-7-1-18|
      18
      |l0|
      (|CCall|
        |G-lazyGetExport!|
        (|Lex| |Struct-loop0-7-dom-20| 20 |l0|)
        (the |SInt| 200090)
        (the |SInt| 484208045)))
    (|SetLex|
      |Struct-loop0-7-0-15|
      15
      |l0|
      (|CCall|
        |G-lazyGetExport!|
        (|Lex| |Struct-loop0-7-dom-20| 20 |l0|)
        (the |SInt| 200089)
        (the |SInt| 484208045)))
    (|SetLex|
      |Struct-loop0-7-Boolean-0|
      0
      |l0|
      (|CCall| |G-rtLazyDomFrInit| t1 (the |SInt| 0)))
    (|SetLex|
      |Struct-loop0-7->-13|
      13
      |l0|
      (|CCall|
        |G-stdGetWordWordRetWord0|
        (|CCall|
          |G-rtDelayedGetExport!|
          (|Lex| |Struct-loop0-7-dom-20| 20 |l0|)
          (the |SInt| 200103)
          (the |SInt| 651003586))))
    (|SetLex|
      |Struct-loop0-7-*-19|
      19
      |l0|
      (|CCall|
        |G-stdGetWordWordRetWord0|
        (|CCall|
          |G-rtDelayedGetExport!|
          (|Lex| |Struct-loop0-7-dom-20| 20 |l0|)
          (the |SInt| 200083)
          (the |SInt| 394967248))))
    (|SetLex|
      |Struct-loop0-7---17|
      17
      |l0|
      (|CCall|
        |G-stdGetWordWordRetWord0|
        (|CCall|
          |G-rtDelayedGetExport!|
          (|Lex| |Struct-loop0-7-dom-20| 20 |l0|)
          (the |SInt| 200086)
          (the |SInt| 394967248))))
    (|SetLex|
      |Struct-loop0-7-dom-21|
      21
      |l0|
      (|Lex| |Struct-loop0-7-Boolean-0| 0 |l0|))
    (|SetLex|
      |Struct-loop0-7-true-5|
      5
      |l0|
      (|CCall|
        |G-lazyGetExport!|
        (|Lex| |Struct-loop0-7-dom-21| 21 |l0|)
        (the |SInt| 11137124)
        (the |SInt| 740244383)))
    (|SetLex|
      |Struct-loop0-7-Segment-1|
      1
      |l0|
      (|CCall|
        |G-stdGetWordRetWord0|
        (|CCall| |G-rtDelayedInit!| t2 (the |SInt| 0))))
    (|SetLex|
      |Struct-loop0-7-dom-22|
      22
      |l0|
      (|CCall|
        (|Lex| |Struct-loop0-7-Segment-1| 1 |l0|)
        (|Lex| |Struct-loop0-7-Integer-2| 2 |l0|)))
    (|SetLex|
      |Struct-loop0-7-ClosedSegment-23|
      23
      |l0|
      (|CCall|
        |G-stdGetWordRetWord0|
        (|CCall| |G-rtDelayedInit!| t2 (the |SInt| 1))))
    (|FoamEnvEnsure|
      (|ClosEnv| (|Lex| |Struct-loop0-7-ClosedSegment-23| 23 |l0|)))
    (setq t3 (the |SInt| 794824237))
    |Lab1|
    (|SetLex|
      |Struct-loop0-7-generator-10|
      10
      |l0|
      (|C5-loop0-lazyFnGetter|
        (|CCall|
          |G-rtDelayedGetExport!|
          (|Lex| |Struct-loop0-7-dom-22| 22 |l0|)
          (the |SInt| 113320568)
          (|SIntPlusMod|
            (the |SInt| 490013613)
            (|SIntShiftUp|
              (|SIntAnd|
                (|SIntPlusMod|
                  (the |SInt| 32236)
                  (|SIntShiftUp|
                    (|SIntAnd|
                      (|SIntPlusMod| t3 (the |SInt| 74075968) (the |SInt| 1073741789))
                      (the |SInt| 16777215))
                    (the |SInt| 6))
                  (the |SInt| 1073741789))
                (the |SInt| 16777215))
              (the |SInt| 6))
            (the |SInt| 1073741789)))
        |e0|))
    (|FoamEnvEnsure|
      (|ClosEnv| (|Lex| |Struct-loop0-7-ClosedSegment-23| 23 |l0|)))
    (setq t4 (the |SInt| 794824237))
    |Lab3|
    (|SetLex|
      |Struct-loop0-7-..-9|
      9
      |l0|
      (|CCall|
        |G-stdGetWordWordRetWord0|
        (|CCall|
          |G-rtDelayedGetExport!|
          (|Lex| |Struct-loop0-7-dom-22| 22 |l0|)
          (the |SInt| 51488814)
          (|SIntPlusMod| t4 (the |SInt| 984500992) (the |SInt| 1073741789)))))
    (|SetLex|
      |Struct-loop0-7-integer-11|
      11
      |l0|
      (|CCall|
        |G-stdGetWordRetWord0|
        (|CCall|
          |G-rtDelayedGetExport!|
          (|Lex| |Struct-loop0-7-dom-20| 20 |l0|)
          (the |SInt| 477900237)
          (the |SInt| 305834192))))
    (|SetLex|
      |Struct-loop0-7-+-16|
      16
      |l0|
      (|CCall|
        |G-stdGetWordWordRetWord0|
        (|CCall|
          |G-rtDelayedGetExport!|
          (|Lex| |Struct-loop0-7-dom-20| 20 |l0|)
          (the |SInt| 200084)
          (the |SInt| 394967248))))
    (|SetLex|
      |Struct-loop0-7-<=-14|
      14
      |l0|
      (|CCall|
        |G-stdGetWordWordRetWord0|
        (|CCall|
          |G-rtDelayedGetExport!|
          (|Lex| |Struct-loop0-7-dom-20| 20 |l0|)
          (the |SInt| 51492427)
          (the |SInt| 651003586))))
    (|SetLex|
      |Struct-loop0-7-TextWriter-4|
      4
      |l0|
      (|CCall| |G-rtLazyDomFrInit| t5 (the |SInt| 0)))
    (|SetLex|
      |Struct-loop0-7-dom-24|
      24
      |l0|
      (|Lex| |Struct-loop0-7-TextWriter-4| 4 |l0|))
    (|SetLex|
      |Struct-loop0-7-print-8|
      8
      |l0|
      (|CCall|
        |G-lazyGetExport!|
        (|Lex| |Struct-loop0-7-dom-24| 24 |l0|)
        (the |SInt| 828947258)
        (the |SInt| 182752316)))
    (|SetLex|
      |Struct-loop0-7-<<-12|
      12
      |l0|
      (|CCall|
        |G-stdGetWordWordRetWord0|
        (|CCall|
          |G-rtDelayedGetExport!|
          (|Lex| |Struct-loop0-7-dom-20| 20 |l0|)
          (the |SInt| 51492426)
          (the |SInt| 533651260))))
    (|SetLex|
      |Struct-loop0-7-Character-3|
      3
      |l0|
      (|CCall| |G-rtLazyDomFrInit| t6 (the |SInt| 0)))
    (|SetLex|
      |Struct-loop0-7-dom-25|
      25
      |l0|
      (|Lex| |Struct-loop0-7-Character-3| 3 |l0|))
    (|SetLex|
      |Struct-loop0-7-newline-7|
      7
      |l0|
      (|CCall|
        |G-lazyGetExport!|
        (|Lex| |Struct-loop0-7-dom-25| 25 |l0|)
        (the |SInt| 493486801)
        (the |SInt| 803414590)))
    (|SetLex|
      |Struct-loop0-7-<<-6|
      6
      |l0|
      (|CCall|
        |G-stdGetWordWordRetWord0|
        (|CCall|
          |G-rtDelayedGetExport!|
          (|Lex| |Struct-loop0-7-dom-25| 25 |l0|)
          (the |SInt| 51492426)
          (the |SInt| 186261308))))
    (|CCall|
      (|Lex| |Struct-loop0-7-<<-6| 6 |l0|)
      (|CCall|
        (|Lex| |Struct-loop0-7-<<-12| 12 |l0|)
        (|CCall|
          |G-lazyForceImport|
          (|Lex| |Struct-loop0-7-print-8| 8 |l0|))
        (|C1-loop0-pow1|
          (|CCall| (|Lex| |Struct-loop0-7-integer-11| 11 |l0|) (|MakeLit| "3"))
          (|CCall| (|Lex| |Struct-loop0-7-integer-11| 11 |l0|) (|MakeLit| "4"))
          |e0|))
      (|CCall|
        |G-lazyForceImport|
        (|Lex| |Struct-loop0-7-newline-7| 7 |l0|)))
    (|CCall|
      (|Lex| |Struct-loop0-7-<<-6| 6 |l0|)
      (|CCall|
        (|Lex| |Struct-loop0-7-<<-12| 12 |l0|)
        (|CCall|
          |G-lazyForceImport|
          (|Lex| |Struct-loop0-7-print-8| 8 |l0|))
        (|C2-loop0-pow2|
          (|CCall| (|Lex| |Struct-loop0-7-integer-11| 11 |l0|) (|MakeLit| "3"))
          (|CCall| (|Lex| |Struct-loop0-7-integer-11| 11 |l0|) (|MakeLit| "4"))
          |e0|))
      (|CCall|
        |G-lazyForceImport|
        (|Lex| |Struct-loop0-7-newline-7| 7 |l0|)))
    (|CCall|
      (|Lex| |Struct-loop0-7-<<-6| 6 |l0|)
      (|CCall|
        (|Lex| |Struct-loop0-7-<<-12| 12 |l0|)
        (|CCall|
          |G-lazyForceImport|
          (|Lex| |Struct-loop0-7-print-8| 8 |l0|))
        (|C3-loop0-pow3|
          (|CCall| (|Lex| |Struct-loop0-7-integer-11| 11 |l0|) (|MakeLit| "3"))
          (|CCall| (|Lex| |Struct-loop0-7-integer-11| 11 |l0|) (|MakeLit| "4"))
          |e0|))
      (|CCall|
        |G-lazyForceImport|
        (|Lex| |Struct-loop0-7-newline-7| 7 |l0|)))
    (|CCall|
      (|Lex| |Struct-loop0-7-<<-6| 6 |l0|)
      (|CCall|
        (|Lex| |Struct-loop0-7-<<-12| 12 |l0|)
        (|CCall|
          |G-lazyForceImport|
          (|Lex| |Struct-loop0-7-print-8| 8 |l0|))
        (|C4-loop0-pow4|
          (|CCall| (|Lex| |Struct-loop0-7-integer-11| 11 |l0|) (|MakeLit| "3"))
          (|CCall| (|Lex| |Struct-loop0-7-integer-11| 11 |l0|) (|MakeLit| "4"))
          |e0|))
      (|CCall|
        |G-lazyForceImport|
        (|Lex| |Struct-loop0-7-newline-7| 7 |l0|)))
    (block-return |C0-loop0-loop0| ())
    |Lab2|
    (setq
      t4
      (|CCall|
        |G-domainHash!|
        (|CCall|
          (|Lex| |Struct-loop0-7-ClosedSegment-23| 23 |l0|)
          (|Lex| |Struct-loop0-7-Integer-2| 2 |l0|))))
    (go |Lab3|)
    |Lab0|
    (setq
      t3
      (|CCall|
        |G-domainHash!|
        (|CCall|
          (|Lex| |Struct-loop0-7-ClosedSegment-23| 23 |l0|)
          (|Lex| |Struct-loop0-7-Integer-2| 2 |l0|))))
    (go |Lab1|)))

(defprog
  ((|C1-loop0-pow1| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ((|T0-prod| |Word|) (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (setq
      |T0-prod|
      (|CCall| |G-lazyForceImport| (|Lex| |Struct-loop0-7-1-18| 18 |l1|)))
    (go |Lab1|)
    |Lab0|
    (setq
      |T0-prod|
      (|CCall| (|Lex| |Struct-loop0-7-*-19| 19 |l1|) |P0-i| |T0-prod|))
    (setq
      |P1-j|
      (|CCall|
        (|Lex| |Struct-loop0-7---17| 17 |l1|)
        |P1-j|
        (|CCall| |G-lazyForceImport| (|Lex| |Struct-loop0-7-1-18| 18 |l1|))))
    |Lab1|
    (when
      (|BoolNot|
        (|CCall|
          (|Lex| |Struct-loop0-7->-13| 13 |l1|)
          |P1-j|
          (|CCall| |G-lazyForceImport| (|Lex| |Struct-loop0-7-0-15| 15 |l1|))))
      (go |Lab2|))
    (go |Lab0|)
    |Lab2|
    (block-return |C1-loop0-pow1| |T0-prod|)))

(defprog
  ((|C2-loop0-pow2| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ((|T0-prod| |Word|) (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (setq
      |T0-prod|
      (|CCall| |G-lazyForceImport| (|Lex| |Struct-loop0-7-1-18| 18 |l1|)))
    (go |Lab1|)
    |Lab0|
    (setq
      |P1-j|
      (|CCall|
        (|Lex| |Struct-loop0-7---17| 17 |l1|)
        |P1-j|
        (|CCall| |G-lazyForceImport| (|Lex| |Struct-loop0-7-1-18| 18 |l1|))))
    |Lab1|
    (when
      (|BoolNot|
        (|CCall|
          (|Lex| |Struct-loop0-7->-13| 13 |l1|)
          |P1-j|
          (|CCall| |G-lazyForceImport| (|Lex| |Struct-loop0-7-0-15| 15 |l1|))))
      (go |Lab2|))
    (setq
      |T0-prod|
      (|CCall| (|Lex| |Struct-loop0-7-*-19| 19 |l1|) |P0-i| |T0-prod|))
    (when
      (|BoolNot|
        (|CCall| |G-lazyForceImport| (|Lex| |Struct-loop0-7-true-5| 5 |l1|)))
      (go |Lab2|))
    (go |Lab0|)
    |Lab2|
    (block-return |C2-loop0-pow2| |T0-prod|)))

(defprog
  ((|C3-loop0-pow3| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ((|T0-prod| |Word|)
    (t1 |Clos|)
    (t2 |Clos|)
    (t3 |Clos|)
    (t4 |Clos|)
    (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (setq
      |T0-prod|
      (|CCall| |G-lazyForceImport| (|Lex| |Struct-loop0-7-1-18| 18 |l1|)))
    (multiple-value-setq
      (t1 t2 t3 t4)
      (|CCall|
        (|CCall|
          (|Lex| |Struct-loop0-7-generator-10| 10 |l1|)
          (|CCall|
            (|Lex| |Struct-loop0-7-..-9| 9 |l1|)
            (|CCall| |G-lazyForceImport| (|Lex| |Struct-loop0-7-1-18| 18 |l1|))
            |P1-j|))))
    |Lab1|
    (|CCall| t2)
    (when (|CCall| t1) (go |Lab2|))
    (|CCall| t3)
    (setq
      |T0-prod|
      (|CCall| (|Lex| |Struct-loop0-7-*-19| 19 |l1|) |P0-i| |T0-prod|))
    (go |Lab1|)
    |Lab2|
    (block-return |C3-loop0-pow3| |T0-prod|)))

(defprog
  ((|C4-loop0-pow4| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|e1| |Env|)))
  ((|T0-prod| |Word|)
    (|T1-k| |Word|)
    (|T2-h| |Word|)
    (t3 |Clos|)
    (t4 |Clos|)
    (t5 |Clos|)
    (t6 |Clos|)
    (t7 |Clos|)
    (t8 |Clos|)
    (t9 |Clos|)
    (t10 |Clos|)
    (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (setq
      |T0-prod|
      (|CCall| |G-lazyForceImport| (|Lex| |Struct-loop0-7-1-18| 18 |l1|)))
    (multiple-value-setq
      (t3 t4 t5 t6)
      (|CCall|
        (|CCall|
          (|Lex| |Struct-loop0-7-generator-10| 10 |l1|)
          (|CCall|
            (|Lex| |Struct-loop0-7-..-9| 9 |l1|)
            (|CCall| (|Lex| |Struct-loop0-7-integer-11| 11 |l1|) (|MakeLit| "2"))
            (|CCall|
              (|Lex| |Struct-loop0-7-+-16| 16 |l1|)
              |P1-j|
              (|CCall| |G-lazyForceImport| (|Lex| |Struct-loop0-7-1-18| 18 |l1|)))))))
    (multiple-value-setq
      (t7 t8 t9 t10)
      (|CCall|
        (|CCall|
          (|Lex| |Struct-loop0-7-generator-10| 10 |l1|)
          (|CCall|
            (|Lex| |Struct-loop0-7-..-9| 9 |l1|)
            (|CCall| |G-lazyForceImport| (|Lex| |Struct-loop0-7-1-18| 18 |l1|))
            |P1-j|))))
    |Lab1|
    (|CCall| t4)
    (when (|CCall| t3) (go |Lab2|))
    (setq |T2-h| (|CCall| t5))
    (|CCall| t8)
    (when (|CCall| t7) (go |Lab2|))
    (setq |T1-k| (|CCall| t9))
    (when
      (|CCall| (|Lex| |Struct-loop0-7->-13| 13 |l1|) |T2-h| |T1-k|)
      (go |Lab3|))
    (go |Lab1|)
    |Lab3|
    (when
      (|BoolNot|
        (|CCall| (|Lex| |Struct-loop0-7-<=-14| 14 |l1|) |T1-k| |T2-h|))
      (go |Lab2|))
    (setq
      |T0-prod|
      (|CCall| (|Lex| |Struct-loop0-7-*-19| 19 |l1|) |P0-i| |T0-prod|))
    (go |Lab1|)
    |Lab2|
    (block-return |C4-loop0-pow4| |T0-prod|)))

(defprog
  ((|C5-loop0-lazyFnGetter| |Clos|) ((|P0-init| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-loop0-6| |Struct-loop0-6|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|SetLex| |Struct-loop0-6-getter-0| 0 |l0| |P0-init|)
  (|SetLex| |Struct-loop0-6-flag-1| 1 |l0| (the |Bool| nil))
  (|SetLex|
    |Struct-loop0-6-self-2|
    2
    |l0|
    (|Clos| |e0| |C6-loop0-lazyGetter|))
  (|SetEnvInfo| |e0| (|Clos| |e0| |C7-loop0-lazyGetter2|))
  (block-return
    |C5-loop0-lazyFnGetter|
    (|Lex| |Struct-loop0-6-self-2| 2 |l0|)))

(defprog
  ((|C6-loop0-lazyGetter| |Clos|) ((|P0-a| |Word|) (|e1| |Env|)))
  ((t0 |Clos|) (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-loop0-6-flag-1| 1 |l1|) (go |Lab0|))
    (setq t0 (|CCall| (|Lex| |Struct-loop0-6-getter-0| 0 |l1|)))
    (|SetClosEnv| (|Lex| |Struct-loop0-6-self-2| 2 |l1|) (|ClosEnv| t0))
    (|SetClosFun| (|Lex| |Struct-loop0-6-self-2| 2 |l1|) (|ClosFun| t0))
    (|SetLex| |Struct-loop0-6-flag-1| 1 |l1| (the |Bool| t))
    |Lab0|
    (block-return
      |C6-loop0-lazyGetter|
      (|CCall| (|Lex| |Struct-loop0-6-self-2| 2 |l1|) |P0-a|))))

(defprog
  ((|C7-loop0-lazyGetter2|) ((|e1| |Env|)))
  ((t0 |Clos|) (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-loop0-6-flag-1| 1 |l1|) (go |Lab0|))
    (setq t0 (|CCall| (|Lex| |Struct-loop0-6-getter-0| 0 |l1|)))
    (|SetLex| |Struct-loop0-6-flag-1| 1 |l1| (the |Bool| t))
    (|SetClosEnv| (|Lex| |Struct-loop0-6-self-2| 2 |l1|) (|ClosEnv| t0))
    (|SetClosFun| (|Lex| |Struct-loop0-6-self-2| 2 |l1|) (|ClosFun| t0))
    (|SetEnvInfo| |e1| nil)
    |Lab0|
    (block-return |C7-loop0-lazyGetter2| ())))

(defprog
  ((|C8-loop0-char-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-loop0-7--26| 26 |l1|) (go |Lab0|))
    (|SetLex| |Struct-loop0-7--26| 26 |l1| (the |Bool| t))
    (|CCall| |G-char|)
    |Lab0|
    (block-return |C8-loop0-char-init| |G-char_Character_157812325|)))

(defprog
  ((|C9-loop0-textwrit-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-loop0-7--27| 27 |l1|) (go |Lab0|))
    (|SetLex| |Struct-loop0-7--27| 27 |l1| (the |Bool| t))
    (|CCall| |G-textwrit|)
    |Lab0|
    (block-return
      |C9-loop0-textwrit-init|
      |G-textwrit_TextWriter_981343789|)))

(defprog
  ((|C10-loop0-integer-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-loop0-7--28| 28 |l1|) (go |Lab0|))
    (|SetLex| |Struct-loop0-7--28| 28 |l1| (the |Bool| t))
    (|CCall| |G-integer|)
    |Lab0|
    (block-return |C10-loop0-integer-init| |G-integer_Integer_856101873|)))

(defprog
  ((|C11-loop0-segment-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-loop0-7--29| 29 |l1|) (go |Lab0|))
    (|SetLex| |Struct-loop0-7--29| 29 |l1| (the |Bool| t))
    (|CCall| |G-segment|)
    |Lab0|
    (when (|SIntNE| |P0-idx| (the |SInt| 1)) (go |Lab1|))
    (block-return
      |C11-loop0-segment-init|
      |G-segment_ClosedSegment_763025775|)
    |Lab1|
    (block-return |C11-loop0-segment-init| |G-segment_Segment_234912097|)))

(defprog
  ((|C12-loop0-boolean-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-loop0-7--30| 30 |l1|) (go |Lab0|))
    (|SetLex| |Struct-loop0-7--30| 30 |l1| (the |Bool| t))
    (|CCall| |G-boolean|)
    |Lab0|
    (block-return |C12-loop0-boolean-init| |G-boolean_Boolean_494244583|)))

(setq |G-loop0| (|Clos| nil |C0-loop0-loop0|))

(setq |G-loop0_pow4_933001063| nil)

(setq |G-loop0_pow3_933001063| nil)

(setq |G-loop0_pow2_933001063| nil)

(setq |G-loop0_pow1_933001063| nil)

(file-imports
  '((|G-boolean| "boolean" |initializer| "")
      (|G-segment| "segment" |initializer| "")
      (|G-integer| "integer" |initializer| "")
      (|G-textwrit| "textwrit" |initializer| "")
      (|G-char| "char" |initializer| "")
      (|G-char_Character_157812325| "Character" 157812325 "char")
      (|G-textwrit_TextWriter_981343789| "TextWriter" 981343789 "textwrit")
      (|G-segment_ClosedSegment_763025775|
        "ClosedSegment"
        763025775
        "segment")
      (|G-stdGetWordRetWord0| "stdGetWordRetWord0" 0 "")
      (|G-rtDelayedInit!| "rtDelayedInit!" 0 "")
      (|G-segment_Segment_234912097| "Segment" 234912097 "segment")
      (|G-stdGetWordWordRetWord0| "stdGetWordWordRetWord0" 0 "")
      (|G-rtDelayedGetExport!| "rtDelayedGetExport!" 0 "")
      (|G-boolean_Boolean_494244583| "Boolean" 494244583 "boolean")
      (|G-lazyForceImport| "lazyForceImport" 0 "")
      (|G-lazyGetExport!| "lazyGetExport!" 0 "")
      (|G-domainHash!| "domainHash!" 0 "")
      (|G-rtLazyDomFrInit| "rtLazyDomFrInit" 0 "")
      (|G-integer_Integer_856101873| "Integer" 856101873 "integer")
      (|G-runtime| "runtime" |initializer| "")
      (|G-noOperation| "noOperation" 0 "")))

(file-exports
  '((|G-loop0_pow1_933001063| "pow1" 933001063 "loop0")
      (|G-loop0_pow2_933001063| "pow2" 933001063 "loop0")
      (|G-loop0_pow3_933001063| "pow3" 933001063 "loop0")
      (|G-loop0_pow4_933001063| "pow4" 933001063 "loop0")
      (|G-loop0| "loop0" |initializer| "")))
