/*
 * C code generated by Aldor from file "mandel.as".
 */

#include "foam_c.h"

typedef struct Fmt5  *PFmt5;
typedef struct Fmt6  *PFmt6;
typedef struct Fmt7  *PFmt7;
typedef struct Fmt8  *PFmt8;
typedef struct Fmt9  *PFmt9;
typedef struct Fmt10  *PFmt10;
typedef struct Fmt11  *PFmt11;
typedef struct Fmt12  *PFmt12;
typedef struct Fmt13  *PFmt13;
typedef struct Fmt14  *PFmt14;
typedef struct Fmt15  *PFmt15;
typedef struct Fmt16  *PFmt16;
typedef struct Fmt17  *PFmt17;
typedef struct Fmt18  *PFmt18;
typedef struct Fmt19  *PFmt19;
typedef struct Fmt20  *PFmt20;
typedef struct Fmt21  *PFmt21;
struct Fmt5 {
        FiPtr X0_empty;
};
struct Fmt6 {
        FiPtr X0_empty;
};
struct Fmt7 {
        FiWord X0_maxIters;
};
struct Fmt8 {
        FiPtr X0_empty;
};
struct Fmt9 {
        FiWord X0_DoubleFloat;
        FiClos X1_Complex;
        FiWord X2_TextWriter;
        FiWord X3_print;
        FiWord X4_0;
        FiWord X5_dom;
        FiWord X6_dom;
        FiBool X7;
        FiBool X8;
        FiBool X9;
};
struct Fmt10 {
        FiPtr X0_empty;
};
struct Fmt11 {
        FiPtr X0_empty;
};
struct Fmt12 {
        FiPtr X0_empty;
};
struct Fmt13 {
        FiPtr X0_empty;
};
struct Fmt14 {
        FiDFlo X0_double;
};
struct Fmt15 {
        FiPtr X0_empty;
};
struct Fmt16 {
        FiWord X0_real;
        FiWord X1_imag;
};
struct Fmt17 {
        FiPtr X0_empty;
};
struct Fmt18 {
        FiPtr X0_empty;
};
struct Fmt19 {
        FiPtr X0_empty;
};
struct Fmt20 {
        FiPtr X0_empty;
};
struct Fmt21 {
        FiClos X0;
        FiClos X1;
        FiClos X2;
};
static FiProg C0_mandel;
static void CF0_mandel(FiEnv e1);
static FiProg C1_drawMand;
static void CF1_drawMand(FiEnv e1, FiWord P0_minR, FiWord P1_maxR, FiWord P2_numR, FiWord P3_minI, FiWord P4_maxI, FiWord P5_numI, FiClos P6_drawPt, FiWord P7_maxIters);
static FiProg C2_mandel;
static FiWord CF2_mandel(FiEnv e1, FiWord P0_c);
static FiProg C3_drawPoint;
static void CF3_drawPoint(FiEnv e1, FiWord P0_x, FiWord P1_y, FiWord P2_n);
static FiProg C4_textwrit_MINUS_init;
static FiWord CF4_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C5_dfloat_MINUS_init;
static FiWord CF5_dfloat_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C6_complex_MINUS_init;
static FiWord CF6_complex_MINUS_init(FiEnv e1, FiSInt P0_idx);
extern FiClos G_TY19J_mandel;
static FiClos *pG_NQYQM_noOperation;
extern FiClos G_TAMI0_mandel__drawPoint__326;
extern FiWord G_OSMNC_mandel__maxY__08372534;
extern FiWord G_EYTUA_mandel__maxX__08372534;
extern FiWord G_CEZY9_mandel__maxN__08372534;
extern FiClos G_64T72_mandel__drawMand__6597;
static FiClos *pG_XIPRL_runtime;
static FiWord *pG_KJ3UJ_dfloat__DoubleFloat__;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_LM9I3_complex__Complex__500;
static FiClos *pG_RSHLY_rtDelayedInit_BANG_;
static FiClos *pG_ZZZKG_stdGetWordRetWord0;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiWord *pG_NBIQ7_textwrit__TextWriter;
static FiClos *pG_EC2QI_textwrit;
static FiClos *pG_DEGQL_dfloat;
static FiClos *pG_I0RMM_complex;
extern FiWord formatSInt();



static void
CF0_mandel(FiEnv e1)
{
        FiWord T10;
        FiDFlo T7_double, T8_double, T9_double;
        PFmt14 T3, T4, T5, T6;
        FiClos T0, T1, T2;
        PFmt9 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt9 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCCall0(void, (*pG_XIPRL_runtime));
        G_TY19J_mandel = (FiClos) (*pG_NQYQM_noOperation);
        T0 = fiClosMake(e0, C5_dfloat_MINUS_init);
        T1 = fiClosMake(e0, C6_complex_MINUS_init);
        G_64T72_mandel__drawMand__6597 = fiClosMake(e0, C1_drawMand);
        T2 = fiClosMake(e0, C4_textwrit_MINUS_init);
        G_TAMI0_mandel__drawPoint__326 = fiClosMake(e0, C3_drawPoint);
        l0->X7 = 0L;
        l0->X8 = 0L;
        l0->X9 = 0L;
        l0->X0_DoubleFloat = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T0, 0L);
        T10 = fiCCall2(FiWord, (*pG_RSHLY_rtDelayedInit_BANG_), T1, 0L);
        l0->X1_Complex = fiCCall1(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T10);
        l0->X5_dom = fiCCall1(FiWord, l0->X1_Complex, l0->
        	X0_DoubleFloat);
        fiEnvEnsure(l0->X1_Complex->env);
        l0->X4_0 = fiCCall3(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X5_dom, 200089L, 312883127L);
        fiEnvEnsure(l0->X1_Complex->env);
        fiEnvEnsure(l0->X1_Complex->env);
        fiEnvEnsure(l0->X1_Complex->env);
        fiEnvEnsure(l0->X1_Complex->env);
        fiEnvEnsure(l0->X1_Complex->env);
        fiEnvEnsure(l0->X1_Complex->env);
        fiEnvEnsure(l0->X1_Complex->env);
        fiEnvEnsure(l0->X1_Complex->env);
        G_CEZY9_mandel__maxN__08372534 = (FiWord) 100L;
        G_EYTUA_mandel__maxX__08372534 = (FiWord) 25L;
        G_OSMNC_mandel__maxY__08372534 = (FiWord) 25L;
        l0->X2_TextWriter = fiCCall2(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T2, 0L);
        l0->X6_dom = l0->X2_TextWriter;
        l0->X3_print = fiCCall3(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X6_dom, 828947258L, 182752316L);
        T7_double = 1.0000000000000000;
        T3 = fi0RecNew(struct Fmt14 , CENSUS_Rec);
        T3->X0_double = -T7_double;
        T8_double = 2.0000000000000000;
        T4 = fi0RecNew(struct Fmt14 , CENSUS_Rec);
        T4->X0_double = -T8_double;
        T5 = fi0RecNew(struct Fmt14 , CENSUS_Rec);
        T5->X0_double = 0.50000000000000000;
        T9_double = 0.50000000000000000;
        T6 = fi0RecNew(struct Fmt14 , CENSUS_Rec);
        T6->X0_double = -T9_double;
        CF1_drawMand(e0, (FiWord) T4, (FiWord) T3, (FiWord) 25L, (FiWord) T6, (
        	FiWord) T5, (FiWord) 25L, (FiClos) 
        	G_TAMI0_mandel__drawPoint__326, (FiWord) 100L);
        return ;
}

static struct _FiProg  tmp0_mandel = {
        (FiFun) CF0_mandel,
        0L,
        0L,
        0L
};


static void
CF1_drawMand(FiEnv e1, FiWord P0_minR, FiWord P1_maxR, FiWord P2_numR, 
        	FiWord P3_minI, FiWord P4_maxI, FiWord P5_numI, FiClos 
        	P6_drawPt, FiWord P7_maxIters)
{
        FiDFlo T3, T4, T6, T7, T12_double, T13_double, T14_double, T15_double, T17_double, T18_double, T19_double, T20_double, T21_double, T22_double, T23_double, T24_double, T25_double, T26_double, T27_double, T28_double, T29_double, T31_double, T32_double, T33_double, T35, T36;
        FiSInt T0, T2, T5, T8_a, T11_a, T16_a, T30_a, T34_a;
        FiWord T1, T9_real, T10_imag;
        T31_double = ((PFmt14) P3_minI)->X0_double;
        T6 = ((PFmt14) P4_maxI)->X0_double - T31_double;
        T5 = (FiSInt) P5_numI - 1L;
        fiSINT_TO_DFLO(T7, FiDFlo, T5);
        T24_double = T6 / T7;
        T32_double = T31_double;
        T34_a = 1L;
        if (1L <= (FiSInt) P5_numI) goto L15;
L0:	return ;
L15:	T33_double = T31_double;
        T16_a = 1L;
L5:	if (T16_a <= (FiSInt) P5_numI) goto L6;
        goto L0;
L6:	T27_double = ((PFmt14) P0_minR)->X0_double;
        T3 = ((PFmt14) P1_maxR)->X0_double - T27_double;
        T2 = (FiSInt) P2_numR - 1L;
        fiSINT_TO_DFLO(T4, FiDFlo, T2);
        T22_double = T3 / T4;
        T28_double = T27_double;
        T30_a = 1L;
        if (1L <= (FiSInt) P2_numR) goto L11;
L9:	T23_double = T32_double + T24_double;
        T32_double = T23_double;
L8:	T34_a = T34_a + 1L;
        if (T34_a <= (FiSInt) P5_numI) goto L14;
        goto L0;
L14:	T33_double = T32_double;
        T16_a = T16_a + 1L;
        goto L5;
L11:	T29_double = T27_double;
        T8_a = 1L;
L4:	if (T8_a <= (FiSInt) P2_numR) goto L13;
        T23_double = T32_double + T24_double;
        T32_double = T23_double;
        goto L8;
L13:	T1 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), ((PFmt9) 
        	fiEnvLevel0(e1))->X4_0);
        T9_real = ((PFmt16) T1)->X0_real;
        T25_double = ((PFmt14) T9_real)->X0_double;
        T10_imag = ((PFmt16) T1)->X1_imag;
        T26_double = ((PFmt14) T10_imag)->X0_double;
        T0 = 0L;
        T35 = T25_double * T25_double;
        T36 = T26_double * T26_double;
        T13_double = T35 + T36;
        T12_double = 4.0000000000000000;
        if (T13_double < T12_double) goto L1;
L10:	fiCCall3(void, P6_drawPt, (FiWord) T8_a, (FiWord) T16_a, (FiWord) T0);
        T21_double = T28_double + T22_double;
        T28_double = T21_double;
L7:	T30_a = T30_a + 1L;
        if (T30_a <= (FiSInt) P2_numR) goto L12;
        goto L9;
L12:	T29_double = T28_double;
        T8_a = T8_a + 1L;
        goto L4;
L1:	T11_a = 1L;
L2:	if (T11_a <= (FiSInt) P7_maxIters) goto L16;
        fiCCall3(void, P6_drawPt, (FiWord) T8_a, (FiWord) T16_a, (FiWord) T0);
        T21_double = T28_double + T22_double;
        T28_double = T21_double;
        goto L7;
L16:	T0 = T11_a;
        T19_double = T35 - T36;
        T14_double = T25_double * T26_double;
        T15_double = T26_double * T25_double;
        T20_double = T14_double + T15_double;
        T17_double = T19_double + T29_double;
        T18_double = T20_double + T33_double;
        T25_double = T17_double;
        T26_double = T18_double;
        T35 = T17_double * T17_double;
        T36 = T18_double * T18_double;
        T13_double = T35 + T36;
        T12_double = 4.0000000000000000;
        if (T13_double < T12_double) goto L3;
        goto L10;
L3:	T11_a = T11_a + 1L;
        goto L2;
}

static struct _FiProg  tmp1_drawMand = {
        (FiFun) CF1_drawMand,
        0L,
        0L,
        0L
};


static FiWord
CF2_mandel(FiEnv e1, FiWord P0_c)
{
        FiDFlo T6_double, T7_double, T8_double, T9_double, T10_double, T11_double, T12_double, T13_double, T14_double, T15_double, T16, T17;
        FiSInt T0_n, T5_a;
        FiWord T1_z, T2, T3_real, T4_imag;
        PFmt7 l1;
        PFmt9 l2;
        FiEnv e2;
        l1 = (PFmt7) fiEnvLevel(e1);
        e2 = fiEnvNext(e1);
        l2 = (PFmt9) fiEnvLevel(e2);
        T1_z = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l2->X4_0);
        T3_real = ((PFmt16) T1_z)->X0_real;
        T14_double = ((PFmt14) T3_real)->X0_double;
        T4_imag = ((PFmt16) T1_z)->X1_imag;
        T15_double = ((PFmt14) T4_imag)->X0_double;
        T0_n = 0L;
        T2 = l1->X0_maxIters;
        T16 = T14_double * T14_double;
        T17 = T15_double * T15_double;
        T7_double = T16 + T17;
        T6_double = 4.0000000000000000;
        if (T7_double < T6_double) goto L1;
L0:	return (FiWord) T0_n;
L1:	T5_a = 1L;
L2:	if (T5_a <= (FiSInt) T2) goto L4;
        goto L0;
L4:	T0_n = T5_a;
        T12_double = T16 - T17;
        T8_double = T14_double * T15_double;
        T9_double = T15_double * T14_double;
        T13_double = T8_double + T9_double;
        T10_double = T12_double + ((PFmt14) ((PFmt16) P0_c)->
        	X0_real)->X0_double;
        T11_double = T13_double + ((PFmt14) ((PFmt16) P0_c)->
        	X1_imag)->X0_double;
        T14_double = T10_double;
        T15_double = T11_double;
        T16 = T10_double * T10_double;
        T17 = T11_double * T11_double;
        T7_double = T16 + T17;
        T6_double = 4.0000000000000000;
        if (T7_double < T6_double) goto L3;
        goto L0;
L3:	T5_a = T5_a + 1L;
        goto L2;
}

static struct _FiProg  tmp2_mandel = {
        (FiFun) CF2_mandel,
        0L,
        0L,
        0L
};


static void
CF3_drawPoint(FiEnv e1, FiWord P0_x, FiWord P1_y, FiWord P2_n)
{
        FiWord T0, T1, T5, T9, T13, T17, T21, T25;
        FiClos T2, T3, T4, T6, T7, T8, T10, T11, T12, T14, T15, T16, T18, T19, T20, T22, T23, T24;
        PFmt9 l1;
        l1 = (PFmt9) fiEnvLevel(e1);
        T1 = (FiWord) G_CEZY9_mandel__maxN__08372534;
        if ((FiSInt) P2_n == (FiSInt) T1) goto L0;
        if ((FiSInt) P2_n < 10L) goto L2;
        T13 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l1->X3_print);
        ((void(*)(FiEnv , FiClos* , FiClos* , FiClos* )) fiRawCProg((
        	FiClos) T13))(((FiClos) T13)->env, &T10, &T11, &T12);
        fiCCall3(FiWord, T11, (FiWord) " ", (FiWord) 1L, (FiWord) 0L);
        T25 = formatSInt((FiSInt) P2_n);
        ((void(*)(FiEnv , FiClos* , FiClos* , FiClos* )) fiRawCProg((
        	FiClos) T13))(((FiClos) T13)->env, &T22, &T23, &T24);
        fiCCall3(FiWord, T23, T25, (FiWord) 1L, (FiWord) 0L);
L1:	T0 = (FiWord) G_EYTUA_mandel__maxX__08372534;
        if ((FiSInt) P0_x == (FiSInt) T0) goto L3;
L4:	return ;
L3:	T5 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l1->X3_print);
        ((void(*)(FiEnv , FiClos* , FiClos* , FiClos* )) fiRawCProg((
        	FiClos) T5))(((FiClos) T5)->env, &T2, &T3, &T4);
        fiCCall1(void, T2, (FiWord) 10L);
        goto L4;
L2:	T17 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l1->X3_print);
        ((void(*)(FiEnv , FiClos* , FiClos* , FiClos* )) fiRawCProg((
        	FiClos) T17))(((FiClos) T17)->env, &T14, &T15, &T16);
        fiCCall3(FiWord, T15, (FiWord) "  ", (FiWord) 1L, (FiWord) 0L);
        T21 = formatSInt((FiSInt) P2_n);
        ((void(*)(FiEnv , FiClos* , FiClos* , FiClos* )) fiRawCProg((
        	FiClos) T17))(((FiClos) T17)->env, &T18, &T19, &T20);
        fiCCall3(FiWord, T19, T21, (FiWord) 1L, (FiWord) 0L);
        goto L1;
L0:	T9 = fiCCall1(FiWord, (*pG_R3D1K_lazyForceImport), l1->X3_print);
        ((void(*)(FiEnv , FiClos* , FiClos* , FiClos* )) fiRawCProg((
        	FiClos) T9))(((FiClos) T9)->env, &T6, &T7, &T8);
        fiCCall3(FiWord, T7, (FiWord) "   ", (FiWord) 1L, (FiWord) 0L);
        goto L1;
}

static struct _FiProg  tmp3_drawPoint = {
        (FiFun) CF3_drawPoint,
        0L,
        0L,
        0L
};


static FiWord
CF4_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt9 l1;
        l1 = (PFmt9) fiEnvLevel(e1);
        if (l1->X7) goto L0;
        l1->X7 = 1L;
        fiCCall0(void, (*pG_EC2QI_textwrit));
L0:	return (FiWord) (*pG_NBIQ7_textwrit__TextWriter);
}

static struct _FiProg  tmp4_textwrit_MINUS_init = {
        (FiFun) CF4_textwrit_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF5_dfloat_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt9 l1;
        l1 = (PFmt9) fiEnvLevel(e1);
        if (l1->X8) goto L0;
        l1->X8 = 1L;
        fiCCall0(void, (*pG_DEGQL_dfloat));
L0:	return (FiWord) (*pG_KJ3UJ_dfloat__DoubleFloat__);
}

static struct _FiProg  tmp5_dfloat_MINUS_init = {
        (FiFun) CF5_dfloat_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF6_complex_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt9 l1;
        l1 = (PFmt9) fiEnvLevel(e1);
        if (l1->X9) goto L0;
        l1->X9 = 1L;
        fiCCall0(void, (*pG_I0RMM_complex));
L0:	return (FiWord) (*pG_LM9I3_complex__Complex__500);
}

static struct _FiProg  tmp6_complex_MINUS_init = {
        (FiFun) CF6_complex_MINUS_init,
        0L,
        0L,
        0L
};

extern int
INIT__0_mandel(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_complex(void);
        extern int INIT__0_dfloat(void);
        extern int INIT__0_textwrit(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_drawMand = &tmp1_drawMand;
        C2_mandel = &tmp2_mandel;
        C3_drawPoint = &tmp3_drawPoint;
        C4_textwrit_MINUS_init = &tmp4_textwrit_MINUS_init;
        C5_dfloat_MINUS_init = &tmp5_dfloat_MINUS_init;
        C6_complex_MINUS_init = &tmp6_complex_MINUS_init;
        C0_mandel = &tmp0_mandel;
        fiExportGlobal("G_TY19J_mandel", G_TY19J_mandel);
        fiExportGlobal("G_TAMI0_mandel__drawPoint__326", 
        	G_TAMI0_mandel__drawPoint__326);
        fiExportGlobal("G_OSMNC_mandel__maxY__08372534", 
        	G_OSMNC_mandel__maxY__08372534);
        fiExportGlobal("G_EYTUA_mandel__maxX__08372534", 
        	G_EYTUA_mandel__maxX__08372534);
        fiExportGlobal("G_CEZY9_mandel__maxN__08372534", 
        	G_CEZY9_mandel__maxN__08372534);
        fiExportGlobal("G_64T72_mandel__drawMand__6597", 
        	G_64T72_mandel__drawMand__6597);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_KJ3UJ_dfloat__DoubleFloat__9", 
        	pG_KJ3UJ_dfloat__DoubleFloat__);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_LM9I3_complex__Complex__5006", 
        	pG_LM9I3_complex__Complex__500);
        fiImportGlobal("G_RSHLY_rtDelayedInit_BANG_", 
        	pG_RSHLY_rtDelayedInit_BANG_);
        fiImportGlobal("G_ZZZKG_stdGetWordRetWord0", 
        	pG_ZZZKG_stdGetWordRetWord0);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_NBIQ7_textwrit__TextWriter__", 
        	pG_NBIQ7_textwrit__TextWriter);
        fiImportGlobal("G_EC2QI_textwrit", pG_EC2QI_textwrit);
        fiImportGlobal("G_DEGQL_dfloat", pG_DEGQL_dfloat);
        fiImportGlobal("G_I0RMM_complex", pG_I0RMM_complex);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("complex");
                fiFileInitializer("dfloat");
                fiFileInitializer("textwrit");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_complex();
                INIT__0_dfloat();
                INIT__0_textwrit();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}

FiClos G_64T72_mandel__drawMand__6597;
FiWord G_CEZY9_mandel__maxN__08372534;
FiWord G_EYTUA_mandel__maxX__08372534;
FiWord G_OSMNC_mandel__maxY__08372534;
FiClos G_TAMI0_mandel__drawPoint__326;

static struct _FiClos  tmpClos0_mandel = {
        0L,
        (FiProg) &tmp0_mandel
};
FiClos G_TY19J_mandel = &tmpClos0_mandel;
