;;;
;;; Lisp code generated by Aldor from file "matops.as".
;;;

(in-package "FOAM-USER" :use '("FOAM" "LISP"))

(declare-prog (|C0-matops-matops|) ((|e1| |Env|)))

(declare-prog
  (|C1-matops-MatrixOpSym| |Word|)
  ((p0-r |Word|) (|e1| |Env|)))

(declare-prog
  (|C2-matops-addLevel0| |Clos|)
  ((|P0-domain| |Word|) (|e1| |Env|)))

(declare-prog
  (|C3-matops-addLevel1| |Word|)
  ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))

(declare-prog
  (|C4-matops-symmetricPart| |Word|)
  ((|P0-m| |Word|) (|e1| |Env|)))

(declare-prog
  (|C5-matops-axextend-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-type |G-matops| |Clos|)

(declare-type |G-matops_MatrixOpSym_856301676| |Clos|)

(defspecials |G-matops_MatrixOpSym_856301676|)

(|DDecl| |Struct-matops-5| (|size-0| |SInt|) (|values-1| |Arr|))

(|DDecl| |Struct-matops-6| (|found-0| |Word|) (|value-1| |Word|))

(|DDecl|
  |Struct-matops-7|
  (|size-0| |SInt|)
  (|nsize-1| |SInt|)
  (|values-2| |Word|))

(|DDecl|
  |Struct-matops-8|
  (|symmetricPart-0| |Clos|)
  (|transpose-1| |Clos|)
  (\+-2 |Clos|)
  (*-3 |Clos|)
  (\+-4 |Clos|)
  (\1-5 |Word|)
  (|inv-6| |Clos|)
  (|dom-7| |Word|)
  (|dom-8| |Word|))

(|DDecl| |Struct-matops-9| (r-0 |Word|))

(|DDecl|
  |Struct-matops-10|
  (|Matrix-0| |Clos|)
  (\-1 |Word|)
  (\-2 |Bool|))

(defprog
  ((|C0-matops-matops|) ((|e1| |Env|)))
  ((t0 |Clos|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (|l0| |Level|)
    (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-matops-10| |Struct-matops-10|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall| |G-runtime|)
  (setq |G-matops| |G-noOperation|)
  (setq t0 (|Clos| |e0| |C5-matops-axextend-init|))
  (|SetLex| |Struct-matops-10--1| 1 |l0| nil)
  (setq
    |G-matops_MatrixOpSym_856301676|
    (|Clos| |e0| |C1-matops-MatrixOpSym|))
  (|SetProgHashCode|
    (|ClosFun| |G-matops_MatrixOpSym_856301676|)
    (the |SInt| 812781808))
  (|SetLex| |Struct-matops-10--2| 2 |l0| (the |Bool| nil))
  (setq t1 (|ANew| |Word| (the |SInt| 1)))
  (setq t2 (|ANew| |Word| (the |SInt| 1)))
  (|SetAElt| t1 (the |SInt| 0) (the |SInt| 749874377))
  (|SetAElt| t2 (the |SInt| 0) (|MakeLit| "symmetricPart"))
  (setq t3 (|RNew| |Struct-matops-7|))
  (|SetRElt| |Struct-matops-7| |size| 0 t3 (the |SInt| 1))
  (|SetRElt| |Struct-matops-7| |nsize| 1 t3 (the |SInt| 1))
  (|SetRElt| |Struct-matops-7| |values| 2 t3 t1)
  (setq t4 (|RNew| |Struct-matops-7|))
  (|SetRElt| |Struct-matops-7| |size| 0 t4 (the |SInt| 1))
  (|SetRElt| |Struct-matops-7| |nsize| 1 t4 (the |SInt| 1))
  (|SetRElt| |Struct-matops-7| |values| 2 t4 t2)
  (|CCall| |G-rtAddStrings| t3 t4)
  (|SetLex|
    |Struct-matops-10-Matrix-0|
    0
    |l0|
    (|CCall|
      |G-stdGetWordRetWord0|
      (|CCall| |G-rtDelayedInit!| t0 (the |SInt| 0))))
  (block-return |C0-matops-matops| ()))

(defprog
  ((|C1-matops-MatrixOpSym| |Word|) ((p0-r |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Record|)
    (t2 |Word|)
    (t3 |Word|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-matops-9| |Struct-matops-9|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (|SetLex| |Struct-matops-9-R-0| 0 |l0| p0-r)
    (setq t0 (|ANew| |Word| (the |SInt| 1)))
    (setq t1 (|RNew| |Struct-matops-5|))
    (|SetRElt| |Struct-matops-5| |size| 0 t1 (the |SInt| 1))
    (|SetRElt| |Struct-matops-5| |values| 1 t1 t0)
    (when
      (|BoolNot| (|PtrIsNil| (|Lex| |Struct-matops-10--1| 1 |l1|)))
      (go |Lab1|))
    (|SetLex|
      |Struct-matops-10--1|
      1
      |l1|
      (|CCall| |G-rtCacheExplicitMake| (the |SInt| 15)))
    |Lab1|
    (|SetAElt| t0 (the |SInt| 0) (|Lex| |Struct-matops-9-R-0| 0 |l0|))
    (multiple-value-setq
      (t2 t3)
      (|CCall| |G-rtCacheCheck| (|Lex| |Struct-matops-10--1| 1 |l1|) t1))
    (when t3 (go |Lab0|))
    (setq t2 (|CCall| |G-domainMake| (|Clos| |e0| |C2-matops-addLevel0|)))
    (setq
      t2
      (|CCall| |G-rtCacheAdd| (|Lex| |Struct-matops-10--1| 1 |l1|) t1 t2))
    |Lab0|
    (block-return |C1-matops-MatrixOpSym| t2)))

(defprog
  ((|C2-matops-addLevel0| |Clos|) ((|P0-domain| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|) (|l1| |Level|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (|CCall|
    |G-domainAddNameFn!|
    |P0-domain|
    (|CCall|
      |G-rtSingleParamNameFn|
      (|MakeLit| "MatrixOpSym")
      (|Lex| |Struct-matops-9-R-0| 0 |l1|)))
  (|CCall|
    |G-domainAddHash!|
    |P0-domain|
    (|SIntPlusMod|
      (|CCall| |G-domainHash!| (|Lex| |Struct-matops-9-R-0| 0 |l1|))
      (the |SInt| 478428160)
      (the |SInt| 1073741789)))
  (block-return
    |C2-matops-addLevel0|
    (|Clos| |e0| |C3-matops-addLevel1|)))

(defprog
  ((|C3-matops-addLevel1| |Word|)
    ((|P0-domain| |Word|) (|P1-hashcode| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Arr|)
    (t2 |Arr|)
    (t3 |Record|)
    (t4 |Record|)
    (t5 |Record|)
    (t6 |SInt|)
    (t7 |SInt|)
    (t8 |SInt|)
    (t9 |SInt|)
    (t10 |SInt|)
    (t11 |SInt|)
    (t12 |SInt|)
    (t13 |SInt|)
    (t14 |SInt|)
    (t15 |SInt|)
    (t16 |SInt|)
    (t17 |SInt|)
    (t18 |SInt|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|e2| |Env|)
    (|l2| |Level|)
    (|e3| |Env|)
    (|l3| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-matops-8| |Struct-matops-8|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |e2| (|EnvNext| |e1|))
  (setq |l2| (|EnvLevel| |e2|))
  (setq |e3| (|EnvNext| |e2|))
  (setq |l3| (|EnvLevel| |e3|))
  (tagbody
    (setq t0 (|ANew| |SInt| (the |SInt| 1)))
    (setq t1 (|ANew| |SInt| (the |SInt| 1)))
    (setq t2 (|ANew| |Word| (the |SInt| 1)))
    (|SetLex|
      |Struct-matops-8-symmetricPart-0|
      0
      |l0|
      (|Clos| |e0| |C4-matops-symmetricPart|))
    (setq
      t12
      (|CCall| |G-domainHash!| (|Lex| |Struct-matops-9-R-0| 0 |l2|)))
    (|FoamEnvEnsure|
      (|ClosEnv| (|Lex| |Struct-matops-10-Matrix-0| 0 |l3|)))
    (setq
      t11
      (|SIntPlusMod| t12 (the |SInt| 768375488) (the |SInt| 1073741789)))
    |Lab1|
    (|FoamEnvEnsure|
      (|ClosEnv| (|Lex| |Struct-matops-10-Matrix-0| 0 |l3|)))
    (setq
      t13
      (|SIntPlusMod| t12 (the |SInt| 768375488) (the |SInt| 1073741789)))
    |Lab3|
    (setq
      t6
      (|SIntPlusMod|
        t13
        (|SIntShiftUp|
          (|SIntAnd|
            (|SIntPlusMod|
              (the |SInt| 32236)
              (|SIntShiftUp|
                (|SIntAnd|
                  (|SIntPlusMod| t11 (the |SInt| 74075968) (the |SInt| 1073741789))
                  (the |SInt| 16777215))
                (the |SInt| 6))
              (the |SInt| 1073741789))
            (the |SInt| 16777215))
          (the |SInt| 6))
        (the |SInt| 1073741789)))
    (setq
      t7
      (|SIntPlusMod|
        t12
        (|SIntShiftUp|
          (|SIntAnd|
            (|SIntPlusMod|
              (the |SInt| 32236)
              (|SIntShiftUp|
                (|SIntAnd|
                  (|SIntPlusMod|
                    t12
                    (|SIntShiftUp|
                      (|SIntAnd|
                        (|SIntPlusMod| t12 (the |SInt| 74075968) (the |SInt| 1073741789))
                        (the |SInt| 16777215))
                      (the |SInt| 6))
                    (the |SInt| 1073741789))
                  (the |SInt| 16777215))
                (the |SInt| 6))
              (the |SInt| 1073741789))
            (the |SInt| 16777215))
          (the |SInt| 6))
        (the |SInt| 1073741789)))
    (setq
      t8
      (|SIntPlusMod|
        t12
        (|SIntShiftUp|
          (|SIntAnd|
            (|SIntPlusMod|
              (the |SInt| 32236)
              (|SIntShiftUp|
                (|SIntAnd|
                  (|SIntPlusMod| t12 (the |SInt| 74075968) (the |SInt| 1073741789))
                  (the |SInt| 16777215))
                (the |SInt| 6))
              (the |SInt| 1073741789))
            (the |SInt| 16777215))
          (the |SInt| 6))
        (the |SInt| 1073741789)))
    (|FoamEnvEnsure|
      (|ClosEnv| (|Lex| |Struct-matops-10-Matrix-0| 0 |l3|)))
    (setq
      t14
      (|SIntPlusMod| t12 (the |SInt| 768375488) (the |SInt| 1073741789)))
    |Lab5|
    (|FoamEnvEnsure|
      (|ClosEnv| (|Lex| |Struct-matops-10-Matrix-0| 0 |l3|)))
    (setq
      t15
      (|SIntPlusMod| t12 (the |SInt| 768375488) (the |SInt| 1073741789)))
    |Lab7|
    (|FoamEnvEnsure|
      (|ClosEnv| (|Lex| |Struct-matops-10-Matrix-0| 0 |l3|)))
    (setq
      t16
      (|SIntPlusMod| t12 (the |SInt| 768375488) (the |SInt| 1073741789)))
    |Lab9|
    (setq
      t9
      (|SIntPlusMod|
        t16
        (|SIntShiftUp|
          (|SIntAnd|
            (|SIntPlusMod|
              (the |SInt| 32236)
              (|SIntShiftUp|
                (|SIntAnd|
                  (|SIntPlusMod|
                    t15
                    (|SIntShiftUp|
                      (|SIntAnd|
                        (|SIntPlusMod| t14 (the |SInt| 74075968) (the |SInt| 1073741789))
                        (the |SInt| 16777215))
                      (the |SInt| 6))
                    (the |SInt| 1073741789))
                  (the |SInt| 16777215))
                (the |SInt| 6))
              (the |SInt| 1073741789))
            (the |SInt| 16777215))
          (the |SInt| 6))
        (the |SInt| 1073741789)))
    (|FoamEnvEnsure|
      (|ClosEnv| (|Lex| |Struct-matops-10-Matrix-0| 0 |l3|)))
    (setq
      t17
      (|SIntPlusMod| t12 (the |SInt| 768375488) (the |SInt| 1073741789)))
    |Lab11|
    (|FoamEnvEnsure|
      (|ClosEnv| (|Lex| |Struct-matops-10-Matrix-0| 0 |l3|)))
    (setq
      t18
      (|SIntPlusMod| t12 (the |SInt| 768375488) (the |SInt| 1073741789)))
    |Lab13|
    (setq
      t10
      (|SIntPlusMod|
        t18
        (|SIntShiftUp|
          (|SIntAnd|
            (|SIntPlusMod|
              (the |SInt| 32236)
              (|SIntShiftUp|
                (|SIntAnd|
                  (|SIntPlusMod|
                    t17
                    (|SIntShiftUp|
                      (|SIntAnd|
                        (|SIntPlusMod| t12 (the |SInt| 74075968) (the |SInt| 1073741789))
                        (the |SInt| 16777215))
                      (the |SInt| 6))
                    (the |SInt| 1073741789))
                  (the |SInt| 16777215))
                (the |SInt| 6))
              (the |SInt| 1073741789))
            (the |SInt| 16777215))
          (the |SInt| 6))
        (the |SInt| 1073741789)))
    (setq t3 (|RNew| |Struct-matops-7|))
    (|SetRElt| |Struct-matops-7| |size| 0 t3 (the |SInt| 1))
    (|SetRElt| |Struct-matops-7| |nsize| 1 t3 (the |SInt| 1))
    (|SetRElt| |Struct-matops-7| |values| 2 t3 t0)
    (setq t4 (|RNew| |Struct-matops-7|))
    (|SetRElt| |Struct-matops-7| |size| 0 t4 (the |SInt| 1))
    (|SetRElt| |Struct-matops-7| |nsize| 1 t4 (the |SInt| 1))
    (|SetRElt| |Struct-matops-7| |values| 2 t4 t1)
    (setq t5 (|RNew| |Struct-matops-7|))
    (|SetRElt| |Struct-matops-7| |size| 0 t5 (the |SInt| 1))
    (|SetRElt| |Struct-matops-7| |nsize| 1 t5 (the |SInt| 1))
    (|SetRElt| |Struct-matops-7| |values| 2 t5 t2)
    (|CCall| |G-domainAddExports!| |P0-domain| t3 t4 t5)
    (|SetLex|
      |Struct-matops-8-dom-7|
      7
      |l0|
      (|CCall|
        (|Lex| |Struct-matops-10-Matrix-0| 0 |l3|)
        (|Lex| |Struct-matops-9-R-0| 0 |l2|)))
    (|SetLex|
      |Struct-matops-8-transpose-1|
      1
      |l0|
      (|CCall|
        |G-stdGetWordRetWord0|
        (|CCall|
          |G-rtDelayedGetExport!|
          (|Lex| |Struct-matops-8-dom-7| 7 |l0|)
          (the |SInt| 743203728)
          t6)))
    (|SetLex|
      |Struct-matops-8-dom-8|
      8
      |l0|
      (|Lex| |Struct-matops-9-R-0| 0 |l2|))
    (|SetLex|
      |Struct-matops-8-1-5|
      5
      |l0|
      (|CCall|
        |G-lazyGetExport!|
        (|Lex| |Struct-matops-8-dom-8| 8 |l0|)
        (the |SInt| 200090)
        t12))
    (|SetLex|
      |Struct-matops-8-+-4|
      4
      |l0|
      (|CCall|
        |G-stdGetWordWordRetWord0|
        (|CCall|
          |G-rtDelayedGetExport!|
          (|Lex| |Struct-matops-8-dom-8| 8 |l0|)
          (the |SInt| 200084)
          t7)))
    (|SetLex|
      |Struct-matops-8-inv-6|
      6
      |l0|
      (|CCall|
        |G-stdGetWordRetWord0|
        (|CCall|
          |G-rtDelayedGetExport!|
          (|Lex| |Struct-matops-8-dom-8| 8 |l0|)
          (the |SInt| 318722696)
          t8)))
    (|SetLex|
      |Struct-matops-8-+-2|
      2
      |l0|
      (|CCall|
        |G-stdGetWordWordRetWord0|
        (|CCall|
          |G-rtDelayedGetExport!|
          (|Lex| |Struct-matops-8-dom-7| 7 |l0|)
          (the |SInt| 200084)
          t9)))
    (|SetLex|
      |Struct-matops-8-*-3|
      3
      |l0|
      (|CCall|
        |G-stdGetWordWordRetWord0|
        (|CCall|
          |G-rtDelayedGetExport!|
          (|Lex| |Struct-matops-8-dom-7| 7 |l0|)
          (the |SInt| 200083)
          t10)))
    (|SetAElt| t0 (the |SInt| 0) (the |SInt| 749874377))
    (|SetAElt| t1 (the |SInt| 0) t6)
    (|SetAElt|
      t2
      (the |SInt| 0)
      (|Lex| |Struct-matops-8-symmetricPart-0| 0 |l0|))
    (block-return |C3-matops-addLevel1| |P0-domain|)
    |Lab12|
    (setq
      t18
      (|CCall|
        |G-domainHash!|
        (|CCall|
          (|Lex| |Struct-matops-10-Matrix-0| 0 |l3|)
          (|Lex| |Struct-matops-9-R-0| 0 |l2|))))
    (go |Lab13|)
    |Lab10|
    (setq
      t17
      (|CCall|
        |G-domainHash!|
        (|CCall|
          (|Lex| |Struct-matops-10-Matrix-0| 0 |l3|)
          (|Lex| |Struct-matops-9-R-0| 0 |l2|))))
    (go |Lab11|)
    |Lab8|
    (setq
      t16
      (|CCall|
        |G-domainHash!|
        (|CCall|
          (|Lex| |Struct-matops-10-Matrix-0| 0 |l3|)
          (|Lex| |Struct-matops-9-R-0| 0 |l2|))))
    (go |Lab9|)
    |Lab6|
    (setq
      t15
      (|CCall|
        |G-domainHash!|
        (|CCall|
          (|Lex| |Struct-matops-10-Matrix-0| 0 |l3|)
          (|Lex| |Struct-matops-9-R-0| 0 |l2|))))
    (go |Lab7|)
    |Lab4|
    (setq
      t14
      (|CCall|
        |G-domainHash!|
        (|CCall|
          (|Lex| |Struct-matops-10-Matrix-0| 0 |l3|)
          (|Lex| |Struct-matops-9-R-0| 0 |l2|))))
    (go |Lab5|)
    |Lab2|
    (setq
      t13
      (|CCall|
        |G-domainHash!|
        (|CCall|
          (|Lex| |Struct-matops-10-Matrix-0| 0 |l3|)
          (|Lex| |Struct-matops-9-R-0| 0 |l2|))))
    (go |Lab3|)
    |Lab0|
    (setq
      t11
      (|CCall|
        |G-domainHash!|
        (|CCall|
          (|Lex| |Struct-matops-10-Matrix-0| 0 |l3|)
          (|Lex| |Struct-matops-9-R-0| 0 |l2|))))
    (go |Lab1|)))

(defprog
  ((|C4-matops-symmetricPart| |Word|) ((|P0-m| |Word|) (|e1| |Env|)))
  ((|T0-m1| |Word|) (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (setq
    |T0-m1|
    (|CCall| (|Lex| |Struct-matops-8-transpose-1| 1 |l1|) |P0-m|))
  (block-return
    |C4-matops-symmetricPart|
    (|CCall|
      (|Lex| |Struct-matops-8-*-3| 3 |l1|)
      (|CCall|
        (|Lex| |Struct-matops-8-inv-6| 6 |l1|)
        (|CCall|
          (|Lex| |Struct-matops-8-+-4| 4 |l1|)
          (|CCall| |G-lazyForceImport| (|Lex| |Struct-matops-8-1-5| 5 |l1|))
          (|CCall| |G-lazyForceImport| (|Lex| |Struct-matops-8-1-5| 5 |l1|))))
      (|CCall| (|Lex| |Struct-matops-8-+-2| 2 |l1|) |P0-m| |T0-m1|))))

(defprog
  ((|C5-matops-axextend-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-matops-10--2| 2 |l1|) (go |Lab0|))
    (|SetLex| |Struct-matops-10--2| 2 |l1| (the |Bool| t))
    (|CCall| |G-axextend|)
    |Lab0|
    (block-return |C5-matops-axextend-init| |G-axextend_Matrix_677795208|)))

(setq |G-matops| (|Clos| nil |C0-matops-matops|))

(setq |G-matops_MatrixOpSym_856301676| nil)

(file-imports
  '((|G-axextend| "axextend" |initializer| "")
      (|G-rtAddStrings| "rtAddStrings" 0 "")
      (|G-rtCacheAdd| "rtCacheAdd" 0 "")
      (|G-domainMake| "domainMake" 0 "")
      (|G-stdGetWordWordRetWord0| "stdGetWordWordRetWord0" 0 "")
      (|G-lazyForceImport| "lazyForceImport" 0 "")
      (|G-lazyGetExport!| "lazyGetExport!" 0 "")
      (|G-rtDelayedGetExport!| "rtDelayedGetExport!" 0 "")
      (|G-stdGetWordRetWord0| "stdGetWordRetWord0" 0 "")
      (|G-rtDelayedInit!| "rtDelayedInit!" 0 "")
      (|G-axextend_Matrix_677795208| "Matrix" 677795208 "axextend")
      (|G-domainAddExports!| "domainAddExports!" 0 "")
      (|G-domainAddHash!| "domainAddHash!" 0 "")
      (|G-domainAddNameFn!| "domainAddNameFn!" 0 "")
      (|G-rtSingleParamNameFn| "rtSingleParamNameFn" 0 "")
      (|G-domainHash!| "domainHash!" 0 "")
      (|G-rtCacheCheck| "rtCacheCheck" 0 "")
      (|G-rtCacheExplicitMake| "rtCacheExplicitMake" 0 "")
      (|G-runtime| "runtime" |initializer| "")
      (|G-noOperation| "noOperation" 0 "")))

(file-exports
  '((|G-matops_MatrixOpSym_856301676| "MatrixOpSym" 856301676 "matops")
      (|G-matops| "matops" |initializer| "")))
