"none0.as", line 46: g1 () : Type == {
                     ................^
[L46 C17] #1 (Error) A value is needed but an empty sequence does not produce one.

"none0.as", line 50: g2 () : Type == {
                     ................^
[L50 C17] #2 (Error) A value is needed but `=>' does not produce one.

"none0.as", line 55: g3 () : Type == {
                     ................^
[L55 C17] #3 (Error) A value is needed but `if' expression has no `else'.
[L55 C17] #5 (Error) Have determined 0 possible types for the expression.
  Subexpression `1':
	Meaning 1: Type
  The context requires an expression of type Type.

"none0.as", line 61:         ()
                     ........^
[L61 C9] #6 (Error) Have determined 1 possible types for the expression.
	Meaning 1: (0 types)
  The context requires an expression of type Type.

