;;;
;;; Lisp code generated by Aldor from file "triv5.as".
;;;

(in-package "FOAM-USER" :use '("FOAM" "LISP"))

(declare-prog (|C0-triv5-triv5|) ((|e1| |Env|)))

(declare-prog
  (|C1-triv5-string-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C2-triv5-char-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C3-triv5-textwrit-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-type |G-triv5| |Clos|)

(|DDecl|
  |Struct-triv5-5|
  (|Character-0| |Word|)
  (|String-1| |Word|)
  (|TextWriter-2| |Word|)
  (|print-3| |Word|)
  (<<-4 |Clos|)
  (|newline-5| |Word|)
  (|string-6| |Clos|)
  (<<-7 |Clos|)
  (|dom-8| |Word|)
  (|dom-9| |Word|)
  (|dom-10| |Word|)
  (\-11 |Bool|)
  (\-12 |Bool|)
  (\-13 |Bool|))

(defprog
  ((|C0-triv5-triv5|) ((|e1| |Env|)))
  ((t0 |Clos|) (t1 |Clos|) (t2 |Clos|) (|l0| |Level|) (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-triv5-5| |Struct-triv5-5|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall| |G-runtime|)
  (setq |G-triv5| |G-noOperation|)
  (setq t0 (|Clos| |e0| |C3-triv5-textwrit-init|))
  (setq t1 (|Clos| |e0| |C1-triv5-string-init|))
  (setq t2 (|Clos| |e0| |C2-triv5-char-init|))
  (|SetLex| |Struct-triv5-5--11| 11 |l0| (the |Bool| nil))
  (|SetLex| |Struct-triv5-5--12| 12 |l0| (the |Bool| nil))
  (|SetLex| |Struct-triv5-5--13| 13 |l0| (the |Bool| nil))
  (|SetLex|
    |Struct-triv5-5-TextWriter-2|
    2
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t0 (the |SInt| 0)))
  (|SetLex|
    |Struct-triv5-5-dom-8|
    8
    |l0|
    (|Lex| |Struct-triv5-5-TextWriter-2| 2 |l0|))
  (|SetLex|
    |Struct-triv5-5-print-3|
    3
    |l0|
    (|CCall|
      |G-lazyGetExport!|
      (|Lex| |Struct-triv5-5-dom-8| 8 |l0|)
      (the |SInt| 828947258)
      (|CCall|
        |G-domainHash!|
        (|Lex| |Struct-triv5-5-TextWriter-2| 2 |l0|))))
  (|SetLex|
    |Struct-triv5-5-String-1|
    1
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t1 (the |SInt| 0)))
  (|SetLex|
    |Struct-triv5-5-dom-9|
    9
    |l0|
    (|Lex| |Struct-triv5-5-String-1| 1 |l0|))
  (|SetLex|
    |Struct-triv5-5-string-6|
    6
    |l0|
    (|CCall|
      |G-stdGetWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-triv5-5-dom-9| 9 |l0|)
        (the |SInt| 585283853)
        (|SIntPlusMod|
          (|CCall| |G-domainHash!| (|Lex| |Struct-triv5-5-String-1| 1 |l0|))
          (the |SInt| 895367936)
          (the |SInt| 1073741789)))))
  (|SetLex|
    |Struct-triv5-5-<<-7|
    7
    |l0|
    (|CCall|
      |G-stdGetWordWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-triv5-5-dom-9| 9 |l0|)
        (the |SInt| 51492426)
        (|SIntPlusMod|
          (|CCall|
            |G-domainHash!|
            (|Lex| |Struct-triv5-5-TextWriter-2| 2 |l0|))
          (|SIntShiftUp|
            (|SIntAnd|
              (|SIntPlusMod|
                (the |SInt| 32236)
                (|SIntShiftUp|
                  (|SIntAnd|
                    (|SIntPlusMod|
                      (|CCall| |G-domainHash!| (|Lex| |Struct-triv5-5-String-1| 1 |l0|))
                      (|SIntShiftUp|
                        (|SIntAnd|
                          (|SIntPlusMod|
                            (|CCall|
                              |G-domainHash!|
                              (|Lex| |Struct-triv5-5-TextWriter-2| 2 |l0|))
                            (the |SInt| 74075968)
                            (the |SInt| 1073741789))
                          (the |SInt| 16777215))
                        (the |SInt| 6))
                      (the |SInt| 1073741789))
                    (the |SInt| 16777215))
                  (the |SInt| 6))
                (the |SInt| 1073741789))
              (the |SInt| 16777215))
            (the |SInt| 6))
          (the |SInt| 1073741789)))))
  (|SetLex|
    |Struct-triv5-5-Character-0|
    0
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t2 (the |SInt| 0)))
  (|SetLex|
    |Struct-triv5-5-dom-10|
    10
    |l0|
    (|Lex| |Struct-triv5-5-Character-0| 0 |l0|))
  (|SetLex|
    |Struct-triv5-5-newline-5|
    5
    |l0|
    (|CCall|
      |G-lazyGetExport!|
      (|Lex| |Struct-triv5-5-dom-10| 10 |l0|)
      (the |SInt| 493486801)
      (|CCall|
        |G-domainHash!|
        (|Lex| |Struct-triv5-5-Character-0| 0 |l0|))))
  (|SetLex|
    |Struct-triv5-5-<<-4|
    4
    |l0|
    (|CCall|
      |G-stdGetWordWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-triv5-5-dom-10| 10 |l0|)
        (the |SInt| 51492426)
        (|SIntPlusMod|
          (|CCall|
            |G-domainHash!|
            (|Lex| |Struct-triv5-5-TextWriter-2| 2 |l0|))
          (|SIntShiftUp|
            (|SIntAnd|
              (|SIntPlusMod|
                (the |SInt| 32236)
                (|SIntShiftUp|
                  (|SIntAnd|
                    (|SIntPlusMod|
                      (|CCall|
                        |G-domainHash!|
                        (|Lex| |Struct-triv5-5-Character-0| 0 |l0|))
                      (|SIntShiftUp|
                        (|SIntAnd|
                          (|SIntPlusMod|
                            (|CCall|
                              |G-domainHash!|
                              (|Lex| |Struct-triv5-5-TextWriter-2| 2 |l0|))
                            (the |SInt| 74075968)
                            (the |SInt| 1073741789))
                          (the |SInt| 16777215))
                        (the |SInt| 6))
                      (the |SInt| 1073741789))
                    (the |SInt| 16777215))
                  (the |SInt| 6))
                (the |SInt| 1073741789))
              (the |SInt| 16777215))
            (the |SInt| 6))
          (the |SInt| 1073741789)))))
  (|CCall|
    (|Lex| |Struct-triv5-5-<<-4| 4 |l0|)
    (|CCall|
      (|Lex| |Struct-triv5-5-<<-7| 7 |l0|)
      (|CCall|
        |G-lazyForceImport|
        (|Lex| |Struct-triv5-5-print-3| 3 |l0|))
      (|CCall| (|Lex| |Struct-triv5-5-string-6| 6 |l0|) (|MakeLit| "!")))
    (|CCall|
      |G-lazyForceImport|
      (|Lex| |Struct-triv5-5-newline-5| 5 |l0|)))
  (block-return |C0-triv5-triv5| ()))

(defprog
  ((|C1-triv5-string-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-triv5-5--11| 11 |l1|) (go |Lab0|))
    (|SetLex| |Struct-triv5-5--11| 11 |l1| (the |Bool| t))
    (|CCall| |G-string|)
    |Lab0|
    (block-return |C1-triv5-string-init| |G-string_String_517719887|)))

(defprog
  ((|C2-triv5-char-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-triv5-5--12| 12 |l1|) (go |Lab0|))
    (|SetLex| |Struct-triv5-5--12| 12 |l1| (the |Bool| t))
    (|CCall| |G-char|)
    |Lab0|
    (block-return |C2-triv5-char-init| |G-char_Character_157812325|)))

(defprog
  ((|C3-triv5-textwrit-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-triv5-5--13| 13 |l1|) (go |Lab0|))
    (|SetLex| |Struct-triv5-5--13| 13 |l1| (the |Bool| t))
    (|CCall| |G-textwrit|)
    |Lab0|
    (block-return
      |C3-triv5-textwrit-init|
      |G-textwrit_TextWriter_981343789|)))

(setq |G-triv5| (|Clos| nil |C0-triv5-triv5|))

(file-imports
  '((|G-textwrit| "textwrit" |initializer| "")
      (|G-char| "char" |initializer| "")
      (|G-string| "string" |initializer| "")
      (|G-char_Character_157812325| "Character" 157812325 "char")
      (|G-stdGetWordWordRetWord0| "stdGetWordWordRetWord0" 0 "")
      (|G-stdGetWordRetWord0| "stdGetWordRetWord0" 0 "")
      (|G-rtDelayedGetExport!| "rtDelayedGetExport!" 0 "")
      (|G-string_String_517719887| "String" 517719887 "string")
      (|G-lazyForceImport| "lazyForceImport" 0 "")
      (|G-lazyGetExport!| "lazyGetExport!" 0 "")
      (|G-domainHash!| "domainHash!" 0 "")
      (|G-rtLazyDomFrInit| "rtLazyDomFrInit" 0 "")
      (|G-textwrit_TextWriter_981343789| "TextWriter" 981343789 "textwrit")
      (|G-runtime| "runtime" |initializer| "")
      (|G-noOperation| "noOperation" 0 "")))

(file-exports '((|G-triv5| "triv5" |initializer| "")))
