/*
 * C code generated by Aldor from file "triv1.as".
 */

#include "foam_c.h"

static FiProg C0_triv1;
static void CF0_triv1(FiEnv e1);
static FiProg C1_string;
static FiWord CF1_string(FiEnv e1, FiWord P0_s);
extern FiClos G_U4YTS_triv1;
static FiClos *pG_NQYQM_noOperation;
extern FiWord G_2GPDN_triv1__Type__547582661;
extern FiClos G_8AM3C_triv1__Tuple__96754565;
extern FiClos G_ZZK3U_triv1___MINUS__GT___73;
extern FiWord G_B5FWS_triv1__Literal__547582;
extern FiWord G_X5I5Z_triv1__String__5475826;
extern void puts();
extern FiClos G_WD5ZE_triv1__string__3056395;
static FiClos *pG_XIPRL_runtime;



static void
CF0_triv1(FiEnv e1)
{
        FiEnv e0;
        e0 = fiEnvPush(fiNil, e1);
        fiCCall0(void, (*pG_XIPRL_runtime));
        G_U4YTS_triv1 = (FiClos) (*pG_NQYQM_noOperation);
        G_WD5ZE_triv1__string__3056395 = fiClosMake(e0, C1_string);
        puts(CF1_string(e0, (FiWord) "42 Skidoo"));
        return ;
}

static struct _FiProg  tmp0_triv1 = {
        (FiFun) CF0_triv1,
        0L,
        0L,
        0L
};


static FiWord
CF1_string(FiEnv e1, FiWord P0_s)
{
        return P0_s;
}

static struct _FiProg  tmp1_string = {
        (FiFun) CF1_string,
        0L,
        0L,
        0L
};

extern int
INIT__0_triv1(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_string = &tmp1_string;
        C0_triv1 = &tmp0_triv1;
        fiExportGlobal("G_U4YTS_triv1", G_U4YTS_triv1);
        fiExportGlobal("G_2GPDN_triv1__Type__547582661", 
        	G_2GPDN_triv1__Type__547582661);
        fiExportGlobal("G_8AM3C_triv1__Tuple__96754565", 
        	G_8AM3C_triv1__Tuple__96754565);
        fiExportGlobal("G_ZZK3U_triv1___MINUS__GT___73", 
        	G_ZZK3U_triv1___MINUS__GT___73);
        fiExportGlobal("G_B5FWS_triv1__Literal__547582", 
        	G_B5FWS_triv1__Literal__547582);
        fiExportGlobal("G_X5I5Z_triv1__String__5475826", 
        	G_X5I5Z_triv1__String__5475826);
        fiExportGlobal("G_WD5ZE_triv1__string__3056395", 
        	G_WD5ZE_triv1__string__3056395);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}

FiClos G_WD5ZE_triv1__string__3056395;
FiWord G_X5I5Z_triv1__String__5475826;
FiWord G_B5FWS_triv1__Literal__547582;
FiClos G_ZZK3U_triv1___MINUS__GT___73;
FiClos G_8AM3C_triv1__Tuple__96754565;
FiWord G_2GPDN_triv1__Type__547582661;

static struct _FiClos  tmpClos0_triv1 = {
        0L,
        (FiProg) &tmp0_triv1
};
FiClos G_U4YTS_triv1 = &tmpClos0_triv1;
