# include "axlgen.h"
struct Buffer::Rep { Length pos; Length argc; UByte *argv; };
const Buffer Buffer::nil{nullptr};
Buffer Buffer::create(){static_assert(offsetof(Rep,pos)==0); static_assert(offsetof(Rep,argc)>=sizeof(Length)); static_assert(sizeof(Rep)>=offsetof(Rep,argv)+sizeof(UByte*)); Rep*b=(Rep*)stoAlloc(OB_Buffer,sizeof(*b));b->argv=(UByte*)stoAlloc(OB_Other,BUF_INIT_SIZE);b->argc=BUF_INIT_SIZE;b->pos=0;return Buffer(b);}
void Buffer::free(){stoFree((void *)rep_->argv);stoFree((void *)rep_);}
Buffer Buffer::capture(MutString s,Length l){Rep*b=(Rep*)stoAlloc(OB_Buffer,sizeof(*b));b->argv=(UByte*)s;b->argc=l;b->pos=0;return Buffer(b);}
MutString Buffer::liberate(){MutString s=(MutString)rep_->argv;if(rep_->pos==0&&rep_->argc)s[0]='\0';stoFree((void *)rep_);return s;}
MutString Buffer::chars()const noexcept{return(MutString)rep_->argv;} UByte *Buffer::bytes()const noexcept{return rep_->argv;} Length Buffer::size()const noexcept{return rep_->argc;} Length Buffer::position()const noexcept{return rep_->pos;}
void Buffer::setPosition(Length n)noexcept{rep_->pos=n;} void Buffer::start()noexcept{rep_->pos=0;} void Buffer::skip(Length n)noexcept{rep_->pos+=n;} void Buffer::back()noexcept{rep_->pos--;} UByte Buffer::next()const noexcept{return rep_->argv[rep_->pos];} UByte Buffer::get1()noexcept{return rep_->argv[rep_->pos++];}
Buffer Buffer::need(Length n){if(rep_->argc<n){rep_->argv=(UByte*)stoResize(rep_->argv,n);rep_->argc=n;}return*this;} Buffer Buffer::grow(Length inc){rep_->argv=(UByte*)stoResize(rep_->argv,rep_->argc+inc);rep_->argc+=inc;return*this;}
int Buffer::add1Char(int c){if(rep_->pos==rep_->argc)grow(rep_->argc/2);return rep_->argv[rep_->pos++]=c;} Buffer Buffer::add1(int c){add1Char(c);return*this;} Buffer Buffer::addn(const char*s,Length n){need(rep_->pos+n);memmove(rep_->argv+rep_->pos,s,n);skip(n);return*this;}
MutString Buffer::getn(Length n){UByte*s=rep_->argv+rep_->pos;skip(n);return(MutString)s;} MutString Buffer::gets(){UByte*s=rep_->argv+rep_->pos;int cc=strlen((MutString)s);skip(cc+1);return(MutString)s;}
int Buffer::puts(String s){int cc=strlen(s);addn(s,cc);add1Char(char0);back();return cc;} int Buffer::putc(int c){add1Char((char)c);add1Char(char0);back();return c;} int Buffer::putcTimes(int c,int times){for(int i=0;i<times;i++)putc(c);return c;}
int Buffer::puti(int i){Length pos0=position();int ndig,digits[4*bitsizeof(int)];if(i==0)add1Char('0');else{if(i<0){add1Char('-');i=-i;}for(ndig=0;i;i/=10,ndig++)digits[ndig]=i%10;while(ndig--)add1Char('0'+(char)digits[ndig]);}add1Char(char0);back();return position()-pos0;}
static Buffer pbuf; static int bufferXPut(const char*s,int n){if(n==-1)n=strlen(s);pbuf.addn(s,n);return n;} int Buffer::vprintf(const char*fmt,va_list argp){pbuf=*this;if(rep_->pos>0&&rep_->argv[rep_->pos-1]==0)back();int cc=vxprintf(bufferXPut,fmt,argp);add1Char(char0);back();return cc;} int Buffer::printf(const char*fmt,...){va_list ap;va_start(ap,fmt);int cc=vprintf(fmt,ap);va_end(ap);return cc;}
int Buffer::print(FILE*fout)const{int cc=fprintf(fout,"[%d/%d]",(int)rep_->pos,(int)rep_->argc);cc+=strPrint(fout,(MutString)rep_->argv,'"','"','\\',"\\%#x");return cc;}
UByte Buffer::readUByte(){UByte r;BUF_GET_BYTE(*this,r);return r;} UShort Buffer::readUShort(){UShort r;BUF_GET_HINT(*this,r);return r;} ULong Buffer::readULong(){ULong r;BUF_GET_SINT(*this,r);return r;} int Buffer::writeUByte(UByte b){BUF_PUT_BYTE(*this,b);return BYTE_BYTES;} int Buffer::writeUShort(UShort s){BUF_PUT_HINT(*this,s);return HINT_BYTES;} int Buffer::writeULong(ULong l){BUF_PUT_SINT(*this,l);return SINT_BYTES;}
SFloat Buffer::readSFloat(){XSFloat*p=(XSFloat*)getn(XSFLOAT_BYTES);SFloat s;xsfToNative(p,&s);return s;} DFloat Buffer::readDFloat(){XDFloat*p=(XDFloat*)getn(XDFLOAT_BYTES);DFloat d;xdfToNative(p,&d);return d;} int Buffer::writeSFloat(SFloat s){XSFloat x;SFloat bs=s;xsfFrNative(&x,&bs);addn((char*)&x,XSFLOAT_BYTES);return XSFLOAT_BYTES;} int Buffer::writeDFloat(DFloat d){XDFloat x;xdfFrNative(&x,&d);addn((char*)&x,XDFLOAT_BYTES);return XDFLOAT_BYTES;}
MutString Buffer::readChars(int cc){MutString s=strAlloc(cc);BUF_GET_CHARS(*this,s,cc);return strnFrAscii(s,cc);} int Buffer::writeChars(int cc,String s){BUF_PUT_CHARS(*this,strnToAsciiStatic(s,cc),cc);return cc;} MutString Buffer::readString(){int cc;BUF_GET_SINT(*this,cc);MutString s=strAlloc(cc);BUF_GET_CHARS(*this,s,cc);return strnFrAscii(s,cc);} int Buffer::writeString(String s){int cc=strLength(s)+1;BUF_PUT_SINT(*this,cc);BUF_PUT_CHARS(*this,strnToAsciiStatic(s,cc),cc);return SINT_BYTES+cc;} MutString Buffer::getString(){MutString s=strCopy(gets());return strnFrAscii(s,strLength(s)+1);} Buffer Buffer::readBuffer(){int cc;BUF_GET_SINT(*this,cc);MutString s=strAlloc(cc);BUF_GET_CHARS(*this,s,cc);return capture(s,cc);} int Buffer::writeBuffer(Buffer b){int cc=b.position();BUF_PUT_SINT(*this,cc);BUF_PUT_CHARS(*this,b.chars(),cc);return SINT_BYTES+cc;}
