#!/bin/bash

doBuild() {
	compileAldorIntoLib sal_data     "$@"
	compileAldorIntoLib sal_bdata    "$@"
	compileAldorIntoLib sal_ddata    "$@"
	compileAldorIntoLib sal_lstruc   "$@"
	compileAldorIntoLib sal_fstruc   "$@"
	compileAldorIntoLib sal_bstruc   "$@"
	compileAldorIntoLib sal_list     "$@"
	compileAldorIntoLib sal_cklist   "$@"
	compileAldorIntoLib sal_set      "$@"
	compileAldorIntoLib sal_sset     "$@"
	compileAldorIntoLib sal_slist    "$@"
	compileAldorIntoLib sal_parray   "$@"
	compileAldorIntoLib sal_pkarray  "$@"
	compileAldorIntoLib ald_queue    "$@"
	compileAldorIntoLib sal_barray   "$@"
	compileAldorIntoLib ald_flags    "$@"
	compileAldorIntoLib sal_array    "$@"
	compileAldorIntoLib sal_string   "$@"
	compileAldorIntoLib sal_ckarray  "$@"
	compileAldorIntoLib sal_memblk   "$@"
	compileAldorIntoLib sal_ckmembk  "$@"
	compileAldorIntoLib sal_stream   "$@"
	compileAldorIntoLib sal_table    "$@"
	compileAldorIntoLib sal_kntry    "$@"
	compileAldorIntoLib sal_hash     "$@"
	compileAldorIntoLib sal_sortas   "$@"
	compileAldorIntoLib ald_symbol   "$@"
	compileAldorIntoLib ald_symtab   "$@"
}

source "$ALDORROOT"/toolbin/build-fns.sh ; doMain "$@"
