"abcheck3.as", line 17: 2 := 3
                        ^
[L17 C1] #1 (Error) Incorrect left-hand side of an assignment.

"abcheck3.as", line 18: 2 == 3
                        ^
[L18 C1] #2 (Error) Incorrect left-hand side of a definition. Check indentation of succeeding definitions, if any.

"abcheck3.as", line 20: 2.4 := 6
                        ^
[L20 C1] #3 (Error) Incorrect left-hand side of an assignment.

"abcheck3.as", line 21: 2.4 == 6
                        ^
[L21 C1] #4 (Error) Incorrect left-hand side of a definition. Check indentation of succeeding definitions, if any.

"abcheck3.as", line 23: "abc" := "xyz"
                        ^
[L23 C1] #5 (Error) Incorrect left-hand side of an assignment.

"abcheck3.as", line 24: "abc" == "xyz"
                        ^
[L24 C1] #6 (Error) Incorrect left-hand side of a definition. Check indentation of succeeding definitions, if any.

