"abcheck0.as", line 25: makeRec: (a:I, b:I) :R == ratio(a,b) pretend R
                        ....................^
[L25 C21] #1 (Error) Syntax error.

"abcheck0.as", line 35:                 0 <= t and t < 1
                        ................^.^
[L35 C17] #2 (Warning) Suspicious juxtaposition.  Check for missing `;'.
Check indentation if you are using `#pile'.
[L35 C19] #3 (Error) Syntax error.

"abcheck0.as", line 84: from Builtin                    -- ok
                        ......................................^
[L84 C39] #4 (Error) Cannot recover from earlier syntax errors.

