"abcheck1.as", line 89:                  yield apply(v,i)
                        .......................^
[L89 C24] #2 (Error) Expecting a comma separated list of parameters.

"abcheck1.as", line 91:        (p: TextWriter) << (v: VI): TextWriter ==
                        .......^
[L91 C8] #1 (Warning) Suspicious juxtaposition.  Check for missing `;'.
Check indentation if you are using `#pile'.

