"assign2.as", line 28: u : (Integer,Integer) == (1,2)
                       ^
[L28 C1] #1 (Error) Improper form appearing within a declaration.

"assign2.as", line 32: local tascia: (Integer, Integer)
                       ......^
[L32 C7] #2 (Error) Improper form appearing within a declaration.

"assign2.as", line 36: x : (Integer, Integer) := (1,1)
                       ^
[L36 C1] #3 (Error) Improper form appearing within a declaration.

