/*
 * C code generated by Aldor from file "builtin1.as".
 */

#include "foam_c.h"

typedef struct Fmt5  *PFmt5;
typedef struct Fmt6  *PFmt6;
struct Fmt5 {
        FiClos X0_getter;
        FiBool X1_flag;
        FiClos X2_self;
};
struct Fmt6 {
        FiWord X0_Machine;
        FiWord X1_SingleInteger;
        FiWord X2_Character;
        FiWord X3_DoubleFloat;
        FiWord X4_TextWriter;
        FiClos X5__LT__LT_;
        FiWord X6_newline;
        FiWord X7_print;
        FiClos X8__PLUS_;
        FiClos X9_integer;
        FiClos X10__LT__LT_;
        FiClos X11_coerce;
        FiClos X12_coerce;
        FiClos X13_float;
        FiWord X14_dom;
        FiWord X15_dom;
        FiWord X16_dom;
        FiWord X17_dom;
        FiWord X18_dom;
        FiBool X19;
        FiBool X20;
        FiBool X21;
        FiBool X22;
        FiBool X23;
};
static FiProg C0_builtin1;
static void CF0_builtin1(FiEnv e1);
static FiProg C1_f;
static FiDFlo CF1_f(FiEnv e1, FiDFlo P0_x);
static FiProg C2_lazyFnGetter;
static FiClos CF2_lazyFnGetter(FiEnv e1, FiWord P0_init);
static FiProg C3_lazyGetter;
static FiWord CF3_lazyGetter(FiEnv e1, FiDFlo P0_a);
static FiProg C4_lazyGetter2;
static void CF4_lazyGetter2(FiEnv e1);
static FiProg C5_lazyFnGetter;
static FiClos CF5_lazyFnGetter(FiEnv e1, FiWord P0_init);
static FiProg C6_lazyGetter;
static FiDFlo CF6_lazyGetter(FiEnv e1, FiDFlo P0_a, FiDFlo P1_b);
static FiProg C7_lazyFnGetter;
static FiClos CF7_lazyFnGetter(FiEnv e1, FiWord P0_init);
static FiProg C8_lazyGetter;
static FiDFlo CF8_lazyGetter(FiEnv e1, FiWord P0_a);
static FiProg C9_machine_MINUS_init;
static FiWord CF9_machine_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C10_char_MINUS_init;
static FiWord CF10_char_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C11_textwrit_MINUS_init;
static FiWord CF11_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C12_dfloat_MINUS_init;
static FiWord CF12_dfloat_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C13_sinteger_MINUS_init;
static FiWord CF13_sinteger_MINUS_init(FiEnv e1, FiSInt P0_idx);
#define fiCallSpecial0(fn,a1) (fiProtoCFun(FiDFlo,(FiEnv,FiWord),fn)((fn)->env,a1))

#define fiCallSpecial1(fn,a1,a2) (fiProtoCFun(FiDFlo,(FiEnv,FiDFlo,FiDFlo),fn)((fn)->env,a1,a2))

#define fiCallSpecial2(fn,a1) (fiProtoCFun(FiWord,(FiEnv,FiDFlo),fn)((fn)->env,a1))

#define fiCallSpecial3(fn,a1,a2) (fiProtoCFun(FiDFlo,(FiEnv,FiDFlo,FiDFlo),fn)((fn)->env,a1,a2))

#define fiCallSpecial4(fn,a1) (fiProtoCFun(FiDFlo,(FiEnv,FiWord),fn)((fn)->env,a1))

#define fiCallSpecial5(fn,a1) (fiProtoCFun(FiDFlo,(FiEnv,FiWord),fn)((fn)->env,a1))

#define fiCallSpecial6(fn,a1) (fiProtoCFun(FiWord,(FiEnv,FiDFlo),fn)((fn)->env,a1))

extern FiClos G_D6480_builtin1;
static FiClos *pG_NQYQM_noOperation;
extern FiClos G_YKL9H_builtin1__Vector__9675;
extern FiClos G_LAY7B_builtin1__f__668349938;
static FiClos *pG_XIPRL_runtime;
static FiWord *pG_D0MRQ_sinteger__SingleInteg;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_QRAZA_rtDelayedGetExport;
static FiClos *pG_ZZZKG_stdGetWordRetWord0;
static FiWord *pG_STDSR_dfloat__DoubleFloat__;
static FiWord *pG_1B0E6_machine__Machine__915;
static FiWord *pG_Z4122_textwrit__TextWriter;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiClos *pG_DLXW8_stdGetWordWordRetWord;
static FiWord *pG_PRTGD_char__Character__7004;
static FiClos *pG_JNB1W_machine;
static FiClos *pG_AKTR8_char;
static FiClos *pG_EC2QI_textwrit;
static FiClos *pG_DEGQL_dfloat;
static FiClos *pG_HAQ5R_sinteger;



static void
CF0_builtin1(FiEnv e1)
{
        FiDFlo T7;
        FiWord T5, T6;
        FiClos T0, T1, T2, T3, T4;
        PFmt6 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt6 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCall0(void, (*pG_XIPRL_runtime));
        G_D6480_builtin1 = (FiClos) (*pG_NQYQM_noOperation);
        T0 = fiClosMake(e0, C13_sinteger_MINUS_init);
        T1 = fiClosMake(e0, C12_dfloat_MINUS_init);
        T2 = fiClosMake(e0, C9_machine_MINUS_init);
        G_LAY7B_builtin1__f__668349938 = fiClosMake(e0, C1_f);
        T3 = fiClosMake(e0, C11_textwrit_MINUS_init);
        T4 = fiClosMake(e0, C10_char_MINUS_init);
        l0->X19 = 0L;
        l0->X20 = 0L;
        l0->X21 = 0L;
        l0->X22 = 0L;
        l0->X23 = 0L;
        l0->X1_SingleInteger = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T0, 0L);
        l0->X14_dom = l0->X1_SingleInteger;
        T5 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X14_dom, 
        	477900237L, 2130877288L);
        l0->X9_integer = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T5);
        l0->X3_DoubleFloat = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T1, 0L);
        l0->X15_dom = l0->X3_DoubleFloat;
        l0->X0_Machine = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), T2, 
        	0L);
        l0->X16_dom = l0->X0_Machine;
        l0->X11_coerce = CF7_lazyFnGetter(e0, (FiWord) fiCall(FiWord, (*
        	pG_QRAZA_rtDelayedGetExport), l0->X15_dom, 770345191L, 
        	-1653824252L));
        T5 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X15_dom, 
        	474568739L, -349802997L);
        l0->X13_float = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T5);
        l0->X8__PLUS_ = CF5_lazyFnGetter(e0, (FiWord) fiCall(FiWord, (*
        	pG_QRAZA_rtDelayedGetExport), l0->X16_dom, 200084L, 
        	-1053765200L));
        l0->X4_TextWriter = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T3, 0L);
        l0->X17_dom = l0->X4_TextWriter;
        l0->X7_print = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X17_dom, 828947258L, 182752316L);
        l0->X12_coerce = CF2_lazyFnGetter(e0, (FiWord) fiCall(FiWord, (*
        	pG_QRAZA_rtDelayedGetExport), l0->X15_dom, 770345191L, 
        	-1175847156L));
        T5 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X15_dom, 
        	51492426L, 1843665685L);
        l0->X10__LT__LT_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T5);
        l0->X2_Character = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T4, 0L);
        l0->X18_dom = l0->X2_Character;
        l0->X6_newline = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X18_dom, 493486801L, 803414590L);
        T5 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X18_dom, 
        	51492426L, 936629095L);
        l0->X5__LT__LT_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T5);
        T5 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X7_print);
        T6 = fiCall(FiWord, l0->X13_float, (FiWord) "3.0");
        T7 = fiCallSpecial5(l0->X11_coerce, (FiWord) T6);
        T7 = CF1_f(e0, (FiDFlo) T7);
        T6 = fiCallSpecial6(l0->X12_coerce, T7);
        T5 = fiCall(FiWord, l0->X10__LT__LT_, T5, T6);
        T6 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X6_newline);
        fiCall(FiWord, l0->X5__LT__LT_, T5, T6);
        return ;
}

static struct _FiProg  tmp0_builtin1 = {
        (FiFun) CF0_builtin1,
        0L,
        0L,
        0L
};


static FiDFlo
CF1_f(FiEnv e1, FiDFlo P0_x)
{
        FiWord T0_vd, T1;
        PFmt6 l1;
        l1 = (PFmt6) fiEnvLevel(e1);
        fiARRNEW_DFlo(T0_vd, FiWord, fiCall(FiWord, l1->X9_integer, (FiWord) "3"));
        T1 = fiCall(FiWord, l1->X13_float, (FiWord) "2.0");
        ((FiDFlo*) T0_vd)[fiCall(FiWord, l1->X9_integer, (FiWord) "2")] = 
        	fiCallSpecial0(l1->X11_coerce, (FiWord) T1);
        T1 = fiCall(FiWord, l1->X9_integer, (FiWord) "2");
        return fiCallSpecial1(l1->X8__PLUS_, P0_x, ((FiDFlo*) T0_vd)[T1]);
}

static struct _FiProg  tmp1_f = {
        (FiFun) CF1_f,
        0L,
        0L,
        0L
};


static FiClos
CF2_lazyFnGetter(FiEnv e1, FiWord P0_init)
{
        PFmt5 l0;
        FiEnv e0;
        PFmt6 l1;
        l0 = fi0New(struct Fmt5 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        l1 = (PFmt6) fiEnvLevel(e1);
        l0->X0_getter = (FiClos) P0_init;
        l0->X1_flag = 0L;
        l0->X2_self = fiClosMake(e0, C3_lazyGetter);
        fiEnvInfo(e0) = (FiWord) fiClosMake(e0, C4_lazyGetter2);
        return l0->X2_self;
}

static struct _FiProg  tmp2_lazyFnGetter = {
        (FiFun) CF2_lazyFnGetter,
        0L,
        0L,
        0L
};


static FiWord
CF3_lazyGetter(FiEnv e1, FiDFlo P0_a)
{
        FiClos T0;
        PFmt5 l1;
        PFmt6 l2;
        FiEnv e2;
        l1 = (PFmt5) fiEnvLevel(e1);
        e2 = fiEnvNext(e1);
        l2 = (PFmt6) fiEnvLevel(e2);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCall0(FiWord, l1->X0_getter);
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        l1->X1_flag = 1L;
L0:	return fiCallSpecial2(l1->X2_self, P0_a);
}

static struct _FiProg  tmp3_lazyGetter = {
        (FiFun) CF3_lazyGetter,
        0L,
        0L,
        0L
};


static void
CF4_lazyGetter2(FiEnv e1)
{
        FiClos T0;
        PFmt5 l1;
        PFmt6 l2;
        FiEnv e2;
        l1 = (PFmt5) fiEnvLevel(e1);
        e2 = fiEnvNext(e1);
        l2 = (PFmt6) fiEnvLevel(e2);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCall0(FiWord, l1->X0_getter);
        l1->X1_flag = 1L;
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        fiEnvInfo(e1) = (FiWord) fiNil;
L0:	return ;
}

static struct _FiProg  tmp4_lazyGetter2 = {
        (FiFun) CF4_lazyGetter2,
        0L,
        0L,
        0L
};


static FiClos
CF5_lazyFnGetter(FiEnv e1, FiWord P0_init)
{
        PFmt5 l0;
        FiEnv e0;
        PFmt6 l1;
        l0 = fi0New(struct Fmt5 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        l1 = (PFmt6) fiEnvLevel(e1);
        l0->X0_getter = (FiClos) P0_init;
        l0->X1_flag = 0L;
        l0->X2_self = fiClosMake(e0, C6_lazyGetter);
        fiEnvInfo(e0) = (FiWord) fiClosMake(e0, C4_lazyGetter2);
        return l0->X2_self;
}

static struct _FiProg  tmp5_lazyFnGetter = {
        (FiFun) CF5_lazyFnGetter,
        0L,
        0L,
        0L
};


static FiDFlo
CF6_lazyGetter(FiEnv e1, FiDFlo P0_a, FiDFlo P1_b)
{
        FiClos T0;
        PFmt5 l1;
        PFmt6 l2;
        FiEnv e2;
        l1 = (PFmt5) fiEnvLevel(e1);
        e2 = fiEnvNext(e1);
        l2 = (PFmt6) fiEnvLevel(e2);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCall0(FiWord, l1->X0_getter);
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        l1->X1_flag = 1L;
L0:	return fiCallSpecial3(l1->X2_self, P0_a, P1_b);
}

static struct _FiProg  tmp6_lazyGetter = {
        (FiFun) CF6_lazyGetter,
        0L,
        0L,
        0L
};


static FiClos
CF7_lazyFnGetter(FiEnv e1, FiWord P0_init)
{
        PFmt5 l0;
        FiEnv e0;
        PFmt6 l1;
        l0 = fi0New(struct Fmt5 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        l1 = (PFmt6) fiEnvLevel(e1);
        l0->X0_getter = (FiClos) P0_init;
        l0->X1_flag = 0L;
        l0->X2_self = fiClosMake(e0, C8_lazyGetter);
        fiEnvInfo(e0) = (FiWord) fiClosMake(e0, C4_lazyGetter2);
        return l0->X2_self;
}

static struct _FiProg  tmp7_lazyFnGetter = {
        (FiFun) CF7_lazyFnGetter,
        0L,
        0L,
        0L
};


static FiDFlo
CF8_lazyGetter(FiEnv e1, FiWord P0_a)
{
        FiClos T0;
        PFmt5 l1;
        PFmt6 l2;
        FiEnv e2;
        l1 = (PFmt5) fiEnvLevel(e1);
        e2 = fiEnvNext(e1);
        l2 = (PFmt6) fiEnvLevel(e2);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCall0(FiWord, l1->X0_getter);
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        l1->X1_flag = 1L;
L0:	return fiCallSpecial4(l1->X2_self, (FiWord) P0_a);
}

static struct _FiProg  tmp8_lazyGetter = {
        (FiFun) CF8_lazyGetter,
        0L,
        0L,
        0L
};


static FiWord
CF9_machine_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt6 l1;
        l1 = (PFmt6) fiEnvLevel(e1);
        if (l1->X19) goto L0;
        l1->X19 = 1L;
        fiCall0(void, (*pG_JNB1W_machine));
L0:	return (FiWord) (*pG_1B0E6_machine__Machine__915);
}

static struct _FiProg  tmp9_machine_MINUS_init = {
        (FiFun) CF9_machine_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF10_char_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt6 l1;
        l1 = (PFmt6) fiEnvLevel(e1);
        if (l1->X20) goto L0;
        l1->X20 = 1L;
        fiCall0(void, (*pG_AKTR8_char));
L0:	return (FiWord) (*pG_PRTGD_char__Character__7004);
}

static struct _FiProg  tmp10_char_MINUS_init = {
        (FiFun) CF10_char_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF11_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt6 l1;
        l1 = (PFmt6) fiEnvLevel(e1);
        if (l1->X21) goto L0;
        l1->X21 = 1L;
        fiCall0(void, (*pG_EC2QI_textwrit));
L0:	return (FiWord) (*pG_Z4122_textwrit__TextWriter);
}

static struct _FiProg  tmp11_textwrit_MINUS_init = {
        (FiFun) CF11_textwrit_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF12_dfloat_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt6 l1;
        l1 = (PFmt6) fiEnvLevel(e1);
        if (l1->X22) goto L0;
        l1->X22 = 1L;
        fiCall0(void, (*pG_DEGQL_dfloat));
L0:	return (FiWord) (*pG_STDSR_dfloat__DoubleFloat__);
}

static struct _FiProg  tmp12_dfloat_MINUS_init = {
        (FiFun) CF12_dfloat_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF13_sinteger_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt6 l1;
        l1 = (PFmt6) fiEnvLevel(e1);
        if (l1->X23) goto L0;
        l1->X23 = 1L;
        fiCall0(void, (*pG_HAQ5R_sinteger));
L0:	return (FiWord) (*pG_D0MRQ_sinteger__SingleInteg);
}

static struct _FiProg  tmp13_sinteger_MINUS_init = {
        (FiFun) CF13_sinteger_MINUS_init,
        0L,
        0L,
        0L
};

extern int
INIT__0_builtin1(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_sinteger(void);
        extern int INIT__0_dfloat(void);
        extern int INIT__0_textwrit(void);
        extern int INIT__0_char(void);
        extern int INIT__0_machine(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_f = &tmp1_f;
        C2_lazyFnGetter = &tmp2_lazyFnGetter;
        C3_lazyGetter = &tmp3_lazyGetter;
        C4_lazyGetter2 = &tmp4_lazyGetter2;
        C5_lazyFnGetter = &tmp5_lazyFnGetter;
        C6_lazyGetter = &tmp6_lazyGetter;
        C7_lazyFnGetter = &tmp7_lazyFnGetter;
        C8_lazyGetter = &tmp8_lazyGetter;
        C9_machine_MINUS_init = &tmp9_machine_MINUS_init;
        C10_char_MINUS_init = &tmp10_char_MINUS_init;
        C11_textwrit_MINUS_init = &tmp11_textwrit_MINUS_init;
        C12_dfloat_MINUS_init = &tmp12_dfloat_MINUS_init;
        C13_sinteger_MINUS_init = &tmp13_sinteger_MINUS_init;
        C0_builtin1 = &tmp0_builtin1;
        fiExportGlobal("G_D6480_builtin1", G_D6480_builtin1);
        fiExportGlobal("G_YKL9H_builtin1__Vector__9675", 
        	G_YKL9H_builtin1__Vector__9675);
        fiExportGlobal("G_LAY7B_builtin1__f__668349938", 
        	G_LAY7B_builtin1__f__668349938);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_D0MRQ_sinteger__SingleIntege", 
        	pG_D0MRQ_sinteger__SingleInteg);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_QRAZA_rtDelayedGetExport", 
        	pG_QRAZA_rtDelayedGetExport);
        fiImportGlobal("G_ZZZKG_stdGetWordRetWord0", 
        	pG_ZZZKG_stdGetWordRetWord0);
        fiImportGlobal("G_STDSR_dfloat__DoubleFloat__7", 
        	pG_STDSR_dfloat__DoubleFloat__);
        fiImportGlobal("G_1B0E6_machine__Machine__9157", 
        	pG_1B0E6_machine__Machine__915);
        fiImportGlobal("G_Z4122_textwrit__TextWriter__", 
        	pG_Z4122_textwrit__TextWriter);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_DLXW8_stdGetWordWordRetWord0", 
        	pG_DLXW8_stdGetWordWordRetWord);
        fiImportGlobal("G_PRTGD_char__Character__70042", 
        	pG_PRTGD_char__Character__7004);
        fiImportGlobal("G_JNB1W_machine", pG_JNB1W_machine);
        fiImportGlobal("G_AKTR8_char", pG_AKTR8_char);
        fiImportGlobal("G_EC2QI_textwrit", pG_EC2QI_textwrit);
        fiImportGlobal("G_DEGQL_dfloat", pG_DEGQL_dfloat);
        fiImportGlobal("G_HAQ5R_sinteger", pG_HAQ5R_sinteger);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("sinteger");
                fiFileInitializer("dfloat");
                fiFileInitializer("textwrit");
                fiFileInitializer("char");
                fiFileInitializer("machine");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_sinteger();
                INIT__0_dfloat();
                INIT__0_textwrit();
                INIT__0_char();
                INIT__0_machine();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}

FiClos G_LAY7B_builtin1__f__668349938;
FiClos G_YKL9H_builtin1__Vector__9675;

static struct _FiClos  tmpClos0_builtin1 = {
        0L,
        (FiProg) &tmp0_builtin1
};
FiClos G_D6480_builtin1 = &tmpClos0_builtin1;
