"coerce.as", line 14: j0: Byte == b():: Integer
                      ..................^
[L14 C19] #1 (Error) There are no suitable meanings for the operator `coerce'.
   The possible types of the left hand side are:
          -- Boolean
          -- Byte

"coerce.as", line 15: j1: Byte == false:: Integer
                      ....................^
[L15 C21] #2 (Error) There are no suitable meanings for the operator `coerce'.
   The possible types of the left hand side are:
          -- Boolean

"coerce.as", line 17: j3:Integer == 0 ::DoubleFloat
                      ..................^
[L17 C19] #3 (Error) There are no suitable meanings for the operator `coerce'.
   The possible types of the left hand side are:
          -- Integer
          -- Byte

"coerce.as", line 18: j4:Integer == false ::Integer
                      ......................^
[L18 C23] #4 (Error) There are no suitable meanings for the operator `coerce'.
   The possible types of the left hand side are:
          -- Boolean

"coerce.as", line 19: j5:Integer == false ::SingleFloat
                      ......................^
[L19 C23] #5 (Error) There are no suitable meanings for the operator `coerce'.
   The possible types of the left hand side are:
          -- Boolean

"coerce.as", line 20: j6:Integer == left( 1,false)::Boolean
                      ..............................^
[L20 C31] #6 (Error) There are no suitable meanings for the operator `coerce'.
   The possible types of the left hand side are:
          -- Byte

"coerce.as", line 24: :: Integer
                      ...^
[L24 C4] #7 (Error) There are no suitable meanings for the operator `coerce'.
   The possible types of the left hand side are:
          -- Boolean

"coerce.as", line 26:    Integer
                      ...^
[L26 C4] #8 (Error) There are no suitable meanings for the operator `coerce'.
   The possible types of the left hand side are:
          -- Boolean

