"const8.as", line 22:       p : Float == f(pi);
                      .....................^
[L22 C22] #1 (Error) Implementation restriction: you cannot use a non-lazy constant outside an `add' before it has been defined. Perhaps you ought to define `pi' sooner.
(see Note 1)

"const8.as", line 24:       pi: Float == 3.14159;
                      ......^
[L24 C7] #2 (Note 1)  (cf. L22 C22)

