/*
 * C code generated by Aldor from file "exptoc2.as".
 */

#include "foam_c.h"

typedef struct Fmt6  *PFmt6;
typedef struct Fmt7  *PFmt7;
typedef struct Fmt8  *PFmt8;
struct Fmt6 {
        FiWord X0;
        FiWord X1;
};
struct Fmt7 {
        FiPtr X0_empty;
};
struct Fmt8 {
        FiClos X0_print;
        FiClos X1_quotient;
        FiWord X2_SingleInteger;
        FiWord X3_Character;
        FiWord X4_TextWriter;
        FiClos X5__LT__LT_;
        FiWord X6_newline;
        FiWord X7_print;
        FiClos X8__LT__LT_;
        FiClos X9_divide;
        FiWord X10_dom;
        FiWord X11_dom;
        FiWord X12_dom;
        FiBool X13;
        FiBool X14;
        FiBool X15;
};
static FiProg C0_exptoc2;
static void CF0_exptoc2(FiEnv e1);
static FiProg C1_quotient;
static void CF1_quotient(FiEnv e1, FiWord P0_x, FiWord P1_y, FiWord* R0, FiWord* R1);
static FiProg C2_print;
static void CF2_print(FiEnv e1, FiWord P0_x);
static FiProg C3_char_MINUS_init;
static FiWord CF3_char_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C4_textwrit_MINUS_init;
static FiWord CF4_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C5_sinteger_MINUS_init;
static FiWord CF5_sinteger_MINUS_init(FiEnv e1, FiSInt P0_idx);
#define fiCallSpecial0(fn,a1,a2,a3,a4) (fiProtoCFun(void,(FiEnv,FiWord,FiWord,FiWord *,FiWord *),fn)((fn)->env,a1,a2,a3,a4))

#define fiCallSpecial1(fn,a1) (fiProtoCFun(void,(FiEnv,FiWord),fn)((fn)->env,a1))

#define fiCallSpecial2(fn,a1,a2,a3,a4) (fiProtoCFun(void,(FiEnv,FiWord,FiWord,FiWord *,FiWord *),fn)((fn)->env,a1,a2,a3,a4))

extern int INIT__0_exptoc2(void);
extern FiClos G_IMU9E_exptoc2;
static FiClos *pG_NQYQM_noOperation;
extern void bar(void);
static FiClos *pG_XIPRL_runtime;
extern FiClos G_Y7CPV_quotient;
extern FiClos G_PJ7V9_print;
static FiWord *pG_D0MRQ_sinteger__SingleInteg;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_LD0B5_domainHash_BANG_;
static FiClos *pG_QRAZA_rtDelayedGetExport;
static FiClos *pG_30VT8_stdGetWordWordRetNOp2;
static FiWord *pG_Z4122_textwrit__TextWriter;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiClos *pG_DLXW8_stdGetWordWordRetWord;
static FiWord *pG_PRTGD_char__Character__7004;
static FiClos *pG_AKTR8_char;
static FiClos *pG_EC2QI_textwrit;
static FiClos *pG_HAQ5R_sinteger;


void
quotient(FiWord P0_x, FiWord P1_y, FiWord* R0, FiWord* R1)
{
        INIT__0_exptoc2();
        if (!G_Y7CPV_quotient) fiCall0(FiClos, G_IMU9E_exptoc2);
        fiCallSpecial0(G_Y7CPV_quotient, (FiWord) P0_x, (FiWord) P1_y, R0, R1);
}

void
print(FiWord P0_x)
{
        INIT__0_exptoc2();
        if (!G_PJ7V9_print) fiCall0(FiClos, G_IMU9E_exptoc2);
        fiCallSpecial1(G_PJ7V9_print, (FiWord) P0_x);
}


static void
CF0_exptoc2(FiEnv e1)
{
        FiWord T3;
        FiClos T0, T1, T2;
        PFmt8 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt8 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCall0(void, (*pG_XIPRL_runtime));
        G_IMU9E_exptoc2 = (FiClos) (*pG_NQYQM_noOperation);
        T0 = fiClosMake(e0, C5_sinteger_MINUS_init);
        l0->X1_quotient = fiClosMake(e0, C1_quotient);
        T1 = fiClosMake(e0, C4_textwrit_MINUS_init);
        T2 = fiClosMake(e0, C3_char_MINUS_init);
        l0->X0_print = fiClosMake(e0, C2_print);
        l0->X13 = 0L;
        l0->X14 = 0L;
        l0->X15 = 0L;
        G_Y7CPV_quotient = l0->X1_quotient;
        G_PJ7V9_print = l0->X0_print;
        l0->X2_SingleInteger = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T0, 0L);
        l0->X10_dom = l0->X2_SingleInteger;
        T3 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X10_dom, 
        	42114539L, 2002712267L);
        l0->X9_divide = fiCall(FiClos, (*pG_30VT8_stdGetWordWordRetNOp2), 
        	T3);
        l0->X4_TextWriter = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T1, 0L);
        l0->X11_dom = l0->X4_TextWriter;
        l0->X7_print = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X11_dom, 828947258L, 182752316L);
        T3 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X10_dom, 
        	51492426L, 1430340162L);
        l0->X8__LT__LT_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T3);
        l0->X3_Character = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T2, 0L);
        l0->X12_dom = l0->X3_Character;
        l0->X6_newline = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X12_dom, 493486801L, 803414590L);
        T3 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X12_dom, 
        	51492426L, 936629095L);
        l0->X5__LT__LT_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T3);
        bar();
        return ;
}

static struct _FiProg  tmp0_exptoc2 = {
        (FiFun) CF0_exptoc2,
        0L,
        0L,
        0L
};


static void
CF1_quotient(FiEnv e1, FiWord P0_x, FiWord P1_y, FiWord* R0, FiWord* 
        	R1)
{
        FiWord T0, T1;
        PFmt8 l1;
        l1 = (PFmt8) fiEnvLevel(e1);
        fiCallSpecial2(l1->X9_divide, (FiWord) P0_x, (FiWord) P1_y, &T0, &
        	T1);
        *R0 = T0;
        *R1 = T1;
        return ;
}

static struct _FiProg  tmp1_quotient = {
        (FiFun) CF1_quotient,
        0L,
        0L,
        0L
};


static void
CF2_print(FiEnv e1, FiWord P0_x)
{
        FiWord T0, T1;
        PFmt8 l1;
        l1 = (PFmt8) fiEnvLevel(e1);
        T0 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X7_print);
        T0 = fiCall(FiWord, l1->X8__LT__LT_, T0, P0_x);
        T1 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X6_newline);
        fiCall(FiWord, l1->X5__LT__LT_, T0, T1);
        return ;
}

static struct _FiProg  tmp2_print = {
        (FiFun) CF2_print,
        0L,
        0L,
        0L
};


static FiWord
CF3_char_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt8 l1;
        l1 = (PFmt8) fiEnvLevel(e1);
        if (l1->X13) goto L0;
        l1->X13 = 1L;
        fiCall0(void, (*pG_AKTR8_char));
L0:	return (FiWord) (*pG_PRTGD_char__Character__7004);
}

static struct _FiProg  tmp3_char_MINUS_init = {
        (FiFun) CF3_char_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF4_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt8 l1;
        l1 = (PFmt8) fiEnvLevel(e1);
        if (l1->X14) goto L0;
        l1->X14 = 1L;
        fiCall0(void, (*pG_EC2QI_textwrit));
L0:	return (FiWord) (*pG_Z4122_textwrit__TextWriter);
}

static struct _FiProg  tmp4_textwrit_MINUS_init = {
        (FiFun) CF4_textwrit_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF5_sinteger_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt8 l1;
        l1 = (PFmt8) fiEnvLevel(e1);
        if (l1->X15) goto L0;
        l1->X15 = 1L;
        fiCall0(void, (*pG_HAQ5R_sinteger));
L0:	return (FiWord) (*pG_D0MRQ_sinteger__SingleInteg);
}

static struct _FiProg  tmp5_sinteger_MINUS_init = {
        (FiFun) CF5_sinteger_MINUS_init,
        0L,
        0L,
        0L
};

extern int
INIT__0_exptoc2(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_sinteger(void);
        extern int INIT__0_textwrit(void);
        extern int INIT__0_char(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_quotient = &tmp1_quotient;
        C2_print = &tmp2_print;
        C3_char_MINUS_init = &tmp3_char_MINUS_init;
        C4_textwrit_MINUS_init = &tmp4_textwrit_MINUS_init;
        C5_sinteger_MINUS_init = &tmp5_sinteger_MINUS_init;
        C0_exptoc2 = &tmp0_exptoc2;
        fiExportGlobal("G_IMU9E_exptoc2", G_IMU9E_exptoc2);
        fiExportGlobal("G_Y7CPV_quotient", G_Y7CPV_quotient);
        fiExportGlobal("G_PJ7V9_print", G_PJ7V9_print);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_D0MRQ_sinteger__SingleIntege", 
        	pG_D0MRQ_sinteger__SingleInteg);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_LD0B5_domainHash_BANG_", pG_LD0B5_domainHash_BANG_);
        fiImportGlobal("G_QRAZA_rtDelayedGetExport", 
        	pG_QRAZA_rtDelayedGetExport);
        fiImportGlobal("G_30VT8_stdGetWordWordRetNOp2", 
        	pG_30VT8_stdGetWordWordRetNOp2);
        fiImportGlobal("G_Z4122_textwrit__TextWriter__", 
        	pG_Z4122_textwrit__TextWriter);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_DLXW8_stdGetWordWordRetWord0", 
        	pG_DLXW8_stdGetWordWordRetWord);
        fiImportGlobal("G_PRTGD_char__Character__70042", 
        	pG_PRTGD_char__Character__7004);
        fiImportGlobal("G_AKTR8_char", pG_AKTR8_char);
        fiImportGlobal("G_EC2QI_textwrit", pG_EC2QI_textwrit);
        fiImportGlobal("G_HAQ5R_sinteger", pG_HAQ5R_sinteger);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("sinteger");
                fiFileInitializer("textwrit");
                fiFileInitializer("char");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_sinteger();
                INIT__0_textwrit();
                INIT__0_char();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}

FiClos G_PJ7V9_print;
FiClos G_Y7CPV_quotient;

static struct _FiClos  tmpClos0_exptoc2 = {
        0L,
        (FiProg) &tmp0_exptoc2
};
FiClos G_IMU9E_exptoc2 = &tmpClos0_exptoc2;
