/*
 * C code generated by Aldor from file "forn3.as".
 */

#include "foam_c.h"

typedef struct Fmt7  *PFmt7;
typedef struct Fmt8  *PFmt8;
typedef struct Fmt9  *PFmt9;
typedef struct Fmt10  *PFmt10;
typedef struct Fmt11  *PFmt11;
typedef struct Fmt12  *PFmt12;
typedef struct Fmt13  *PFmt13;
typedef struct Fmt14  *PFmt14;
typedef struct Fmt15  *PFmt15;
typedef struct Fmt16  *PFmt16;
typedef struct Fmt17  *PFmt17;
typedef struct Fmt18  *PFmt18;
typedef struct Fmt19  *PFmt19;
typedef struct Fmt20  *PFmt20;
typedef struct Fmt21  *PFmt21;
struct Fmt7 {
        FiPtr X0_empty;
};
struct Fmt8 {
        FiPtr X0_empty;
};
struct Fmt9 {
        FiWord X0;
        FiWord X1;
};
struct Fmt10 {
        FiClos X0_getter;
        FiBool X1_flag;
        FiClos X2_self;
};
struct Fmt11 {
        FiWord X0_DoubleFloat;
        FiWord X1_TextWriter;
        FiWord X2_print;
        FiClos X3_step;
        FiWord X4_dom;
        FiWord X5_dom;
        FiBool X6;
        FiBool X7;
};
struct Fmt12 {
        FiPtr X0_empty;
};
struct Fmt13 {
        FiClos X0;
        FiClos X1;
        FiClos X2;
};
struct Fmt14 {
        FiPtr X0_empty;
};
struct Fmt15 {
        FiClos X0_getter;
        FiBool X1_flag;
        FiClos X2_self;
};
struct Fmt16 {
        FiPtr X0_empty;
};
struct Fmt17 {
        FiPtr X0_empty;
};
struct Fmt18 {
        FiPtr X0_empty;
};
struct Fmt19 {
        FiPtr X0_empty;
};
struct Fmt20 {
        FiPtr X0_empty;
};
struct Fmt21 {
        FiWord X0_RoundingMode;
        FiWord X1_Machine;
        FiWord X2_FortranDouble;
        FiWord X3_FloatingPointNumberSystem;
        FiWord X4_OrderedFinite;
        FiWord X5_DenseStorageCategory;
        FiWord X6_BasicType;
        FiWord X7_SingleInteger;
        FiClos X8_BinaryPowering;
        FiWord X9_Integer;
        FiClos X10_Record;
        FiWord X11_DFlo;
        FiWord X12_max;
        FiWord X13_min;
        FiWord X14_epsilon;
        FiWord X15_dom;
        FiClos X16_Segment;
        FiBool X17;
        FiBool X18;
        FiBool X19;
        FiBool X20;
        FiBool X21;
        FiBool X22;
        FiBool X23;
        FiBool X24;
};
static FiProg C0_forn3;
static void CF0_forn3(FiEnv e1);
static FiProg C1_T1;
static void CF1_T1(FiEnv e1);
static FiProg C2_t1;
static void CF2_t1(FiEnv e1, FiClos P0_f);
static FiProg C3_foreignWrapper;
static FiDFlo CF3_foreignWrapper(FiEnv e1, FiDFlo P0);
static FiProg C4_foreignWrapper;
static FiDFlo CF4_foreignWrapper(FiEnv e1, FiDFlo P0);
static FiProg C5_foreignWrapper;
static FiDFlo CF5_foreignWrapper(FiEnv e1, FiDFlo P0);
static FiProg C6_T2;
static void CF6_T2(FiEnv e1);
static FiProg C7_foreignWrapper;
static void CF7_foreignWrapper(FiEnv e1, FiWord P0, FiWord* R0, FiWord* R1);
static FiProg C8_lazyGetter2;
static void CF8_lazyGetter2(FiEnv e1);
static FiProg C9_lazyFnGetter;
static FiClos CF9_lazyFnGetter(FiEnv e1, FiWord P0_init);
static FiProg C10_lazyGetter;
static FiClos CF10_lazyGetter(FiEnv e1, FiWord P0_a);
static FiProg C11_textwrit_MINUS_init;
static FiWord CF11_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C12_dfloat_MINUS_init;
static FiWord CF12_dfloat_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C13_lazyFnGetter;
static FiClos CF13_lazyFnGetter(FiEnv e1, FiWord P0_init);
static FiProg C14_lazyGetter;
static FiClos CF14_lazyGetter(FiEnv e1, FiWord P0_a);
static FiProg C15_lazyGetter2;
static void CF15_lazyGetter2(FiEnv e1);
#define fiCallSpecial0(fn,a1,a2,a3) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3))

#define fiCallSpecial1(fn,a1,a2,a3) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3))

#define fiCallSpecial2(fn,a1) (fiProtoCFun(FiDFlo,(FiEnv,FiDFlo),fn)((fn)->env,a1))

#define fiCallSpecial3(fn,a1,a2,a3) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3))

#define fiCallSpecial4(fn,a1,a2,a3) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3))

#define fiCallSpecial5(fn,a1,a2,a3) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3))

#define fiCallSpecial6(fn,a1,a2,a3) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3))

extern FiClos G_336E0_forn3;
static FiClos *pG_NQYQM_noOperation;
extern FiDFlo sin(FiDFlo P0);
extern FiDFlo cos(FiDFlo P0);
extern FiDFlo tan(FiDFlo P0);
extern void zzz(FiWord P0, FiPtr R0, FiPtr R1);
extern FiClos G_3UUT1_forn3__T2__778822608;
extern FiClos G_Q798B_forn3__T1__778822608;
static FiClos *pG_XIPRL_runtime;
static FiWord *pG_STDSR_dfloat__DoubleFloat__;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_QRAZA_rtDelayedGetExport;
static FiWord *pG_Z4122_textwrit__TextWriter;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiClos *pG_EC2QI_textwrit;
static FiClos *pG_DEGQL_dfloat;
extern FiWord formatSInt(FiSInt P0);



static void
CF0_forn3(FiEnv e1)
{
        FiClos T0, T1;
        PFmt11 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt11 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCall0(void, (*pG_XIPRL_runtime));
        G_336E0_forn3 = (FiClos) (*pG_NQYQM_noOperation);
        T0 = fiClosMake(e0, C12_dfloat_MINUS_init);
        T1 = fiClosMake(e0, C11_textwrit_MINUS_init);
        G_Q798B_forn3__T1__778822608 = fiClosMake(e0, C1_T1);
        G_3UUT1_forn3__T2__778822608 = fiClosMake(e0, C6_T2);
        l0->X6 = 0L;
        l0->X7 = 0L;
        l0->X0_DoubleFloat = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T0, 0L);
        l0->X4_dom = l0->X0_DoubleFloat;
        l0->X3_step = CF9_lazyFnGetter(e0, (FiWord) fiCall(FiWord, (*
        	pG_QRAZA_rtDelayedGetExport), l0->X4_dom, 61407584L, 
        	-1717401541L));
        l0->X1_TextWriter = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T1, 0L);
        l0->X5_dom = l0->X1_TextWriter;
        l0->X2_print = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X5_dom, 828947258L, 182752316L);
        CF1_T1(e0);
        return ;
}

static struct _FiProg  tmp0_forn3 = {
        (FiFun) CF0_forn3,
        0L,
        0L,
        0L
};


static void
CF1_T1(FiEnv e1)
{
        FiEnv e0;
        PFmt11 l1;
        e0 = fiEnvPush(fiNil, e1);
        l1 = (PFmt11) fiEnvLevel(e1);
        CF2_t1(e0, (FiClos) fiClosMake(e0, C3_foreignWrapper));
        CF2_t1(e0, (FiClos) fiClosMake(e0, C4_foreignWrapper));
        CF2_t1(e0, (FiClos) fiClosMake(e0, C5_foreignWrapper));
        return ;
}

static struct _FiProg  tmp1_T1 = {
        (FiFun) CF1_T1,
        0L,
        0L,
        0L
};


static void
CF2_t1(FiEnv e1, FiClos P0_f)
{
        FiSInt T11, T13, T18, T20, T29_a, T31, T32;
        FiDFlo T4, T22, T23, T25_double, T26_double, T27_double, T28_double, T30_double;
        FiWord T3, T14, T21, T24_dom;
        FiChar *T12, *T19;
        FiClos T0, T1, T2, T5, T6, T7, T8, T9, T10, T15, T16, T17;
        PFmt11 l2;
        FiEnv e2;
        e2 = fiEnvNext(e1);
        l2 = (PFmt11) fiEnvLevel(e2);
        fiEnvEnsure(l2->X3_step->env);
        T25_double = 0.0000000000000000;
        T26_double = 1.0000000000000000;
        T24_dom = fiCall(FiWord, ((PFmt21) fiEnvLevel2(l2->X3_step->
        	env))->X16_Segment, ((PFmt21) fiEnvLevel2(l2->X3_step->
        	env))->X7_SingleInteger);
        CF13_lazyFnGetter(fiEnvNext(fiEnvNext(l2->X3_step->env)), (FiWord) 
        	fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), T24_dom, 
        	113320568L, 788651633L));
        T22 = T26_double - T25_double;
        fiSINT_TO_DFLO(T23, FiDFlo, 10L);
        T28_double = T22 / T23;
        T30_double = T25_double;
        T29_a = 1L;
L4:	if (T29_a <= 11L) goto L5;
        return ;
L5:	T14 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l2->X2_print);
        fiARRNEW_Char(T12, FiChar*, 51L);
        T12[0L] = 0L;
        T12[50L] = 0L;
        T13 = 1L;
L0:	if (T13 <= 50L) goto L1;
        fiFORMAT_DFLO(T31, FiSInt, T30_double, T12, 0L);
        fiCallSpecial0((FiClos) T14, &T8, &T9, &T10);
        fiCall(FiWord, T9, (FiWord) T12, (FiWord) 1L, (FiWord) 0L);
        fiFree((FiPtr) T12);
        fiCallSpecial1((FiClos) T14, &T5, &T6, &T7);
        fiCall(FiWord, T6, (FiWord) "->", (FiWord) 1L, (FiWord) 0L);
        T4 = fiCallSpecial2(P0_f, T30_double);
        T21 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l2->X2_print);
        fiARRNEW_Char(T19, FiChar*, 51L);
        T19[0L] = 0L;
        T19[50L] = 0L;
        T20 = 1L;
L2:	if (T20 <= 50L) goto L3;
        fiFORMAT_DFLO(T32, FiSInt, T4, T19, 0L);
        fiCallSpecial3((FiClos) T21, &T15, &T16, &T17);
        fiCall(FiWord, T16, (FiWord) T19, (FiWord) 1L, (FiWord) 0L);
        fiFree((FiPtr) T19);
        T3 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l2->X2_print);
        fiCallSpecial4((FiClos) T3, &T0, &T1, &T2);
        fiCall(void, T0, (FiWord) 10L);
        T27_double = T30_double + T28_double;
        T30_double = T27_double;
        T29_a = T29_a + 1L;
        goto L4;
L3:	T18 = T20 - 1L;
        T19[T18] = 32L;
        T20 = T20 + 1L;
        goto L2;
L1:	T11 = T13 - 1L;
        T12[T11] = 32L;
        T13 = T13 + 1L;
        goto L0;
}

static struct _FiProg  tmp2_t1 = {
        (FiFun) CF2_t1,
        0L,
        0L,
        0L
};


static FiDFlo
CF3_foreignWrapper(FiEnv e1, FiDFlo P0)
{
        return sin((FiDFlo) P0);
}

static struct _FiProg  tmp3_foreignWrapper = {
        (FiFun) CF3_foreignWrapper,
        0L,
        0L,
        0L
};


static FiDFlo
CF4_foreignWrapper(FiEnv e1, FiDFlo P0)
{
        return cos((FiDFlo) P0);
}

static struct _FiProg  tmp4_foreignWrapper = {
        (FiFun) CF4_foreignWrapper,
        0L,
        0L,
        0L
};


static FiDFlo
CF5_foreignWrapper(FiEnv e1, FiDFlo P0)
{
        return tan((FiDFlo) P0);
}

static struct _FiProg  tmp5_foreignWrapper = {
        (FiFun) CF5_foreignWrapper,
        0L,
        0L,
        0L
};


static void
CF6_T2(FiEnv e1)
{
        FiWord T6, T7;
        FiClos T0, T1, T2, T3, T4, T5;
        FiEnv e0;
        PFmt11 l1;
        e0 = fiEnvPush(fiNil, e1);
        l1 = (PFmt11) fiEnvLevel(e1);
        T7 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X2_print);
        T6 = formatSInt((FiSInt) fiClosMake(e0, C7_foreignWrapper));
        fiCallSpecial5((FiClos) T7, &T3, &T4, &T5);
        fiCall(FiWord, T4, T6, (FiWord) 1L, (FiWord) 0L);
        fiCallSpecial6((FiClos) T7, &T0, &T1, &T2);
        fiCall(void, T0, (FiWord) 10L);
        return ;
}

static struct _FiProg  tmp6_T2 = {
        (FiFun) CF6_T2,
        0L,
        0L,
        0L
};


static void
CF7_foreignWrapper(FiEnv e1, FiWord P0, FiWord* R0, FiWord* R1)
{
        FiWord T0, T1;
        zzz((FiWord) P0, &T0, &T1);
        *R0 = T0;
        *R1 = T1;
        return ;
}

static struct _FiProg  tmp7_foreignWrapper = {
        (FiFun) CF7_foreignWrapper,
        0L,
        0L,
        0L
};


static void
CF8_lazyGetter2(FiEnv e1)
{
        FiClos T0;
        PFmt10 l1;
        l1 = (PFmt10) fiEnvLevel(e1);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCall0(FiWord, l1->X0_getter);
        l1->X1_flag = 1L;
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        fiEnvInfo(e1) = (FiWord) fiNil;
L0:	return ;
}

static struct _FiProg  tmp8_lazyGetter2 = {
        (FiFun) CF8_lazyGetter2,
        0L,
        0L,
        0L
};


static FiClos
CF9_lazyFnGetter(FiEnv e1, FiWord P0_init)
{
        PFmt10 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt10 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        l0->X0_getter = (FiClos) P0_init;
        l0->X1_flag = 0L;
        l0->X2_self = fiClosMake(e0, C10_lazyGetter);
        fiEnvInfo(e0) = (FiWord) fiClosMake(e0, C8_lazyGetter2);
        return l0->X2_self;
}

static struct _FiProg  tmp9_lazyFnGetter = {
        (FiFun) CF9_lazyFnGetter,
        0L,
        0L,
        0L
};


static FiClos
CF10_lazyGetter(FiEnv e1, FiWord P0_a)
{
        FiClos T0;
        PFmt10 l1;
        l1 = (PFmt10) fiEnvLevel(e1);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCall0(FiWord, l1->X0_getter);
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        l1->X1_flag = 1L;
L0:	return fiCall(FiClos, l1->X2_self, P0_a);
}

static struct _FiProg  tmp10_lazyGetter = {
        (FiFun) CF10_lazyGetter,
        0L,
        0L,
        0L
};


static FiWord
CF11_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt11 l1;
        l1 = (PFmt11) fiEnvLevel(e1);
        if (l1->X6) goto L0;
        l1->X6 = 1L;
        fiCall0(void, (*pG_EC2QI_textwrit));
L0:	return (FiWord) (*pG_Z4122_textwrit__TextWriter);
}

static struct _FiProg  tmp11_textwrit_MINUS_init = {
        (FiFun) CF11_textwrit_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF12_dfloat_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt11 l1;
        l1 = (PFmt11) fiEnvLevel(e1);
        if (l1->X7) goto L0;
        l1->X7 = 1L;
        fiCall0(void, (*pG_DEGQL_dfloat));
L0:	return (FiWord) (*pG_STDSR_dfloat__DoubleFloat__);
}

static struct _FiProg  tmp12_dfloat_MINUS_init = {
        (FiFun) CF12_dfloat_MINUS_init,
        0L,
        0L,
        0L
};


static FiClos
CF13_lazyFnGetter(FiEnv e1, FiWord P0_init)
{
        PFmt15 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt15 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        l0->X0_getter = (FiClos) P0_init;
        l0->X1_flag = 0L;
        l0->X2_self = fiClosMake(e0, C14_lazyGetter);
        fiEnvInfo(e0) = (FiWord) fiClosMake(e0, C15_lazyGetter2);
        return l0->X2_self;
}

static struct _FiProg  tmp13_lazyFnGetter = {
        (FiFun) CF13_lazyFnGetter,
        0L,
        0L,
        0L
};


static FiClos
CF14_lazyGetter(FiEnv e1, FiWord P0_a)
{
        FiClos T0;
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCall0(FiWord, l1->X0_getter);
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        l1->X1_flag = 1L;
L0:	return fiCall(FiClos, l1->X2_self, P0_a);
}

static struct _FiProg  tmp14_lazyGetter = {
        (FiFun) CF14_lazyGetter,
        0L,
        0L,
        0L
};


static void
CF15_lazyGetter2(FiEnv e1)
{
        FiClos T0;
        PFmt15 l1;
        l1 = (PFmt15) fiEnvLevel(e1);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCall0(FiWord, l1->X0_getter);
        l1->X1_flag = 1L;
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        fiEnvInfo(e1) = (FiWord) fiNil;
L0:	return ;
}

static struct _FiProg  tmp15_lazyGetter2 = {
        (FiFun) CF15_lazyGetter2,
        0L,
        0L,
        0L
};

extern int
INIT__0_forn3(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_dfloat(void);
        extern int INIT__0_textwrit(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_T1 = &tmp1_T1;
        C2_t1 = &tmp2_t1;
        C3_foreignWrapper = &tmp3_foreignWrapper;
        C4_foreignWrapper = &tmp4_foreignWrapper;
        C5_foreignWrapper = &tmp5_foreignWrapper;
        C6_T2 = &tmp6_T2;
        C7_foreignWrapper = &tmp7_foreignWrapper;
        C8_lazyGetter2 = &tmp8_lazyGetter2;
        C9_lazyFnGetter = &tmp9_lazyFnGetter;
        C10_lazyGetter = &tmp10_lazyGetter;
        C11_textwrit_MINUS_init = &tmp11_textwrit_MINUS_init;
        C12_dfloat_MINUS_init = &tmp12_dfloat_MINUS_init;
        C13_lazyFnGetter = &tmp13_lazyFnGetter;
        C14_lazyGetter = &tmp14_lazyGetter;
        C15_lazyGetter2 = &tmp15_lazyGetter2;
        C0_forn3 = &tmp0_forn3;
        fiExportGlobal("G_336E0_forn3", G_336E0_forn3);
        fiExportGlobal("G_3UUT1_forn3__T2__778822608", 
        	G_3UUT1_forn3__T2__778822608);
        fiExportGlobal("G_Q798B_forn3__T1__778822608", 
        	G_Q798B_forn3__T1__778822608);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_STDSR_dfloat__DoubleFloat__7", 
        	pG_STDSR_dfloat__DoubleFloat__);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_QRAZA_rtDelayedGetExport", 
        	pG_QRAZA_rtDelayedGetExport);
        fiImportGlobal("G_Z4122_textwrit__TextWriter__", 
        	pG_Z4122_textwrit__TextWriter);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_EC2QI_textwrit", pG_EC2QI_textwrit);
        fiImportGlobal("G_DEGQL_dfloat", pG_DEGQL_dfloat);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("dfloat");
                fiFileInitializer("textwrit");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_dfloat();
                INIT__0_textwrit();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}

FiClos G_Q798B_forn3__T1__778822608;
FiClos G_3UUT1_forn3__T2__778822608;

static struct _FiClos  tmpClos0_forn3 = {
        0L,
        (FiProg) &tmp0_forn3
};
FiClos G_336E0_forn3 = &tmpClos0_forn3;
