/*
 * C code generated by Aldor from file "forn1.as".
 */

#include "foam_c.h"

#include <stdio.h>

typedef struct Fmt6  *PFmt6;
typedef struct Fmt7  *PFmt7;
struct Fmt6 {
        FiClos X0_getter;
        FiBool X1_flag;
        FiClos X2_self;
};
struct Fmt7 {
        FiWord X0_String;
        FiClos X1_string;
        FiClos X2_data;
        FiWord X3_dom;
        FiBool X4;
};
static FiProg C0_forn1;
static void CF0_forn1(FiEnv e1);
static FiProg C1_puts;
static FiWord CF1_puts(FiEnv e1, FiWord P0_n);
static FiProg C2_lazyFnGetter;
static FiClos CF2_lazyFnGetter(FiEnv e1, FiWord P0_init);
static FiProg C3_lazyGetter;
static FiPtr CF3_lazyGetter(FiEnv e1, FiWord P0_a);
static FiProg C4_lazyGetter2;
static void CF4_lazyGetter2(FiEnv e1);
static FiProg C5_string_MINUS_init;
static FiWord CF5_string_MINUS_init(FiEnv e1, FiSInt P0_idx);
extern FiClos G_336DY_forn1;
static FiClos *pG_NQYQM_noOperation;
extern FiClos G_SWVYW_forn1__puts__847847226;
static FiClos *pG_XIPRL_runtime;
static FiWord *pG_OI71W_string__String__90554;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_QRAZA_rtDelayedGetExport;
static FiClos *pG_ZZZKG_stdGetWordRetWord0;
static FiClos *pG_OGNYK_string;



static void
CF0_forn1(FiEnv e1)
{
        FiWord T1;
        FiClos T0;
        PFmt7 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt7 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCall0(void, (*pG_XIPRL_runtime));
        G_336DY_forn1 = (FiClos) (*pG_NQYQM_noOperation);
        G_SWVYW_forn1__puts__847847226 = fiClosMake(e0, C1_puts);
        T0 = fiClosMake(e0, C5_string_MINUS_init);
        l0->X4 = 0L;
        l0->X0_String = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), T0, 
        	0L);
        l0->X3_dom = l0->X0_String;
        T1 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X3_dom, 
        	585283853L, -1916843600L);
        l0->X1_string = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T1);
        l0->X2_data = CF2_lazyFnGetter(e0, (FiWord) fiCall(FiWord, (*
        	pG_QRAZA_rtDelayedGetExport), l0->X3_dom, 814227774L, 
        	-1640661988L));
        T1 = fiCall(FiWord, l0->X1_string, (FiWord) "Hello world!");
        puts((FiPtr) fiCall(FiPtr, l0->X2_data, T1));
        return ;
}

static struct _FiProg  tmp0_forn1 = {
        (FiFun) CF0_forn1,
        0L,
        0L,
        0L
};


static FiWord
CF1_puts(FiEnv e1, FiWord P0_n)
{
        return P0_n;
}

static struct _FiProg  tmp1_puts = {
        (FiFun) CF1_puts,
        0L,
        0L,
        0L
};


static FiClos
CF2_lazyFnGetter(FiEnv e1, FiWord P0_init)
{
        PFmt6 l0;
        FiEnv e0;
        PFmt7 l1;
        l0 = fi0New(struct Fmt6 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        l1 = (PFmt7) fiEnvLevel(e1);
        l0->X0_getter = (FiClos) P0_init;
        l0->X1_flag = 0L;
        l0->X2_self = fiClosMake(e0, C3_lazyGetter);
        fiEnvInfo(e0) = (FiWord) fiClosMake(e0, C4_lazyGetter2);
        return l0->X2_self;
}

static struct _FiProg  tmp2_lazyFnGetter = {
        (FiFun) CF2_lazyFnGetter,
        0L,
        0L,
        0L
};


static FiPtr
CF3_lazyGetter(FiEnv e1, FiWord P0_a)
{
        FiClos T0;
        PFmt6 l1;
        PFmt7 l2;
        FiEnv e2;
        l1 = (PFmt6) fiEnvLevel(e1);
        e2 = fiEnvNext(e1);
        l2 = (PFmt7) fiEnvLevel(e2);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCall0(FiWord, l1->X0_getter);
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        l1->X1_flag = 1L;
L0:	return fiCall(FiPtr, l1->X2_self, P0_a);
}

static struct _FiProg  tmp3_lazyGetter = {
        (FiFun) CF3_lazyGetter,
        0L,
        0L,
        0L
};


static void
CF4_lazyGetter2(FiEnv e1)
{
        FiClos T0;
        PFmt6 l1;
        PFmt7 l2;
        FiEnv e2;
        l1 = (PFmt6) fiEnvLevel(e1);
        e2 = fiEnvNext(e1);
        l2 = (PFmt7) fiEnvLevel(e2);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCall0(FiWord, l1->X0_getter);
        l1->X1_flag = 1L;
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        fiEnvInfo(e1) = (FiWord) fiNil;
L0:	return ;
}

static struct _FiProg  tmp4_lazyGetter2 = {
        (FiFun) CF4_lazyGetter2,
        0L,
        0L,
        0L
};


static FiWord
CF5_string_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt7 l1;
        l1 = (PFmt7) fiEnvLevel(e1);
        if (l1->X4) goto L0;
        l1->X4 = 1L;
        fiCall0(void, (*pG_OGNYK_string));
L0:	return (FiWord) (*pG_OI71W_string__String__90554);
}

static struct _FiProg  tmp5_string_MINUS_init = {
        (FiFun) CF5_string_MINUS_init,
        0L,
        0L,
        0L
};

extern int
INIT__0_forn1(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_string(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_puts = &tmp1_puts;
        C2_lazyFnGetter = &tmp2_lazyFnGetter;
        C3_lazyGetter = &tmp3_lazyGetter;
        C4_lazyGetter2 = &tmp4_lazyGetter2;
        C5_string_MINUS_init = &tmp5_string_MINUS_init;
        C0_forn1 = &tmp0_forn1;
        fiExportGlobal("G_336DY_forn1", G_336DY_forn1);
        fiExportGlobal("G_SWVYW_forn1__puts__847847226", 
        	G_SWVYW_forn1__puts__847847226);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_OI71W_string__String__905549", 
        	pG_OI71W_string__String__90554);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_QRAZA_rtDelayedGetExport", 
        	pG_QRAZA_rtDelayedGetExport);
        fiImportGlobal("G_ZZZKG_stdGetWordRetWord0", 
        	pG_ZZZKG_stdGetWordRetWord0);
        fiImportGlobal("G_OGNYK_string", pG_OGNYK_string);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("string");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_string();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}

FiClos G_SWVYW_forn1__puts__847847226;

static struct _FiClos  tmpClos0_forn1 = {
        0L,
        (FiProg) &tmp0_forn1
};
FiClos G_336DY_forn1 = &tmpClos0_forn1;
