/*
 * C code generated by Aldor from file "forn4.as".
 */

#include "foam_c.h"

#include "myfile.h"

#include "hisfile.h0"

#include "c:\\heavy\\equip\\vehicles.h"

#include <ctype.h>

#include <math.h>

typedef struct Fmt8  *PFmt8;
typedef struct Fmt9  *PFmt9;
struct Fmt8 {
        FiPtr X0_empty;
};
struct Fmt9 {
        FiClos X0_print;
        FiClos X1_fact;
        FiWord X2_SingleInteger;
        FiWord X3_Character;
        FiWord X4_String;
        FiWord X5_TextWriter;
        FiClos X6_string;
        FiClos X7__LT__LT_;
        FiWord X8_newline;
        FiWord X9_print;
        FiClos X10__EQ_;
        FiClos X11__LT__LT_;
        FiWord X12_0;
        FiClos X13__MINUS_;
        FiWord X14_1;
        FiClos X15__STAR_;
        FiClos X16_integer;
        FiWord X17_dom;
        FiWord X18_dom;
        FiWord X19_dom;
        FiWord X20_dom;
        FiBool X21;
        FiBool X22;
        FiBool X23;
        FiBool X24;
};
static FiProg C0_forn4;
static void CF0_forn4(FiEnv e1);
static FiProg C1_fact;
static FiWord CF1_fact(FiEnv e1, FiWord P0_x);
static FiProg C2_print;
static void CF2_print(FiEnv e1, FiWord P0_x);
static FiProg C3_string_MINUS_init;
static FiWord CF3_string_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C4_char_MINUS_init;
static FiWord CF4_char_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C5_textwrit_MINUS_init;
static FiWord CF5_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C6_sinteger_MINUS_init;
static FiWord CF6_sinteger_MINUS_init(FiEnv e1, FiSInt P0_idx);
#define fiCallSpecial0(fn,a1) (fiProtoCFun(void,(FiEnv,FiWord),fn)((fn)->env,a1))

extern int INIT__0_forn4(void);
extern FiClos G_336E1_forn4;
static FiClos *pG_NQYQM_noOperation;
extern FiWord roo(FiWord P0, FiWord P1);
extern FiWord qoo(FiWord P0, FiWord P1);
extern FiWord moo(FiWord P0, FiWord P1);
extern FiWord noo(FiWord P0, FiWord P1);
extern FiWord G_2G6ZG_forn4__x__057166236;
static FiClos *pG_XIPRL_runtime;
static FiWord *pG_OI71W_string__String__90554;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_LD0B5_domainHash_BANG_;
static FiClos *pG_QRAZA_rtDelayedGetExport;
static FiClos *pG_ZZZKG_stdGetWordRetWord0;
static FiWord *pG_D0MRQ_sinteger__SingleInteg;
extern FiClos G_9M4BW_fact;
extern FiClos G_PJ7V9_print;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiWord *pG_9B9PO_boolean__Boolean__545;
static FiClos *pG_DLXW8_stdGetWordWordRetWord;
static FiWord *pG_Z4122_textwrit__TextWriter;
static FiWord *pG_PRTGD_char__Character__7004;
static FiClos *pG_OGNYK_string;
static FiClos *pG_AKTR8_char;
static FiClos *pG_EC2QI_textwrit;
static FiClos *pG_P63GL_boolean;
static FiClos *pG_HAQ5R_sinteger;


FiWord
fact(FiWord P0_x)
{
        INIT__0_forn4();
        if (!G_9M4BW_fact) fiCall0(FiClos, G_336E1_forn4);
        return (FiWord) fiCall(FiWord, G_9M4BW_fact, P0_x);
}

void
print(FiWord P0_x)
{
        INIT__0_forn4();
        if (!G_PJ7V9_print) fiCall0(FiClos, G_336E1_forn4);
        fiCallSpecial0(G_PJ7V9_print, (FiWord) P0_x);
}


static void
CF0_forn4(FiEnv e1)
{
        FiWord T4;
        FiClos T0, T1, T2, T3;
        PFmt9 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt9 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCall0(void, (*pG_XIPRL_runtime));
        G_336E1_forn4 = (FiClos) (*pG_NQYQM_noOperation);
        T0 = fiClosMake(e0, C3_string_MINUS_init);
        T1 = fiClosMake(e0, C6_sinteger_MINUS_init);
        l0->X1_fact = fiClosMake(e0, C1_fact);
        T2 = fiClosMake(e0, C5_textwrit_MINUS_init);
        T3 = fiClosMake(e0, C4_char_MINUS_init);
        l0->X0_print = fiClosMake(e0, C2_print);
        l0->X21 = 0L;
        l0->X22 = 0L;
        l0->X23 = 0L;
        l0->X24 = 0L;
        G_2G6ZG_forn4__x__057166236 = (FiWord) earth;
        l0->X4_String = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), T0, 
        	0L);
        l0->X17_dom = l0->X4_String;
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X17_dom, 
        	585283853L, -1916843600L);
        l0->X6_string = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T4);
        l0->X2_SingleInteger = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T1, 0L);
        l0->X18_dom = l0->X2_SingleInteger;
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X18_dom, 
        	477900237L, 2130877288L);
        l0->X16_integer = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T4);
        l0->X12_0 = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), l0->
        	X18_dom, 200089L, 142471813L);
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X18_dom, 
        	200102L, 1912236122L);
        l0->X10__EQ_ = fiCall(FiClos, (*pG_DLXW8_stdGetWordWordRetWord), 
        	T4);
        l0->X14_1 = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), l0->
        	X18_dom, 200090L, 142471813L);
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X18_dom, 
        	200086L, -490952084L);
        l0->X13__MINUS_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T4);
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X18_dom, 
        	200083L, -490952084L);
        l0->X15__STAR_ = fiCall(FiClos, (*pG_DLXW8_stdGetWordWordRetWord), 
        	T4);
        moo((FiWord) fiCall(FiWord, l0->X6_string, (FiWord) "hello"), (
        	FiWord) fiCall(FiWord, l0->X16_integer, (FiWord) "2"));
        noo((FiWord) fiCall(FiWord, l0->X6_string, (FiWord) "hello"), (
        	FiWord) fiCall(FiWord, l0->X16_integer, (FiWord) "2"));
        toupper((FiWord) fiCall(FiWord, l0->X16_integer, (FiWord) "100"));
        xxbar();
        xxfoo((FiWord) fiCall(FiWord, l0->X6_string, (FiWord) "hello"), (
        	FiWord) fiCall(FiWord, l0->X16_integer, (FiWord) "2"));
        xxboo((FiWord) fiCall(FiWord, l0->X6_string, (FiWord) "hello"), (
        	FiWord) fiCall(FiWord, l0->X16_integer, (FiWord) "2"));
        xxhoo((FiWord) fiCall(FiWord, l0->X6_string, (FiWord) "hello"), (
        	FiWord) fiCall(FiWord, l0->X16_integer, (FiWord) "2"));
        xxmover((FiWord) earth);
        G_9M4BW_fact = l0->X1_fact;
        G_PJ7V9_print = l0->X0_print;
        l0->X5_TextWriter = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T2, 0L);
        l0->X19_dom = l0->X5_TextWriter;
        l0->X9_print = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X19_dom, 828947258L, 182752316L);
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X18_dom, 
        	51492426L, 1430340162L);
        l0->X11__LT__LT_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T4);
        l0->X3_Character = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T3, 0L);
        l0->X20_dom = l0->X3_Character;
        l0->X8_newline = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X20_dom, 493486801L, 803414590L);
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X20_dom, 
        	51492426L, 936629095L);
        l0->X7__LT__LT_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T4);
        return ;
}

static struct _FiProg  tmp0_forn4 = {
        (FiFun) CF0_forn4,
        0L,
        0L,
        0L
};


static FiWord
CF1_fact(FiEnv e1, FiWord P0_x)
{
        FiWord T0, T1;
        PFmt9 l1;
        l1 = (PFmt9) fiEnvLevel(e1);
        T1 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X12_0);
        if ((FiBool) fiCall(FiWord, l1->X10__EQ_, P0_x, T1)) goto L0;
        T1 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X14_1);
        T1 = fiCall(FiWord, l1->X13__MINUS_, P0_x, T1);
        T1 = CF1_fact(e1, (FiWord) T1);
        T0 = fiCall(FiWord, l1->X15__STAR_, P0_x, T1);
        goto L1;
L0:	T0 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X14_1);
L1:	return T0;
}

static struct _FiProg  tmp1_fact = {
        (FiFun) CF1_fact,
        0L,
        0L,
        0L
};


static void
CF2_print(FiEnv e1, FiWord P0_x)
{
        FiWord T0, T1;
        PFmt9 l1;
        l1 = (PFmt9) fiEnvLevel(e1);
        T0 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X9_print);
        T0 = fiCall(FiWord, l1->X11__LT__LT_, T0, P0_x);
        T1 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X8_newline);
        fiCall(FiWord, l1->X7__LT__LT_, T0, T1);
        return ;
}

static struct _FiProg  tmp2_print = {
        (FiFun) CF2_print,
        0L,
        0L,
        0L
};


static FiWord
CF3_string_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt9 l1;
        l1 = (PFmt9) fiEnvLevel(e1);
        if (l1->X21) goto L0;
        l1->X21 = 1L;
        fiCall0(void, (*pG_OGNYK_string));
L0:	return (FiWord) (*pG_OI71W_string__String__90554);
}

static struct _FiProg  tmp3_string_MINUS_init = {
        (FiFun) CF3_string_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF4_char_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt9 l1;
        l1 = (PFmt9) fiEnvLevel(e1);
        if (l1->X22) goto L0;
        l1->X22 = 1L;
        fiCall0(void, (*pG_AKTR8_char));
L0:	return (FiWord) (*pG_PRTGD_char__Character__7004);
}

static struct _FiProg  tmp4_char_MINUS_init = {
        (FiFun) CF4_char_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF5_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt9 l1;
        l1 = (PFmt9) fiEnvLevel(e1);
        if (l1->X23) goto L0;
        l1->X23 = 1L;
        fiCall0(void, (*pG_EC2QI_textwrit));
L0:	return (FiWord) (*pG_Z4122_textwrit__TextWriter);
}

static struct _FiProg  tmp5_textwrit_MINUS_init = {
        (FiFun) CF5_textwrit_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF6_sinteger_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt9 l1;
        l1 = (PFmt9) fiEnvLevel(e1);
        if (l1->X24) goto L0;
        l1->X24 = 1L;
        fiCall0(void, (*pG_HAQ5R_sinteger));
L0:	return (FiWord) (*pG_D0MRQ_sinteger__SingleInteg);
}

static struct _FiProg  tmp6_sinteger_MINUS_init = {
        (FiFun) CF6_sinteger_MINUS_init,
        0L,
        0L,
        0L
};

extern int
INIT__0_forn4(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_sinteger(void);
        extern int INIT__0_boolean(void);
        extern int INIT__0_textwrit(void);
        extern int INIT__0_char(void);
        extern int INIT__0_string(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_fact = &tmp1_fact;
        C2_print = &tmp2_print;
        C3_string_MINUS_init = &tmp3_string_MINUS_init;
        C4_char_MINUS_init = &tmp4_char_MINUS_init;
        C5_textwrit_MINUS_init = &tmp5_textwrit_MINUS_init;
        C6_sinteger_MINUS_init = &tmp6_sinteger_MINUS_init;
        C0_forn4 = &tmp0_forn4;
        fiExportGlobal("G_336E1_forn4", G_336E1_forn4);
        fiExportGlobal("G_2G6ZG_forn4__x__057166236", 
        	G_2G6ZG_forn4__x__057166236);
        fiExportGlobal("G_9M4BW_fact", G_9M4BW_fact);
        fiExportGlobal("G_PJ7V9_print", G_PJ7V9_print);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_OI71W_string__String__905549", 
        	pG_OI71W_string__String__90554);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_LD0B5_domainHash_BANG_", pG_LD0B5_domainHash_BANG_);
        fiImportGlobal("G_QRAZA_rtDelayedGetExport", 
        	pG_QRAZA_rtDelayedGetExport);
        fiImportGlobal("G_ZZZKG_stdGetWordRetWord0", 
        	pG_ZZZKG_stdGetWordRetWord0);
        fiImportGlobal("G_D0MRQ_sinteger__SingleIntege", 
        	pG_D0MRQ_sinteger__SingleInteg);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_9B9PO_boolean__Boolean__5458", 
        	pG_9B9PO_boolean__Boolean__545);
        fiImportGlobal("G_DLXW8_stdGetWordWordRetWord0", 
        	pG_DLXW8_stdGetWordWordRetWord);
        fiImportGlobal("G_Z4122_textwrit__TextWriter__", 
        	pG_Z4122_textwrit__TextWriter);
        fiImportGlobal("G_PRTGD_char__Character__70042", 
        	pG_PRTGD_char__Character__7004);
        fiImportGlobal("G_OGNYK_string", pG_OGNYK_string);
        fiImportGlobal("G_AKTR8_char", pG_AKTR8_char);
        fiImportGlobal("G_EC2QI_textwrit", pG_EC2QI_textwrit);
        fiImportGlobal("G_P63GL_boolean", pG_P63GL_boolean);
        fiImportGlobal("G_HAQ5R_sinteger", pG_HAQ5R_sinteger);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("sinteger");
                fiFileInitializer("boolean");
                fiFileInitializer("textwrit");
                fiFileInitializer("char");
                fiFileInitializer("string");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_sinteger();
                INIT__0_boolean();
                INIT__0_textwrit();
                INIT__0_char();
                INIT__0_string();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}

FiClos G_PJ7V9_print;
FiClos G_9M4BW_fact;
FiWord G_2G6ZG_forn4__x__057166236;

static struct _FiClos  tmpClos0_forn4 = {
        0L,
        (FiProg) &tmp0_forn4
};
FiClos G_336E1_forn4 = &tmpClos0_forn4;
