"funct3.as", line 13:         i:Integer == true + 1   
                      .....................^
[L13 C22] #1 (Error) Argument 1 of `+' did not match any possible parameter type.
    The rejected type is Boolean.
    Expected one of:
      -- C0
      -- Integer

"funct3.as", line 14:         b:Boolean == true + 1   
                      .....................^
[L14 C22] #2 (Error) Argument 1 of `+' did not match any possible parameter type.
    The rejected type is Boolean.
    Expected one of:
      -- C0
      -- Integer

