/*
 * C code generated by Aldor from file "funvar.as".
 */

#include "foam_c.h"

typedef struct Fmt5  *PFmt5;
struct Fmt5 {
        FiClos X0_f;
        FiWord X1_Integer;
        FiWord X2_Character;
        FiWord X3_String;
        FiWord X4_TextWriter;
        FiClos X5_string;
        FiClos X6__LT__LT_;
        FiClos X7__LT__LT_;
        FiWord X8_newline;
        FiWord X9_print;
        FiClos X10_integer;
        FiClos X11__LT__LT_;
        FiClos X12__PLUS_;
        FiClos X13__MINUS_;
        FiWord X14_1;
        FiClos X15_even_QMARK_;
        FiWord X16_dom;
        FiWord X17_dom;
        FiWord X18_dom;
        FiWord X19_dom;
        FiBool X20;
        FiBool X21;
        FiBool X22;
        FiBool X23;
};
static FiProg C0_funvar;
static void CF0_funvar(FiEnv e1);
static FiProg C1_f0;
static FiWord CF1_f0(FiEnv e1, FiWord P0_n);
static FiProg C2_f1;
static FiWord CF2_f1(FiEnv e1, FiWord P0_n);
static FiProg C3_f2;
static FiWord CF3_f2(FiEnv e1, FiWord P0_n);
static FiProg C4_g;
static FiWord CF4_g(FiEnv e1, FiWord P0_n);
static FiProg C5_h;
static FiWord CF5_h(FiEnv e1, FiWord P0_n);
static FiProg C6_string_MINUS_init;
static FiWord CF6_string_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C7_char_MINUS_init;
static FiWord CF7_char_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C8_textwrit_MINUS_init;
static FiWord CF8_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C9_integer_MINUS_init;
static FiWord CF9_integer_MINUS_init(FiEnv e1, FiSInt P0_idx);
extern FiClos G_CK2SY_funvar;
static FiClos *pG_NQYQM_noOperation;
extern FiClos G_O1A90_funvar__h__847847226;
extern FiClos G_BY8SG_funvar__g__847847226;
extern FiClos G_BNG6U_funvar__f2__847847226;
extern FiClos G_LJT1F_funvar__f1__847847226;
extern FiClos G_B7KX9_funvar__f0__847847226;
static FiClos *pG_XIPRL_runtime;
static FiWord *pG_C26T4_integer__Integer__244;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiClos *pG_QRAZA_rtDelayedGetExport;
static FiClos *pG_DLXW8_stdGetWordWordRetWord;
static FiClos *pG_ZZZKG_stdGetWordRetWord0;
static FiWord *pG_Z4122_textwrit__TextWriter;
static FiWord *pG_OI71W_string__String__90554;
static FiWord *pG_PRTGD_char__Character__7004;
static FiClos *pG_OGNYK_string;
static FiClos *pG_AKTR8_char;
static FiClos *pG_EC2QI_textwrit;
static FiClos *pG_WJ27Y_integer;



static void
CF0_funvar(FiEnv e1)
{
        FiWord T4, T5;
        FiClos T0, T1, T2, T3;
        PFmt5 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt5 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCall0(void, (*pG_XIPRL_runtime));
        G_CK2SY_funvar = (FiClos) (*pG_NQYQM_noOperation);
        G_B7KX9_funvar__f0__847847226 = fiClosMake(e0, C1_f0);
        T0 = fiClosMake(e0, C9_integer_MINUS_init);
        G_LJT1F_funvar__f1__847847226 = fiClosMake(e0, C2_f1);
        G_BNG6U_funvar__f2__847847226 = fiClosMake(e0, C3_f2);
        G_BY8SG_funvar__g__847847226 = fiClosMake(e0, C4_g);
        G_O1A90_funvar__h__847847226 = fiClosMake(e0, C5_h);
        T1 = fiClosMake(e0, C8_textwrit_MINUS_init);
        T2 = fiClosMake(e0, C6_string_MINUS_init);
        T3 = fiClosMake(e0, C7_char_MINUS_init);
        l0->X20 = 0L;
        l0->X21 = 0L;
        l0->X22 = 0L;
        l0->X23 = 0L;
        l0->X1_Integer = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), T0, 
        	0L);
        l0->X16_dom = l0->X1_Integer;
        l0->X14_1 = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), l0->
        	X16_dom, 200090L, 484208045L);
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X16_dom, 
        	200084L, 2104366580L);
        l0->X12__PLUS_ = fiCall(FiClos, (*pG_DLXW8_stdGetWordWordRetWord), 
        	T4);
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X16_dom, 
        	200086L, 2104366580L);
        l0->X13__MINUS_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T4);
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X16_dom, 
        	498514682L, -1376822255L);
        l0->X15_even_QMARK_ = fiCall(FiClos, (*
        	pG_ZZZKG_stdGetWordRetWord0), T4);
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X16_dom, 
        	477900237L, 128860016L);
        l0->X10_integer = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T4);
        l0->X4_TextWriter = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T1, 0L);
        l0->X17_dom = l0->X4_TextWriter;
        l0->X9_print = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X17_dom, 828947258L, 182752316L);
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X16_dom, 
        	51492426L, -2075677734L);
        l0->X11__LT__LT_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T4);
        l0->X3_String = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), T2, 
        	0L);
        l0->X18_dom = l0->X3_String;
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X18_dom, 
        	585283853L, -1916843600L);
        l0->X5_string = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T4);
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X18_dom, 
        	51492426L, -421540838L);
        l0->X6__LT__LT_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T4);
        l0->X2_Character = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T3, 0L);
        l0->X19_dom = l0->X2_Character;
        l0->X8_newline = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X19_dom, 493486801L, 803414590L);
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X19_dom, 
        	51492426L, 936629095L);
        l0->X7__LT__LT_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T4);
        T4 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X9_print);
        T5 = fiCall(FiWord, l0->X10_integer, (FiWord) "2");
        T5 = CF4_g(e0, (FiWord) T5);
        T4 = fiCall(FiWord, l0->X11__LT__LT_, T4, T5);
        T5 = fiCall(FiWord, l0->X5_string, (FiWord) " = 5");
        T4 = fiCall(FiWord, l0->X6__LT__LT_, T4, T5);
        T5 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X8_newline);
        fiCall(FiWord, l0->X7__LT__LT_, T4, T5);
        T4 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X9_print);
        T5 = fiCall(FiWord, l0->X10_integer, (FiWord) "3");
        T5 = CF4_g(e0, (FiWord) T5);
        T4 = fiCall(FiWord, l0->X11__LT__LT_, T4, T5);
        T5 = fiCall(FiWord, l0->X5_string, (FiWord) " = 5");
        T4 = fiCall(FiWord, l0->X6__LT__LT_, T4, T5);
        T5 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X8_newline);
        fiCall(FiWord, l0->X7__LT__LT_, T4, T5);
        T4 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X9_print);
        T5 = fiCall(FiWord, l0->X10_integer, (FiWord) "2");
        T5 = CF5_h(e0, (FiWord) T5);
        T4 = fiCall(FiWord, l0->X11__LT__LT_, T4, T5);
        T5 = fiCall(FiWord, l0->X5_string, (FiWord) " = 1003");
        T4 = fiCall(FiWord, l0->X6__LT__LT_, T4, T5);
        T5 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X8_newline);
        fiCall(FiWord, l0->X7__LT__LT_, T4, T5);
        T4 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X9_print);
        T5 = fiCall(FiWord, l0->X10_integer, (FiWord) "3");
        T5 = CF5_h(e0, (FiWord) T5);
        T4 = fiCall(FiWord, l0->X11__LT__LT_, T4, T5);
        T5 = fiCall(FiWord, l0->X5_string, (FiWord) " = 1002");
        T4 = fiCall(FiWord, l0->X6__LT__LT_, T4, T5);
        T5 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X8_newline);
        fiCall(FiWord, l0->X7__LT__LT_, T4, T5);
        return ;
}

static struct _FiProg  tmp0_funvar = {
        (FiFun) CF0_funvar,
        0L,
        0L,
        0L
};


static FiWord
CF1_f0(FiEnv e1, FiWord P0_n)
{
        return P0_n;
}

static struct _FiProg  tmp1_f0 = {
        (FiFun) CF1_f0,
        0L,
        0L,
        0L
};


static FiWord
CF2_f1(FiEnv e1, FiWord P0_n)
{
        FiWord T0;
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        T0 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X14_1);
        return fiCall(FiWord, l1->X12__PLUS_, P0_n, T0);
}

static struct _FiProg  tmp2_f1 = {
        (FiFun) CF2_f1,
        0L,
        0L,
        0L
};


static FiWord
CF3_f2(FiEnv e1, FiWord P0_n)
{
        FiWord T0;
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        T0 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X14_1);
        return fiCall(FiWord, l1->X13__MINUS_, P0_n, T0);
}

static struct _FiProg  tmp3_f2 = {
        (FiFun) CF3_f2,
        0L,
        0L,
        0L
};


static FiWord
CF4_g(FiEnv e1, FiWord P0_n)
{
        FiWord T0, T1;
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if ((FiBool) fiCall(FiWord, l1->X15_even_QMARK_, P0_n)) goto L0;
        l1->X0_f = (FiClos) G_BNG6U_funvar__f2__847847226;
        goto L1;
L0:	l1->X0_f = (FiClos) G_LJT1F_funvar__f1__847847226;
L1:	T0 = CF1_f0(e1, (FiWord) P0_n);
        T1 = fiCall(FiWord, l1->X0_f, P0_n);
        return fiCall(FiWord, l1->X12__PLUS_, T0, T1);
}

static struct _FiProg  tmp4_g = {
        (FiFun) CF4_g,
        0L,
        0L,
        0L
};


static FiWord
CF5_h(FiEnv e1, FiWord P0_n)
{
        FiWord T1;
        FiClos T0;
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        T1 = fiCall(FiWord, l1->X10_integer, (FiWord) "1000");
        P0_n = fiCall(FiWord, l1->X12__PLUS_, P0_n, T1);
        if ((FiBool) fiCall(FiWord, l1->X15_even_QMARK_, P0_n)) goto L0;
        T0 = (FiClos) G_BNG6U_funvar__f2__847847226;
        goto L1;
L0:	T0 = (FiClos) G_LJT1F_funvar__f1__847847226;
L1:	return fiCall(FiWord, T0, P0_n);
}

static struct _FiProg  tmp5_h = {
        (FiFun) CF5_h,
        0L,
        0L,
        0L
};


static FiWord
CF6_string_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X20) goto L0;
        l1->X20 = 1L;
        fiCall0(void, (*pG_OGNYK_string));
L0:	return (FiWord) (*pG_OI71W_string__String__90554);
}

static struct _FiProg  tmp6_string_MINUS_init = {
        (FiFun) CF6_string_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF7_char_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X21) goto L0;
        l1->X21 = 1L;
        fiCall0(void, (*pG_AKTR8_char));
L0:	return (FiWord) (*pG_PRTGD_char__Character__7004);
}

static struct _FiProg  tmp7_char_MINUS_init = {
        (FiFun) CF7_char_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF8_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X22) goto L0;
        l1->X22 = 1L;
        fiCall0(void, (*pG_EC2QI_textwrit));
L0:	return (FiWord) (*pG_Z4122_textwrit__TextWriter);
}

static struct _FiProg  tmp8_textwrit_MINUS_init = {
        (FiFun) CF8_textwrit_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF9_integer_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X23) goto L0;
        l1->X23 = 1L;
        fiCall0(void, (*pG_WJ27Y_integer));
L0:	return (FiWord) (*pG_C26T4_integer__Integer__244);
}

static struct _FiProg  tmp9_integer_MINUS_init = {
        (FiFun) CF9_integer_MINUS_init,
        0L,
        0L,
        0L
};

extern int
INIT__0_funvar(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_integer(void);
        extern int INIT__0_textwrit(void);
        extern int INIT__0_char(void);
        extern int INIT__0_string(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_f0 = &tmp1_f0;
        C2_f1 = &tmp2_f1;
        C3_f2 = &tmp3_f2;
        C4_g = &tmp4_g;
        C5_h = &tmp5_h;
        C6_string_MINUS_init = &tmp6_string_MINUS_init;
        C7_char_MINUS_init = &tmp7_char_MINUS_init;
        C8_textwrit_MINUS_init = &tmp8_textwrit_MINUS_init;
        C9_integer_MINUS_init = &tmp9_integer_MINUS_init;
        C0_funvar = &tmp0_funvar;
        fiExportGlobal("G_CK2SY_funvar", G_CK2SY_funvar);
        fiExportGlobal("G_O1A90_funvar__h__847847226", 
        	G_O1A90_funvar__h__847847226);
        fiExportGlobal("G_BY8SG_funvar__g__847847226", 
        	G_BY8SG_funvar__g__847847226);
        fiExportGlobal("G_BNG6U_funvar__f2__847847226", 
        	G_BNG6U_funvar__f2__847847226);
        fiExportGlobal("G_LJT1F_funvar__f1__847847226", 
        	G_LJT1F_funvar__f1__847847226);
        fiExportGlobal("G_B7KX9_funvar__f0__847847226", 
        	G_B7KX9_funvar__f0__847847226);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_C26T4_integer__Integer__2448", 
        	pG_C26T4_integer__Integer__244);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_QRAZA_rtDelayedGetExport", 
        	pG_QRAZA_rtDelayedGetExport);
        fiImportGlobal("G_DLXW8_stdGetWordWordRetWord0", 
        	pG_DLXW8_stdGetWordWordRetWord);
        fiImportGlobal("G_ZZZKG_stdGetWordRetWord0", 
        	pG_ZZZKG_stdGetWordRetWord0);
        fiImportGlobal("G_Z4122_textwrit__TextWriter__", 
        	pG_Z4122_textwrit__TextWriter);
        fiImportGlobal("G_OI71W_string__String__905549", 
        	pG_OI71W_string__String__90554);
        fiImportGlobal("G_PRTGD_char__Character__70042", 
        	pG_PRTGD_char__Character__7004);
        fiImportGlobal("G_OGNYK_string", pG_OGNYK_string);
        fiImportGlobal("G_AKTR8_char", pG_AKTR8_char);
        fiImportGlobal("G_EC2QI_textwrit", pG_EC2QI_textwrit);
        fiImportGlobal("G_WJ27Y_integer", pG_WJ27Y_integer);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("integer");
                fiFileInitializer("textwrit");
                fiFileInitializer("char");
                fiFileInitializer("string");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_integer();
                INIT__0_textwrit();
                INIT__0_char();
                INIT__0_string();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}

FiClos G_B7KX9_funvar__f0__847847226;
FiClos G_LJT1F_funvar__f1__847847226;
FiClos G_BNG6U_funvar__f2__847847226;
FiClos G_BY8SG_funvar__g__847847226;
FiClos G_O1A90_funvar__h__847847226;

static struct _FiClos  tmpClos0_funvar = {
        0L,
        (FiProg) &tmp0_funvar
};
FiClos G_CK2SY_funvar = &tmpClos0_funvar;
