/*
 * C code generated by Aldor from file "l00p.as".
 */

#include "foam_c.h"

typedef struct Fmt5  *PFmt5;
typedef struct Fmt6  *PFmt6;
typedef struct Fmt7  *PFmt7;
struct Fmt5 {
        FiClos X0_done_QMARK_;
        FiClos X1_step_BANG_;
        FiClos X2_value;
        FiClos X3_bound;
};
struct Fmt6 {
        FiClos X0_getter;
        FiBool X1_flag;
        FiClos X2_self;
};
struct Fmt7 {
        FiWord X0_Boolean;
        FiClos X1_Segment;
        FiWord X2_Integer;
        FiWord X3_Character;
        FiWord X4_TextWriter;
        FiWord X5_true;
        FiClos X6__LT__LT_;
        FiWord X7_newline;
        FiWord X8_print;
        FiClos X9__DOT__DOT_;
        FiClos X10_generator;
        FiClos X11_integer;
        FiClos X12__LT__LT_;
        FiClos X13__GT_;
        FiClos X14__LT__EQ_;
        FiWord X15_0;
        FiClos X16__PLUS_;
        FiClos X17__MINUS_;
        FiWord X18_1;
        FiClos X19__STAR_;
        FiWord X20_dom;
        FiWord X21_dom;
        FiWord X22_dom;
        FiClos X23_ClosedSegment;
        FiWord X24_dom;
        FiWord X25_dom;
        FiBool X26;
        FiBool X27;
        FiBool X28;
        FiBool X29;
        FiBool X30;
};
static FiProg C0_l00p;
static void CF0_l00p(FiEnv e1);
static FiProg C1_pow1;
static FiWord CF1_pow1(FiEnv e1, FiWord P0_i, FiWord P1_j);
static FiProg C2_pow2;
static FiWord CF2_pow2(FiEnv e1, FiWord P0_i, FiWord P1_j);
static FiProg C3_pow3;
static FiWord CF3_pow3(FiEnv e1, FiWord P0_i, FiWord P1_j);
static FiProg C4_pow4;
static FiWord CF4_pow4(FiEnv e1, FiWord P0_i, FiWord P1_j);
static FiProg C5_lazyFnGetter;
static FiClos CF5_lazyFnGetter(FiEnv e1, FiWord P0_init);
static FiProg C6_lazyGetter;
static FiClos CF6_lazyGetter(FiEnv e1, FiWord P0_a);
static FiProg C7_lazyGetter2;
static void CF7_lazyGetter2(FiEnv e1);
static FiProg C8_char_MINUS_init;
static FiWord CF8_char_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C9_textwrit_MINUS_init;
static FiWord CF9_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C10_integer_MINUS_init;
static FiWord CF10_integer_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C11_segment_MINUS_init;
static FiWord CF11_segment_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C12_boolean_MINUS_init;
static FiWord CF12_boolean_MINUS_init(FiEnv e1, FiSInt P0_idx);
#define fiCallSpecial0(fn,a1,a2,a3,a4) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3,a4))

#define fiCallSpecial1(fn,a1,a2,a3,a4) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3,a4))

#define fiCallSpecial2(fn,a1,a2,a3,a4) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3,a4))

extern FiClos G_7WJSD_l00p;
static FiClos *pG_NQYQM_noOperation;
extern FiClos G_LFBYH_l00p__pow4__933001063;
extern FiClos G_L80G1_l00p__pow3__933001063;
extern FiClos G_NNRQ5_l00p__pow2__933001063;
extern FiClos G_YRWWR_l00p__pow1__933001063;
static FiClos *pG_XIPRL_runtime;
static FiWord *pG_C26T4_integer__Integer__244;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_LD0B5_domainHash_BANG_;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiWord *pG_9B9PO_boolean__Boolean__545;
static FiClos *pG_QRAZA_rtDelayedGetExport;
static FiClos *pG_DLXW8_stdGetWordWordRetWord;
static FiClos *pG_NYJZQ_segment__Segment__234;
static FiClos *pG_RSHLY_rtDelayedInit_BANG_;
static FiClos *pG_ZZZKG_stdGetWordRetWord0;
static FiClos *pG_MN6X6_segment__ClosedSegmen;
static FiWord *pG_Z4122_textwrit__TextWriter;
static FiWord *pG_PRTGD_char__Character__7004;
static FiClos *pG_AKTR8_char;
static FiClos *pG_EC2QI_textwrit;
static FiClos *pG_WJ27Y_integer;
static FiClos *pG_WVJG4_segment;
static FiClos *pG_P63GL_boolean;



static void
CF0_l00p(FiEnv e1)
{
        FiWord T7, T8, T9;
        FiClos T0, T1, T2, T5, T6;
        FiSInt T3, T4;
        PFmt7 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt7 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCall0(void, (*pG_XIPRL_runtime));
        G_7WJSD_l00p = (FiClos) (*pG_NQYQM_noOperation);
        T0 = fiClosMake(e0, C10_integer_MINUS_init);
        T1 = fiClosMake(e0, C12_boolean_MINUS_init);
        G_YRWWR_l00p__pow1__933001063 = fiClosMake(e0, C1_pow1);
        G_NNRQ5_l00p__pow2__933001063 = fiClosMake(e0, C2_pow2);
        T2 = fiClosMake(e0, C11_segment_MINUS_init);
        G_L80G1_l00p__pow3__933001063 = fiClosMake(e0, C3_pow3);
        G_LFBYH_l00p__pow4__933001063 = fiClosMake(e0, C4_pow4);
        T5 = fiClosMake(e0, C9_textwrit_MINUS_init);
        T6 = fiClosMake(e0, C8_char_MINUS_init);
        l0->X26 = 0L;
        l0->X27 = 0L;
        l0->X28 = 0L;
        l0->X29 = 0L;
        l0->X30 = 0L;
        l0->X2_Integer = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), T0, 
        	0L);
        l0->X20_dom = l0->X2_Integer;
        l0->X18_1 = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), l0->
        	X20_dom, 200090L, 484208045L);
        l0->X15_0 = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), l0->
        	X20_dom, 200089L, 484208045L);
        l0->X0_Boolean = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), T1, 
        	0L);
        T7 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X20_dom, 
        	200103L, -1296727158L);
        l0->X13__GT_ = fiCall(FiClos, (*pG_DLXW8_stdGetWordWordRetWord), 
        	T7);
        T7 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X20_dom, 
        	200083L, 2104366580L);
        l0->X19__STAR_ = fiCall(FiClos, (*pG_DLXW8_stdGetWordWordRetWord), 
        	T7);
        T7 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X20_dom, 
        	200086L, 2104366580L);
        l0->X17__MINUS_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T7);
        l0->X21_dom = l0->X0_Boolean;
        l0->X5_true = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X21_dom, 11137124L, 740244383L);
        T7 = fiCall(FiWord, (*pG_RSHLY_rtDelayedInit_BANG_), T2, 0L);
        l0->X1_Segment = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T7);
        l0->X22_dom = fiCall(FiWord, l0->X1_Segment, l0->X2_Integer);
        T7 = fiCall(FiWord, (*pG_RSHLY_rtDelayedInit_BANG_), T2, 1L);
        l0->X23_ClosedSegment = fiCall(FiClos, (*
        	pG_ZZZKG_stdGetWordRetWord0), T7);
        fiEnvEnsure(l0->X23_ClosedSegment->env);
        T3 = 1522410237L;
L1:	l0->X10_generator = CF5_lazyFnGetter(e0, (FiWord) fiCall(FiWord, (*
        	pG_QRAZA_rtDelayedGetExport), l0->X22_dom, 113320568L, 
        	fiAldorHash32Combine((FiSInt) -1409278289L, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) 32236L, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) T3, (FiSInt) 51489085L)))));
        fiEnvEnsure(l0->X23_ClosedSegment->env);
        T4 = 1522410237L;
L3:	T7 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X22_dom, 
        	51488814L, fiAldorHash32Combine((FiSInt) T4, (FiSInt) 
        	149976849L));
        l0->X9__DOT__DOT_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T7);
        T7 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X20_dom, 
        	477900237L, 128860016L);
        l0->X11_integer = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T7);
        T7 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X20_dom, 
        	200084L, 2104366580L);
        l0->X16__PLUS_ = fiCall(FiClos, (*pG_DLXW8_stdGetWordWordRetWord), 
        	T7);
        T7 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X20_dom, 
        	51492427L, -1296727158L);
        l0->X14__LT__EQ_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T7);
        l0->X4_TextWriter = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T5, 0L);
        l0->X24_dom = l0->X4_TextWriter;
        l0->X8_print = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X24_dom, 828947258L, 182752316L);
        T7 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X20_dom, 
        	51492426L, -2075677734L);
        l0->X12__LT__LT_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T7);
        l0->X3_Character = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T6, 0L);
        l0->X25_dom = l0->X3_Character;
        l0->X7_newline = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X25_dom, 493486801L, 803414590L);
        T7 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X25_dom, 
        	51492426L, 936629095L);
        l0->X6__LT__LT_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T7);
        T7 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X8_print);
        T8 = fiCall(FiWord, l0->X11_integer, (FiWord) "3");
        T9 = fiCall(FiWord, l0->X11_integer, (FiWord) "4");
        T8 = CF1_pow1(e0, (FiWord) T8, (FiWord) T9);
        T7 = fiCall(FiWord, l0->X12__LT__LT_, T7, T8);
        T8 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X7_newline);
        fiCall(FiWord, l0->X6__LT__LT_, T7, T8);
        T7 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X8_print);
        T8 = fiCall(FiWord, l0->X11_integer, (FiWord) "3");
        T9 = fiCall(FiWord, l0->X11_integer, (FiWord) "4");
        T8 = CF2_pow2(e0, (FiWord) T8, (FiWord) T9);
        T7 = fiCall(FiWord, l0->X12__LT__LT_, T7, T8);
        T8 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X7_newline);
        fiCall(FiWord, l0->X6__LT__LT_, T7, T8);
        T7 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X8_print);
        T8 = fiCall(FiWord, l0->X11_integer, (FiWord) "3");
        T9 = fiCall(FiWord, l0->X11_integer, (FiWord) "4");
        T8 = CF3_pow3(e0, (FiWord) T8, (FiWord) T9);
        T7 = fiCall(FiWord, l0->X12__LT__LT_, T7, T8);
        T8 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X7_newline);
        fiCall(FiWord, l0->X6__LT__LT_, T7, T8);
        T7 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X8_print);
        T8 = fiCall(FiWord, l0->X11_integer, (FiWord) "3");
        T9 = fiCall(FiWord, l0->X11_integer, (FiWord) "4");
        T8 = CF4_pow4(e0, (FiWord) T8, (FiWord) T9);
        T7 = fiCall(FiWord, l0->X12__LT__LT_, T7, T8);
        T8 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X7_newline);
        fiCall(FiWord, l0->X6__LT__LT_, T7, T8);
        return ;
L2:	T7 = fiCall(FiWord, l0->X23_ClosedSegment, l0->X2_Integer);
        T4 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), T7);
        goto L3;
L0:	T7 = fiCall(FiWord, l0->X23_ClosedSegment, l0->X2_Integer);
        T3 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), T7);
        goto L1;
}

static struct _FiProg  tmp0_l00p = {
        (FiFun) CF0_l00p,
        0L,
        0L,
        0L
};


static FiWord
CF1_pow1(FiEnv e1, FiWord P0_i, FiWord P1_j)
{
        FiWord T0_prod, T1;
        PFmt7 l1;
        l1 = (PFmt7) fiEnvLevel(e1);
        T0_prod = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X18_1);
        goto L1;
L0:	T0_prod = fiCall(FiWord, l1->X19__STAR_, P0_i, T0_prod);
        T1 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X18_1);
        P1_j = fiCall(FiWord, l1->X17__MINUS_, P1_j, T1);
L1:	T1 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X15_0);
        if (!(FiBool) fiCall(FiWord, l1->X13__GT_, P1_j, T1)) goto L2;
        goto L0;
L2:	return T0_prod;
}

static struct _FiProg  tmp1_pow1 = {
        (FiFun) CF1_pow1,
        0L,
        0L,
        0L
};


static FiWord
CF2_pow2(FiEnv e1, FiWord P0_i, FiWord P1_j)
{
        FiWord T0_prod, T1;
        PFmt7 l1;
        l1 = (PFmt7) fiEnvLevel(e1);
        T0_prod = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X18_1);
        goto L1;
L0:	T1 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X18_1);
        P1_j = fiCall(FiWord, l1->X17__MINUS_, P1_j, T1);
L1:	T1 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X15_0);
        if (!(FiBool) fiCall(FiWord, l1->X13__GT_, P1_j, T1)) goto L2;
        T0_prod = fiCall(FiWord, l1->X19__STAR_, P0_i, T0_prod);
        if (!(FiBool) fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->
        	X5_true)) goto L2;
        goto L0;
L2:	return T0_prod;
}

static struct _FiProg  tmp2_pow2 = {
        (FiFun) CF2_pow2,
        0L,
        0L,
        0L
};


static FiWord
CF3_pow3(FiEnv e1, FiWord P0_i, FiWord P1_j)
{
        FiClos T1, T2, T3, T4, T6;
        FiWord T0_prod, T5;
        PFmt7 l1;
        l1 = (PFmt7) fiEnvLevel(e1);
        T0_prod = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X18_1);
        T5 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X18_1);
        T5 = fiCall(FiWord, l1->X9__DOT__DOT_, T5, P1_j);
        T6 = fiCall(FiClos, l1->X10_generator, T5);
        fiCallSpecial0(T6, &T1, &T2, &T3, &T4);
L1:	fiCall0(void, T2);
        if ((FiBool) fiCall0(FiWord, T1)) goto L2;
        fiCall0(FiWord, T3);
        T0_prod = fiCall(FiWord, l1->X19__STAR_, P0_i, T0_prod);
        goto L1;
L2:	return T0_prod;
}

static struct _FiProg  tmp3_pow3 = {
        (FiFun) CF3_pow3,
        0L,
        0L,
        0L
};


static FiWord
CF4_pow4(FiEnv e1, FiWord P0_i, FiWord P1_j)
{
        FiClos T3, T4, T5, T6, T7, T8, T9, T10, T13;
        FiWord T0_prod, T1_k, T2_h, T11, T12;
        PFmt7 l1;
        l1 = (PFmt7) fiEnvLevel(e1);
        T0_prod = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X18_1);
        T11 = fiCall(FiWord, l1->X11_integer, (FiWord) "2");
        T12 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X18_1);
        T12 = fiCall(FiWord, l1->X16__PLUS_, P1_j, T12);
        T11 = fiCall(FiWord, l1->X9__DOT__DOT_, T11, T12);
        T13 = fiCall(FiClos, l1->X10_generator, T11);
        fiCallSpecial1(T13, &T3, &T4, &T5, &T6);
        T11 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X18_1);
        T11 = fiCall(FiWord, l1->X9__DOT__DOT_, T11, P1_j);
        T13 = fiCall(FiClos, l1->X10_generator, T11);
        fiCallSpecial2(T13, &T7, &T8, &T9, &T10);
L1:	fiCall0(void, T4);
        if ((FiBool) fiCall0(FiWord, T3)) goto L2;
        T2_h = fiCall0(FiWord, T5);
        fiCall0(void, T8);
        if ((FiBool) fiCall0(FiWord, T7)) goto L2;
        T1_k = fiCall0(FiWord, T9);
        if ((FiBool) fiCall(FiWord, l1->X13__GT_, T2_h, T1_k)) goto L3;
        goto L1;
L3:	if (!(FiBool) fiCall(FiWord, l1->X14__LT__EQ_, T1_k, T2_h)) goto L2;
        T0_prod = fiCall(FiWord, l1->X19__STAR_, P0_i, T0_prod);
        goto L1;
L2:	return T0_prod;
}

static struct _FiProg  tmp4_pow4 = {
        (FiFun) CF4_pow4,
        0L,
        0L,
        0L
};


static FiClos
CF5_lazyFnGetter(FiEnv e1, FiWord P0_init)
{
        PFmt6 l0;
        FiEnv e0;
        PFmt7 l1;
        l0 = fi0New(struct Fmt6 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        l1 = (PFmt7) fiEnvLevel(e1);
        l0->X0_getter = (FiClos) P0_init;
        l0->X1_flag = 0L;
        l0->X2_self = fiClosMake(e0, C6_lazyGetter);
        fiEnvInfo(e0) = (FiWord) fiClosMake(e0, C7_lazyGetter2);
        return l0->X2_self;
}

static struct _FiProg  tmp5_lazyFnGetter = {
        (FiFun) CF5_lazyFnGetter,
        0L,
        0L,
        0L
};


static FiClos
CF6_lazyGetter(FiEnv e1, FiWord P0_a)
{
        FiClos T0;
        PFmt6 l1;
        PFmt7 l2;
        FiEnv e2;
        l1 = (PFmt6) fiEnvLevel(e1);
        e2 = fiEnvNext(e1);
        l2 = (PFmt7) fiEnvLevel(e2);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCall0(FiWord, l1->X0_getter);
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        l1->X1_flag = 1L;
L0:	return fiCall(FiClos, l1->X2_self, P0_a);
}

static struct _FiProg  tmp6_lazyGetter = {
        (FiFun) CF6_lazyGetter,
        0L,
        0L,
        0L
};


static void
CF7_lazyGetter2(FiEnv e1)
{
        FiClos T0;
        PFmt6 l1;
        PFmt7 l2;
        FiEnv e2;
        l1 = (PFmt6) fiEnvLevel(e1);
        e2 = fiEnvNext(e1);
        l2 = (PFmt7) fiEnvLevel(e2);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCall0(FiWord, l1->X0_getter);
        l1->X1_flag = 1L;
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        fiEnvInfo(e1) = (FiWord) fiNil;
L0:	return ;
}

static struct _FiProg  tmp7_lazyGetter2 = {
        (FiFun) CF7_lazyGetter2,
        0L,
        0L,
        0L
};


static FiWord
CF8_char_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt7 l1;
        l1 = (PFmt7) fiEnvLevel(e1);
        if (l1->X26) goto L0;
        l1->X26 = 1L;
        fiCall0(void, (*pG_AKTR8_char));
L0:	return (FiWord) (*pG_PRTGD_char__Character__7004);
}

static struct _FiProg  tmp8_char_MINUS_init = {
        (FiFun) CF8_char_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF9_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt7 l1;
        l1 = (PFmt7) fiEnvLevel(e1);
        if (l1->X27) goto L0;
        l1->X27 = 1L;
        fiCall0(void, (*pG_EC2QI_textwrit));
L0:	return (FiWord) (*pG_Z4122_textwrit__TextWriter);
}

static struct _FiProg  tmp9_textwrit_MINUS_init = {
        (FiFun) CF9_textwrit_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF10_integer_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt7 l1;
        l1 = (PFmt7) fiEnvLevel(e1);
        if (l1->X28) goto L0;
        l1->X28 = 1L;
        fiCall0(void, (*pG_WJ27Y_integer));
L0:	return (FiWord) (*pG_C26T4_integer__Integer__244);
}

static struct _FiProg  tmp10_integer_MINUS_init = {
        (FiFun) CF10_integer_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF11_segment_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt7 l1;
        l1 = (PFmt7) fiEnvLevel(e1);
        if (l1->X29) goto L0;
        l1->X29 = 1L;
        fiCall0(void, (*pG_WVJG4_segment));
L0:	if (P0_idx != 1L) goto L1;
        return (FiWord) (*pG_MN6X6_segment__ClosedSegmen);
L1:	return (FiWord) (*pG_NYJZQ_segment__Segment__234);
}

static struct _FiProg  tmp11_segment_MINUS_init = {
        (FiFun) CF11_segment_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF12_boolean_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt7 l1;
        l1 = (PFmt7) fiEnvLevel(e1);
        if (l1->X30) goto L0;
        l1->X30 = 1L;
        fiCall0(void, (*pG_P63GL_boolean));
L0:	return (FiWord) (*pG_9B9PO_boolean__Boolean__545);
}

static struct _FiProg  tmp12_boolean_MINUS_init = {
        (FiFun) CF12_boolean_MINUS_init,
        0L,
        0L,
        0L
};

extern int
INIT__0_l00p(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_boolean(void);
        extern int INIT__0_segment(void);
        extern int INIT__0_integer(void);
        extern int INIT__0_textwrit(void);
        extern int INIT__0_char(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_pow1 = &tmp1_pow1;
        C2_pow2 = &tmp2_pow2;
        C3_pow3 = &tmp3_pow3;
        C4_pow4 = &tmp4_pow4;
        C5_lazyFnGetter = &tmp5_lazyFnGetter;
        C6_lazyGetter = &tmp6_lazyGetter;
        C7_lazyGetter2 = &tmp7_lazyGetter2;
        C8_char_MINUS_init = &tmp8_char_MINUS_init;
        C9_textwrit_MINUS_init = &tmp9_textwrit_MINUS_init;
        C10_integer_MINUS_init = &tmp10_integer_MINUS_init;
        C11_segment_MINUS_init = &tmp11_segment_MINUS_init;
        C12_boolean_MINUS_init = &tmp12_boolean_MINUS_init;
        C0_l00p = &tmp0_l00p;
        fiExportGlobal("G_7WJSD_l00p", G_7WJSD_l00p);
        fiExportGlobal("G_LFBYH_l00p__pow4__933001063", 
        	G_LFBYH_l00p__pow4__933001063);
        fiExportGlobal("G_L80G1_l00p__pow3__933001063", 
        	G_L80G1_l00p__pow3__933001063);
        fiExportGlobal("G_NNRQ5_l00p__pow2__933001063", 
        	G_NNRQ5_l00p__pow2__933001063);
        fiExportGlobal("G_YRWWR_l00p__pow1__933001063", 
        	G_YRWWR_l00p__pow1__933001063);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_C26T4_integer__Integer__2448", 
        	pG_C26T4_integer__Integer__244);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_LD0B5_domainHash_BANG_", pG_LD0B5_domainHash_BANG_);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_9B9PO_boolean__Boolean__5458", 
        	pG_9B9PO_boolean__Boolean__545);
        fiImportGlobal("G_QRAZA_rtDelayedGetExport", 
        	pG_QRAZA_rtDelayedGetExport);
        fiImportGlobal("G_DLXW8_stdGetWordWordRetWord0", 
        	pG_DLXW8_stdGetWordWordRetWord);
        fiImportGlobal("G_NYJZQ_segment__Segment__2349", 
        	pG_NYJZQ_segment__Segment__234);
        fiImportGlobal("G_RSHLY_rtDelayedInit_BANG_", 
        	pG_RSHLY_rtDelayedInit_BANG_);
        fiImportGlobal("G_ZZZKG_stdGetWordRetWord0", 
        	pG_ZZZKG_stdGetWordRetWord0);
        fiImportGlobal("G_MN6X6_segment__ClosedSegment", 
        	pG_MN6X6_segment__ClosedSegmen);
        fiImportGlobal("G_Z4122_textwrit__TextWriter__", 
        	pG_Z4122_textwrit__TextWriter);
        fiImportGlobal("G_PRTGD_char__Character__70042", 
        	pG_PRTGD_char__Character__7004);
        fiImportGlobal("G_AKTR8_char", pG_AKTR8_char);
        fiImportGlobal("G_EC2QI_textwrit", pG_EC2QI_textwrit);
        fiImportGlobal("G_WJ27Y_integer", pG_WJ27Y_integer);
        fiImportGlobal("G_WVJG4_segment", pG_WVJG4_segment);
        fiImportGlobal("G_P63GL_boolean", pG_P63GL_boolean);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("boolean");
                fiFileInitializer("segment");
                fiFileInitializer("integer");
                fiFileInitializer("textwrit");
                fiFileInitializer("char");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_boolean();
                INIT__0_segment();
                INIT__0_integer();
                INIT__0_textwrit();
                INIT__0_char();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}

FiClos G_YRWWR_l00p__pow1__933001063;
FiClos G_NNRQ5_l00p__pow2__933001063;
FiClos G_L80G1_l00p__pow3__933001063;
FiClos G_LFBYH_l00p__pow4__933001063;

static struct _FiClos  tmpClos0_l00p = {
        0L,
        (FiProg) &tmp0_l00p
};
FiClos G_7WJSD_l00p = &tmpClos0_l00p;
