/*
 * C code generated by Aldor from file "lit0.as".
 */

#include "foam_c.h"

typedef struct Fmt5  *PFmt5;
struct Fmt5 {
        FiWord X0_Integer;
        FiWord X1_String;
        FiWord X2_SingleFloat;
        FiWord X3_DoubleFloat;
        FiClos X4_string;
        FiClos X5_integer;
        FiWord X6_0;
        FiWord X7_0;
        FiClos X8_float;
        FiClos X9_float;
        FiWord X10_dom;
        FiWord X11_dom;
        FiWord X12_dom;
        FiWord X13_dom;
        FiBool X14;
        FiBool X15;
        FiBool X16;
        FiBool X17;
};
static FiProg C0_lit0;
static void CF0_lit0(FiEnv e1);
static FiProg C1_string_MINUS_init;
static FiWord CF1_string_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C2_dfloat_MINUS_init;
static FiWord CF2_dfloat_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C3_integer_MINUS_init;
static FiWord CF3_integer_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C4_sfloat_MINUS_init;
static FiWord CF4_sfloat_MINUS_init(FiEnv e1, FiSInt P0_idx);
extern FiClos G_AREQY_lit0;
static FiClos *pG_NQYQM_noOperation;
extern FiWord G_X2C6B_lit0__s2__526496392;
extern FiWord G_G2DXI_lit0__s1__526496392;
extern FiWord G_TXBSU_lit0__s0__526496392;
extern FiWord G_7ZGWE_lit0__gx__754279279;
extern FiWord G_W73CK_lit0__g2__754279279;
extern FiWord G_CE2MT_lit0__g0__754279279;
extern FiWord G_MLOJ_lit0__fx__130771574;
extern FiWord G_MNSN9_lit0__f2__130771574;
extern FiWord G_8AHH0_lit0__f0__130771574;
extern FiWord G_EPV4R_lit0__i2__425461576;
extern FiWord G_PBYE8_lit0__i0__425461576;
static FiClos *pG_XIPRL_runtime;
static FiWord *pG_C26T4_integer__Integer__244;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiClos *pG_QRAZA_rtDelayedGetExport;
static FiClos *pG_ZZZKG_stdGetWordRetWord0;
static FiWord *pG_MNALG_sfloat__SingleFloat__;
static FiWord *pG_STDSR_dfloat__DoubleFloat__;
static FiWord *pG_OI71W_string__String__90554;
static FiClos *pG_OGNYK_string;
static FiClos *pG_DEGQL_dfloat;
static FiClos *pG_WJ27Y_integer;
static FiClos *pG_T13QO_sfloat;



static void
CF0_lit0(FiEnv e1)
{
        FiWord T4;
        FiClos T0, T1, T2, T3;
        PFmt5 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt5 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCall0(void, (*pG_XIPRL_runtime));
        G_AREQY_lit0 = (FiClos) (*pG_NQYQM_noOperation);
        T0 = fiClosMake(e0, C3_integer_MINUS_init);
        T1 = fiClosMake(e0, C4_sfloat_MINUS_init);
        T2 = fiClosMake(e0, C2_dfloat_MINUS_init);
        T3 = fiClosMake(e0, C1_string_MINUS_init);
        l0->X14 = 0L;
        l0->X15 = 0L;
        l0->X16 = 0L;
        l0->X17 = 0L;
        l0->X0_Integer = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), T0, 
        	0L);
        l0->X10_dom = l0->X0_Integer;
        l0->X6_0 = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), l0->
        	X10_dom, 200089L, 484208045L);
        G_PBYE8_lit0__i0__425461576 = fiCall(FiWord, (*
        	pG_R3D1K_lazyForceImport), l0->X6_0);
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X10_dom, 
        	477900237L, 128860016L);
        l0->X5_integer = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T4);
        G_EPV4R_lit0__i2__425461576 = fiCall(FiWord, l0->X5_integer, (
        	FiWord) "2");
        l0->X2_SingleFloat = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T1, 0L);
        l0->X11_dom = l0->X2_SingleFloat;
        l0->X7_0 = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), l0->
        	X11_dom, 200089L, 189518043L);
        G_8AHH0_lit0__f0__130771574 = fiCall(FiWord, (*
        	pG_R3D1K_lazyForceImport), l0->X7_0);
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X11_dom, 
        	474568739L, 727880786L);
        l0->X8_float = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), T4);
        G_MNSN9_lit0__f2__130771574 = fiCall(FiWord, l0->X8_float, (
        	FiWord) "2.0");
        G_MLOJ_lit0__fx__130771574 = fiCall(FiWord, l0->X8_float, (
        	FiWord) ".0000000000111");
        l0->X3_DoubleFloat = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T2, 0L);
        l0->X12_dom = l0->X3_DoubleFloat;
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X12_dom, 
        	474568739L, -349802997L);
        l0->X9_float = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), T4);
        G_CE2MT_lit0__g0__754279279 = fiCall(FiWord, l0->X9_float, (
        	FiWord) "0e0");
        G_W73CK_lit0__g2__754279279 = fiCall(FiWord, l0->X9_float, (
        	FiWord) "2.0");
        G_7ZGWE_lit0__gx__754279279 = fiCall(FiWord, l0->X9_float, (
        	FiWord) "16r.FCC0e+1");
        l0->X1_String = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), T3, 
        	0L);
        l0->X13_dom = l0->X1_String;
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X13_dom, 
        	585283853L, -1916843600L);
        l0->X4_string = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T4);
        G_TXBSU_lit0__s0__526496392 = fiCall(FiWord, l0->X4_string, (
        	FiWord) "");
        G_G2DXI_lit0__s1__526496392 = fiCall(FiWord, l0->X4_string, (
        	FiWord) "X");
        G_X2C6B_lit0__s2__526496392 = fiCall(FiWord, l0->X4_string, (
        	FiWord) "Hello There");
        return ;
}

static struct _FiProg  tmp0_lit0 = {
        (FiFun) CF0_lit0,
        0L,
        0L,
        0L
};


static FiWord
CF1_string_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X14) goto L0;
        l1->X14 = 1L;
        fiCall0(void, (*pG_OGNYK_string));
L0:	return (FiWord) (*pG_OI71W_string__String__90554);
}

static struct _FiProg  tmp1_string_MINUS_init = {
        (FiFun) CF1_string_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF2_dfloat_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X15) goto L0;
        l1->X15 = 1L;
        fiCall0(void, (*pG_DEGQL_dfloat));
L0:	return (FiWord) (*pG_STDSR_dfloat__DoubleFloat__);
}

static struct _FiProg  tmp2_dfloat_MINUS_init = {
        (FiFun) CF2_dfloat_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF3_integer_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X16) goto L0;
        l1->X16 = 1L;
        fiCall0(void, (*pG_WJ27Y_integer));
L0:	return (FiWord) (*pG_C26T4_integer__Integer__244);
}

static struct _FiProg  tmp3_integer_MINUS_init = {
        (FiFun) CF3_integer_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF4_sfloat_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X17) goto L0;
        l1->X17 = 1L;
        fiCall0(void, (*pG_T13QO_sfloat));
L0:	return (FiWord) (*pG_MNALG_sfloat__SingleFloat__);
}

static struct _FiProg  tmp4_sfloat_MINUS_init = {
        (FiFun) CF4_sfloat_MINUS_init,
        0L,
        0L,
        0L
};

extern int
INIT__0_lit0(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_sfloat(void);
        extern int INIT__0_integer(void);
        extern int INIT__0_dfloat(void);
        extern int INIT__0_string(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_string_MINUS_init = &tmp1_string_MINUS_init;
        C2_dfloat_MINUS_init = &tmp2_dfloat_MINUS_init;
        C3_integer_MINUS_init = &tmp3_integer_MINUS_init;
        C4_sfloat_MINUS_init = &tmp4_sfloat_MINUS_init;
        C0_lit0 = &tmp0_lit0;
        fiExportGlobal("G_AREQY_lit0", G_AREQY_lit0);
        fiExportGlobal("G_X2C6B_lit0__s2__526496392", 
        	G_X2C6B_lit0__s2__526496392);
        fiExportGlobal("G_G2DXI_lit0__s1__526496392", 
        	G_G2DXI_lit0__s1__526496392);
        fiExportGlobal("G_TXBSU_lit0__s0__526496392", 
        	G_TXBSU_lit0__s0__526496392);
        fiExportGlobal("G_7ZGWE_lit0__gx__754279279", 
        	G_7ZGWE_lit0__gx__754279279);
        fiExportGlobal("G_W73CK_lit0__g2__754279279", 
        	G_W73CK_lit0__g2__754279279);
        fiExportGlobal("G_CE2MT_lit0__g0__754279279", 
        	G_CE2MT_lit0__g0__754279279);
        fiExportGlobal("G_MLOJ_lit0__fx__130771574", 
        	G_MLOJ_lit0__fx__130771574);
        fiExportGlobal("G_MNSN9_lit0__f2__130771574", 
        	G_MNSN9_lit0__f2__130771574);
        fiExportGlobal("G_8AHH0_lit0__f0__130771574", 
        	G_8AHH0_lit0__f0__130771574);
        fiExportGlobal("G_EPV4R_lit0__i2__425461576", 
        	G_EPV4R_lit0__i2__425461576);
        fiExportGlobal("G_PBYE8_lit0__i0__425461576", 
        	G_PBYE8_lit0__i0__425461576);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_C26T4_integer__Integer__2448", 
        	pG_C26T4_integer__Integer__244);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_QRAZA_rtDelayedGetExport", 
        	pG_QRAZA_rtDelayedGetExport);
        fiImportGlobal("G_ZZZKG_stdGetWordRetWord0", 
        	pG_ZZZKG_stdGetWordRetWord0);
        fiImportGlobal("G_MNALG_sfloat__SingleFloat__3", 
        	pG_MNALG_sfloat__SingleFloat__);
        fiImportGlobal("G_STDSR_dfloat__DoubleFloat__7", 
        	pG_STDSR_dfloat__DoubleFloat__);
        fiImportGlobal("G_OI71W_string__String__905549", 
        	pG_OI71W_string__String__90554);
        fiImportGlobal("G_OGNYK_string", pG_OGNYK_string);
        fiImportGlobal("G_DEGQL_dfloat", pG_DEGQL_dfloat);
        fiImportGlobal("G_WJ27Y_integer", pG_WJ27Y_integer);
        fiImportGlobal("G_T13QO_sfloat", pG_T13QO_sfloat);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("sfloat");
                fiFileInitializer("integer");
                fiFileInitializer("dfloat");
                fiFileInitializer("string");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_sfloat();
                INIT__0_integer();
                INIT__0_dfloat();
                INIT__0_string();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}

FiWord G_PBYE8_lit0__i0__425461576;
FiWord G_EPV4R_lit0__i2__425461576;
FiWord G_8AHH0_lit0__f0__130771574;
FiWord G_MNSN9_lit0__f2__130771574;
FiWord G_MLOJ_lit0__fx__130771574;
FiWord G_CE2MT_lit0__g0__754279279;
FiWord G_W73CK_lit0__g2__754279279;
FiWord G_7ZGWE_lit0__gx__754279279;
FiWord G_TXBSU_lit0__s0__526496392;
FiWord G_G2DXI_lit0__s1__526496392;
FiWord G_X2C6B_lit0__s2__526496392;

static struct _FiClos  tmpClos0_lit0 = {
        0L,
        (FiProg) &tmp0_lit0
};
FiClos G_AREQY_lit0 = &tmpClos0_lit0;
