;;;
;;; Lisp code generated by Aldor from file "mandel_t.as".
;;;

(in-package "FOAM-USER" :use '("FOAM" "LISP"))

(declare-prog (|C0-mandel_t-mandel_t|) ((|e1| |Env|)))

(declare-prog
  (|C1-mandel_t-drawMand| |Word|)
  ((|P0-minR| |Word|)
    (|P1-maxR| |Word|)
    (|P2-numR| |Word|)
    (|P3-minI| |Word|)
    (|P4-maxI| |Word|)
    (|P5-numI| |Word|)
    (|e1| |Env|)))

(declare-prog
  (|C2-mandel_t-mandel| |Word|)
  ((|P0-c| |Word|) (|e1| |Env|)))

(declare-prog
  (|C3-mandel_t-drawPoint|)
  ((|P0-x| |Word|) (|P1-y| |Word|) (|P2-n| |Word|) (|e1| |Env|)))

(declare-prog (|C4-mandel_t-endRow|) ((|e1| |Env|)))

(declare-prog
  (|C5-mandel_t-lazyFnGetter| |Clos|)
  ((|P0-init| |Word|) (|e1| |Env|)))

(declare-prog
  (|C6-mandel_t-lazyGetter| |Clos|)
  ((|P0-a| |Word|) (|e1| |Env|)))

(declare-prog (|C7-mandel_t-lazyGetter2|) ((|e1| |Env|)))

(declare-prog
  (|C8-mandel_t-textwrit-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C9-mandel_t-dfloat-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C10-mandel_t-complex-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C11-mandel_t-lazyFnGetter| |Clos|)
  ((|P0-init| |Word|) (|e1| |Env|)))

(declare-prog
  (|C12-mandel_t-lazyGetter| |Clos|)
  ((|P0-a| |Word|) (|e1| |Env|)))

(declare-prog (|C13-mandel_t-lazyGetter2|) ((|e1| |Env|)))

(declare-type |G-mandel_t| |Clos|)

(declare-type |G-mandel_t_drawMand_361523023| |Clos|)

(declare-type |G-mandel_t_drawPoint_326007403| |Clos|)

(declare-type |G-mandel_t_endRow_778822608| |Clos|)

(defspecials
  |G-mandel_t_maxIters_083725344|
  |G-mandel_t_endRow_778822608|
  |G-mandel_t_drawPoint_326007403|
  |G-mandel_t_drawMand_361523023|)

(|DDecl|
  |Struct-mandel_t-8|
  (|getter-0| |Clos|)
  (|flag-1| |Bool|)
  (|self-2| |Clos|))

(|DDecl|
  |Struct-mandel_t-9|
  (|DoubleFloat-0| |Word|)
  (|Complex-1| |Clos|)
  (|TextWriter-2| |Word|)
  (|print-3| |Word|)
  (\0-4 |Word|)
  (|step-5| |Clos|)
  (|dom-6| |Word|)
  (|dom-7| |Word|)
  (|dom-8| |Word|)
  (\-9 |Bool|)
  (\-10 |Bool|)
  (\-11 |Bool|))

(|DDecl| |Struct-mandel_t-14| (|double-0| |DFlo|))

(|DDecl| |Struct-mandel_t-16| (|real-0| |Word|) (|imag-1| |Word|))

(|DDecl|
  |Struct-mandel_t-18|
  (|getter-0| |Clos|)
  (|flag-1| |Bool|)
  (|self-2| |Clos|))

(|DDecl|
  |Struct-mandel_t-21|
  (|RoundingMode-0| |Word|)
  (|Machine-1| |Word|)
  (|FortranDouble-2| |Word|)
  (|FloatingPointNumberSystem-3| |Word|)
  (|OrderedFinite-4| |Word|)
  (|DenseStorageCategory-5| |Word|)
  (|BasicType-6| |Word|)
  (|SingleInteger-7| |Word|)
  (|BinaryPowering-8| |Clos|)
  (|Integer-9| |Word|)
  (|Record-10| |Clos|)
  (|DFlo-11| |Word|)
  (|max-12| |Word|)
  (|min-13| |Word|)
  (|epsilon-14| |Word|)
  (|dom-15| |Word|)
  (|Segment-16| |Clos|)
  (\-17 |Bool|)
  (\-18 |Bool|)
  (\-19 |Bool|)
  (\-20 |Bool|)
  (\-21 |Bool|)
  (\-22 |Bool|)
  (\-23 |Bool|)
  (\-24 |Bool|))

(|DDecl| |Struct-mandel_t-22| (\-0 |Clos|) (\-1 |Clos|) (\-2 |Clos|))

(|DDecl| |Struct-mandel_t-23| (p0-0 |SInt|))

(defprog
  ((|C0-mandel_t-mandel_t|) ((|e1| |Env|)))
  ((t0 |Clos|)
    (t1 |Clos|)
    (t2 |Clos|)
    (t3 |Clos|)
    (t4 |Clos|)
    (t5 |Clos|)
    (t6 |Record|)
    (t7 |Record|)
    (t8 |Record|)
    (t9 |Record|)
    (t10 |Clos|)
    (t11 |Clos|)
    (t12 |Clos|)
    (t13 |Word|)
    (t14 |Word|)
    (t15 |Word|)
    (|T16-double| |DFlo|)
    (|T17-double| |DFlo|)
    (|T18-double| |DFlo|)
    (|l0| |Level|)
    (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-mandel_t-9| |Struct-mandel_t-9|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall| |G-runtime|)
  (setq |G-mandel_t| |G-noOperation|)
  (setq t0 (|Clos| |e0| |C9-mandel_t-dfloat-init|))
  (setq t1 (|Clos| |e0| |C10-mandel_t-complex-init|))
  (setq t2 (|Clos| |e0| |C8-mandel_t-textwrit-init|))
  (setq
    |G-mandel_t_drawMand_361523023|
    (|Clos| |e0| |C1-mandel_t-drawMand|))
  (setq
    |G-mandel_t_drawPoint_326007403|
    (|Clos| |e0| |C3-mandel_t-drawPoint|))
  (setq
    |G-mandel_t_endRow_778822608|
    (|Clos| |e0| |C4-mandel_t-endRow|))
  (|SetLex| |Struct-mandel_t-9--9| 9 |l0| (the |Bool| nil))
  (|SetLex| |Struct-mandel_t-9--10| 10 |l0| (the |Bool| nil))
  (|SetLex| |Struct-mandel_t-9--11| 11 |l0| (the |Bool| nil))
  (setq |G-mandel_t_maxIters_083725344| (the |SInt| 100))
  (|SetLex|
    |Struct-mandel_t-9-DoubleFloat-0|
    0
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t0 (the |SInt| 0)))
  (|SetLex|
    |Struct-mandel_t-9-Complex-1|
    1
    |l0|
    (|CCall|
      |G-stdGetWordRetWord0|
      (|CCall| |G-rtDelayedInit!| t1 (the |SInt| 0))))
  (|SetLex|
    |Struct-mandel_t-9-dom-6|
    6
    |l0|
    (|CCall|
      (|Lex| |Struct-mandel_t-9-Complex-1| 1 |l0|)
      (|Lex| |Struct-mandel_t-9-DoubleFloat-0| 0 |l0|)))
  (|FoamEnvEnsure|
    (|ClosEnv| (|Lex| |Struct-mandel_t-9-Complex-1| 1 |l0|)))
  (|SetLex|
    |Struct-mandel_t-9-0-4|
    4
    |l0|
    (|CCall|
      |G-lazyGetExport!|
      (|Lex| |Struct-mandel_t-9-dom-6| 6 |l0|)
      (the |SInt| 200089)
      (the |SInt| 1616131033)))
  (|FoamEnvEnsure|
    (|ClosEnv| (|Lex| |Struct-mandel_t-9-Complex-1| 1 |l0|)))
  (|SetLex|
    |Struct-mandel_t-9-dom-7|
    7
    |l0|
    (|Lex| |Struct-mandel_t-9-DoubleFloat-0| 0 |l0|))
  (|FoamEnvEnsure|
    (|ClosEnv| (|Lex| |Struct-mandel_t-9-Complex-1| 1 |l0|)))
  (|FoamEnvEnsure|
    (|ClosEnv| (|Lex| |Struct-mandel_t-9-Complex-1| 1 |l0|)))
  (|FoamEnvEnsure|
    (|ClosEnv| (|Lex| |Struct-mandel_t-9-Complex-1| 1 |l0|)))
  (|FoamEnvEnsure|
    (|ClosEnv| (|Lex| |Struct-mandel_t-9-Complex-1| 1 |l0|)))
  (|FoamEnvEnsure|
    (|ClosEnv| (|Lex| |Struct-mandel_t-9-Complex-1| 1 |l0|)))
  (|FoamEnvEnsure|
    (|ClosEnv| (|Lex| |Struct-mandel_t-9-Complex-1| 1 |l0|)))
  (|SetLex|
    |Struct-mandel_t-9-step-5|
    5
    |l0|
    (|C5-mandel_t-lazyFnGetter|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-mandel_t-9-dom-7| 7 |l0|)
        (the |SInt| 61407584)
        (the |SInt| -1717401541))
      |e0|))
  (|FoamEnvEnsure|
    (|ClosEnv| (|Lex| |Struct-mandel_t-9-Complex-1| 1 |l0|)))
  (|SetLex|
    |Struct-mandel_t-9-TextWriter-2|
    2
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t2 (the |SInt| 0)))
  (|SetLex|
    |Struct-mandel_t-9-dom-8|
    8
    |l0|
    (|Lex| |Struct-mandel_t-9-TextWriter-2| 2 |l0|))
  (|SetLex|
    |Struct-mandel_t-9-print-3|
    3
    |l0|
    (|CCall|
      |G-lazyGetExport!|
      (|Lex| |Struct-mandel_t-9-dom-8| 8 |l0|)
      (the |SInt| 828947258)
      (the |SInt| 182752316)))
  (setq t6 (|RNew| |Struct-mandel_t-14|))
  (|SetRElt|
    |Struct-mandel_t-14|
    |double|
    0
    t6
    (the |DFlo| 0.50000000000000000e0))
  (setq |T16-double| (the |DFlo| 1.0000000000000000e0))
  (setq |T18-double| (the |DFlo| 2.0000000000000000e0))
  (setq t7 (|RNew| |Struct-mandel_t-14|))
  (|SetRElt|
    |Struct-mandel_t-14|
    |double|
    0
    t7
    (|DFloNegate| |T18-double|))
  (setq |T17-double| (the |DFlo| 0.50000000000000000e0))
  (setq t8 (|RNew| |Struct-mandel_t-14|))
  (|SetRElt|
    |Struct-mandel_t-14|
    |double|
    0
    t8
    (|DFloNegate| |T17-double|))
  (setq t9 (|RNew| |Struct-mandel_t-14|))
  (|SetRElt|
    |Struct-mandel_t-14|
    |double|
    0
    t9
    (|DFloNegate| |T16-double|))
  (setq
    t14
    (|CCall|
      |G-lazyForceImport|
      (|Lex| |Struct-mandel_t-9-print-3| 3 |l0|)))
  (setq
    t15
    (|C1-mandel_t-drawMand|
      t7
      t9
      (the |SInt| 600)
      t8
      t6
      (the |SInt| 600)
      |e0|))
  (setq t13 (|formatSInt| t15))
  (multiple-value-setq (t10 t11 t12) (|CCall| t14))
  (|CCall| t11 t13 (the |SInt| 1) (the |SInt| 0))
  (multiple-value-setq (t3 t4 t5) (|CCall| t14))
  (|CCall| t3 (the |Char| #\Newline))
  (block-return |C0-mandel_t-mandel_t| ()))

(defprog
  ((|C1-mandel_t-drawMand| |Word|)
    ((|P0-minR| |Word|)
      (|P1-maxR| |Word|)
      (|P2-numR| |Word|)
      (|P3-minI| |Word|)
      (|P4-maxI| |Word|)
      (|P5-numI| |Word|)
      (|e1| |Env|)))
  ((|T0-sum| |SInt|)
    (t1 |SInt|)
    (t2 |Word|)
    (t3 |Word|)
    (t4 |Word|)
    (t5 |Clos|)
    (t6 |Clos|)
    (t7 |Clos|)
    (t8 |Clos|)
    (t9 |Clos|)
    (t10 |Clos|)
    (t11 |Word|)
    (t12 |Clos|)
    (t13 |Clos|)
    (t14 |Clos|)
    (t15 |Word|)
    (t16 |SInt|)
    (t17 |DFlo|)
    (t18 |DFlo|)
    (t19 |SInt|)
    (t20 |DFlo|)
    (t21 |DFlo|)
    (|T22-a| |SInt|)
    (|T23-double| |DFlo|)
    (|T24-double| |DFlo|)
    (|T25-double| |DFlo|)
    (|T26-double| |DFlo|)
    (|T27-dom| |Word|)
    (|T28-dom| |Word|)
    (|T29-real| |Word|)
    (|T30-imag| |Word|)
    (|T31-double| |DFlo|)
    (|T32-double| |DFlo|)
    (|T33-double| |DFlo|)
    (|T34-double| |DFlo|)
    (|T35-double| |DFlo|)
    (|T36-double| |DFlo|)
    (|T37-double| |DFlo|)
    (|T38-double| |DFlo|)
    (|T39-a| |SInt|)
    (|T40-a| |SInt|)
    (|T41-double| |DFlo|)
    (|T42-double| |DFlo|)
    (|T43-double| |DFlo|)
    (|T44-double| |DFlo|)
    (t45 |DFlo|)
    (t46 |DFlo|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (setq |T0-sum| (the |SInt| 0))
    (|FoamEnvEnsure|
      (|ClosEnv| (|Lex| |Struct-mandel_t-9-step-5| 5 |l1|)))
    (setq
      |T37-double|
      (|RElt| |Struct-mandel_t-14| |double| 0 |P3-minI|))
    (setq
      |T28-dom|
      (|CCall|
        (|EElt|
          |Struct-mandel_t-21-Segment-16|
          16
          (|EnvLevel|
            (|EnvNext|
              (|EnvNext| (|ClosEnv| (|Lex| |Struct-mandel_t-9-step-5| 5 |l1|))))))
        (|EElt|
          |Struct-mandel_t-21-SingleInteger-7|
          7
          (|EnvLevel|
            (|EnvNext|
              (|EnvNext| (|ClosEnv| (|Lex| |Struct-mandel_t-9-step-5| 5 |l1|))))))))
    (|C11-mandel_t-lazyFnGetter|
      (|CCall|
        |G-rtDelayedGetExport!|
        |T28-dom|
        (the |SInt| 113320568)
        (the |SInt| 788651633))
      (|EnvNext|
        (|EnvNext| (|ClosEnv| (|Lex| |Struct-mandel_t-9-step-5| 5 |l1|)))))
    (setq
      t20
      (|DFloMinus|
        (|RElt| |Struct-mandel_t-14| |double| 0 |P4-maxI|)
        |T37-double|))
    (setq t19 (|SIntPrev| |P5-numI|))
    (setq t21 (|SIntToDFlo| t19))
    (setq |T38-double| (|DFloDivide| t20 t21))
    (setq |T42-double| |T37-double|)
    (setq |T40-a| (the |SInt| 1))
    |Lab6|
    (when (|SIntLE| |T40-a| |P5-numI|) (go |Lab7|))
    (setq
      t11
      (|CCall|
        |G-lazyForceImport|
        (|Lex| |Struct-mandel_t-9-print-3| 3 |l1|)))
    (multiple-value-setq (t8 t9 t10) (|CCall| t11))
    (|CCall|
      t9
      (|MakeLit| "The sum is ")
      (the |SInt| 1)
      (the |SInt| 0))
    (setq t15 (|formatSInt| |T0-sum|))
    (multiple-value-setq (t12 t13 t14) (|CCall| t11))
    (|CCall| t13 t15 (the |SInt| 1) (the |SInt| 0))
    (multiple-value-setq (t5 t6 t7) (|CCall| t11))
    (|CCall| t5 (the |Char| #\Newline))
    (block-return
      |C1-mandel_t-drawMand|
      (|SIntTimes| |P2-numR| |P5-numI|))
    |Lab7|
    (|FoamEnvEnsure|
      (|ClosEnv| (|Lex| |Struct-mandel_t-9-step-5| 5 |l1|)))
    (setq
      |T35-double|
      (|RElt| |Struct-mandel_t-14| |double| 0 |P0-minR|))
    (setq
      |T27-dom|
      (|CCall|
        (|EElt|
          |Struct-mandel_t-21-Segment-16|
          16
          (|EnvLevel|
            (|EnvNext|
              (|EnvNext| (|ClosEnv| (|Lex| |Struct-mandel_t-9-step-5| 5 |l1|))))))
        (|EElt|
          |Struct-mandel_t-21-SingleInteger-7|
          7
          (|EnvLevel|
            (|EnvNext|
              (|EnvNext| (|ClosEnv| (|Lex| |Struct-mandel_t-9-step-5| 5 |l1|))))))))
    (|C11-mandel_t-lazyFnGetter|
      (|CCall|
        |G-rtDelayedGetExport!|
        |T27-dom|
        (the |SInt| 113320568)
        (the |SInt| 788651633))
      (|EnvNext|
        (|EnvNext| (|ClosEnv| (|Lex| |Struct-mandel_t-9-step-5| 5 |l1|)))))
    (setq
      t17
      (|DFloMinus|
        (|RElt| |Struct-mandel_t-14| |double| 0 |P1-maxR|)
        |T35-double|))
    (setq t16 (|SIntPrev| |P2-numR|))
    (setq t18 (|SIntToDFlo| t16))
    (setq |T36-double| (|DFloDivide| t17 t18))
    (setq |T41-double| |T35-double|)
    (setq |T39-a| (the |SInt| 1))
    |Lab4|
    (when (|SIntLE| |T39-a| |P2-numR|) (go |Lab8|))
    (setq |T37-double| (|DFloPlus| |T42-double| |T38-double|))
    (setq |T42-double| |T37-double|)
    (setq |T40-a| (|SIntNext| |T40-a|))
    (go |Lab6|)
    |Lab8|
    (setq
      t2
      (|CCall|
        |G-lazyForceImport|
        (|EElt| |Struct-mandel_t-9-0-4| 4 (|EnvLevel| (|EnvNext| |e0|)))))
    (setq |T29-real| (|RElt| |Struct-mandel_t-16| |real| 0 t2))
    (setq
      |T43-double|
      (|RElt| |Struct-mandel_t-14| |double| 0 |T29-real|))
    (setq |T30-imag| (|RElt| |Struct-mandel_t-16| |imag| 1 t2))
    (setq
      |T44-double|
      (|RElt| |Struct-mandel_t-14| |double| 0 |T30-imag|))
    (setq t1 (the |SInt| 0))
    (setq t4 |G-mandel_t_maxIters_083725344|)
    (setq |T22-a| (the |SInt| 1))
    |Lab2|
    (when (|SIntLE| |T22-a| t4) (go |Lab3|))
    |Lab0|
    (setq t3 |G-mandel_t_maxIters_083725344|)
    (when (|SIntEQ| t1 t3) (go |Lab1|))
    (setq |T0-sum| (|SIntPlus| |T0-sum| t1))
    (setq |T35-double| (|DFloPlus| |T41-double| |T36-double|))
    (setq |T41-double| |T35-double|)
    |Lab5|
    (setq |T39-a| (|SIntNext| |T39-a|))
    (go |Lab4|)
    |Lab1|
    (setq |T0-sum| |T0-sum|)
    (setq |T35-double| (|DFloPlus| |T41-double| |T36-double|))
    (setq |T41-double| |T35-double|)
    (go |Lab5|)
    |Lab3|
    (setq t45 (|DFloTimes| |T43-double| |T43-double|))
    (setq t46 (|DFloTimes| |T44-double| |T44-double|))
    (setq |T24-double| (|DFloPlus| t45 t46))
    (setq |T23-double| (the |DFlo| 4.0000000000000000e0))
    (when (|DFloLT| |T24-double| |T23-double|) (go |Lab9|))
    (go |Lab0|)
    |Lab9|
    (setq |T33-double| (|DFloMinus| t45 t46))
    (setq |T25-double| (|DFloTimes| |T43-double| |T44-double|))
    (setq |T26-double| (|DFloTimes| |T44-double| |T43-double|))
    (setq |T34-double| (|DFloPlus| |T25-double| |T26-double|))
    (setq |T32-double| (|DFloPlus| |T33-double| |T41-double|))
    (setq |T31-double| (|DFloPlus| |T34-double| |T42-double|))
    (setq |T43-double| |T32-double|)
    (setq |T44-double| |T31-double|)
    (setq t1 |T22-a|)
    (setq |T22-a| (|SIntNext| |T22-a|))
    (go |Lab2|)))

(defprog
  ((|C2-mandel_t-mandel| |Word|) ((|P0-c| |Word|) (|e1| |Env|)))
  ((|T0-nc| |SInt|)
    (|T1-z| |Word|)
    (t2 |Word|)
    (t3 |Word|)
    (|T4-a| |SInt|)
    (|T5-double| |DFlo|)
    (|T6-double| |DFlo|)
    (|T7-double| |DFlo|)
    (|T8-double| |DFlo|)
    (|T9-real| |Word|)
    (|T10-imag| |Word|)
    (|T11-double| |DFlo|)
    (|T12-double| |DFlo|)
    (|T13-double| |DFlo|)
    (|T14-double| |DFlo|)
    (|T15-double| |DFlo|)
    (|T16-double| |DFlo|)
    (t17 |DFlo|)
    (t18 |DFlo|)
    (|e2| |Env|)
    (|l2| |Level|))
  (setq |e2| (|EnvNext| |e1|))
  (setq |l2| (|EnvLevel| |e2|))
  (tagbody
    (setq
      |T1-z|
      (|CCall| |G-lazyForceImport| (|Lex| |Struct-mandel_t-9-0-4| 4 |l2|)))
    (setq |T9-real| (|RElt| |Struct-mandel_t-16| |real| 0 |T1-z|))
    (setq
      |T15-double|
      (|RElt| |Struct-mandel_t-14| |double| 0 |T9-real|))
    (setq |T10-imag| (|RElt| |Struct-mandel_t-16| |imag| 1 |T1-z|))
    (setq
      |T16-double|
      (|RElt| |Struct-mandel_t-14| |double| 0 |T10-imag|))
    (setq |T0-nc| (the |SInt| 0))
    (setq t3 |G-mandel_t_maxIters_083725344|)
    (setq |T4-a| (the |SInt| 1))
    |Lab3|
    (when (|SIntLE| |T4-a| t3) (go |Lab4|))
    |Lab0|
    (setq t2 |G-mandel_t_maxIters_083725344|)
    (when (|SIntEQ| |T0-nc| t2) (go |Lab1|))
    |Lab2|
    (block-return |C2-mandel_t-mandel| |T0-nc|)
    |Lab1|
    (setq |T0-nc| (the |SInt| 0))
    (go |Lab2|)
    |Lab4|
    (setq t17 (|DFloTimes| |T15-double| |T15-double|))
    (setq t18 (|DFloTimes| |T16-double| |T16-double|))
    (setq |T6-double| (|DFloPlus| t17 t18))
    (setq |T5-double| (the |DFlo| 4.0000000000000000e0))
    (when (|DFloLT| |T6-double| |T5-double|) (go |Lab5|))
    (go |Lab0|)
    |Lab5|
    (setq |T13-double| (|DFloMinus| t17 t18))
    (setq |T7-double| (|DFloTimes| |T15-double| |T16-double|))
    (setq |T8-double| (|DFloTimes| |T16-double| |T15-double|))
    (setq |T14-double| (|DFloPlus| |T7-double| |T8-double|))
    (setq
      |T12-double|
      (|DFloPlus|
        |T13-double|
        (|RElt|
          |Struct-mandel_t-14|
          |double|
          0
          (|RElt| |Struct-mandel_t-16| |real| 0 |P0-c|))))
    (setq
      |T11-double|
      (|DFloPlus|
        |T14-double|
        (|RElt|
          |Struct-mandel_t-14|
          |double|
          0
          (|RElt| |Struct-mandel_t-16| |imag| 1 |P0-c|))))
    (setq |T15-double| |T12-double|)
    (setq |T16-double| |T11-double|)
    (setq |T0-nc| |T4-a|)
    (setq |T4-a| (|SIntNext| |T4-a|))
    (go |Lab3|)))

(defprog
  ((|C3-mandel_t-drawPoint|)
    ((|P0-x| |Word|) (|P1-y| |Word|) (|P2-n| |Word|) (|e1| |Env|)))
  ((t0 |Arr|)
    (t1 |Clos|)
    (t2 |Clos|)
    (t3 |Clos|)
    (t4 |Word|)
    (t5 |Clos|)
    (t6 |Clos|)
    (t7 |Clos|)
    (t8 |Word|)
    (t9 |Clos|)
    (t10 |Clos|)
    (t11 |Clos|)
    (t12 |Word|)
    (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|SIntIsZero| |P2-n|) (go |Lab0|))
    (when (|SIntLT| |P2-n| (the |SInt| 10)) (go |Lab2|))
    (setq t0 (|MakeLit| " "))
    |Lab3|
    (setq
      t4
      (|CCall|
        |G-lazyForceImport|
        (|Lex| |Struct-mandel_t-9-print-3| 3 |l1|)))
    (multiple-value-setq (t1 t2 t3) (|CCall| t4))
    (|CCall| t2 t0 (the |SInt| 1) (the |SInt| 0))
    (setq t12 (|formatSInt| |P2-n|))
    (multiple-value-setq (t9 t10 t11) (|CCall| t4))
    (|CCall| t10 t12 (the |SInt| 1) (the |SInt| 0))
    |Lab1|
    (block-return |C3-mandel_t-drawPoint| ())
    |Lab2|
    (setq t0 (|MakeLit| "  "))
    (go |Lab3|)
    |Lab0|
    (setq
      t8
      (|CCall|
        |G-lazyForceImport|
        (|Lex| |Struct-mandel_t-9-print-3| 3 |l1|)))
    (multiple-value-setq (t5 t6 t7) (|CCall| t8))
    (|CCall| t6 (|MakeLit| "   ") (the |SInt| 1) (the |SInt| 0))
    (go |Lab1|)))

(defprog
  ((|C4-mandel_t-endRow|) ((|e1| |Env|)))
  ((t0 |Clos|) (t1 |Clos|) (t2 |Clos|) (t3 |Word|) (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (setq
    t3
    (|CCall|
      |G-lazyForceImport|
      (|Lex| |Struct-mandel_t-9-print-3| 3 |l1|)))
  (multiple-value-setq (t0 t1 t2) (|CCall| t3))
  (|CCall| t0 (the |Char| #\Newline))
  (block-return |C4-mandel_t-endRow| ()))

(defprog
  ((|C5-mandel_t-lazyFnGetter| |Clos|)
    ((|P0-init| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-mandel_t-8| |Struct-mandel_t-8|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|SetLex| |Struct-mandel_t-8-getter-0| 0 |l0| |P0-init|)
  (|SetLex| |Struct-mandel_t-8-flag-1| 1 |l0| (the |Bool| nil))
  (|SetLex|
    |Struct-mandel_t-8-self-2|
    2
    |l0|
    (|Clos| |e0| |C6-mandel_t-lazyGetter|))
  (|SetEnvInfo| |e0| (|Clos| |e0| |C7-mandel_t-lazyGetter2|))
  (block-return
    |C5-mandel_t-lazyFnGetter|
    (|Lex| |Struct-mandel_t-8-self-2| 2 |l0|)))

(defprog
  ((|C6-mandel_t-lazyGetter| |Clos|) ((|P0-a| |Word|) (|e1| |Env|)))
  ((t0 |Clos|) (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-mandel_t-8-flag-1| 1 |l1|) (go |Lab0|))
    (setq t0 (|CCall| (|Lex| |Struct-mandel_t-8-getter-0| 0 |l1|)))
    (|SetClosEnv|
      (|Lex| |Struct-mandel_t-8-self-2| 2 |l1|)
      (|ClosEnv| t0))
    (|SetClosFun|
      (|Lex| |Struct-mandel_t-8-self-2| 2 |l1|)
      (|ClosFun| t0))
    (|SetLex| |Struct-mandel_t-8-flag-1| 1 |l1| (the |Bool| t))
    |Lab0|
    (block-return
      |C6-mandel_t-lazyGetter|
      (|CCall| (|Lex| |Struct-mandel_t-8-self-2| 2 |l1|) |P0-a|))))

(defprog
  ((|C7-mandel_t-lazyGetter2|) ((|e1| |Env|)))
  ((t0 |Clos|) (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-mandel_t-8-flag-1| 1 |l1|) (go |Lab0|))
    (setq t0 (|CCall| (|Lex| |Struct-mandel_t-8-getter-0| 0 |l1|)))
    (|SetLex| |Struct-mandel_t-8-flag-1| 1 |l1| (the |Bool| t))
    (|SetClosEnv|
      (|Lex| |Struct-mandel_t-8-self-2| 2 |l1|)
      (|ClosEnv| t0))
    (|SetClosFun|
      (|Lex| |Struct-mandel_t-8-self-2| 2 |l1|)
      (|ClosFun| t0))
    (|SetEnvInfo| |e1| nil)
    |Lab0|
    (block-return |C7-mandel_t-lazyGetter2| ())))

(defprog
  ((|C8-mandel_t-textwrit-init| |Word|)
    ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-mandel_t-9--9| 9 |l1|) (go |Lab0|))
    (|SetLex| |Struct-mandel_t-9--9| 9 |l1| (the |Bool| t))
    (|CCall| |G-textwrit|)
    |Lab0|
    (block-return
      |C8-mandel_t-textwrit-init|
      |G-textwrit_TextWriter_636558258|)))

(defprog
  ((|C9-mandel_t-dfloat-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-mandel_t-9--10| 10 |l1|) (go |Lab0|))
    (|SetLex| |Struct-mandel_t-9--10| 10 |l1| (the |Bool| t))
    (|CCall| |G-dfloat|)
    |Lab0|
    (block-return
      |C9-mandel_t-dfloat-init|
      |G-dfloat_DoubleFloat_701519844|)))

(defprog
  ((|C10-mandel_t-complex-init| |Word|)
    ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-mandel_t-9--11| 11 |l1|) (go |Lab0|))
    (|SetLex| |Struct-mandel_t-9--11| 11 |l1| (the |Bool| t))
    (|CCall| |G-complex|)
    |Lab0|
    (block-return
      |C10-mandel_t-complex-init|
      |G-complex_Complex_500608513|)))

(defprog
  ((|C11-mandel_t-lazyFnGetter| |Clos|)
    ((|P0-init| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq
    |l0|
    (|MakeLevel| |MAKE-Struct-mandel_t-18| |Struct-mandel_t-18|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|SetLex| |Struct-mandel_t-18-getter-0| 0 |l0| |P0-init|)
  (|SetLex| |Struct-mandel_t-18-flag-1| 1 |l0| (the |Bool| nil))
  (|SetLex|
    |Struct-mandel_t-18-self-2|
    2
    |l0|
    (|Clos| |e0| |C12-mandel_t-lazyGetter|))
  (|SetEnvInfo| |e0| (|Clos| |e0| |C13-mandel_t-lazyGetter2|))
  (block-return
    |C11-mandel_t-lazyFnGetter|
    (|Lex| |Struct-mandel_t-18-self-2| 2 |l0|)))

(defprog
  ((|C12-mandel_t-lazyGetter| |Clos|) ((|P0-a| |Word|) (|e1| |Env|)))
  ((t0 |Clos|) (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-mandel_t-18-flag-1| 1 |l1|) (go |Lab0|))
    (setq t0 (|CCall| (|Lex| |Struct-mandel_t-18-getter-0| 0 |l1|)))
    (|SetClosEnv|
      (|Lex| |Struct-mandel_t-18-self-2| 2 |l1|)
      (|ClosEnv| t0))
    (|SetClosFun|
      (|Lex| |Struct-mandel_t-18-self-2| 2 |l1|)
      (|ClosFun| t0))
    (|SetLex| |Struct-mandel_t-18-flag-1| 1 |l1| (the |Bool| t))
    |Lab0|
    (block-return
      |C12-mandel_t-lazyGetter|
      (|CCall| (|Lex| |Struct-mandel_t-18-self-2| 2 |l1|) |P0-a|))))

(defprog
  ((|C13-mandel_t-lazyGetter2|) ((|e1| |Env|)))
  ((t0 |Clos|) (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-mandel_t-18-flag-1| 1 |l1|) (go |Lab0|))
    (setq t0 (|CCall| (|Lex| |Struct-mandel_t-18-getter-0| 0 |l1|)))
    (|SetLex| |Struct-mandel_t-18-flag-1| 1 |l1| (the |Bool| t))
    (|SetClosEnv|
      (|Lex| |Struct-mandel_t-18-self-2| 2 |l1|)
      (|ClosEnv| t0))
    (|SetClosFun|
      (|Lex| |Struct-mandel_t-18-self-2| 2 |l1|)
      (|ClosFun| t0))
    (|SetEnvInfo| |e1| nil)
    |Lab0|
    (block-return |C13-mandel_t-lazyGetter2| ())))

(setq |G-mandel_t| (|Clos| nil |C0-mandel_t-mandel_t|))

(setq |G-mandel_t_endRow_778822608| nil)

(setq |G-mandel_t_drawPoint_326007403| nil)

(setq |G-mandel_t_drawMand_361523023| nil)

(setq |G-mandel_t_maxIters_083725344| nil)

(setq |C14-mandel_t-maxIters| (the |SInt| 100))

(file-imports
  '((|G-complex| "complex" |initializer| "")
      (|G-dfloat| "dfloat" |initializer| "")
      (|G-textwrit| "textwrit" |initializer| "")
      (|G-textwrit_TextWriter_636558258| "TextWriter" 636558258 "textwrit")
      (|G-lazyForceImport| "lazyForceImport" 0 "")
      (|G-lazyGetExport!| "lazyGetExport!" 0 "")
      (|G-rtDelayedInit!| "rtDelayedInit!" 0 "")
      (|G-complex_Complex_500608513| "Complex" 500608513 "complex")
      (|G-dfloat_DoubleFloat_701519844| "DoubleFloat" 701519844 "dfloat")
      (|G-stdGetWordRetWord0| "stdGetWordRetWord0" 0 "")
      (|G-rtDelayedGetExport!| "rtDelayedGetExport!" 0 "")
      (|G-rtLazyDomFrInit| "rtLazyDomFrInit" 0 "")
      (|G-runtime| "runtime" |initializer| "")
      (|G-noOperation| "noOperation" 0 "")))

(file-exports
  '((|G-mandel_t_maxIters_083725344| "t_maxIters" 83725344 "mandel")
      (|G-mandel_t_drawMand_361523023| "t_drawMand" 361523023 "mandel")
      (|G-mandel_t_drawPoint_326007403| "t_drawPoint" 326007403 "mandel")
      (|G-mandel_t_endRow_778822608| "t_endRow" 778822608 "mandel")
      (|G-mandel_t| "mandel_t" |initializer| "")))
