/*
 * C code generated by Aldor from file "mandel_t.as".
 */

#include "foam_c.h"

typedef struct Fmt5  *PFmt5;
typedef struct Fmt6  *PFmt6;
typedef struct Fmt7  *PFmt7;
typedef struct Fmt8  *PFmt8;
typedef struct Fmt9  *PFmt9;
typedef struct Fmt10  *PFmt10;
typedef struct Fmt11  *PFmt11;
typedef struct Fmt12  *PFmt12;
typedef struct Fmt13  *PFmt13;
typedef struct Fmt14  *PFmt14;
typedef struct Fmt15  *PFmt15;
typedef struct Fmt16  *PFmt16;
typedef struct Fmt17  *PFmt17;
typedef struct Fmt18  *PFmt18;
typedef struct Fmt19  *PFmt19;
typedef struct Fmt20  *PFmt20;
typedef struct Fmt21  *PFmt21;
typedef struct Fmt22  *PFmt22;
struct Fmt5 {
        FiPtr X0_empty;
};
struct Fmt6 {
        FiPtr X0_empty;
};
struct Fmt7 {
        FiPtr X0_empty;
};
struct Fmt8 {
        FiClos X0_getter;
        FiBool X1_flag;
        FiClos X2_self;
};
struct Fmt9 {
        FiWord X0_DoubleFloat;
        FiClos X1_Complex;
        FiWord X2_TextWriter;
        FiWord X3_print;
        FiWord X4_0;
        FiClos X5_step;
        FiWord X6_dom;
        FiWord X7_dom;
        FiWord X8_dom;
        FiBool X9;
        FiBool X10;
        FiBool X11;
};
struct Fmt10 {
        FiPtr X0_empty;
};
struct Fmt11 {
        FiPtr X0_empty;
};
struct Fmt12 {
        FiPtr X0_empty;
};
struct Fmt13 {
        FiPtr X0_empty;
};
struct Fmt14 {
        FiDFlo X0_double;
};
struct Fmt15 {
        FiPtr X0_empty;
};
struct Fmt16 {
        FiWord X0_real;
        FiWord X1_imag;
};
struct Fmt17 {
        FiPtr X0_empty;
};
struct Fmt18 {
        FiClos X0_getter;
        FiBool X1_flag;
        FiClos X2_self;
};
struct Fmt19 {
        FiPtr X0_empty;
};
struct Fmt20 {
        FiPtr X0_empty;
};
struct Fmt21 {
        FiWord X0_RoundingMode;
        FiWord X1_Machine;
        FiWord X2_FortranDouble;
        FiWord X3_FloatingPointNumberSystem;
        FiWord X4_OrderedFinite;
        FiWord X5_DenseStorageCategory;
        FiWord X6_BasicType;
        FiWord X7_SingleInteger;
        FiClos X8_BinaryPowering;
        FiWord X9_Integer;
        FiClos X10_Record;
        FiWord X11_DFlo;
        FiWord X12_max;
        FiWord X13_min;
        FiWord X14_epsilon;
        FiWord X15_dom;
        FiClos X16_Segment;
        FiBool X17;
        FiBool X18;
        FiBool X19;
        FiBool X20;
        FiBool X21;
        FiBool X22;
        FiBool X23;
        FiBool X24;
};
struct Fmt22 {
        FiClos X0;
        FiClos X1;
        FiClos X2;
};
static FiProg C0_mandel__t;
static void CF0_mandel__t(FiEnv e1);
static FiProg C1_drawMand;
static FiWord CF1_drawMand(FiEnv e1, FiWord P0_minR, FiWord P1_maxR, FiWord P2_numR, FiWord P3_minI, FiWord P4_maxI, FiWord P5_numI);
static FiProg C2_mandel;
static FiWord CF2_mandel(FiEnv e1, FiWord P0_c);
static FiProg C3_drawPoint;
static void CF3_drawPoint(FiEnv e1, FiWord P0_x, FiWord P1_y, FiWord P2_n);
static FiProg C4_endRow;
static void CF4_endRow(FiEnv e1);
static FiProg C5_lazyFnGetter;
static FiClos CF5_lazyFnGetter(FiEnv e1, FiWord P0_init);
static FiProg C6_lazyGetter;
static FiClos CF6_lazyGetter(FiEnv e1, FiWord P0_a);
static FiProg C7_lazyGetter2;
static void CF7_lazyGetter2(FiEnv e1);
static FiProg C8_textwrit_MINUS_init;
static FiWord CF8_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C9_dfloat_MINUS_init;
static FiWord CF9_dfloat_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C10_complex_MINUS_init;
static FiWord CF10_complex_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C11_lazyFnGetter;
static FiClos CF11_lazyFnGetter(FiEnv e1, FiWord P0_init);
static FiProg C12_lazyGetter;
static FiClos CF12_lazyGetter(FiEnv e1, FiWord P0_a);
static FiProg C13_lazyGetter2;
static void CF13_lazyGetter2(FiEnv e1);
#define fiCallSpecial0(fn,a1,a2,a3) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3))

#define fiCallSpecial1(fn,a1,a2,a3) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3))

#define fiCallSpecial2(fn,a1,a2,a3) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3))

#define fiCallSpecial3(fn,a1,a2,a3) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3))

#define fiCallSpecial4(fn,a1,a2,a3) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3))

#define fiCallSpecial5(fn,a1,a2,a3) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3))

#define fiCallSpecial6(fn,a1,a2,a3) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3))

#define fiCallSpecial7(fn,a1,a2,a3) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3))

#define fiCallSpecial8(fn,a1,a2,a3) (fiProtoCFun(void,(FiEnv,FiClos *,FiClos *,FiClos *),fn)((fn)->env,a1,a2,a3))

extern FiClos G_C4XH_mandel__t;
static FiClos *pG_NQYQM_noOperation;
extern FiClos G_1YJKI_mandel__t__endRow__778;
extern FiClos G_5OG7O_mandel__t__drawPoint__;
extern FiClos G_513PV_mandel__t__drawMand__3;
extern FiWord G_GUBFY_mandel__t__maxIters__0;
static FiClos *pG_XIPRL_runtime;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_QRAZA_rtDelayedGetExport;
static FiClos *pG_ZZZKG_stdGetWordRetWord0;
static FiWord *pG_STDSR_dfloat__DoubleFloat__;
static FiClos *pG_LM9I3_complex__Complex__500;
static FiClos *pG_RSHLY_rtDelayedInit_BANG_;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiWord *pG_Z4122_textwrit__TextWriter;
static FiClos *pG_EC2QI_textwrit;
static FiClos *pG_DEGQL_dfloat;
static FiClos *pG_I0RMM_complex;
extern FiWord formatSInt(FiSInt P0);



static void
CF0_mandel__t(FiEnv e1)
{
        FiWord T13, T14, T15, T19;
        FiDFlo T16_double, T17_double, T18_double;
        FiClos T0, T1, T2, T3, T4, T5, T10, T11, T12;
        PFmt14 T6, T7, T8, T9;
        PFmt9 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt9 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCall0(void, (*pG_XIPRL_runtime));
        G_C4XH_mandel__t = (FiClos) (*pG_NQYQM_noOperation);
        T0 = fiClosMake(e0, C9_dfloat_MINUS_init);
        T1 = fiClosMake(e0, C10_complex_MINUS_init);
        T2 = fiClosMake(e0, C8_textwrit_MINUS_init);
        G_513PV_mandel__t__drawMand__3 = fiClosMake(e0, C1_drawMand);
        G_5OG7O_mandel__t__drawPoint__ = fiClosMake(e0, C3_drawPoint);
        G_1YJKI_mandel__t__endRow__778 = fiClosMake(e0, C4_endRow);
        l0->X9 = 0L;
        l0->X10 = 0L;
        l0->X11 = 0L;
        G_GUBFY_mandel__t__maxIters__0 = (FiWord) 100L;
        l0->X0_DoubleFloat = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T0, 0L);
        T19 = fiCall(FiWord, (*pG_RSHLY_rtDelayedInit_BANG_), T1, 0L);
        l0->X1_Complex = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T19);
        l0->X6_dom = fiCall(FiWord, l0->X1_Complex, l0->
        	X0_DoubleFloat);
        fiEnvEnsure(l0->X1_Complex->env);
        l0->X4_0 = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), l0->
        	X6_dom, 200089L, 1616131033L);
        fiEnvEnsure(l0->X1_Complex->env);
        l0->X7_dom = l0->X0_DoubleFloat;
        fiEnvEnsure(l0->X1_Complex->env);
        fiEnvEnsure(l0->X1_Complex->env);
        fiEnvEnsure(l0->X1_Complex->env);
        fiEnvEnsure(l0->X1_Complex->env);
        fiEnvEnsure(l0->X1_Complex->env);
        fiEnvEnsure(l0->X1_Complex->env);
        l0->X5_step = CF5_lazyFnGetter(e0, (FiWord) fiCall(FiWord, (*
        	pG_QRAZA_rtDelayedGetExport), l0->X7_dom, 61407584L, 
        	-1717401541L));
        fiEnvEnsure(l0->X1_Complex->env);
        l0->X2_TextWriter = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T2, 0L);
        l0->X8_dom = l0->X2_TextWriter;
        l0->X3_print = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X8_dom, 828947258L, 182752316L);
        T6 = fi0RecNew(struct Fmt14 , CENSUS_Rec);
        T6->X0_double = 0.50000000000000000;
        T16_double = 1.0000000000000000;
        T18_double = 2.0000000000000000;
        T7 = fi0RecNew(struct Fmt14 , CENSUS_Rec);
        T7->X0_double = -T18_double;
        T17_double = 0.50000000000000000;
        T8 = fi0RecNew(struct Fmt14 , CENSUS_Rec);
        T8->X0_double = -T17_double;
        T9 = fi0RecNew(struct Fmt14 , CENSUS_Rec);
        T9->X0_double = -T16_double;
        T14 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X3_print);
        T15 = CF1_drawMand(e0, (FiWord) T7, (FiWord) T9, (FiWord) 600L, (
        	FiWord) T8, (FiWord) T6, (FiWord) 600L);
        T13 = formatSInt((FiSInt) T15);
        fiCallSpecial7((FiClos) T14, &T10, &T11, &T12);
        fiCall(FiWord, T11, T13, (FiWord) 1L, (FiWord) 0L);
        fiCallSpecial8((FiClos) T14, &T3, &T4, &T5);
        fiCall(void, T3, (FiWord) 10L);
        return ;
}

static struct _FiProg  tmp0_mandel__t = {
        (FiFun) CF0_mandel__t,
        0L,
        0L,
        0L
};


static FiWord
CF1_drawMand(FiEnv e1, FiWord P0_minR, FiWord P1_maxR, FiWord P2_numR, 
        	FiWord P3_minI, FiWord P4_maxI, FiWord P5_numI)
{
        FiDFlo T17, T18, T20, T21, T23_double, T24_double, T25_double, T26_double, T31_double, T32_double, T33_double, T34_double, T35_double, T36_double, T37_double, T38_double, T41_double, T42_double, T43_double, T44_double, T45, T46;
        FiSInt T0_sum, T1, T16, T19, T22_a, T39_a, T40_a;
        FiWord T2, T3, T4, T11, T15, T27_dom, T28_dom, T29_real, T30_imag;
        FiClos T5, T6, T7, T8, T9, T10, T12, T13, T14;
        PFmt9 l1;
        FiEnv e0;
        e0 = fiEnvPush(fiNil, e1);
        l1 = (PFmt9) fiEnvLevel(e1);
        T0_sum = 0L;
        fiEnvEnsure(l1->X5_step->env);
        T37_double = ((PFmt14) P3_minI)->X0_double;
        T28_dom = fiCall(FiWord, ((PFmt21) fiEnvLevel2(l1->X5_step->
        	env))->X16_Segment, ((PFmt21) fiEnvLevel2(l1->X5_step->
        	env))->X7_SingleInteger);
        CF11_lazyFnGetter(fiEnvNext(fiEnvNext(l1->X5_step->env)), (FiWord) 
        	fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), T28_dom, 
        	113320568L, 788651633L));
        T20 = ((PFmt14) P4_maxI)->X0_double - T37_double;
        T19 = (FiSInt) P5_numI - 1L;
        fiSINT_TO_DFLO(T21, FiDFlo, T19);
        T38_double = T20 / T21;
        T42_double = T37_double;
        T40_a = 1L;
L6:	if (T40_a <= (FiSInt) P5_numI) goto L7;
        T11 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X3_print);
        fiCallSpecial0((FiClos) T11, &T8, &T9, &T10);
        fiCall(FiWord, T9, (FiWord) "The sum is ", (FiWord) 1L, (FiWord) 0L);
        T15 = formatSInt(T0_sum);
        fiCallSpecial1((FiClos) T11, &T12, &T13, &T14);
        fiCall(FiWord, T13, T15, (FiWord) 1L, (FiWord) 0L);
        fiCallSpecial2((FiClos) T11, &T5, &T6, &T7);
        fiCall(void, T5, (FiWord) 10L);
        return (FiWord) ((FiSInt) P2_numR * (FiSInt) P5_numI);
L7:	fiEnvEnsure(l1->X5_step->env);
        T35_double = ((PFmt14) P0_minR)->X0_double;
        T27_dom = fiCall(FiWord, ((PFmt21) fiEnvLevel2(l1->X5_step->
        	env))->X16_Segment, ((PFmt21) fiEnvLevel2(l1->X5_step->
        	env))->X7_SingleInteger);
        CF11_lazyFnGetter(fiEnvNext(fiEnvNext(l1->X5_step->env)), (FiWord) 
        	fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), T27_dom, 
        	113320568L, 788651633L));
        T17 = ((PFmt14) P1_maxR)->X0_double - T35_double;
        T16 = (FiSInt) P2_numR - 1L;
        fiSINT_TO_DFLO(T18, FiDFlo, T16);
        T36_double = T17 / T18;
        T41_double = T35_double;
        T39_a = 1L;
L4:	if (T39_a <= (FiSInt) P2_numR) goto L8;
        T37_double = T42_double + T38_double;
        T42_double = T37_double;
        T40_a = T40_a + 1L;
        goto L6;
L8:	T2 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), ((PFmt9) 
        	fiEnvLevel1(e0))->X4_0);
        T29_real = ((PFmt16) T2)->X0_real;
        T43_double = ((PFmt14) T29_real)->X0_double;
        T30_imag = ((PFmt16) T2)->X1_imag;
        T44_double = ((PFmt14) T30_imag)->X0_double;
        T1 = 0L;
        T4 = (FiWord) G_GUBFY_mandel__t__maxIters__0;
        T22_a = 1L;
L2:	if (T22_a <= (FiSInt) T4) goto L3;
L0:	T3 = (FiWord) G_GUBFY_mandel__t__maxIters__0;
        if (T1 == (FiSInt) T3) goto L1;
        T0_sum = T0_sum + T1;
        T35_double = T41_double + T36_double;
        T41_double = T35_double;
L5:	T39_a = T39_a + 1L;
        goto L4;
L1:	T0_sum = T0_sum;
        T35_double = T41_double + T36_double;
        T41_double = T35_double;
        goto L5;
L3:	T45 = T43_double * T43_double;
        T46 = T44_double * T44_double;
        T24_double = T45 + T46;
        T23_double = 4.0000000000000000;
        if (T24_double < T23_double) goto L9;
        goto L0;
L9:	T33_double = T45 - T46;
        T25_double = T43_double * T44_double;
        T26_double = T44_double * T43_double;
        T34_double = T25_double + T26_double;
        T32_double = T33_double + T41_double;
        T31_double = T34_double + T42_double;
        T43_double = T32_double;
        T44_double = T31_double;
        T1 = T22_a;
        T22_a = T22_a + 1L;
        goto L2;
}

static struct _FiProg  tmp1_drawMand = {
        (FiFun) CF1_drawMand,
        0L,
        0L,
        0L
};


static FiWord
CF2_mandel(FiEnv e1, FiWord P0_c)
{
        FiDFlo T5_double, T6_double, T7_double, T8_double, T11_double, T12_double, T13_double, T14_double, T15_double, T16_double, T17, T18;
        FiWord T1_z, T2, T3, T9_real, T10_imag;
        FiSInt T0_nc, T4_a;
        PFmt9 l2;
        FiEnv e2;
        e2 = fiEnvNext(e1);
        l2 = (PFmt9) fiEnvLevel(e2);
        T1_z = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l2->X4_0);
        T9_real = ((PFmt16) T1_z)->X0_real;
        T15_double = ((PFmt14) T9_real)->X0_double;
        T10_imag = ((PFmt16) T1_z)->X1_imag;
        T16_double = ((PFmt14) T10_imag)->X0_double;
        T0_nc = 0L;
        T3 = (FiWord) G_GUBFY_mandel__t__maxIters__0;
        T4_a = 1L;
L3:	if (T4_a <= (FiSInt) T3) goto L4;
L0:	T2 = (FiWord) G_GUBFY_mandel__t__maxIters__0;
        if (T0_nc == (FiSInt) T2) goto L1;
L2:	return (FiWord) T0_nc;
L1:	T0_nc = 0L;
        goto L2;
L4:	T17 = T15_double * T15_double;
        T18 = T16_double * T16_double;
        T6_double = T17 + T18;
        T5_double = 4.0000000000000000;
        if (T6_double < T5_double) goto L5;
        goto L0;
L5:	T13_double = T17 - T18;
        T7_double = T15_double * T16_double;
        T8_double = T16_double * T15_double;
        T14_double = T7_double + T8_double;
        T12_double = T13_double + ((PFmt14) ((PFmt16) P0_c)->
        	X0_real)->X0_double;
        T11_double = T14_double + ((PFmt14) ((PFmt16) P0_c)->
        	X1_imag)->X0_double;
        T15_double = T12_double;
        T16_double = T11_double;
        T0_nc = T4_a;
        T4_a = T4_a + 1L;
        goto L3;
}

static struct _FiProg  tmp2_mandel = {
        (FiFun) CF2_mandel,
        0L,
        0L,
        0L
};


static void
CF3_drawPoint(FiEnv e1, FiWord P0_x, FiWord P1_y, FiWord P2_n)
{
        FiWord T4, T8, T12;
        FiClos T1, T2, T3, T5, T6, T7, T9, T10, T11;
        FiChar *T0;
        PFmt9 l1;
        l1 = (PFmt9) fiEnvLevel(e1);
        if ((FiSInt) P2_n == 0) goto L0;
        if ((FiSInt) P2_n < 10L) goto L2;
        T0 = (FiChar*) " ";
L3:	T4 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X3_print);
        fiCallSpecial3((FiClos) T4, &T1, &T2, &T3);
        fiCall(FiWord, T2, (FiWord) T0, (FiWord) 1L, (FiWord) 0L);
        T12 = formatSInt((FiSInt) P2_n);
        fiCallSpecial4((FiClos) T4, &T9, &T10, &T11);
        fiCall(FiWord, T10, T12, (FiWord) 1L, (FiWord) 0L);
L1:	return ;
L2:	T0 = (FiChar*) "  ";
        goto L3;
L0:	T8 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X3_print);
        fiCallSpecial5((FiClos) T8, &T5, &T6, &T7);
        fiCall(FiWord, T6, (FiWord) "   ", (FiWord) 1L, (FiWord) 0L);
        goto L1;
}

static struct _FiProg  tmp3_drawPoint = {
        (FiFun) CF3_drawPoint,
        0L,
        0L,
        0L
};


static void
CF4_endRow(FiEnv e1)
{
        FiWord T3;
        FiClos T0, T1, T2;
        PFmt9 l1;
        l1 = (PFmt9) fiEnvLevel(e1);
        T3 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X3_print);
        fiCallSpecial6((FiClos) T3, &T0, &T1, &T2);
        fiCall(void, T0, (FiWord) 10L);
        return ;
}

static struct _FiProg  tmp4_endRow = {
        (FiFun) CF4_endRow,
        0L,
        0L,
        0L
};


static FiClos
CF5_lazyFnGetter(FiEnv e1, FiWord P0_init)
{
        PFmt8 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt8 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        l0->X0_getter = (FiClos) P0_init;
        l0->X1_flag = 0L;
        l0->X2_self = fiClosMake(e0, C6_lazyGetter);
        fiEnvInfo(e0) = (FiWord) fiClosMake(e0, C7_lazyGetter2);
        return l0->X2_self;
}

static struct _FiProg  tmp5_lazyFnGetter = {
        (FiFun) CF5_lazyFnGetter,
        0L,
        0L,
        0L
};


static FiClos
CF6_lazyGetter(FiEnv e1, FiWord P0_a)
{
        FiClos T0;
        PFmt8 l1;
        l1 = (PFmt8) fiEnvLevel(e1);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCall0(FiWord, l1->X0_getter);
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        l1->X1_flag = 1L;
L0:	return fiCall(FiClos, l1->X2_self, P0_a);
}

static struct _FiProg  tmp6_lazyGetter = {
        (FiFun) CF6_lazyGetter,
        0L,
        0L,
        0L
};


static void
CF7_lazyGetter2(FiEnv e1)
{
        FiClos T0;
        PFmt8 l1;
        l1 = (PFmt8) fiEnvLevel(e1);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCall0(FiWord, l1->X0_getter);
        l1->X1_flag = 1L;
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        fiEnvInfo(e1) = (FiWord) fiNil;
L0:	return ;
}

static struct _FiProg  tmp7_lazyGetter2 = {
        (FiFun) CF7_lazyGetter2,
        0L,
        0L,
        0L
};


static FiWord
CF8_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt9 l1;
        l1 = (PFmt9) fiEnvLevel(e1);
        if (l1->X9) goto L0;
        l1->X9 = 1L;
        fiCall0(void, (*pG_EC2QI_textwrit));
L0:	return (FiWord) (*pG_Z4122_textwrit__TextWriter);
}

static struct _FiProg  tmp8_textwrit_MINUS_init = {
        (FiFun) CF8_textwrit_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF9_dfloat_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt9 l1;
        l1 = (PFmt9) fiEnvLevel(e1);
        if (l1->X10) goto L0;
        l1->X10 = 1L;
        fiCall0(void, (*pG_DEGQL_dfloat));
L0:	return (FiWord) (*pG_STDSR_dfloat__DoubleFloat__);
}

static struct _FiProg  tmp9_dfloat_MINUS_init = {
        (FiFun) CF9_dfloat_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF10_complex_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt9 l1;
        l1 = (PFmt9) fiEnvLevel(e1);
        if (l1->X11) goto L0;
        l1->X11 = 1L;
        fiCall0(void, (*pG_I0RMM_complex));
L0:	return (FiWord) (*pG_LM9I3_complex__Complex__500);
}

static struct _FiProg  tmp10_complex_MINUS_init = {
        (FiFun) CF10_complex_MINUS_init,
        0L,
        0L,
        0L
};


static FiClos
CF11_lazyFnGetter(FiEnv e1, FiWord P0_init)
{
        PFmt18 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt18 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        l0->X0_getter = (FiClos) P0_init;
        l0->X1_flag = 0L;
        l0->X2_self = fiClosMake(e0, C12_lazyGetter);
        fiEnvInfo(e0) = (FiWord) fiClosMake(e0, C13_lazyGetter2);
        return l0->X2_self;
}

static struct _FiProg  tmp11_lazyFnGetter = {
        (FiFun) CF11_lazyFnGetter,
        0L,
        0L,
        0L
};


static FiClos
CF12_lazyGetter(FiEnv e1, FiWord P0_a)
{
        FiClos T0;
        PFmt18 l1;
        l1 = (PFmt18) fiEnvLevel(e1);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCall0(FiWord, l1->X0_getter);
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        l1->X1_flag = 1L;
L0:	return fiCall(FiClos, l1->X2_self, P0_a);
}

static struct _FiProg  tmp12_lazyGetter = {
        (FiFun) CF12_lazyGetter,
        0L,
        0L,
        0L
};


static void
CF13_lazyGetter2(FiEnv e1)
{
        FiClos T0;
        PFmt18 l1;
        l1 = (PFmt18) fiEnvLevel(e1);
        if (l1->X1_flag) goto L0;
        T0 = (FiClos) fiCall0(FiWord, l1->X0_getter);
        l1->X1_flag = 1L;
        l1->X2_self->env = T0->env;
        l1->X2_self->prog = T0->prog;
        fiEnvInfo(e1) = (FiWord) fiNil;
L0:	return ;
}

static struct _FiProg  tmp13_lazyGetter2 = {
        (FiFun) CF13_lazyGetter2,
        0L,
        0L,
        0L
};

extern int
INIT__0_mandel__t(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_complex(void);
        extern int INIT__0_dfloat(void);
        extern int INIT__0_textwrit(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_drawMand = &tmp1_drawMand;
        C2_mandel = &tmp2_mandel;
        C3_drawPoint = &tmp3_drawPoint;
        C4_endRow = &tmp4_endRow;
        C5_lazyFnGetter = &tmp5_lazyFnGetter;
        C6_lazyGetter = &tmp6_lazyGetter;
        C7_lazyGetter2 = &tmp7_lazyGetter2;
        C8_textwrit_MINUS_init = &tmp8_textwrit_MINUS_init;
        C9_dfloat_MINUS_init = &tmp9_dfloat_MINUS_init;
        C10_complex_MINUS_init = &tmp10_complex_MINUS_init;
        C11_lazyFnGetter = &tmp11_lazyFnGetter;
        C12_lazyGetter = &tmp12_lazyGetter;
        C13_lazyGetter2 = &tmp13_lazyGetter2;
        C0_mandel__t = &tmp0_mandel__t;
        fiExportGlobal("G_C4XH_mandel__t", G_C4XH_mandel__t);
        fiExportGlobal("G_1YJKI_mandel__t__endRow__778", 
        	G_1YJKI_mandel__t__endRow__778);
        fiExportGlobal("G_5OG7O_mandel__t__drawPoint__", 
        	G_5OG7O_mandel__t__drawPoint__);
        fiExportGlobal("G_513PV_mandel__t__drawMand__3", 
        	G_513PV_mandel__t__drawMand__3);
        fiExportGlobal("G_GUBFY_mandel__t__maxIters__0", 
        	G_GUBFY_mandel__t__maxIters__0);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_QRAZA_rtDelayedGetExport", 
        	pG_QRAZA_rtDelayedGetExport);
        fiImportGlobal("G_ZZZKG_stdGetWordRetWord0", 
        	pG_ZZZKG_stdGetWordRetWord0);
        fiImportGlobal("G_STDSR_dfloat__DoubleFloat__7", 
        	pG_STDSR_dfloat__DoubleFloat__);
        fiImportGlobal("G_LM9I3_complex__Complex__5006", 
        	pG_LM9I3_complex__Complex__500);
        fiImportGlobal("G_RSHLY_rtDelayedInit_BANG_", 
        	pG_RSHLY_rtDelayedInit_BANG_);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_Z4122_textwrit__TextWriter__", 
        	pG_Z4122_textwrit__TextWriter);
        fiImportGlobal("G_EC2QI_textwrit", pG_EC2QI_textwrit);
        fiImportGlobal("G_DEGQL_dfloat", pG_DEGQL_dfloat);
        fiImportGlobal("G_I0RMM_complex", pG_I0RMM_complex);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("complex");
                fiFileInitializer("dfloat");
                fiFileInitializer("textwrit");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_complex();
                INIT__0_dfloat();
                INIT__0_textwrit();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}

FiWord G_GUBFY_mandel__t__maxIters__0;
FiClos G_513PV_mandel__t__drawMand__3;
FiClos G_5OG7O_mandel__t__drawPoint__;
FiClos G_1YJKI_mandel__t__endRow__778;

static struct _FiClos  tmpClos0_mandel__t = {
        0L,
        (FiProg) &tmp0_mandel__t
};
FiClos G_C4XH_mandel__t = &tmpClos0_mandel__t;
