/*
 * C code generated by Aldor from file "ratio0.as".
 */

#include "foam_c.h"

typedef struct Fmt5  *PFmt5;
typedef struct Fmt6  *PFmt6;
struct Fmt5 {
        FiPtr X0_empty;
};
struct Fmt6 {
        FiWord X0_SingleInteger;
        FiWord X1_Integer;
        FiWord X2_Character;
        FiClos X3_Ratio;
        FiWord X4_TextWriter;
        FiClos X5__LT__LT_;
        FiWord X6_newline;
        FiWord X7_print;
        FiClos X8_integer;
        FiWord X9_1;
        FiClos X10_integer;
        FiClos X11__LT__LT_;
        FiClos X12__PLUS_;
        FiClos X13__SLASH_;
        FiClos X14__LT__LT_;
        FiClos X15__PLUS_;
        FiClos X16__SLASH_;
        FiWord X17_dom;
        FiWord X18_dom;
        FiWord X19_dom;
        FiWord X20_dom;
        FiWord X21_dom;
        FiWord X22_dom;
        FiBool X23;
        FiBool X24;
        FiBool X25;
        FiBool X26;
        FiBool X27;
};
static FiProg C0_ratio0;
static void CF0_ratio0(FiEnv e1);
static FiProg C1_f;
static void CF1_f(FiEnv e1);
static FiProg C2_char_MINUS_init;
static FiWord CF2_char_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C3_textwrit_MINUS_init;
static FiWord CF3_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C4_integer_MINUS_init;
static FiWord CF4_integer_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C5_sinteger_MINUS_init;
static FiWord CF5_sinteger_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C6_ratio_MINUS_init;
static FiWord CF6_ratio_MINUS_init(FiEnv e1, FiSInt P0_idx);
extern FiClos G_P9WRR_ratio0;
static FiClos *pG_NQYQM_noOperation;
extern FiClos G_94MT_ratio0__f__778822608;
static FiClos *pG_XIPRL_runtime;
static FiWord *pG_C26T4_integer__Integer__244;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_LD0B5_domainHash_BANG_;
static FiClos *pG_QRAZA_rtDelayedGetExport;
static FiClos *pG_ZZZKG_stdGetWordRetWord0;
static FiClos *pG_VOMTT_ratio__Ratio__9872531;
static FiClos *pG_RSHLY_rtDelayedInit_BANG_;
static FiClos *pG_DLXW8_stdGetWordWordRetWord;
static FiWord *pG_D0MRQ_sinteger__SingleInteg;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiWord *pG_Z4122_textwrit__TextWriter;
static FiWord *pG_PRTGD_char__Character__7004;
static FiClos *pG_AKTR8_char;
static FiClos *pG_EC2QI_textwrit;
static FiClos *pG_WJ27Y_integer;
static FiClos *pG_HAQ5R_sinteger;
static FiClos *pG_JQTZC_ratio;



static void
CF0_ratio0(FiEnv e1)
{
        FiWord T15;
        FiSInt T2, T4, T5, T6, T7, T9, T11, T12, T13, T14;
        FiClos T0, T1, T3, T8, T10;
        PFmt6 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt6 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCall0(void, (*pG_XIPRL_runtime));
        G_P9WRR_ratio0 = (FiClos) (*pG_NQYQM_noOperation);
        T0 = fiClosMake(e0, C4_integer_MINUS_init);
        T1 = fiClosMake(e0, C6_ratio_MINUS_init);
        T3 = fiClosMake(e0, C5_sinteger_MINUS_init);
        T8 = fiClosMake(e0, C3_textwrit_MINUS_init);
        T10 = fiClosMake(e0, C2_char_MINUS_init);
        G_94MT_ratio0__f__778822608 = fiClosMake(e0, C1_f);
        l0->X23 = 0L;
        l0->X24 = 0L;
        l0->X25 = 0L;
        l0->X26 = 0L;
        l0->X27 = 0L;
        l0->X1_Integer = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), T0, 
        	0L);
        l0->X17_dom = l0->X1_Integer;
        T15 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X17_dom, 
        	477900237L, 128860016L);
        l0->X8_integer = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T15);
        T15 = fiCall(FiWord, (*pG_RSHLY_rtDelayedInit_BANG_), T1, 0L);
        l0->X3_Ratio = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T15);
        l0->X18_dom = fiCall(FiWord, l0->X3_Ratio, l0->X1_Integer);
        fiEnvEnsure(l0->X3_Ratio->env);
        T2 = 1117343091L;
L1:	T15 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X18_dom, 
        	200088L, fiAldorHash32Combine((FiSInt) T2, (FiSInt) 
        	149976849L));
        l0->X13__SLASH_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T15);
        l0->X0_SingleInteger = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T3, 0L);
        l0->X19_dom = l0->X0_SingleInteger;
        l0->X9_1 = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), l0->
        	X19_dom, 200090L, 142471813L);
        T15 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X19_dom, 
        	477900237L, 2130877288L);
        l0->X10_integer = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T15);
        l0->X20_dom = fiCall(FiWord, l0->X3_Ratio, l0->
        	X0_SingleInteger);
        fiEnvEnsure(l0->X3_Ratio->env);
        T4 = -1475078997L;
L3:	T15 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X20_dom, 
        	200088L, fiAldorHash32Combine((FiSInt) T4, (FiSInt) 
        	-1825427999L));
        l0->X16__SLASH_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T15);
        fiEnvEnsure(l0->X3_Ratio->env);
        T5 = -1475078997L;
L5:	fiEnvEnsure(l0->X3_Ratio->env);
        T6 = -1475078997L;
L7:	fiEnvEnsure(l0->X3_Ratio->env);
        T7 = -1475078997L;
L9:	T15 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X20_dom, 
        	200084L, fiAldorHash32Combine((FiSInt) T7, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) 32236L, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) T6, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) T5, (FiSInt) 51489085L)))));
        l0->X15__PLUS_ = fiCall(FiClos, (*pG_DLXW8_stdGetWordWordRetWord), 
        	T15);
        l0->X4_TextWriter = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T8, 0L);
        l0->X21_dom = l0->X4_TextWriter;
        l0->X7_print = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X21_dom, 828947258L, 182752316L);
        fiEnvEnsure(l0->X3_Ratio->env);
        T9 = 1117343091L;
L11:	T15 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X18_dom, 
        	51492426L, fiAldorHash32Combine((FiSInt) 182752316L, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) 32236L, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) T9, (FiSInt) -1374746477L))));
        l0->X11__LT__LT_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T15);
        l0->X2_Character = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T10, 0L);
        l0->X22_dom = l0->X2_Character;
        l0->X6_newline = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X22_dom, 493486801L, 803414590L);
        T15 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X22_dom, 
        	51492426L, 936629095L);
        l0->X5__LT__LT_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T15);
        fiEnvEnsure(l0->X3_Ratio->env);
        T11 = 1117343091L;
L13:	fiEnvEnsure(l0->X3_Ratio->env);
        T12 = 1117343091L;
L15:	fiEnvEnsure(l0->X3_Ratio->env);
        T13 = 1117343091L;
L17:	T15 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X18_dom, 
        	200084L, fiAldorHash32Combine((FiSInt) T13, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) 32236L, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) T12, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) T11, (FiSInt) 51489085L)))));
        l0->X12__PLUS_ = fiCall(FiClos, (*pG_DLXW8_stdGetWordWordRetWord), 
        	T15);
        fiEnvEnsure(l0->X3_Ratio->env);
        T14 = -1475078997L;
L19:	T15 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X20_dom, 
        	51492426L, fiAldorHash32Combine((FiSInt) 182752316L, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) 32236L, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) T14, (FiSInt) -1374746477L))));
        l0->X14__LT__LT_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T15);
        CF1_f(e0);
        return ;
L18:	T15 = fiCall(FiWord, l0->X3_Ratio, l0->X0_SingleInteger);
        T14 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), T15);
        goto L19;
L16:	T15 = fiCall(FiWord, l0->X3_Ratio, l0->X1_Integer);
        T13 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), T15);
        goto L17;
L14:	T15 = fiCall(FiWord, l0->X3_Ratio, l0->X1_Integer);
        T12 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), T15);
        goto L15;
L12:	T15 = fiCall(FiWord, l0->X3_Ratio, l0->X1_Integer);
        T11 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), T15);
        goto L13;
L10:	T15 = fiCall(FiWord, l0->X3_Ratio, l0->X1_Integer);
        T9 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), T15);
        goto L11;
L8:	T15 = fiCall(FiWord, l0->X3_Ratio, l0->X0_SingleInteger);
        T7 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), T15);
        goto L9;
L6:	T15 = fiCall(FiWord, l0->X3_Ratio, l0->X0_SingleInteger);
        T6 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), T15);
        goto L7;
L4:	T15 = fiCall(FiWord, l0->X3_Ratio, l0->X0_SingleInteger);
        T5 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), T15);
        goto L5;
L2:	T15 = fiCall(FiWord, l0->X3_Ratio, l0->X0_SingleInteger);
        T4 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), T15);
        goto L3;
L0:	T15 = fiCall(FiWord, l0->X3_Ratio, l0->X1_Integer);
        T2 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), T15);
        goto L1;
}

static struct _FiProg  tmp0_ratio0 = {
        (FiFun) CF0_ratio0,
        0L,
        0L,
        0L
};


static void
CF1_f(FiEnv e1)
{
        FiWord T0_s, T1_r, T2, T3, T4;
        PFmt6 l1;
        l1 = (PFmt6) fiEnvLevel(e1);
        T2 = fiCall(FiWord, l1->X8_integer, (FiWord) "1111111111111111111111111111");
        T3 = fiCall(FiWord, l1->X8_integer, (FiWord) "2222222222222222222222222222");
        T1_r = fiCall(FiWord, l1->X13__SLASH_, T2, T3);
        T2 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X9_1);
        T3 = fiCall(FiWord, l1->X10_integer, (FiWord) "2");
        T2 = fiCall(FiWord, l1->X16__SLASH_, T2, T3);
        T3 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X9_1);
        T4 = fiCall(FiWord, l1->X10_integer, (FiWord) "3");
        T3 = fiCall(FiWord, l1->X16__SLASH_, T3, T4);
        T0_s = fiCall(FiWord, l1->X15__PLUS_, T2, T3);
        T2 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X7_print);
        T2 = fiCall(FiWord, l1->X11__LT__LT_, T2, T1_r);
        T3 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X6_newline);
        fiCall(FiWord, l1->X5__LT__LT_, T2, T3);
        T2 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X7_print);
        T3 = fiCall(FiWord, l1->X12__PLUS_, T1_r, T1_r);
        T2 = fiCall(FiWord, l1->X11__LT__LT_, T2, T3);
        T3 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X6_newline);
        fiCall(FiWord, l1->X5__LT__LT_, T2, T3);
        T2 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X7_print);
        T2 = fiCall(FiWord, l1->X14__LT__LT_, T2, T0_s);
        T3 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l1->X6_newline);
        fiCall(FiWord, l1->X5__LT__LT_, T2, T3);
        return ;
}

static struct _FiProg  tmp1_f = {
        (FiFun) CF1_f,
        0L,
        0L,
        0L
};


static FiWord
CF2_char_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt6 l1;
        l1 = (PFmt6) fiEnvLevel(e1);
        if (l1->X23) goto L0;
        l1->X23 = 1L;
        fiCall0(void, (*pG_AKTR8_char));
L0:	return (FiWord) (*pG_PRTGD_char__Character__7004);
}

static struct _FiProg  tmp2_char_MINUS_init = {
        (FiFun) CF2_char_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF3_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt6 l1;
        l1 = (PFmt6) fiEnvLevel(e1);
        if (l1->X24) goto L0;
        l1->X24 = 1L;
        fiCall0(void, (*pG_EC2QI_textwrit));
L0:	return (FiWord) (*pG_Z4122_textwrit__TextWriter);
}

static struct _FiProg  tmp3_textwrit_MINUS_init = {
        (FiFun) CF3_textwrit_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF4_integer_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt6 l1;
        l1 = (PFmt6) fiEnvLevel(e1);
        if (l1->X25) goto L0;
        l1->X25 = 1L;
        fiCall0(void, (*pG_WJ27Y_integer));
L0:	return (FiWord) (*pG_C26T4_integer__Integer__244);
}

static struct _FiProg  tmp4_integer_MINUS_init = {
        (FiFun) CF4_integer_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF5_sinteger_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt6 l1;
        l1 = (PFmt6) fiEnvLevel(e1);
        if (l1->X26) goto L0;
        l1->X26 = 1L;
        fiCall0(void, (*pG_HAQ5R_sinteger));
L0:	return (FiWord) (*pG_D0MRQ_sinteger__SingleInteg);
}

static struct _FiProg  tmp5_sinteger_MINUS_init = {
        (FiFun) CF5_sinteger_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF6_ratio_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt6 l1;
        l1 = (PFmt6) fiEnvLevel(e1);
        if (l1->X27) goto L0;
        l1->X27 = 1L;
        fiCall0(void, (*pG_JQTZC_ratio));
L0:	return (FiWord) (*pG_VOMTT_ratio__Ratio__9872531);
}

static struct _FiProg  tmp6_ratio_MINUS_init = {
        (FiFun) CF6_ratio_MINUS_init,
        0L,
        0L,
        0L
};

extern int
INIT__0_ratio0(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_ratio(void);
        extern int INIT__0_sinteger(void);
        extern int INIT__0_integer(void);
        extern int INIT__0_textwrit(void);
        extern int INIT__0_char(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_f = &tmp1_f;
        C2_char_MINUS_init = &tmp2_char_MINUS_init;
        C3_textwrit_MINUS_init = &tmp3_textwrit_MINUS_init;
        C4_integer_MINUS_init = &tmp4_integer_MINUS_init;
        C5_sinteger_MINUS_init = &tmp5_sinteger_MINUS_init;
        C6_ratio_MINUS_init = &tmp6_ratio_MINUS_init;
        C0_ratio0 = &tmp0_ratio0;
        fiExportGlobal("G_P9WRR_ratio0", G_P9WRR_ratio0);
        fiExportGlobal("G_94MT_ratio0__f__778822608", 
        	G_94MT_ratio0__f__778822608);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_C26T4_integer__Integer__2448", 
        	pG_C26T4_integer__Integer__244);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_LD0B5_domainHash_BANG_", pG_LD0B5_domainHash_BANG_);
        fiImportGlobal("G_QRAZA_rtDelayedGetExport", 
        	pG_QRAZA_rtDelayedGetExport);
        fiImportGlobal("G_ZZZKG_stdGetWordRetWord0", 
        	pG_ZZZKG_stdGetWordRetWord0);
        fiImportGlobal("G_VOMTT_ratio__Ratio__98725315", 
        	pG_VOMTT_ratio__Ratio__9872531);
        fiImportGlobal("G_RSHLY_rtDelayedInit_BANG_", 
        	pG_RSHLY_rtDelayedInit_BANG_);
        fiImportGlobal("G_DLXW8_stdGetWordWordRetWord0", 
        	pG_DLXW8_stdGetWordWordRetWord);
        fiImportGlobal("G_D0MRQ_sinteger__SingleIntege", 
        	pG_D0MRQ_sinteger__SingleInteg);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_Z4122_textwrit__TextWriter__", 
        	pG_Z4122_textwrit__TextWriter);
        fiImportGlobal("G_PRTGD_char__Character__70042", 
        	pG_PRTGD_char__Character__7004);
        fiImportGlobal("G_AKTR8_char", pG_AKTR8_char);
        fiImportGlobal("G_EC2QI_textwrit", pG_EC2QI_textwrit);
        fiImportGlobal("G_WJ27Y_integer", pG_WJ27Y_integer);
        fiImportGlobal("G_HAQ5R_sinteger", pG_HAQ5R_sinteger);
        fiImportGlobal("G_JQTZC_ratio", pG_JQTZC_ratio);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("ratio");
                fiFileInitializer("sinteger");
                fiFileInitializer("integer");
                fiFileInitializer("textwrit");
                fiFileInitializer("char");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_ratio();
                INIT__0_sinteger();
                INIT__0_integer();
                INIT__0_textwrit();
                INIT__0_char();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}

FiClos G_94MT_ratio0__f__778822608;

static struct _FiClos  tmpClos0_ratio0 = {
        0L,
        (FiProg) &tmp0_ratio0
};
FiClos G_P9WRR_ratio0 = &tmpClos0_ratio0;
