"scan5.as", line 13: a(x)    == )
                     ...........^
[L13 C12] #1 (Error) Syntax error.

"scan5.as", line 14: b(x)    == )
                     ...........^
[L14 C12] #2 (Error) Syntax error.

"scan5.as", line 15: c(x)            == )
                     ...................^
[L15 C20] #3 (Error) Syntax error.

"scan5.as", line 16: d(x)            == )
                     ...................^
[L16 C20] #4 (Error) Syntax error.

"scan5.as", line 25:         e(x)    == )
                     ...................^
[L25 C20] #5 (Error) Syntax error.

"scan5.as", line 26:         f(x)    == )
                     ...................^
[L26 C20] #6 (Error) Syntax error.

"scan5.as", line 27:         g(x)            == )
                     ...........................^
[L27 C28] #7 (Error) Syntax error.

"scan5.as", line 28:         h(x)            == )
                     ...........................^
[L28 C28] #8 (Error) Syntax error.

"scan5.as", line 37:         i(x)    == )
                     ...................^
[L37 C20] #9 (Error) Syntax error.

"scan5.as", line 38:         j(x)    == )
                     ...................^
[L38 C20] #10 (Error) Syntax error.
[L38 C20] #11 (Fatal Error) Too many errors (use `-M emax=n' or `-M no-emax' to change the limit).

