"scan6.as", line 47: 
print << "1 base 37   = " << (37rZ) << " (is invalid)" << newline;
..............................^
[L47 C31] #1 (Error) Syntax error: bad radix specification (2 <= radix <= 36).

"scan6.as", line 48: 
print << "1 base 1    = " << (1rZ)  << " (is invalid)" << newline;
..............................^
[L48 C31] #2 (Error) Syntax error: bad radix specification (2 <= radix <= 36).

