"t1125.as", line 222: 
        operator(t:%):OP                == operator tree t;
.................^
[L222 C18] #1 (Warning) Function returns a domain that might not be constant (which may cause problems if it is used in a dependent type).

"t1125.as", line 224:         local operator(t:Tree):OP       == t.oper;
                      .......................^
[L224 C24] #2 (Warning) Function returns a domain that might not be constant (which may cause problems if it is used in a dependent type).

"t1125.as", line 408:         operator(t:%):OP                == rep(t).uop;
                      .................^
[L408 C18] #3 (Warning) Function returns a domain that might not be constant (which may cause problems if it is used in a dependent type).

