/*
 * C code generated by Aldor from file "triv3ai.as".
 */

#include "foam_c.h"

typedef struct Fmt5  *PFmt5;
struct Fmt5 {
        FiWord X0_Character;
        FiWord X1_String;
        FiWord X2_TextWriter;
        FiWord X3_print;
        FiClos X4__LT__LT_;
        FiWord X5_newline;
        FiClos X6_string;
        FiClos X7__LT__LT_;
        FiWord X8_dom;
        FiWord X9_dom;
        FiWord X10_dom;
        FiBool X11;
        FiBool X12;
        FiBool X13;
};
static FiProg C0_triv3ai;
static void CF0_triv3ai(FiEnv e1);
static FiProg C1_string_MINUS_init;
static FiWord CF1_string_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C2_char_MINUS_init;
static FiWord CF2_char_MINUS_init(FiEnv e1, FiSInt P0_idx);
static FiProg C3_textwrit_MINUS_init;
static FiWord CF3_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx);
extern FiClos G_FGKIH_triv3ai;
static FiClos *pG_NQYQM_noOperation;
static FiClos *pG_XIPRL_runtime;
static FiWord *pG_Z4122_textwrit__TextWriter;
static FiClos *pG_KK8CX_rtLazyDomFrInit;
static FiClos *pG_LD0B5_domainHash_BANG_;
static FiClos *pG_4NZQI_lazyGetExport_BANG_;
static FiClos *pG_R3D1K_lazyForceImport;
static FiWord *pG_OI71W_string__String__90554;
static FiClos *pG_QRAZA_rtDelayedGetExport;
static FiClos *pG_ZZZKG_stdGetWordRetWord0;
static FiClos *pG_DLXW8_stdGetWordWordRetWord;
static FiWord *pG_PRTGD_char__Character__7004;
static FiClos *pG_OGNYK_string;
static FiClos *pG_AKTR8_char;
static FiClos *pG_EC2QI_textwrit;



static void
CF0_triv3ai(FiEnv e1)
{
        FiWord T4, T7;
        FiSInt T3, T5, T6;
        FiClos T0, T1, T2;
        PFmt5 l0;
        FiEnv e0;
        l0 = fi0New(struct Fmt5 , CENSUS_EnvLevel);
        e0 = fiEnvPush(l0, e1);
        fiCall0(void, (*pG_XIPRL_runtime));
        G_FGKIH_triv3ai = (FiClos) (*pG_NQYQM_noOperation);
        T0 = fiClosMake(e0, C3_textwrit_MINUS_init);
        T1 = fiClosMake(e0, C1_string_MINUS_init);
        T2 = fiClosMake(e0, C2_char_MINUS_init);
        l0->X11 = 0L;
        l0->X12 = 0L;
        l0->X13 = 0L;
        l0->X2_TextWriter = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T0, 0L);
        l0->X8_dom = l0->X2_TextWriter;
        T3 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), l0->
        	X2_TextWriter);
        l0->X3_print = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X8_dom, 828947258L, T3);
        l0->X1_String = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), T1, 
        	0L);
        l0->X9_dom = l0->X1_String;
        T3 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), l0->X1_String);
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X9_dom, 
        	585283853L, fiAldorHash32Combine((FiSInt) T3, (FiSInt) 
        	-616151683L));
        l0->X6_string = fiCall(FiClos, (*pG_ZZZKG_stdGetWordRetWord0), 
        	T4);
        T3 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), l0->
        	X2_TextWriter);
        T5 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), l0->X1_String);
        T6 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), l0->
        	X2_TextWriter);
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X9_dom, 
        	51492426L, fiAldorHash32Combine((FiSInt) T3, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) 32236L, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) T5, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) T6, (FiSInt) 51489085L)))));
        l0->X7__LT__LT_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T4);
        l0->X0_Character = fiCall(FiWord, (*pG_KK8CX_rtLazyDomFrInit), 
        	T2, 0L);
        l0->X10_dom = l0->X0_Character;
        T3 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), l0->
        	X0_Character);
        l0->X5_newline = fiCall(FiWord, (*pG_4NZQI_lazyGetExport_BANG_), 
        	l0->X10_dom, 493486801L, T3);
        T3 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), l0->
        	X2_TextWriter);
        T5 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), l0->
        	X0_Character);
        T6 = fiCall(FiSInt, (*pG_LD0B5_domainHash_BANG_), l0->
        	X2_TextWriter);
        T4 = fiCall(FiWord, (*pG_QRAZA_rtDelayedGetExport), l0->X10_dom, 
        	51492426L, fiAldorHash32Combine((FiSInt) T3, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) 32236L, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) T5, (FiSInt) 
        	fiAldorHash32Combine((FiSInt) T6, (FiSInt) 51489085L)))));
        l0->X4__LT__LT_ = fiCall(FiClos, (*
        	pG_DLXW8_stdGetWordWordRetWord), T4);
        T4 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X3_print);
        T7 = fiCall(FiWord, l0->X6_string, (FiWord) "!");
        T4 = fiCall(FiWord, l0->X7__LT__LT_, T4, T7);
        T7 = fiCall(FiWord, (*pG_R3D1K_lazyForceImport), l0->X5_newline);
        fiCall(FiWord, l0->X4__LT__LT_, T4, T7);
        return ;
}

static struct _FiProg  tmp0_triv3ai = {
        (FiFun) CF0_triv3ai,
        0L,
        0L,
        0L
};


static FiWord
CF1_string_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X11) goto L0;
        l1->X11 = 1L;
        fiCall0(void, (*pG_OGNYK_string));
L0:	return (FiWord) (*pG_OI71W_string__String__90554);
}

static struct _FiProg  tmp1_string_MINUS_init = {
        (FiFun) CF1_string_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF2_char_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X12) goto L0;
        l1->X12 = 1L;
        fiCall0(void, (*pG_AKTR8_char));
L0:	return (FiWord) (*pG_PRTGD_char__Character__7004);
}

static struct _FiProg  tmp2_char_MINUS_init = {
        (FiFun) CF2_char_MINUS_init,
        0L,
        0L,
        0L
};


static FiWord
CF3_textwrit_MINUS_init(FiEnv e1, FiSInt P0_idx)
{
        PFmt5 l1;
        l1 = (PFmt5) fiEnvLevel(e1);
        if (l1->X13) goto L0;
        l1->X13 = 1L;
        fiCall0(void, (*pG_EC2QI_textwrit));
L0:	return (FiWord) (*pG_Z4122_textwrit__TextWriter);
}

static struct _FiProg  tmp3_textwrit_MINUS_init = {
        (FiFun) CF3_textwrit_MINUS_init,
        0L,
        0L,
        0L
};

extern int
INIT__0_triv3ai(void)
{
        
        extern int INIT__0_rtexns(void);
        extern int INIT__0_textwrit(void);
        extern int INIT__0_char(void);
        extern int INIT__0_string(void);
        extern int INIT__0_runtime(void);
        static int initialized = 0;
        if (initialized) 
                return 0L;
        else 
                initialized = 1;
        C1_string_MINUS_init = &tmp1_string_MINUS_init;
        C2_char_MINUS_init = &tmp2_char_MINUS_init;
        C3_textwrit_MINUS_init = &tmp3_textwrit_MINUS_init;
        C0_triv3ai = &tmp0_triv3ai;
        fiExportGlobal("G_FGKIH_triv3ai", G_FGKIH_triv3ai);
        fiImportGlobal("G_NQYQM_noOperation", pG_NQYQM_noOperation);
        fiImportGlobal("G_XIPRL_runtime", pG_XIPRL_runtime);
        fiImportGlobal("G_Z4122_textwrit__TextWriter__", 
        	pG_Z4122_textwrit__TextWriter);
        fiImportGlobal("G_KK8CX_rtLazyDomFrInit", pG_KK8CX_rtLazyDomFrInit);
        fiImportGlobal("G_LD0B5_domainHash_BANG_", pG_LD0B5_domainHash_BANG_);
        fiImportGlobal("G_4NZQI_lazyGetExport_BANG_", 
        	pG_4NZQI_lazyGetExport_BANG_);
        fiImportGlobal("G_R3D1K_lazyForceImport", pG_R3D1K_lazyForceImport);
        fiImportGlobal("G_OI71W_string__String__905549", 
        	pG_OI71W_string__String__90554);
        fiImportGlobal("G_QRAZA_rtDelayedGetExport", 
        	pG_QRAZA_rtDelayedGetExport);
        fiImportGlobal("G_ZZZKG_stdGetWordRetWord0", 
        	pG_ZZZKG_stdGetWordRetWord0);
        fiImportGlobal("G_DLXW8_stdGetWordWordRetWord0", 
        	pG_DLXW8_stdGetWordWordRetWord);
        fiImportGlobal("G_PRTGD_char__Character__70042", 
        	pG_PRTGD_char__Character__7004);
        fiImportGlobal("G_OGNYK_string", pG_OGNYK_string);
        fiImportGlobal("G_AKTR8_char", pG_AKTR8_char);
        fiImportGlobal("G_EC2QI_textwrit", pG_EC2QI_textwrit);
        if (fiFileInitializer) {
                fiFileInitializer("rtexns");
                fiFileInitializer("textwrit");
                fiFileInitializer("char");
                fiFileInitializer("string");
                fiFileInitializer("runtime");
        }
        else {
                INIT__0_rtexns();
                INIT__0_textwrit();
                INIT__0_char();
                INIT__0_string();
                INIT__0_runtime();
        }
        /* "---------------------------" */
        return 0L;
}


static struct _FiClos  tmpClos0_triv3ai = {
        0L,
        (FiProg) &tmp0_triv3ai
};
FiClos G_FGKIH_triv3ai = &tmpClos0_triv3ai;
