;;;
;;; Lisp code generated by Aldor from file "triv4.as".
;;;

(in-package "FOAM-USER" :use '("FOAM" "LISP"))

(declare-prog (|C0-triv4-triv4|) ((|e1| |Env|)))

(declare-prog
  (|C1-triv4-integer| |SInt|)
  ((|P0-s| |Word|) (|e1| |Env|)))

(declare-prog
  (|C2-triv4-string| |Arr|)
  ((|P0-s| |Word|) (|e1| |Env|)))

(declare-prog (|C3-triv4-printTriv|) ((|e1| |Env|)))

(declare-type |G-triv4| |Clos|)

(declare-type |G-triv4_integer_315047826| |Clos|)

(declare-type |G-triv4_string_033347024| |Clos|)

(declare-type |G-triv4_printTriv_778822608| |Clos|)

(defspecials
  |G-triv4_printTriv_778822608|
  |G-triv4_string_033347024|
  |G-triv4_integer_315047826|)

(|DDecl| |Struct-triv4-5| (p0-0 |Arr|) (p1-1 |SInt|))

(|DDecl| |Struct-triv4-6| (p0-0 |Arr|))

(defprog
  ((|C0-triv4-triv4|) ((|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| nil)
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall| |G-runtime|)
  (setq |G-triv4| |G-noOperation|)
  (setq |G-triv4_integer_315047826| (|Clos| |e0| |C1-triv4-integer|))
  (setq |G-triv4_string_033347024| (|Clos| |e0| |C2-triv4-string|))
  (setq
    |G-triv4_printTriv_778822608|
    (|Clos| |e0| |C3-triv4-printTriv|))
  (|C3-triv4-printTriv| |e0|)
  (block-return |C0-triv4-triv4| ()))

(defprog
  ((|C1-triv4-integer| |SInt|) ((|P0-s| |Word|) (|e1| |Env|)))
  ()
  (block-return |C1-triv4-integer| (|ArrToSInt| |P0-s|)))

(defprog
  ((|C2-triv4-string| |Arr|) ((|P0-s| |Word|) (|e1| |Env|)))
  ()
  (block-return |C2-triv4-string| |P0-s|))

(defprog
  ((|C3-triv4-printTriv|) ((|e1| |Env|)))
  ()
  (|printf-<stdio.h>|
    (|C2-triv4-string| (|MakeLit| "%ld ") |e1|)
    (|C1-triv4-integer| (|MakeLit| "42") |e1|))
  (|puts-<stdio.h>| (|C2-triv4-string| (|MakeLit| "Skidoo") |e1|))
  (block-return |C3-triv4-printTriv| ()))

(setq |G-triv4| (|Clos| nil |C0-triv4-triv4|))

(setq |G-triv4_Type_547582661| nil)

(setq |G-triv4_Tuple_967545652| nil)

(setq |G-triv4_->_739550684| nil)

(setq |G-triv4_Literal_547582661| nil)

(setq |G-triv4_Arr_547582661| nil)

(setq |G-triv4_SInt_547582661| nil)

(setq |G-triv4_printTriv_778822608| nil)

(setq |G-triv4_string_033347024| nil)

(setq |G-triv4_integer_315047826| nil)

(file-imports
  '((|G-runtime| "runtime" |initializer| "")
      (|G-noOperation| "noOperation" 0 "")))

(file-exports
  '((|G-triv4_integer_315047826| "integer" 315047826 "triv4")
      (|G-triv4_string_033347024| "string" 33347024 "triv4")
      (|G-triv4_printTriv_778822608| "printTriv" 778822608 "triv4")
      (|G-triv4_SInt_547582661| "SInt" 547582661 "triv4")
      (|G-triv4_Arr_547582661| "Arr" 547582661 "triv4")
      (|G-triv4_Literal_547582661| "Literal" 547582661 "triv4")
      (|G-triv4_->_739550684| "->" 739550684 "triv4")
      (|G-triv4_Tuple_967545652| "Tuple" 967545652 "triv4")
      (|G-triv4_Type_547582661| "Type" 547582661 "triv4")
      (|G-triv4| "triv4" |initializer| "")))
