"tuple0.as", line 30: (3,4,5,6)
                      .^
[L30 C2] #1 (Error) Have determined 16 possible types for the expression.
	Meaning 1: Integer, Integer, Integer, Integer
	Meaning 2: SingleInteger, Integer, Integer, Integer
	Meaning 3: Integer, SingleInteger, Integer, Integer
	Meaning 4: SingleInteger, SingleInteger, Integer, Integer
	Meaning 5: Integer, Integer, SingleInteger, Integer
	Meaning 6: SingleInteger, Integer, SingleInteger, Integer
	Meaning 7: Integer, SingleInteger, SingleInteger, Integer
	Meaning 8: SingleInteger, SingleInteger, SingleInteger, Integer
	Meaning 9: Integer, Integer, Integer, SingleInteger
	Meaning 10: SingleInteger, Integer, Integer, SingleInteger
	Meaning 11: Integer, SingleInteger, Integer, SingleInteger
	Meaning 12: SingleInteger, SingleInteger, Integer, SingleInteger
	Meaning 13: Integer, Integer, SingleInteger, SingleInteger
	Meaning 14: SingleInteger, Integer, SingleInteger, SingleInteger
	Meaning 15: Integer, SingleInteger, SingleInteger, SingleInteger
	Meaning 16: SingleInteger, SingleInteger, SingleInteger, SingleInteger

