;;;
;;; Lisp code generated by Aldor from file "tuple2.as".
;;;

(in-package "FOAM-USER" :use '("FOAM" "LISP"))

(declare-prog (|C0-tuple2-tuple2|) ((|e1| |Env|)))

(declare-prog
  (|C1-tuple2-id| |Word| |Word| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|P2-k| |Word|) (|e1| |Env|)))

(declare-prog
  (|C2-tuple2-*| |Clos|)
  ((|P0-f| |Clos|) (|P1-g| |Clos|) (|e1| |Env|)))

(declare-prog
  (|C3-tuple2-*| |Word| |Word| |Word|)
  ((|P0-i| |Word|) (|P1-j| |Word|) (|P2-k| |Word|) (|e1| |Env|)))

(declare-prog
  (|C4-tuple2-^| |Clos|)
  ((|P0-f| |Clos|) (|P1-p| |Word|) (|e1| |Env|)))

(declare-prog
  (|C5-tuple2-cycle| |Word| |Word| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|P2-c| |Word|) (|e1| |Env|)))

(declare-prog
  (|C6-tuple2-printIII|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|P2-c| |Word|) (|e1| |Env|)))

(declare-prog (|C7-tuple2-foo|) ((|e1| |Env|)))

(declare-prog
  (|C8-tuple2-bar| |Word| |Word| |Word|)
  ((|P0-a| |Word|) (|P1-b| |Word|) (|P2-c| |Word|) (|e1| |Env|)))

(declare-prog
  (|C9-tuple2-baz| |Word| |Word| |Word|)
  ((|P0-n| |Word|) (|e1| |Env|)))

(declare-prog
  (|C10-tuple2-string-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C11-tuple2-char-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C12-tuple2-textwrit-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-prog
  (|C13-tuple2-integer-init| |Word|)
  ((|P0-idx| |SInt|) (|e1| |Env|)))

(declare-type |G-tuple2| |Clos|)

(declare-type |G-tuple2_id_523605238| |Clos|)

(declare-type |G-tuple2_*_767965809| |Clos|)

(declare-type |G-tuple2_^_231669443| |Clos|)

(declare-type |G-tuple2_cycle_523605238| |Clos|)

(declare-type |G-tuple2_printIII_281389027| |Clos|)

(declare-type |G-tuple2_foo_778822608| |Clos|)

(declare-type |G-tuple2_bar_523605238| |Clos|)

(declare-type |G-tuple2_baz_1047290136| |Clos|)

(defspecials
  |G-tuple2_baz_1047290136|
  |G-tuple2_bar_523605238|
  |G-tuple2_foo_778822608|
  |G-tuple2_printIII_281389027|
  |G-tuple2_cycle_523605238|
  |G-tuple2_^_231669443|
  |G-tuple2_*_767965809|
  |G-tuple2_id_523605238|)

(|DDecl| |Struct-tuple2-5| (\-0 |Word|) (\-1 |Word|) (\-2 |Word|))

(|DDecl| |Struct-tuple2-6| (\-0 |Word|) (\-1 |Word|) (\-2 |Word|))

(|DDecl| |Struct-tuple2-7| (|f-0| |Clos|) (|g-1| |Clos|))

(|DDecl| |Struct-tuple2-8| (\-0 |Word|) (\-1 |Word|) (\-2 |Word|))

(|DDecl|
  |Struct-tuple2-10|
  (\-0 |Word|)
  (\-1 |Word|)
  (\-2 |Word|)
  (\-3 |Word|)
  (\-4 |Word|)
  (\-5 |Word|))

(|DDecl| |Struct-tuple2-11| (\-0 |Word|) (\-1 |Word|) (\-2 |Word|))

(|DDecl|
  |Struct-tuple2-12|
  (|Integer-0| |Word|)
  (|Character-1| |Word|)
  (|String-2| |Word|)
  (|TextWriter-3| |Word|)
  (|string-4| |Clos|)
  (<<-5 |Clos|)
  (<<-6 |Clos|)
  (|newline-7| |Word|)
  (|print-8| |Word|)
  (|integer-9| |Clos|)
  (=-10 |Clos|)
  (<<-11 |Clos|)
  (>-12 |Clos|)
  (<-13 |Clos|)
  (\0-14 |Word|)
  (\--15 |Clos|)
  (\1-16 |Word|)
  (|quo-17| |Clos|)
  (|odd?-18| |Clos|)
  (|dom-19| |Word|)
  (|dom-20| |Word|)
  (|dom-21| |Word|)
  (|dom-22| |Word|)
  (\-23 |Bool|)
  (\-24 |Bool|)
  (\-25 |Bool|)
  (\-26 |Bool|))

(defprog
  ((|C0-tuple2-tuple2|) ((|e1| |Env|)))
  ((t0 |Clos|)
    (t1 |Clos|)
    (t2 |Clos|)
    (t3 |Clos|)
    (t4 |Word|)
    (t5 |Word|)
    (t6 |Word|)
    (t7 |Word|)
    (t8 |Word|)
    (t9 |Word|)
    (t10 |Word|)
    (t11 |Word|)
    (t12 |Word|)
    (t13 |Word|)
    (t14 |Word|)
    (t15 |Word|)
    (|l0| |Level|)
    (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-tuple2-12| |Struct-tuple2-12|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|CCall| |G-runtime|)
  (setq |G-tuple2| |G-noOperation|)
  (setq |G-tuple2_id_523605238| (|Clos| |e0| |C1-tuple2-id|))
  (setq |G-tuple2_*_767965809| (|Clos| |e0| |C2-tuple2-*|))
  (setq t0 (|Clos| |e0| |C13-tuple2-integer-init|))
  (setq |G-tuple2_^_231669443| (|Clos| |e0| |C4-tuple2-^|))
  (setq |G-tuple2_cycle_523605238| (|Clos| |e0| |C5-tuple2-cycle|))
  (setq t1 (|Clos| |e0| |C12-tuple2-textwrit-init|))
  (setq t2 (|Clos| |e0| |C10-tuple2-string-init|))
  (setq t3 (|Clos| |e0| |C11-tuple2-char-init|))
  (setq
    |G-tuple2_printIII_281389027|
    (|Clos| |e0| |C6-tuple2-printIII|))
  (setq |G-tuple2_foo_778822608| (|Clos| |e0| |C7-tuple2-foo|))
  (setq |G-tuple2_bar_523605238| (|Clos| |e0| |C8-tuple2-bar|))
  (setq |G-tuple2_baz_1047290136| (|Clos| |e0| |C9-tuple2-baz|))
  (|SetLex| |Struct-tuple2-12--23| 23 |l0| (the |Bool| nil))
  (|SetLex| |Struct-tuple2-12--24| 24 |l0| (the |Bool| nil))
  (|SetLex| |Struct-tuple2-12--25| 25 |l0| (the |Bool| nil))
  (|SetLex| |Struct-tuple2-12--26| 26 |l0| (the |Bool| nil))
  (|SetLex|
    |Struct-tuple2-12-Integer-0|
    0
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t0 (the |SInt| 0)))
  (|SetLex|
    |Struct-tuple2-12-dom-19|
    19
    |l0|
    (|Lex| |Struct-tuple2-12-Integer-0| 0 |l0|))
  (|SetLex|
    |Struct-tuple2-12-1-16|
    16
    |l0|
    (|CCall|
      |G-lazyGetExport!|
      (|Lex| |Struct-tuple2-12-dom-19| 19 |l0|)
      (the |SInt| 200090)
      (the |SInt| 484208045)))
  (|SetLex|
    |Struct-tuple2-12-<-13|
    13
    |l0|
    (|CCall|
      |G-stdGetWordWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-tuple2-12-dom-19| 19 |l0|)
        (the |SInt| 200101)
        (the |SInt| -1296727158))))
  (|SetLex|
    |Struct-tuple2-12-=-10|
    10
    |l0|
    (|CCall|
      |G-stdGetWordWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-tuple2-12-dom-19| 19 |l0|)
        (the |SInt| 200102)
        (the |SInt| -1296727158))))
  (|SetLex|
    |Struct-tuple2-12-odd?-18|
    18
    |l0|
    (|CCall|
      |G-stdGetWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-tuple2-12-dom-19| 19 |l0|)
        (the |SInt| 665072666)
        (the |SInt| -1376822255))))
  (|SetLex|
    |Struct-tuple2-12-integer-9|
    9
    |l0|
    (|CCall|
      |G-stdGetWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-tuple2-12-dom-19| 19 |l0|)
        (the |SInt| 477900237)
        (the |SInt| 128860016))))
  (|SetLex|
    |Struct-tuple2-12-quo-17|
    17
    |l0|
    (|CCall|
      |G-stdGetWordWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-tuple2-12-dom-19| 19 |l0|)
        (the |SInt| 318204816)
        (the |SInt| 2104366580))))
  (|SetLex|
    |Struct-tuple2-12-TextWriter-3|
    3
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t1 (the |SInt| 0)))
  (|SetLex|
    |Struct-tuple2-12-dom-20|
    20
    |l0|
    (|Lex| |Struct-tuple2-12-TextWriter-3| 3 |l0|))
  (|SetLex|
    |Struct-tuple2-12-print-8|
    8
    |l0|
    (|CCall|
      |G-lazyGetExport!|
      (|Lex| |Struct-tuple2-12-dom-20| 20 |l0|)
      (the |SInt| 828947258)
      (the |SInt| 182752316)))
  (|SetLex|
    |Struct-tuple2-12-String-2|
    2
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t2 (the |SInt| 0)))
  (|SetLex|
    |Struct-tuple2-12-dom-21|
    21
    |l0|
    (|Lex| |Struct-tuple2-12-String-2| 2 |l0|))
  (|SetLex|
    |Struct-tuple2-12-string-4|
    4
    |l0|
    (|CCall|
      |G-stdGetWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-tuple2-12-dom-21| 21 |l0|)
        (the |SInt| 585283853)
        (the |SInt| -1916843600))))
  (|SetLex|
    |Struct-tuple2-12-<<-5|
    5
    |l0|
    (|CCall|
      |G-stdGetWordWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-tuple2-12-dom-21| 21 |l0|)
        (the |SInt| 51492426)
        (the |SInt| -421540838))))
  (|SetLex|
    |Struct-tuple2-12-<<-11|
    11
    |l0|
    (|CCall|
      |G-stdGetWordWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-tuple2-12-dom-19| 19 |l0|)
        (the |SInt| 51492426)
        (the |SInt| -2075677734))))
  (|SetLex|
    |Struct-tuple2-12-Character-1|
    1
    |l0|
    (|CCall| |G-rtLazyDomFrInit| t3 (the |SInt| 0)))
  (|SetLex|
    |Struct-tuple2-12-dom-22|
    22
    |l0|
    (|Lex| |Struct-tuple2-12-Character-1| 1 |l0|))
  (|SetLex|
    |Struct-tuple2-12-newline-7|
    7
    |l0|
    (|CCall|
      |G-lazyGetExport!|
      (|Lex| |Struct-tuple2-12-dom-22| 22 |l0|)
      (the |SInt| 493486801)
      (the |SInt| 803414590)))
  (|SetLex|
    |Struct-tuple2-12-<<-6|
    6
    |l0|
    (|CCall|
      |G-stdGetWordWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-tuple2-12-dom-22| 22 |l0|)
        (the |SInt| 51492426)
        (the |SInt| 936629095))))
  (|SetLex|
    |Struct-tuple2-12->-12|
    12
    |l0|
    (|CCall|
      |G-stdGetWordWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-tuple2-12-dom-19| 19 |l0|)
        (the |SInt| 200103)
        (the |SInt| -1296727158))))
  (|SetLex|
    |Struct-tuple2-12---15|
    15
    |l0|
    (|CCall|
      |G-stdGetWordWordRetWord0|
      (|CCall|
        |G-rtDelayedGetExport!|
        (|Lex| |Struct-tuple2-12-dom-19| 19 |l0|)
        (the |SInt| 200086)
        (the |SInt| 2104366580))))
  (|SetLex|
    |Struct-tuple2-12-0-14|
    14
    |l0|
    (|CCall|
      |G-lazyGetExport!|
      (|Lex| |Struct-tuple2-12-dom-19| 19 |l0|)
      (the |SInt| 200089)
      (the |SInt| 484208045)))
  (|C7-tuple2-foo| |e0|)
  (multiple-value-setq
    (t4 t5 t6)
    (|C8-tuple2-bar|
      (|CCall| |G-lazyForceImport| (|Lex| |Struct-tuple2-12-1-16| 16 |l0|))
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l0|)
        (|MakeLit| "2"))
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l0|)
        (|MakeLit| "3"))
      |e0|))
  (|C6-tuple2-printIII| t4 t5 t6 |e0|)
  (multiple-value-setq
    (t7 t8 t9)
    (|C8-tuple2-bar|
      (|CCall| |G-lazyForceImport| (|Lex| |Struct-tuple2-12-0-14| 14 |l0|))
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l0|)
        (|MakeLit| "2"))
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l0|)
        (|MakeLit| "3"))
      |e0|))
  (|C6-tuple2-printIII| t7 t8 t9 |e0|)
  (multiple-value-setq
    (t10 t11 t12)
    (|C9-tuple2-baz|
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l0|)
        (|MakeLit| "7"))
      |e0|))
  (|C6-tuple2-printIII| t10 t11 t12 |e0|)
  (multiple-value-setq
    (t13 t14 t15)
    (|C9-tuple2-baz|
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l0|)
        (|MakeLit| "20"))
      |e0|))
  (|C6-tuple2-printIII| t13 t14 t15 |e0|)
  (block-return |C0-tuple2-tuple2| ()))

(defprog
  ((|C1-tuple2-id| |Word| |Word| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|P2-k| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-tuple2-6| |Struct-tuple2-6|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|SetLex| |Struct-tuple2-6--0| 0 |l0| |P0-i|)
  (|SetLex| |Struct-tuple2-6--1| 1 |l0| |P1-j|)
  (|SetLex| |Struct-tuple2-6--2| 2 |l0| |P2-k|)
  (block-return
    |C1-tuple2-id|
    (values
      (|Lex| |Struct-tuple2-6--0| 0 |l0|)
      (|Lex| |Struct-tuple2-6--1| 1 |l0|)
      (|Lex| |Struct-tuple2-6--2| 2 |l0|))))

(defprog
  ((|C2-tuple2-*| |Clos|)
    ((|P0-f| |Clos|) (|P1-g| |Clos|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-tuple2-7| |Struct-tuple2-7|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|SetLex| |Struct-tuple2-7-f-0| 0 |l0| |P0-f|)
  (|SetLex| |Struct-tuple2-7-g-1| 1 |l0| |P1-g|)
  (block-return |C2-tuple2-*| (|Clos| |e0| |C3-tuple2-*|)))

(defprog
  ((|C3-tuple2-*| |Word| |Word| |Word|)
    ((|P0-i| |Word|) (|P1-j| |Word|) (|P2-k| |Word|) (|e1| |Env|)))
  ((t0 |Word|)
    (t1 |Word|)
    (t2 |Word|)
    (t3 |Word|)
    (t4 |Word|)
    (t5 |Word|)
    (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (multiple-value-setq
    (t0 t1 t2)
    (|CCall| (|Lex| |Struct-tuple2-7-g-1| 1 |l1|) |P0-i| |P1-j| |P2-k|))
  (multiple-value-setq
    (t3 t4 t5)
    (|CCall| (|Lex| |Struct-tuple2-7-f-0| 0 |l1|) t0 t1 t2))
  (block-return |C3-tuple2-*| (values t3 t4 t5)))

(defprog
  ((|C4-tuple2-^| |Clos|)
    ((|P0-f| |Clos|) (|P1-p| |Word|) (|e1| |Env|)))
  ((t0 |Clos|) (t1 |Clos|) (t2 |Clos|) (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when
      (|CCall|
        (|Lex| |Struct-tuple2-12-<-13| 13 |l1|)
        |P1-p|
        (|CCall| |G-lazyForceImport| (|Lex| |Struct-tuple2-12-1-16| 16 |l1|)))
      (go |Lab0|))
    (when
      (|CCall|
        (|Lex| |Struct-tuple2-12-=-10| 10 |l1|)
        |P1-p|
        (|CCall| |G-lazyForceImport| (|Lex| |Struct-tuple2-12-1-16| 16 |l1|)))
      (go |Lab2|))
    (when
      (|CCall| (|Lex| |Struct-tuple2-12-odd?-18| 18 |l1|) |P1-p|)
      (go |Lab4|))
    (setq
      t2
      (|C4-tuple2-^|
        (|C2-tuple2-*| |P0-f| |P0-f| |e1|)
        (|CCall|
          (|Lex| |Struct-tuple2-12-quo-17| 17 |l1|)
          |P1-p|
          (|CCall|
            (|Lex| |Struct-tuple2-12-integer-9| 9 |l1|)
            (|MakeLit| "2")))
        |e1|))
    |Lab5|
    (setq t1 t2)
    |Lab3|
    (setq t0 t1)
    |Lab1|
    (block-return |C4-tuple2-^| t0)
    |Lab4|
    (setq
      t2
      (|C2-tuple2-*|
        |P0-f|
        (|C4-tuple2-^|
          (|C2-tuple2-*| |P0-f| |P0-f| |e1|)
          (|CCall|
            (|Lex| |Struct-tuple2-12-quo-17| 17 |l1|)
            |P1-p|
            (|CCall|
              (|Lex| |Struct-tuple2-12-integer-9| 9 |l1|)
              (|MakeLit| "2")))
          |e1|)
        |e1|))
    (go |Lab5|)
    |Lab2|
    (setq t1 |P0-f|)
    (go |Lab3|)
    |Lab0|
    (setq t0 |G-tuple2_id_523605238|)
    (go |Lab1|)))

(defprog
  ((|C5-tuple2-cycle| |Word| |Word| |Word|)
    ((|P0-a| |Word|) (|P1-b| |Word|) (|P2-c| |Word|) (|e1| |Env|)))
  ((|l0| |Level|) (|e0| |Env|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-tuple2-8| |Struct-tuple2-8|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (|SetLex| |Struct-tuple2-8--0| 0 |l0| |P2-c|)
  (|SetLex| |Struct-tuple2-8--1| 1 |l0| |P0-a|)
  (|SetLex| |Struct-tuple2-8--2| 2 |l0| |P1-b|)
  (block-return
    |C5-tuple2-cycle|
    (values
      (|Lex| |Struct-tuple2-8--0| 0 |l0|)
      (|Lex| |Struct-tuple2-8--1| 1 |l0|)
      (|Lex| |Struct-tuple2-8--2| 2 |l0|))))

(defprog
  ((|C6-tuple2-printIII|)
    ((|P0-a| |Word|) (|P1-b| |Word|) (|P2-c| |Word|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (|CCall|
    (|Lex| |Struct-tuple2-12-<<-6| 6 |l1|)
    (|CCall|
      (|Lex| |Struct-tuple2-12-<<-11| 11 |l1|)
      (|CCall|
        (|Lex| |Struct-tuple2-12-<<-5| 5 |l1|)
        (|CCall|
          (|Lex| |Struct-tuple2-12-<<-11| 11 |l1|)
          (|CCall|
            (|Lex| |Struct-tuple2-12-<<-5| 5 |l1|)
            (|CCall|
              (|Lex| |Struct-tuple2-12-<<-11| 11 |l1|)
              (|CCall|
                (|Lex| |Struct-tuple2-12-<<-5| 5 |l1|)
                (|CCall|
                  |G-lazyForceImport|
                  (|Lex| |Struct-tuple2-12-print-8| 8 |l1|))
                (|CCall|
                  (|Lex| |Struct-tuple2-12-string-4| 4 |l1|)
                  (|MakeLit| "a = ")))
              |P0-a|)
            (|CCall|
              (|Lex| |Struct-tuple2-12-string-4| 4 |l1|)
              (|MakeLit| " b = ")))
          |P1-b|)
        (|CCall|
          (|Lex| |Struct-tuple2-12-string-4| 4 |l1|)
          (|MakeLit| " c = ")))
      |P2-c|)
    (|CCall|
      |G-lazyForceImport|
      (|Lex| |Struct-tuple2-12-newline-7| 7 |l1|)))
  (block-return |C6-tuple2-printIII| ()))

(defprog
  ((|C7-tuple2-foo|) ((|e1| |Env|)))
  ((t0 |Word|)
    (t1 |Word|)
    (t2 |Word|)
    (t3 |Word|)
    (t4 |Word|)
    (t5 |Word|)
    (t6 |Word|)
    (t7 |Word|)
    (t8 |Word|)
    (t9 |Clos|)
    (t10 |Word|)
    (t11 |Word|)
    (t12 |Word|)
    (t13 |Clos|)
    (t14 |Word|)
    (t15 |Word|)
    (t16 |Word|)
    (|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (multiple-value-setq
    (t0 t1 t2)
    (|C5-tuple2-cycle|
      (|CCall| |G-lazyForceImport| (|Lex| |Struct-tuple2-12-1-16| 16 |l1|))
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l1|)
        (|MakeLit| "2"))
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l1|)
        (|MakeLit| "3"))
      |e1|))
  (|C6-tuple2-printIII| t0 t1 t2 |e1|)
  (multiple-value-setq
    (t3 t4 t5)
    (|C5-tuple2-cycle|
      (|CCall| |G-lazyForceImport| (|Lex| |Struct-tuple2-12-1-16| 16 |l1|))
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l1|)
        (|MakeLit| "2"))
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l1|)
        (|MakeLit| "3"))
      |e1|))
  (multiple-value-setq (t6 t7 t8) (|C5-tuple2-cycle| t3 t4 t5 |e1|))
  (|C6-tuple2-printIII| t6 t7 t8 |e1|)
  (setq
    t9
    (|C2-tuple2-*|
      |G-tuple2_cycle_523605238|
      |G-tuple2_cycle_523605238|
      |e1|))
  (multiple-value-setq
    (t10 t11 t12)
    (|CCall|
      t9
      (|CCall| |G-lazyForceImport| (|Lex| |Struct-tuple2-12-1-16| 16 |l1|))
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l1|)
        (|MakeLit| "2"))
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l1|)
        (|MakeLit| "3"))))
  (|C6-tuple2-printIII| t10 t11 t12 |e1|)
  (setq
    t13
    (|C4-tuple2-^|
      |G-tuple2_cycle_523605238|
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l1|)
        (|MakeLit| "10"))
      |e1|))
  (multiple-value-setq
    (t14 t15 t16)
    (|CCall|
      t13
      (|CCall| |G-lazyForceImport| (|Lex| |Struct-tuple2-12-1-16| 16 |l1|))
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l1|)
        (|MakeLit| "2"))
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l1|)
        (|MakeLit| "3"))))
  (|C6-tuple2-printIII| t14 t15 t16 |e1|)
  (block-return |C7-tuple2-foo| ()))

(defprog
  ((|C8-tuple2-bar| |Word| |Word| |Word|)
    ((|P0-a| |Word|) (|P1-b| |Word|) (|P2-c| |Word|) (|e1| |Env|)))
  ((t0 |Word|)
    (t1 |Word|)
    (t2 |Word|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-tuple2-10| |Struct-tuple2-10|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when
      (|CCall|
        (|Lex| |Struct-tuple2-12-<-13| 13 |l1|)
        |P0-a|
        (|CCall| |G-lazyForceImport| (|Lex| |Struct-tuple2-12-1-16| 16 |l1|)))
      (go |Lab0|))
    (|SetLex| |Struct-tuple2-10--0| 0 |l0| |P0-a|)
    (|SetLex| |Struct-tuple2-10--1| 1 |l0| |P1-b|)
    (|SetLex| |Struct-tuple2-10--2| 2 |l0| |P2-c|)
    (setq t0 (|Lex| |Struct-tuple2-10--0| 0 |l0|))
    (setq t1 (|Lex| |Struct-tuple2-10--1| 1 |l0|))
    (setq t2 (|Lex| |Struct-tuple2-10--2| 2 |l0|))
    (go |Lab1|)
    |Lab0|
    (|SetLex|
      |Struct-tuple2-10--3|
      3
      |l0|
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l1|)
        (|MakeLit| "21")))
    (|SetLex|
      |Struct-tuple2-10--4|
      4
      |l0|
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l1|)
        (|MakeLit| "52")))
    (|SetLex|
      |Struct-tuple2-10--5|
      5
      |l0|
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l1|)
        (|MakeLit| "31")))
    (setq t0 (|Lex| |Struct-tuple2-10--3| 3 |l0|))
    (setq t1 (|Lex| |Struct-tuple2-10--4| 4 |l0|))
    (setq t2 (|Lex| |Struct-tuple2-10--5| 5 |l0|))
    |Lab1|
    (block-return |C8-tuple2-bar| (values t0 t1 t2))))

(defprog
  ((|C9-tuple2-baz| |Word| |Word| |Word|)
    ((|P0-n| |Word|) (|e1| |Env|)))
  ((t0 |Word|)
    (t1 |Word|)
    (t2 |Word|)
    (t3 |Word|)
    (t4 |Word|)
    (t5 |Word|)
    (t6 |Word|)
    (t7 |Word|)
    (t8 |Word|)
    (t9 |Word|)
    (t10 |Word|)
    (t11 |Word|)
    (|l0| |Level|)
    (|e0| |Env|)
    (|l1| |Level|))
  (setq |l0| (|MakeLevel| |MAKE-Struct-tuple2-11| |Struct-tuple2-11|))
  (setq |e0| (|MakeEnv| |e1| |l0|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when
      (|CCall|
        (|Lex| |Struct-tuple2-12->-12| 12 |l1|)
        |P0-n|
        (|CCall|
          (|Lex| |Struct-tuple2-12-integer-9| 9 |l1|)
          (|MakeLit| "10")))
      (go |Lab0|))
    (when
      (|CCall|
        (|Lex| |Struct-tuple2-12-<-13| 13 |l1|)
        |P0-n|
        (|CCall|
          (|Lex| |Struct-tuple2-12-integer-9| 9 |l1|)
          (|MakeLit| "5")))
      (go |Lab2|))
    (multiple-value-setq
      (t6 t7 t8)
      (|C9-tuple2-baz|
        (|CCall|
          (|Lex| |Struct-tuple2-12---15| 15 |l1|)
          |P0-n|
          (|CCall| |G-lazyForceImport| (|Lex| |Struct-tuple2-12-1-16| 16 |l1|)))
        |e1|))
    (setq t3 t6)
    (setq t4 t7)
    (setq t5 t8)
    |Lab3|
    (setq t0 t3)
    (setq t1 t4)
    (setq t2 t5)
    |Lab1|
    (block-return |C9-tuple2-baz| (values t0 t1 t2))
    |Lab2|
    (|SetLex|
      |Struct-tuple2-11--0|
      0
      |l0|
      (|CCall|
        (|Lex| |Struct-tuple2-12-integer-9| 9 |l1|)
        (|MakeLit| "2")))
    (|SetLex|
      |Struct-tuple2-11--1|
      1
      |l0|
      (|CCall| |G-lazyForceImport| (|Lex| |Struct-tuple2-12-1-16| 16 |l1|)))
    (|SetLex| |Struct-tuple2-11--2| 2 |l0| |P0-n|)
    (setq t3 (|Lex| |Struct-tuple2-11--0| 0 |l0|))
    (setq t4 (|Lex| |Struct-tuple2-11--1| 1 |l0|))
    (setq t5 (|Lex| |Struct-tuple2-11--2| 2 |l0|))
    (go |Lab3|)
    |Lab0|
    (multiple-value-setq
      (t9 t10 t11)
      (|C8-tuple2-bar| |P0-n| |P0-n| |P0-n| |e1|))
    (setq t0 t9)
    (setq t1 t10)
    (setq t2 t11)
    (go |Lab1|)))

(defprog
  ((|C10-tuple2-string-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-tuple2-12--23| 23 |l1|) (go |Lab0|))
    (|SetLex| |Struct-tuple2-12--23| 23 |l1| (the |Bool| t))
    (|CCall| |G-string|)
    |Lab0|
    (block-return |C10-tuple2-string-init| |G-string_String_905549850|)))

(defprog
  ((|C11-tuple2-char-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-tuple2-12--24| 24 |l1|) (go |Lab0|))
    (|SetLex| |Struct-tuple2-12--24| 24 |l1| (the |Bool| t))
    (|CCall| |G-char|)
    |Lab0|
    (block-return |C11-tuple2-char-init| |G-char_Character_700429360|)))

(defprog
  ((|C12-tuple2-textwrit-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-tuple2-12--25| 25 |l1|) (go |Lab0|))
    (|SetLex| |Struct-tuple2-12--25| 25 |l1| (the |Bool| t))
    (|CCall| |G-textwrit|)
    |Lab0|
    (block-return
      |C12-tuple2-textwrit-init|
      |G-textwrit_TextWriter_636558258|)))

(defprog
  ((|C13-tuple2-integer-init| |Word|) ((|P0-idx| |SInt|) (|e1| |Env|)))
  ((|l1| |Level|))
  (setq |l1| (|EnvLevel| |e1|))
  (tagbody
    (when (|Lex| |Struct-tuple2-12--26| 26 |l1|) (go |Lab0|))
    (|SetLex| |Struct-tuple2-12--26| 26 |l1| (the |Bool| t))
    (|CCall| |G-integer|)
    |Lab0|
    (block-return |C13-tuple2-integer-init| |G-integer_Integer_244869820|)))

(setq |G-tuple2| (|Clos| nil |C0-tuple2-tuple2|))

(setq |G-tuple2_baz_1047290136| nil)

(setq |G-tuple2_bar_523605238| nil)

(setq |G-tuple2_foo_778822608| nil)

(setq |G-tuple2_printIII_281389027| nil)

(setq |G-tuple2_cycle_523605238| nil)

(setq |G-tuple2_^_231669443| nil)

(setq |G-tuple2_*_767965809| nil)

(setq |G-tuple2_id_523605238| nil)

(file-imports
  '((|G-integer| "integer" |initializer| "")
      (|G-textwrit| "textwrit" |initializer| "")
      (|G-char| "char" |initializer| "")
      (|G-string| "string" |initializer| "")
      (|G-char_Character_700429360| "Character" 700429360 "char")
      (|G-string_String_905549850| "String" 905549850 "string")
      (|G-textwrit_TextWriter_636558258| "TextWriter" 636558258 "textwrit")
      (|G-stdGetWordRetWord0| "stdGetWordRetWord0" 0 "")
      (|G-stdGetWordWordRetWord0| "stdGetWordWordRetWord0" 0 "")
      (|G-rtDelayedGetExport!| "rtDelayedGetExport!" 0 "")
      (|G-lazyForceImport| "lazyForceImport" 0 "")
      (|G-lazyGetExport!| "lazyGetExport!" 0 "")
      (|G-rtLazyDomFrInit| "rtLazyDomFrInit" 0 "")
      (|G-integer_Integer_244869820| "Integer" 244869820 "integer")
      (|G-runtime| "runtime" |initializer| "")
      (|G-noOperation| "noOperation" 0 "")))

(file-exports
  '((|G-tuple2_id_523605238| "id" 523605238 "tuple2")
      (|G-tuple2_*_767965809| "*" 767965809 "tuple2")
      (|G-tuple2_^_231669443| "^" 231669443 "tuple2")
      (|G-tuple2_cycle_523605238| "cycle" 523605238 "tuple2")
      (|G-tuple2_printIII_281389027| "printIII" 281389027 "tuple2")
      (|G-tuple2_foo_778822608| "foo" 778822608 "tuple2")
      (|G-tuple2_bar_523605238| "bar" 523605238 "tuple2")
      (|G-tuple2_baz_1047290136| "baz" 1047290136 "tuple2")
      (|G-tuple2| "tuple2" |initializer| "")))
