#!/bin/bash

doBuild() {
    compileAldorIntoLib sit_pable   "$@"
    compileAldorIntoLib sit_basic   "$@"
    compileAldorIntoLib sit_monoid  "$@"
    compileAldorIntoLib sit_abmon   "$@"
    compileAldorIntoLib sit_abgroup "$@"
    compileAldorIntoLib sit_group   "$@"
    compileAldorIntoLib sit_ring    "$@"
    compileAldorIntoLib sit_ncid    "$@"
    compileAldorIntoLib sit_comring "$@"
    compileAldorIntoLib sit_char0   "$@"
    compileAldorIntoLib sit_charp   "$@"
    compileAldorIntoLib sit_spzble  "$@"
    compileAldorIntoLib sit_intdom  "$@"
    compileAldorIntoLib sit_dcmprng "$@"
    compileAldorIntoLib sit_ptools  "$@"
    compileAldorIntoLib sit_gcd     "$@"
    compileAldorIntoLib sit_euclid  "$@"
    compileAldorIntoLib sit_field   "$@"
    compileAldorIntoLib sit_gexpcat "$@"
    compileAldorIntoLib alg_cansimp "$@"
    compileAldorIntoLib alg_primsrc "$@"
    compileAldorIntoLib sit_linarit "$@"
    compileAldorIntoLib sit_module  "$@"
    compileAldorIntoLib alg_rring   "$@"
    compileAldorIntoLib sit_algebra "$@"
    compileAldorIntoLib sit_automor "$@"
    compileAldorIntoLib sit_deriv   "$@"
    compileAldorIntoLib sit_difring "$@"
    compileAldorIntoLib sit_diffext "$@"
    compileAldorIntoLib alg_rescls  "$@"
    compileAldorIntoLib sit_chrem   "$@"
    compileAldorIntoLib alg_modcmp  "$@"
    compileAldorIntoLib sit_integer "$@" -Mno-ALDOR_W_GenDomFunNotConst
    compileAldorIntoLib sit_intgmp  "$@"
    compileAldorIntoLib sit_qring   "$@"
    compileAldorIntoLib sit_freelc  "$@"
    compileAldorIntoLib sit_idxflc  "$@"
    compileAldorIntoLib sit_freelar "$@"
    compileAldorIntoLib sit_idxflar "$@"
    compileAldorIntoLib sit_freemod "$@"
    compileAldorIntoLib sit_idxfmod "$@"
    compileAldorIntoLib alg_frering "$@"
    compileAldorIntoLib sit_freealg "$@"
    compileAldorIntoLib alg_idxfrng "$@"
    compileAldorIntoLib sit_idxfalg "$@"
    compileAldorIntoLib sit_fset    "$@"
    compileAldorIntoLib alg_ffield  "$@"
    compileAldorIntoLib sit_prfcat0 "$@"
    compileAldorIntoLib sit_spfcat0 "$@"
    compileAldorIntoLib sit_spf0    "$@"
}

source "$ALDORROOT"/toolbin/build-fns.sh ; doMain "$@"
